# Generated by Django 4.0.5 on 2023-05-26 00:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=255)),
                ('gross_weight', models.DecimalField(decimal_places=2, max_digits=15)),
                ('karat_value', models.IntegerField()),
                ('stone_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('wastage', models.DecimalField(decimal_places=2, max_digits=20)),
                ('net_weight', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_weight_22k', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('leverage', models.IntegerField(blank=True, null=True)),
                ('asset_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('rfdi_tag_number', models.CharField(max_length=255)),
                ('gold_ownership', models.CharField(choices=[('Ancestral', 'Ancestral'), ('Gifted', 'Gifted'), ('Self Purchased', 'Self Purchased')], default='Ancestral', max_length=100)),
                ('marketvalueatappraisal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currentmarketvalue', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pouchnumber', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GoldAppriaselModel',
            fields=[
                ('goldappriase_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_weight', models.DecimalField(decimal_places=2, max_digits=15)),
                ('karat_value', models.IntegerField()),
                ('wastage', models.DecimalField(decimal_places=2, max_digits=20)),
                ('net_weight', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_weight_22k', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pouch_no', models.CharField(max_length=255)),
                ('eligible_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('asset_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoldPriceData',
            fields=[
                ('gold_price_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gold_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('karat', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
