# Generated by Django 4.0.5 on 2023-06-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldpricedata',
            name='lending_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
