# Generated by Django 4.0.5 on 2023-06-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_goldpricedata_lending_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldpricedata',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
