# Generated by Django 4.0.5 on 2023-07-04 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_alter_goldpricedata_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldpricedata',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 4, 18, 13, 20, 968506), null=True),
        ),
    ]
