# Generated by Django 4.0.5 on 2023-07-12 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_alter_goldpricedata_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldpricedata',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 12, 17, 25, 7, 572749), null=True),
        ),
    ]
