# Generated by Django 4.0.5 on 2023-08-02 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_alter_goldpricedata_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldpricedata',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 2, 17, 34, 2, 388837), null=True),
        ),
        migrations.AlterField(
            model_name='goldpricedata',
            name='lending_price',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
