# Generated by Django 4.0.5 on 2023-08-02 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_alter_goldpricedata_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldpricedata',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 2, 21, 37, 47, 309754), null=True),
        ),
    ]
