# Generated by Django 4.0.5 on 2023-08-07 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_alter_goldpricedata_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldpricedata',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 7, 17, 55, 17, 731630), null=True),
        ),
    ]
