# Generated by Django 4.0.5 on 2023-09-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0013_alter_goldpricedata_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldpricedata',
            name='lending_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
