# Generated by Django 4.0.5 on 2023-09-26 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0014_alter_goldpricedata_lending_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goldpricedata',
            name='lending_price',
        ),
        migrations.AddField(
            model_name='goldpricedata',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='goldpricedata',
            name='old_gold_price',
            field=models.DecimalField(decimal_places=2, default=5416, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goldpricedata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-09-26'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goldpricedata',
            name='karat',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(22), django.core.validators.MinValueValidator(18)]),
        ),
    ]
