# Generated by Django 4.0.5 on 2023-09-26 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0015_remove_goldpricedata_lending_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldpricedata',
            name='karat',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(22), django.core.validators.MinValueValidator(18)]),
        ),
    ]
