# Generated by Django 4.0.5 on 2023-09-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0016_alter_goldpricedata_karat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldpricedata',
            name='old_gold_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
