# Generated by Django 4.0.5 on 2023-09-28 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0041_alter_loandocument_document_type'),
        ('asset', '0017_alter_goldpricedata_old_gold_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_price_per_gram',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_application', to='application.application'),
        ),
    ]
