# Generated by Django 4.0.5 on 2023-11-02 13:21

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0018_asset_asset_price_per_gram_alter_asset_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPriceHistory',
            fields=[
                ('gold_price_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gold_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('karat', models.IntegerField(validators=[django.core.validators.MaxValueValidator(22), django.core.validators.MinValueValidator(18)])),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
