# Generated by Django 4.0.5 on 2024-02-22 11:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lender', '0001_initial'),
        ('asset', '0019_history_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldpricedata',
            name='lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lender_gold_price', to='lender.lender'),
        ),
        migrations.AddField(
            model_name='goldpricehistory',
            name='lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lender_gold_price_history', to='lender.lender'),
        ),
        migrations.AlterField(
            model_name='goldpricedata',
            name='karat',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(22), django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AddConstraint(
            model_name='goldpricedata',
            constraint=models.UniqueConstraint(fields=('karat', 'lender'), name='lender_karat_unique'),
        ),
    ]
