# Generated by Django 4.0.5 on 2024-02-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0020_goldpricedata_lender_goldpricehistory_lender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goldappriaselmodel',
            name='net_weight_22k',
        ),
    ]
