# Generated by Django 5.2.14 on 2026-05-12 18:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationMaster',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_code', models.CharField(help_text='Unique code for the template (e.g., LEAD_SUCCESS)', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('notification_type', models.CharField(choices=[('SMS', 'Short Message Service'), ('EMAIL', 'Email Notification'), ('PUSH', 'Push Notification')], max_length=10)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body_template', models.TextField(help_text='Template content with placeholders (e.g., Hello {{name}})')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Notification Master',
                'verbose_name_plural': 'Notification Master Templates',
                'db_table': 'notification_master',
            },
        ),
        migrations.CreateModel(
            name='BankCms',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('bank_id', models.IntegerField(help_text='Identifier for the bank')),
                ('slug', models.SlugField(help_text='Unique identifier for the CMS content block', max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='The actual CMS content (HTML or plain text)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional configuration for this content')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bank CMS',
                'verbose_name_plural': 'Bank CMS Blocks',
                'db_table': 'bank_cms',
                'indexes': [models.Index(fields=['bank_id', 'slug'], name='idx_bank_cms_lookup')],
            },
        ),
        migrations.CreateModel(
            name='CustomerCrmLead',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('user_id', models.CharField(help_text='Identifier for the user who initiated the lead', max_length=100)),
                ('bank_id', models.IntegerField(help_text='Identifier for the bank')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=20)),
                ('lead_source', models.CharField(blank=True, default='', max_length=100)),
                ('country_code', models.CharField(blank=True, default='', max_length=10)),
                ('product', models.CharField(blank=True, default='', max_length=100)),
                ('lead_channel', models.CharField(blank=True, default='', max_length=100)),
                ('partner_id', models.CharField(blank=True, default='', max_length=100)),
                ('icici_lead_number', models.CharField(blank=True, help_text='Lead ID returned by ICICI', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Customer CRM Lead',
                'verbose_name_plural': 'Customer CRM Leads',
                'db_table': 'customer_crm_leads',
                'indexes': [models.Index(fields=['mobile_number'], name='idx_lead_mobile'), models.Index(fields=['bank_id'], name='idx_lead_bank')],
            },
        ),
        migrations.CreateModel(
            name='IciciAppSetting',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('bank_id', models.IntegerField(help_text='Unique identifier for the bank (default: 1 for ICICI)', unique=True)),
                ('token_url', models.CharField(help_text='Endpoint URL to fetch access token', max_length=500)),
                ('client_id', models.CharField(help_text='API Client ID provided by ICICI', max_length=200)),
                ('client_secret', models.CharField(help_text='API Client Secret provided by ICICI', max_length=500)),
                ('customer_url', models.CharField(help_text='Endpoint URL for pushing lead details', max_length=500)),
                ('is_async', models.BooleanField(default=False, help_text='Whether to process the request asynchronously')),
                ('call_back_url', models.CharField(blank=True, default='', help_text='Callback URL for async response', max_length=500)),
                ('country_code', models.CharField(blank=True, default='IN', max_length=10)),
                ('lead_source', models.CharField(blank=True, default='', max_length=100)),
                ('product', models.CharField(blank=True, default='', max_length=100)),
                ('lead_channel', models.CharField(blank=True, default='', max_length=100)),
                ('partner_id', models.CharField(blank=True, default='', max_length=100)),
                ('sub_agent_code', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'ICICI App Setting',
                'verbose_name_plural': 'ICICI App Settings',
                'db_table': 'icici_app_settings',
                'indexes': [models.Index(fields=['bank_id'], name='idx_icici_settings_bank_id')],
            },
        ),
        migrations.CreateModel(
            name='IciciRequestLog',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('mobile_number', models.CharField(max_length=20)),
                ('plain_request', models.TextField(help_text='Decrypted/Plain JSON request payload')),
                ('encrypted_request', models.TextField(help_text='Encrypted payload sent to ICICI')),
                ('correlation_id', models.CharField(blank=True, help_text='X-Correlation-ID for tracking', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'ICICI Request Log',
                'verbose_name_plural': 'ICICI Request Logs',
                'db_table': 'icici_request_logs',
                'indexes': [models.Index(fields=['mobile_number'], name='idx_req_log_mobile'), models.Index(fields=['correlation_id'], name='idx_req_log_corr_id')],
            },
        ),
        migrations.CreateModel(
            name='IciciBankResponseLog',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('encrypted_response', models.TextField(help_text='Encrypted JSON response from ICICI')),
                ('plain_response', models.TextField(help_text='Decrypted/Plain JSON response')),
                ('lead_number', models.CharField(blank=True, help_text='Extracted lead number from response', max_length=100, null=True)),
                ('lead_number_id', models.IntegerField(blank=True, help_text='Internal ID of the saved lead', null=True)),
                ('status_code', models.CharField(blank=True, max_length=10, null=True)),
                ('status_text', models.CharField(blank=True, max_length=100, null=True)),
                ('request_log', models.OneToOneField(help_text='Reference to the corresponding request log', on_delete=django.db.models.deletion.CASCADE, related_name='response_log', to='apps.icicirequestlog')),
            ],
            options={
                'verbose_name': 'ICICI Bank Response Log',
                'verbose_name_plural': 'ICICI Bank Response Logs',
                'db_table': 'icici_bank_response_logs',
            },
        ),
    ]
