# Generated by Django 5.2.14 on 2026-05-12 18:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldLoanRequest',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=100)),
                ('loan_amount', models.CharField(blank=True, default='', max_length=50)),
                ('loan_tenure', models.CharField(blank=True, default='', max_length=20)),
                ('loan_account_number', models.CharField(blank=True, default='', max_length=50)),
                ('loan_amount_disbursed', models.CharField(blank=True, default='', max_length=50)),
                ('disbursal_date', models.CharField(blank=True, default='', max_length=50)),
                ('instance_id', models.CharField(blank=True, default='', max_length=100)),
                ('roi', models.CharField(blank=True, default='', max_length=20)),
                ('applicant_id_cust_id', models.CharField(blank=True, default='', max_length=100)),
                ('assessment_id', models.CharField(blank=True, default='', max_length=100)),
                ('variant_facility_type', models.CharField(blank=True, default='', max_length=100)),
                ('gender', models.CharField(blank=True, default='', max_length=20)),
                ('marital_status', models.CharField(blank=True, default='', max_length=50)),
                ('religion', models.CharField(blank=True, default='', max_length=50)),
                ('education', models.CharField(blank=True, default='', max_length=100)),
                ('source_of_funds', models.CharField(blank=True, default='', max_length=100)),
                ('gross_annual_income', models.CharField(blank=True, default='', max_length=50)),
                ('person_with_disability', models.CharField(blank=True, default='', max_length=10)),
                ('vernacular_declaration', models.CharField(blank=True, default='', max_length=10)),
                ('father_name', models.CharField(blank=True, default='', max_length=100)),
                ('mother_maiden_name', models.CharField(blank=True, default='', max_length=100)),
                ('sub_agent_code', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Gold Loan Request',
                'verbose_name_plural': 'Gold Loan Requests',
                'db_table': 'gold_loan_requests',
            },
        ),
        migrations.CreateModel(
            name='LeadAddressDetail',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('address_type', models.CharField(blank=True, default='', max_length=50)),
                ('address_line_1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=255)),
                ('address_line_3', models.CharField(blank=True, default='', max_length=255)),
                ('address_line_4', models.CharField(blank=True, default='', max_length=255)),
                ('landmark', models.CharField(blank=True, default='', max_length=100)),
                ('locality', models.CharField(blank=True, default='', max_length=100)),
                ('village', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('latitude', models.CharField(blank=True, default='', max_length=50)),
                ('longitude', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Lead Address Detail',
                'verbose_name_plural': 'Lead Address Details',
                'db_table': 'lead_address_details',
            },
        ),
        migrations.CreateModel(
            name='LeadAppointmentDetail',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('engagement_type', models.CharField(blank=True, default='', max_length=50)),
                ('is_joint_activity', models.CharField(blank=True, default='', max_length=10)),
                ('initiated_by', models.CharField(blank=True, default='', max_length=100)),
                ('purpose_of_meeting', models.CharField(blank=True, default='', max_length=200)),
                ('place_of_meeting', models.CharField(blank=True, default='', max_length=200)),
                ('start_date_time', models.CharField(blank=True, default='', max_length=50)),
                ('appointment_status', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Lead Appointment Detail',
                'db_table': 'lead_appointment_details',
            },
        ),
        migrations.CreateModel(
            name='LeadOrganisationDetail',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('account_number', models.CharField(blank=True, default='', max_length=50)),
                ('ucc', models.CharField(blank=True, default='', max_length=100)),
                ('ppa_code', models.CharField(blank=True, default='', max_length=50)),
                ('mobile_no', models.CharField(blank=True, default='', max_length=20)),
                ('email_address', models.EmailField(blank=True, default='', max_length=255)),
                ('pan_number', models.CharField(blank=True, default='', max_length=20)),
                ('date_of_incorporation', models.CharField(blank=True, default='', max_length=50)),
                ('contact_person_first_name', models.CharField(blank=True, default='', max_length=100)),
                ('contact_person_middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('contact_person_last_name', models.CharField(blank=True, default='', max_length=100)),
                ('contact_person_mobile_number', models.CharField(blank=True, default='', max_length=20)),
                ('contact_person_pan_number', models.CharField(blank=True, default='', max_length=20)),
                ('contact_person_ucic', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Lead Organisation Detail',
                'db_table': 'lead_organisation_details',
            },
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='account_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='affluent_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='aggregator_lead_source',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='alternate_contact_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='assigned_to_self',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='assignment_based_on',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='assignment_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='assignment_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='branch_sol_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='bre_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='campaign_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='customer_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='customer_segment',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='customer_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='cvce_segment',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='date_of_birth',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='drop_off_page_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='dropoff_page_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='email_address',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='first_time_pa_offer_flag',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='individual_organization_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='lead_generator',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='lead_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='lead_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='medium',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='mode_of_communication',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='office_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='online_coversion_sr',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='overseas_country',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='pa_offer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='pan_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='pincode_lead',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='preferred_call_end_time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='preferred_call_start_time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='preferred_call_time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='priority',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='product_sub_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='referral_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='referred_by_channel_partner_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='referred_by_lead_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='referred_by_other_email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='referred_by_other_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='referred_by_other_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='referrer_account_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='referrer_customer_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='referrer_employee_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='referrer_mobile_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='referrer_organization_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='referrer_pan_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='referrer_ucc',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='referrer_ucic',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='residence_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='residency_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='salutation',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='service_flag',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='sms_short_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='time_of_lead_drop',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='time_spent_on_page',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='ucic',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='uotm_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='utm_campaign',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='utm_fed_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='utm_ga_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='utm_gci_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='utm_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='utm_itm',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='utm_lead_priority',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='utm_lead_propensity',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='utm_lead_score',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='utm_lms',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customercrmlead',
            name='utm_ntb_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customercrmlead',
            name='bank_id',
            field=models.IntegerField(db_index=True, help_text='Identifier for the bank'),
        ),
        migrations.AlterField(
            model_name='customercrmlead',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customercrmlead',
            name='icici_lead_number',
            field=models.CharField(blank=True, db_index=True, help_text='Lead ID returned by ICICI', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customercrmlead',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customercrmlead',
            name='mobile_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='customercrmlead',
            index=models.Index(fields=['pan_number'], name='idx_lead_pan'),
        ),
        migrations.AddIndex(
            model_name='customercrmlead',
            index=models.Index(fields=['icici_lead_number'], name='idx_lead_icici_no'),
        ),
        migrations.AddField(
            model_name='goldloanrequest',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_loan_requests', to='apps.customercrmlead'),
        ),
        migrations.AddField(
            model_name='leadaddressdetail',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_details', to='apps.customercrmlead'),
        ),
        migrations.AddField(
            model_name='leadappointmentdetail',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_details', to='apps.customercrmlead'),
        ),
        migrations.AddField(
            model_name='leadorganisationdetail',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_details', to='apps.customercrmlead'),
        ),
    ]
