# Generated by Django 4.0.5 on 2023-05-26 00:18

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('lender_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lender_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('lender_name', models.CharField(max_length=255)),
                ('lender_address', models.CharField(max_length=255)),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('modified_At', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LenderBranch',
            fields=[
                ('lenderbranch_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('modified_At', models.DateTimeField(auto_now=True)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lender_lenderbranch', to='lender.lender')),
            ],
        ),
        migrations.CreateModel(
            name='LenderBranchMapping',
            fields=[
                ('lenderbranchmapping_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('modified_At', models.DateTimeField(auto_now=True)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lender_lenderbranchmapping', to='lender.lender')),
                ('lenderbranch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lenderbranch_lenderbranchmapping', to='lender.lenderbranch')),
            ],
        ),
    ]
