# Generated by Django 4.0.5 on 2023-05-26 00:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveTracking',
            fields=[
                ('track_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('track_file', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('loan_number', models.CharField(max_length=18, unique=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('ASSET_COLLECTED', 'ASSET_COLLECTED'), ('Active - Good Standing', 'Active - Good Standing'), ('Active - Bad Standing', 'Active - Bad Standing'), ('Approved', 'Approved'), ('Closed - Obligations Met', 'Closed - Obligations Met')], default='NEW', max_length=100)),
                ('term', models.CharField(max_length=255)),
                ('bm_comment', models.TextField(blank=True, null=True)),
                ('cpc_comment', models.TextField(blank=True, null=True)),
                ('loan_amount', models.IntegerField()),
                ('loan_type', models.CharField(max_length=255)),
                ('days_past_dues', models.IntegerField()),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('purpose_of_loan', models.CharField(choices=[('EDUCATIONAL', 'EDUCATIONAL'), ('MARRIAGE', 'MARRIAGE'), ('INCOME_GENERATION', 'INCOME_GENERATION'), ('MEDICAL_EMERGENCY', 'MEDICAL_EMERGENCY'), ('BROAD_CATEGORY', 'BROAD_CATEGORY'), ('PURCHASE_OF_ASSETS', 'PURCHASE_OF_ASSETS'), ('PURCHASE_OF_GOODS', 'PURCHASE_OF_GOODS'), ('LAND_DEVELOPMENT', 'LAND_DEVELOPMENT'), ('PURCHASE_OF_SEEDS', 'PURCHASE_OF_SEEDS'), ('PLANTATION_EXPENSES', 'PLANTATION_EXPENSES'), ('PURCHASE_OF_AGRICULTURAL_EQUIPMENTS', 'PURCHASE_OF_AGRICULTURAL_EQUIPMENTS'), ('PAYMENT_OF_LABOUR_EXPENSES', 'PAYMENT_OF_LABOUR_EXPENSES'), ('MEDICAL_EXPENSES', 'MEDICAL_EXPENSES'), ('TRAVEL_EXPENSES', 'TRAVEL_EXPENSES'), ('OTHER', 'OTHER')], default='OTHER', max_length=300)),
                ('eligible_amount', models.IntegerField(blank=True, null=True)),
                ('total_goods_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('approvedByBMAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('approvedByCPCAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('processing_fee', models.IntegerField(blank=True, null=True)),
                ('current_gst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('gst', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('stamp_duty', models.IntegerField(blank=True, null=True)),
                ('penalty', models.IntegerField(blank=True, null=True)),
                ('ltv', models.IntegerField(blank=True, null=True)),
                ('gold_rate_per_gram', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('lending_gold_rate_per_gram', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tenure', models.IntegerField(blank=True, null=True)),
                ('intrest_rate', models.IntegerField(blank=True, null=True)),
                ('disbursed_amount', models.IntegerField(blank=True, null=True)),
                ('disbursed_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('disbursal_amount', models.IntegerField(blank=True, null=True)),
                ('net_disbursed_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanEMIHeader',
            fields=[
                ('loan_emi_header_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('principal', models.IntegerField()),
                ('apr', models.IntegerField()),
                ('term', models.IntegerField()),
                ('emi_amount', models.IntegerField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanEMIRecord',
            fields=[
                ('loan_emi_record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sequence_no', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('emi_amount', models.IntegerField()),
                ('interest', models.IntegerField()),
                ('principal', models.IntegerField()),
                ('bill_generation_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('paid', models.BooleanField(default=False)),
                ('loan_emi_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loanemiheader')),
            ],
        ),
        migrations.CreateModel(
            name='LoanDisbursalTransaction',
            fields=[
                ('loan_disbursal_transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_disbursal_transaction_application', to='application.application')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_disbursal_transaction_loan', to='loan.loan')),
            ],
        ),
    ]
