# Generated by Django 4.0.5 on 2023-05-26 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('lender', '0001_initial'),
        ('application', '0003_initial'),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='Originatedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_Originatedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_application', to='application.application'),
        ),
        migrations.AddField(
            model_name='loan',
            name='appraisedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_appraisedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='approvedByBM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_approvedByBM', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='approvedByCPC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_approvedByCPC', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_lender', to='lender.lender'),
        ),
        migrations.AddField(
            model_name='loan',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loan_product', to='product.product'),
        ),
        migrations.AddField(
            model_name='livetracking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livetracking_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livetracking',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livetracking_loan', to='loan.loan'),
        ),
        migrations.AddField(
            model_name='livetracking',
            name='loan_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livetracking_loanmanager', to='loan.loan'),
        ),
    ]
