# Generated by Django 4.0.5 on 2023-05-29 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_application_intrest_rate'),
        ('loan', '0003_alter_loan_intrest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='loan_application', to='application.application'),
        ),
    ]
