# Generated by Django 4.0.5 on 2023-06-02 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0004_alter_loan_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livetracking',
            name='loan_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livetracking_loanmanager', to=settings.AUTH_USER_MODEL),
        ),
    ]
