# Generated by Django 4.0.5 on 2023-06-02 16:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_application_live_tracking_id_loandocument_and_more'),
        ('loan', '0005_alter_livetracking_loan_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandisbursaltransaction',
            name='is_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loandisbursaltransaction',
            name='payment_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='loandisbursaltransaction',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='loandisbursaltransaction',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loandisbursaltransaction',
            name='received_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='LoanTakeOver',
            fields=[
                ('take_over_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('lender_name', models.CharField(max_length=100)),
                ('gold_weight_pledged', models.CharField(max_length=100)),
                ('loan_amount', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('tenure', models.IntegerField()),
                ('total_payment_done', models.FloatField()),
                ('loan_amount_remaining', models.FloatField()),
                ('loan_start_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('loan_reference_number', models.IntegerField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_take_over_app', to='application.application')),
            ],
        ),
    ]
