# Generated by Django 4.0.5 on 2023-06-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_loandisbursaltransaction_is_cleared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='current_emi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_accrued_till_date',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_remaining',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='penalty_paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='principal_paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='principal_remaining',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
