# Generated by Django 4.0.5 on 2023-06-05 11:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_loan_current_emi_loan_interest_accrued_till_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPaymentTransaction',
            fields=[
                ('loan_payment_transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('payment_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_amount', models.FloatField(default=0)),
                ('payment_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('received_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_cleared', models.BooleanField(default=False)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_payment_transaction', to='loan.loan')),
            ],
        ),
        migrations.DeleteModel(
            name='LoanDisbursalTransaction',
        ),
    ]
