# Generated by Django 4.0.5 on 2023-06-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_loanpaymenttransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpaymenttransaction',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
