# Generated by Django 4.0.5 on 2023-06-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0009_alter_loanpaymenttransaction_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='accrual_on_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_last_accrued_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
