# Generated by Django 4.0.5 on 2023-06-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0010_loan_accrual_on_hold_loan_interest_last_accrued_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='next_due_generation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_paid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='penalty_paid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='principal_paid',
            field=models.FloatField(default=0),
        ),
    ]
