# Generated by Django 4.0.5 on 2023-06-09 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0011_loan_next_due_date_loan_next_due_generation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanBillGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.IntegerField()),
                ('total_penalty', models.IntegerField()),
                ('bill_satisfied', models.BooleanField(default=False)),
                ('bill_paid', models.BooleanField(default=False)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_bill_generation', to='loan.loan')),
            ],
        ),
    ]
