# Generated by Django 4.0.5 on 2023-06-16 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0012_loanbillgeneration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loantakeover',
            old_name='loan_amount_remaining',
            new_name='requested_amount_from_radian',
        ),
        migrations.RenameField(
            model_name='loantakeover',
            old_name='total_payment_done',
            new_name='total_release_amount',
        ),
    ]
