# Generated by Django 4.0.5 on 2023-06-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0013_rename_loan_amount_remaining_loantakeover_requested_amount_from_radian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantakeover',
            name='bt_undertaking',
            field=models.FileField(blank=True, null=True, upload_to='take_over_loans_bt_docs'),
        ),
        migrations.AddField(
            model_name='loantakeover',
            name='exiting_loan_doc',
            field=models.FileField(blank=True, null=True, upload_to='take_over_loans_doc'),
        ),
    ]
