# Generated by Django 4.0.5 on 2023-06-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0014_loantakeover_bt_undertaking_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loantakeover',
            old_name='exiting_loan_doc',
            new_name='existing_loan_doc',
        ),
    ]
