# Generated by Django 4.0.5 on 2023-06-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0015_rename_exiting_loan_doc_loantakeover_existing_loan_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loantakeover',
            name='bt_undertaking',
        ),
        migrations.RemoveField(
            model_name='loantakeover',
            name='existing_loan_doc',
        ),
    ]
