# Generated by Django 4.0.5 on 2023-06-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_loandocument_document_type_application'),
        ('loan', '0016_remove_loantakeover_bt_undertaking_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoanEMIHeader',
            new_name='LoanEMISchedule',
        ),
    ]
