# Generated by Django 4.0.5 on 2023-06-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0017_rename_loanemiheader_loanemischedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanbillgeneration',
            name='interest',
        ),
        migrations.AddField(
            model_name='loanbillgeneration',
            name='interest_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='loanpaymenttransaction',
            name='interest',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='loanpaymenttransaction',
            name='penalty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='loanpaymenttransaction',
            name='principal',
            field=models.FloatField(default=0),
        ),
    ]
