# Generated by Django 4.0.5 on 2023-06-23 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0018_remove_loanbillgeneration_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanemischedule',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
        ),
    ]
