# Generated by Django 4.0.5 on 2023-06-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0019_alter_loanemischedule_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanemischedule',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanemirecord',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
