# Generated by Django 4.0.5 on 2023-07-27 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0021_remove_loanemischedule_apr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherLenderApprainsal',
            fields=[
                ('appraisal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('loan_amount', models.IntegerField()),
                ('loan_number', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_lender_appraisal_created_by', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_lender_appraisal', to='loan.loan')),
            ],
        ),
    ]
