# Generated by Django 4.0.5 on 2023-07-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0022_otherlenderapprainsal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('SUBMITTED_TO_LENDER', 'SUBMITTED_TO_LENDER'), ('ASSET_COLLECTED', 'ASSET_COLLECTED'), ('Active - Good Standing', 'Active - Good Standing'), ('Active - Bad Standing', 'Active - Bad Standing'), ('Approved', 'Approved'), ('Closed - Obligations Met', 'Closed - Obligations Met')], default='NEW', max_length=100),
        ),
    ]
