# Generated by Django 4.0.5 on 2023-07-27 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_alter_branch_state'),
        ('loan', '0023_alter_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loan_branch', to='branch.branch'),
        ),
    ]
