# Generated by Django 4.0.5 on 2023-07-27 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0024_loan_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherlenderapprainsal',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_lender_appraisal', to='loan.loan', unique=True),
        ),
    ]
