# Generated by Django 4.0.5 on 2023-08-02 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0025_alter_otherlenderapprainsal_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanbillgeneration',
            old_name='interest_rate',
            new_name='interest',
        ),
    ]
