# Generated by Django 4.0.5 on 2023-08-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0026_rename_interest_rate_loanbillgeneration_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
