# Generated by Django 4.0.5 on 2023-09-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0027_loan_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantakeover',
            name='loan_reference_number',
            field=models.CharField(max_length=100),
        ),
    ]
