# Generated by Django 4.0.5 on 2023-09-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0028_alter_loantakeover_loan_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='processing_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
