# Generated by Django 4.0.5 on 2023-11-14 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0030_alter_loan_purpose_of_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanbillgeneration',
            name='bill_satisfied',
        ),
        migrations.RemoveField(
            model_name='loanbillgeneration',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='loanbillgeneration',
            name='total_penalty',
        ),
        migrations.AddField(
            model_name='loanbillgeneration',
            name='emi_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_bill_emi_record', to='loan.loanemirecord'),
        ),
        migrations.AddField(
            model_name='loanbillgeneration',
            name='interest_remaining',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loanbillgeneration',
            name='penalty_remaining',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loanbillgeneration',
            name='principal_remaining',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
