# Generated by Django 4.0.5 on 2023-11-14 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0031_remove_loanbillgeneration_bill_satisfied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanemirecord',
            name='loan_emi_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_emi_schedule', to='loan.loanemischedule'),
        ),
    ]
