# Generated by Django 4.0.5 on 2023-11-14 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0032_alter_loanemirecord_loan_emi_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanbillgeneration',
            name='emi_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_bill_emi_record', to='loan.loanemirecord', unique=True),
        ),
    ]
