# Generated by Django 4.0.5 on 2023-11-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0033_alter_loanbillgeneration_emi_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanbillgeneration',
            name='total_penalty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
