# Generated by Django 4.0.5 on 2023-12-14 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_account_religion'),
        ('loan', '0035_alter_loan_purpose_of_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeOverResidenceAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospect_no', models.CharField(max_length=100)),
                ('person_met', models.CharField(max_length=100)),
                ('relationship_with_applicant', models.CharField(max_length=100)),
                ('any_other_earning_family_member', models.CharField(max_length=100)),
                ('family_member_employement_details', models.CharField(max_length=100)),
                ('no_years_at_residence', models.CharField(max_length=100)),
                ('locating_address_difficulty', models.CharField(max_length=100)),
                ('type_of_accomodation', models.CharField(max_length=100)),
                ('area_sqft', models.CharField(max_length=100)),
                ('neighbor_check', models.BooleanField(default=False)),
                ('is_feedback_positive', models.BooleanField(default=False)),
                ('gprs_photos', models.FileField(upload_to='bt_gprs_photos')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_take_over_residence_details', to='account.account')),
            ],
        ),
    ]
