# Generated by Django 4.0.5 on 2023-12-19 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lender', '0001_initial'),
        ('loan', '0036_takeoverresidenceaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantakeover',
            name='lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='take_over_loan_lender', to='lender.lender'),
        ),
    ]
