# Generated by Django 4.0.5 on 2023-12-26 09:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0037_loantakeover_lender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takeoverresidenceaddress',
            name='id',
        ),
        migrations.AddField(
            model_name='takeoverresidenceaddress',
            name='take_over_residence_details',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
