# Generated by Django 4.0.5 on 2023-12-26 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0038_remove_takeoverresidenceaddress_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takeoverresidenceaddress',
            old_name='take_over_residence_details',
            new_name='take_over_residence_details_id',
        ),
    ]
