# Generated by Django 4.0.5 on 2023-12-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0039_rename_take_over_residence_details_takeoverresidenceaddress_take_over_residence_details_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeoverresidenceaddress',
            name='type_of_accomodation',
            field=models.CharField(choices=[('LOW_INCOME', 'LOW_INCOME'), ('FLAT_APARTMENT', 'FLAT_APARTMENT'), ('BUNGALOW', 'BUNGALOW')], max_length=100),
        ),
    ]
