# Generated by Django 4.0.5 on 2023-12-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0040_alter_takeoverresidenceaddress_type_of_accomodation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeoverresidenceaddress',
            name='locating_address_difficulty',
            field=models.CharField(choices=[('EASY', 'EASY'), ('MEDIUM', 'MEDIUM'), ('DIFFICULT', 'DIFFICULT')], max_length=100),
        ),
    ]
