# Generated by Django 4.0.5 on 2023-12-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0041_alter_takeoverresidenceaddress_locating_address_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeoverresidenceaddress',
            name='address_details',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='takeoverresidenceaddress',
            name='geo_pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='takeoverresidenceaddress',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='takeoverresidenceaddress',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='takeoverresidenceaddress',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='takeoverresidenceaddress',
            name='gprs_photos',
            field=models.FileField(blank=True, null=True, upload_to='bt_gprs_photos'),
        ),
    ]
