# Generated by Django 4.0.5 on 2023-12-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0042_takeoverresidenceaddress_address_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeoverresidenceaddress',
            name='area_sqft',
            field=models.CharField(choices=[('<400', '<400'), ('400-750', '400-750'), ('750-1000', '750-1000'), ('1000-1500', '1000-1500'), ('>1500', '>1500')], max_length=100),
        ),
    ]
