# Generated by Django 4.0.5 on 2023-12-28 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0043_alter_takeoverresidenceaddress_area_sqft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takeoverresidenceaddress',
            name='address_details',
        ),
        migrations.RemoveField(
            model_name='takeoverresidenceaddress',
            name='geo_pincode',
        ),
        migrations.RemoveField(
            model_name='takeoverresidenceaddress',
            name='gprs_photos',
        ),
        migrations.RemoveField(
            model_name='takeoverresidenceaddress',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='takeoverresidenceaddress',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='takeoverresidenceaddress',
            name='pincode',
        ),
        migrations.CreateModel(
            name='GprsPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gprs_photos', models.FileField(blank=True, null=True, upload_to='bt_gprs_photos')),
                ('satellite_map_photos', models.FileField(blank=True, null=True, upload_to='bt_gprs_satellite_photos')),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('address_details', models.CharField(blank=True, max_length=1000, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('take_over_residence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gprs_photos', to='loan.takeoverresidenceaddress')),
            ],
        ),
    ]
