# Generated by Django 4.0.5 on 2023-12-28 14:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0044_remove_takeoverresidenceaddress_address_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gprsphotos',
            name='id',
        ),
        migrations.AddField(
            model_name='gprsphotos',
            name='grps_photos_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
