# Generated by Django 4.0.5 on 2023-12-29 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0045_remove_gprsphotos_id_gprsphotos_grps_photos_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gprsphotos',
            old_name='grps_photos_id',
            new_name='gprs_photos_id',
        ),
    ]
