# Generated by Django 4.0.5 on 2024-01-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0046_rename_grps_photos_id_gprsphotos_gprs_photos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeoverresidenceaddress',
            name='any_other_earning_family_member',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='takeoverresidenceaddress',
            name='area_sqft',
            field=models.CharField(blank=True, choices=[('<400', '<400'), ('400-750', '400-750'), ('750-1000', '750-1000'), ('1000-1500', '1000-1500'), ('>1500', '>1500')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='takeoverresidenceaddress',
            name='family_member_employement_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='takeoverresidenceaddress',
            name='locating_address_difficulty',
            field=models.CharField(blank=True, choices=[('EASY', 'EASY'), ('MEDIUM', 'MEDIUM'), ('DIFFICULT', 'DIFFICULT')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='takeoverresidenceaddress',
            name='no_years_at_residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='takeoverresidenceaddress',
            name='person_met',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='takeoverresidenceaddress',
            name='prospect_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='takeoverresidenceaddress',
            name='relationship_with_applicant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='takeoverresidenceaddress',
            name='type_of_accomodation',
            field=models.CharField(blank=True, choices=[('LOW_INCOME', 'LOW_INCOME'), ('FLAT_APARTMENT', 'FLAT_APARTMENT'), ('BUNGALOW', 'BUNGALOW')], max_length=100, null=True),
        ),
    ]
