# Generated by Django 4.0.5 on 2024-01-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0048_alter_loan_purpose_of_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeoverresidenceaddress',
            name='no_adults',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='takeoverresidenceaddress',
            name='no_children',
            field=models.IntegerField(default=0),
        ),
    ]
