# Generated by Django 4.0.5 on 2024-02-06 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0049_takeoverresidenceaddress_no_adults_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanbillgeneration',
            name='emi_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_bill_emi_record', to='loan.loanemirecord'),
        ),
        migrations.AlterField(
            model_name='otherlenderapprainsal',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_lender_appraisal', to='loan.loan'),
        ),
    ]
