# Generated by Django 4.0.5 on 2024-02-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0050_alter_loanbillgeneration_emi_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanemirecord',
            name='bill_generation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
