# Generated by Django 4.0.5 on 2024-03-02 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0051_alter_loanemirecord_bill_generation_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoanBillGeneration',
            new_name='DemandGeneration',
        ),
    ]
