# Generated by Django 4.0.5 on 2024-03-07 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0052_rename_loanbillgeneration_demandgeneration'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantakeover',
            name='karat',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(22), django.core.validators.MinValueValidator(18)]),
        ),
    ]
