# Generated by Django 4.0.5 on 2024-03-07 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_whitegoods_available_in'),
        ('application', '0060_alter_application_eligible_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branch', '0008_stampdutycharges_minimum_amount_gte_maximum_amount'),
        ('lender', '0001_initial'),
        ('loan', '0052_rename_loanbillgeneration_demandgeneration'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLoan',
            fields=[
                ('loan_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('loan_number', models.CharField(db_index=True, max_length=18)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('SUBMITTED_TO_LENDER', 'SUBMITTED_TO_LENDER'), ('ASSET_COLLECTED', 'ASSET_COLLECTED'), ('Active - Good Standing', 'Active - Good Standing'), ('Active - Bad Standing', 'Active - Bad Standing'), ('Approved', 'Approved'), ('Closed - Obligations Met', 'Closed - Obligations Met')], default='NEW', max_length=100)),
                ('term', models.CharField(max_length=255)),
                ('intrest_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bm_comment', models.TextField(blank=True, null=True)),
                ('cpc_comment', models.TextField(blank=True, null=True)),
                ('processing_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stamp_duty', models.IntegerField(blank=True, null=True)),
                ('penalty', models.IntegerField(blank=True, null=True)),
                ('ltv', models.IntegerField(blank=True, null=True)),
                ('tenure', models.IntegerField(blank=True, null=True)),
                ('loan_amount', models.IntegerField()),
                ('loan_type', models.CharField(max_length=255)),
                ('days_past_dues', models.IntegerField()),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('purpose_of_loan', models.CharField(blank=True, choices=[('EDUCATIONAL', 'EDUCATIONAL'), ('MARRIAGE', 'MARRIAGE'), ('INCOME_GENERATION', 'INCOME_GENERATION'), ('MEDICAL_EMERGENCY', 'MEDICAL_EMERGENCY'), ('BROAD_CATEGORY', 'BROAD_CATEGORY'), ('PURCHASE_OF_ASSETS', 'PURCHASE_OF_ASSETS'), ('PURCHASE_OF_GOODS', 'PURCHASE_OF_GOODS'), ('LAND_DEVELOPMENT', 'LAND_DEVELOPMENT'), ('PURCHASE_OF_SEEDS', 'PURCHASE_OF_SEEDS'), ('PLANTATION_EXPENSES', 'PLANTATION_EXPENSES'), ('PURCHASE_OF_AGRICULTURAL_EQUIPMENTS', 'PURCHASE_OF_AGRICULTURAL_EQUIPMENTS'), ('PAYMENT_OF_LABOUR_EXPENSES', 'PAYMENT_OF_LABOUR_EXPENSES'), ('MEDICAL_EXPENSES', 'MEDICAL_EXPENSES'), ('TRAVEL_EXPENSES', 'TRAVEL_EXPENSES'), ('OTHERS', 'OTHERS')], max_length=300, null=True)),
                ('eligible_amount', models.IntegerField(blank=True, null=True)),
                ('total_goods_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('approvedByBMAt', models.DateTimeField(blank=True, editable=False, null=True)),
                ('approvedByCPCAt', models.DateTimeField(blank=True, editable=False, null=True)),
                ('current_gst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('gst', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('gold_rate_per_gram', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('lending_gold_rate_per_gram', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('disbursed_amount', models.IntegerField(blank=True, null=True)),
                ('disbursed_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('disbursal_amount', models.IntegerField(blank=True, null=True)),
                ('net_disbursed_amount', models.IntegerField(blank=True, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('current_emi', models.FloatField(blank=True, null=True)),
                ('interest_accrued_till_date', models.FloatField(blank=True, null=True)),
                ('principal_paid', models.FloatField(default=0)),
                ('interest_paid', models.FloatField(default=0)),
                ('penalty_paid', models.FloatField(default=0)),
                ('principal_remaining', models.FloatField(blank=True, null=True)),
                ('interest_remaining', models.FloatField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('next_due_generation_date', models.DateField(blank=True, null=True)),
                ('accrual_on_hold', models.BooleanField(default=False)),
                ('interest_last_accrued_on', models.DateField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Originatedby', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='application.application')),
                ('appraisedBy', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('approvedByBM', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('approvedByCPC', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='branch.branch')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lender', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lender.lender')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product')),
            ],
            options={
                'verbose_name': 'historical loan',
                'verbose_name_plural': 'historical loans',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
