# Generated by Django 4.0.5 on 2024-03-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0053_demandgeneration_interest_paid_and_more'),
        ('loan', '0053_loantakeover_karat'),
    ]

    operations = [
    ]
