# Generated by Django 4.0.5 on 2024-04-23 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0053_historicalloan'),
        ('loan', '0054_merge_20240311_1950'),
    ]

    operations = [
    ]
