# Generated by Django 4.0.5 on 2024-06-05 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_alter_account_status_alter_historicalaccount_status'),
        ('loan', '0055_merge_0053_historicalloan_0054_merge_20240311_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='gprsphotos',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_gprs_photos', to='account.account'),
        ),
    ]
