# Generated by Django 4.0.5 on 2024-06-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0057_alter_historicalloan_purpose_of_loan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gprsphotos',
            name='photo_type',
            field=models.CharField(choices=[('IMAGE_OF_HOUSE_WITH_PERSON_STANDING_AT_THE_GATE', 'IMAGE_OF_HOUSE_WITH_PERSON_STANDING_AT_THE_GATE'), ('IMAGE_OF_SHOP_WITH_PERSON_STANDING_AT_THE_GATE', 'IMAGE_OF_SHOP_WITH_PERSON_STANDING_AT_THE_GATE'), ('IMAGE_OF_INSIDE_THE_SHOP', 'IMAGE_OF_INSIDE_THE_SHOP'), ('OTHERS', 'OTHERS')], default='OTHERS', max_length=100),
        ),
    ]
