# Generated by Django 4.0.5 on 2024-06-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0058_gprsphotos_photo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gprsphotos',
            name='photo_type',
            field=models.CharField(blank=True, choices=[('IMAGE_OF_HOUSE_WITH_PERSON_STANDING_AT_THE_GATE', 'IMAGE_OF_HOUSE_WITH_PERSON_STANDING_AT_THE_GATE'), ('IMAGE_OF_SHOP_WITH_PERSON_STANDING_AT_THE_GATE', 'IMAGE_OF_SHOP_WITH_PERSON_STANDING_AT_THE_GATE'), ('IMAGE_OF_INSIDE_THE_SHOP', 'IMAGE_OF_INSIDE_THE_SHOP'), ('OTHERS', 'OTHERS')], max_length=100, null=True),
        ),
    ]
