# Generated by Django 4.0.5 on 2024-12-27 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0079_alter_application_application_loan_type_and_more'),
        ('loan', '0060_alter_gprsphotos_photo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gprsphotos',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_gprs_photos', to='application.application'),
        ),
    ]
