# Generated by Django 4.0.5 on 2025-01-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0062_alter_gprsphotos_photo_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gprsphotos',
            name='photo_type',
            field=models.CharField(blank=True, choices=[('IMAGE_OF_HOUSE_WITH_PERSON_STANDING_AT_THE_GATE', 'IMAGE_OF_HOUSE_WITH_PERSON_STANDING_AT_THE_GATE'), ('IMAGE_OF_SHOP_WITH_PERSON_STANDING_AT_THE_GATE', 'IMAGE_OF_SHOP_WITH_PERSON_STANDING_AT_THE_GATE'), ('IMAGE_OF_INSIDE_THE_SHOP', 'IMAGE_OF_INSIDE_THE_SHOP'), ('OTHERS', 'OTHERS'), ('CO_IMAGE_OF_HOUSE_WITH_PERSON_STANDING_AT_THE_GATE', 'CO_IMAGE_OF_HOUSE_WITH_PERSON_STANDING_AT_THE_GATE'), ('CO_IMAGE_OF_SHOP_WITH_PERSON_STANDING_AT_THE_GATE', 'CO_IMAGE_OF_SHOP_WITH_PERSON_STANDING_AT_THE_GATE'), ('CO_IMAGE_OF_INSIDE_THE_SHOP', 'CO_IMAGE_OF_INSIDE_THE_SHOP'), ('CO_OTHERS', 'CO_OTHERS'), ('AGRI_IMAGE_1', 'AGRI_IMAGE_1'), ('AGRI_IMAGE_2', 'AGRI_IMAGE_2'), ('AGRI_IMAGE_3', 'AGRI_IMAGE_3'), ('AGRI_IMAGE_4', 'AGRI_IMAGE_4'), ('CO_AGRI_IMAGE_1', 'CO_AGRI_IMAGE_1'), ('CO_AGRI_IMAGE_2', 'CO_AGRI_IMAGE_2'), ('CO_AGRI_IMAGE_3', 'CO_AGRI_IMAGE_3'), ('CO_AGRI_IMAGE_4', 'CO_AGRI_IMAGE_4')], max_length=100, null=True),
        ),
    ]
