# Generated by Django 4.0.5 on 2024-05-28 13:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditStatus',
            fields=[
                ('credit_status_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('house_ownership', models.CharField(choices=[('OWN', 'OWN'), ('RENT', 'RENT')], max_length=20)),
                ('house_number_of_year', models.CharField(choices=[('LESS_THAN_2', 'LESS_THAN_2'), ('2_TO_10', '2_TO_10'), ('MORE_THAN_10', 'MORE_THAN_10')], max_length=20)),
                ('shop_ownership', models.CharField(choices=[('OWN', 'OWN'), ('RENT', 'RENT')], max_length=20)),
                ('shop_number_of_year', models.CharField(choices=[('LESS_THAN_2', 'LESS_THAN_2'), ('2_TO_10', '2_TO_10'), ('MORE_THAN_10', 'MORE_THAN_10')], max_length=20)),
                ('nature_of_business', models.CharField(choices=[('RETAIL', 'RETAIL'), ('TRADERS', 'TRADERS'), ('ALLIED_AGRI', 'ALLIED_AGRI'), ('AGRI', 'AGRI')], max_length=20)),
                ('monthly_income', models.IntegerField()),
                ('monthly_expenditure', models.IntegerField()),
                ('no_of_loans_running', models.IntegerField()),
                ('no_of_loans_closed_in_last_1_year', models.IntegerField()),
                ('any_loan_applied_in_last_30_days', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20)),
                ('account_held_for_no_of_years', models.IntegerField()),
                ('fixed_assets_held_by_him_and_family', models.CharField(max_length=500)),
            ],
        ),
    ]
