# Generated by Django 4.0.5 on 2024-05-29 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_account_status_alter_historicalaccount_status'),
        ('credit_status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditstatus',
            name='account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='creditstatus_account', to='account.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='creditstatus',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
