# Generated by Django 4.0.5 on 2024-05-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_status', '0002_creditstatus_account_creditstatus_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditstatus',
            name='house_ownership',
            field=models.CharField(choices=[('OWN', 'OWN'), ('RENTED', 'RENTED')], max_length=20),
        ),
        migrations.AlterField(
            model_name='creditstatus',
            name='shop_ownership',
            field=models.CharField(choices=[('OWN', 'OWN'), ('RENTED', 'RENTED')], max_length=20),
        ),
    ]
