# Generated by Django 4.0.5 on 2024-12-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_status', '0003_alter_creditstatus_house_ownership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditstatus',
            name='nob_others',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='creditstatus',
            name='nature_of_business',
            field=models.CharField(choices=[('RETAIL', 'RETAIL'), ('TRADERS', 'TRADERS'), ('ALLIED_AGRI', 'ALLIED_AGRI'), ('AGRI', 'AGRI'), ('CROP', 'CROP'), ('DAIRY', 'DAIRY'), ('CROP_AND_DAIRY', 'CROP_AND_DAIRY'), ('OTHERS', 'OTHERS')], max_length=20),
        ),
    ]
