server {
    listen 8000;
    listen [::]:8000;
    server_name              dev-api.radianfinserv.com;
    client_max_body_size     5M;

    # location /static {
    #     alias /app/static;
    # }

    # location /media {
    #     alias /app/media;
    # }

    location / {
        proxy_pass http://localhost:8000;
        # proxy_pass http://localhost:8443;
        # proxy_pass http://unix:/app/radian.sock;
    }
}

# sudo certbot --nginx -d dev-api.radianfinserv.com -m service@getafixtechnologies.com -n --agree-tos
# sudo certbot --nginx -d uat-api.radianfinserv.com -m service@getafixtechnologies.com -n --agree-tos

# sudo fuser -k 80/tcp
# sudo fuser -k 443/tcp