FROM nginx:stable-alpine as builder
RUN rm -f /etc/nginx/conf.d/*
COPY docker/nginx/conf/api_gateway.conf /etc/nginx/templates/api_gateway.conf.template

# #maintainer
# LABEL Author="Getafix Technologies Pvt Ltd"


# RUN rm -r /etc/nginx/conf.d/
# COPY docker/nginx/backend.conf /etc/nginx/conf.d/backend.conf


# RUN apk add python3 python3-dev py3-pip build-base libressl-dev musl-dev libffi-dev rust cargo
# RUN pip3 install pip --upgrade
# RUN pip3 install certbot-nginx
# RUN mkdir /etc/letsencrypt

# # Add the cron job
# RUN crontab -l | { cat; echo "0 12 * * * /usr/bin/certbot renew --quiet"; } | crontab -

# # ENTRYPOINT certbot --nginx -d yourdomain.com -d www.yourdomain.com
# ARG DOMAIN_NAME
# RUN certbot --nginx -d ${DOMAIN_NAME} -m service@getafixtechnologies.com -n --agree-tos
# # RUN certbot --nginx -d dev-api.radianfinserv.com -m service@getafixtechnologies.com -n --agree-tos

# CMD ["nginx", "-g", "daemon off;"]



