server {
    listen 80;
    listen [::]:80;
    server_name              dev-app.radianfinserv.com;
    client_max_body_size     5M;
    
    # root /var/www/html;

    # # Add index.php to the list if you are using PHP
    # index index.html index.htm index.nginx-debian.html;

    # server_name _;

    # location / {
    #         # First attempt to serve request as file, then
    #         # as directory, then fall back to displaying a 404.
    #         try_files $uri $uri/ =404;
    # }

    location / {
        proxy_pass http://localhost:8080;
    }
}

# sudo certbot --nginx -d dev-app.radianfinserv.com -m service@getafixtechnologies.com -n --agree-tos
# sudo certbot --nginx -d uat-app.radianfinserv.com -m service@getafixtechnologies.com -n --agree-tos

# sudo fuser -k 80/tcp
# sudo fuser -k 443/tcp