# Generated by Django 4.0.5 on 2025-11-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('group_id', models.CharField(blank=True, max_length=100, null=True)),
                ('response_code', models.CharField(blank=True, max_length=20, null=True)),
                ('response_message', models.CharField(blank=True, max_length=255, null=True)),
                ('billable', models.CharField(blank=True, max_length=5, null=True)),
                ('pan_number', models.CharField(max_length=20)),
                ('pan_holder_name', models.CharField(max_length=150)),
                ('name_match_score', models.CharField(blank=True, max_length=10, null=True)),
                ('pan_type', models.CharField(blank=True, max_length=50, null=True)),
                ('aadhaar_linked_status', models.BooleanField(default=False)),
                ('masked_aadhaar', models.CharField(blank=True, max_length=20, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('user_dob', models.CharField(blank=True, max_length=20, null=True)),
                ('user_address', models.JSONField(blank=True, null=True)),
                ('request_timestamp', models.CharField(blank=True, max_length=50, null=True)),
                ('response_timestamp', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
