# Generated by Django 4.0.5 on 2025-11-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=20)),
                ('name_to_match', models.CharField(max_length=100)),
                ('consent', models.CharField(default='Y', max_length=1)),
                ('consent_text', models.TextField(default='I hereby declare my consent agreement for fetching my information via ZOOP API')),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('group_id', models.CharField(blank=True, max_length=100, null=True)),
                ('success', models.BooleanField(default=False)),
                ('response_code', models.CharField(blank=True, max_length=50, null=True)),
                ('response_message', models.CharField(blank=True, max_length=200, null=True)),
                ('beneficiary_name', models.CharField(blank=True, max_length=150, null=True)),
                ('verification_status', models.CharField(blank=True, max_length=50, null=True)),
                ('name_match_score', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
