# Generated by Django 4.0.5 on 2025-11-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoop', '0002_bankverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingLicenceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_dl_number', models.CharField(max_length=20)),
                ('name_to_match', models.CharField(max_length=100)),
                ('customer_dob', models.CharField(max_length=20)),
                ('consent', models.CharField(default='Y', max_length=5)),
                ('consent_text', models.TextField()),
                ('request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('group_id', models.CharField(blank=True, max_length=100, null=True)),
                ('success', models.BooleanField(default=False)),
                ('response_code', models.CharField(blank=True, max_length=10, null=True)),
                ('response_message', models.CharField(blank=True, max_length=255, null=True)),
                ('user_full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_dob', models.CharField(blank=True, max_length=20, null=True)),
                ('father_or_husband', models.CharField(blank=True, max_length=100, null=True)),
                ('dl_number', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=20, null=True)),
                ('user_blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('name_match_score', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pin', models.CharField(blank=True, max_length=10, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('address_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
