# Generated by Django 4.0.5 on 2025-11-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoop', '0003_drivinglicenceverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeOCRVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_image', models.TextField()),
                ('consent', models.CharField(default='Y', max_length=5)),
                ('consent_text', models.TextField()),
                ('request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('group_id', models.CharField(blank=True, max_length=100, null=True)),
                ('success', models.BooleanField(default=False)),
                ('response_code', models.CharField(blank=True, max_length=10, null=True)),
                ('response_message', models.CharField(blank=True, max_length=255, null=True)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=50, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('request_timestamp', models.CharField(blank=True, max_length=50, null=True)),
                ('response_timestamp', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
