# Generated by Django 4.0.5 on 2025-11-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoop', '0004_chequeocrverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRLiteVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_front_image', models.TextField()),
                ('card_back_image', models.TextField(blank=True, null=True)),
                ('card_type', models.CharField(max_length=20)),
                ('consent', models.CharField(default='Y', max_length=1)),
                ('consent_text', models.TextField(default='I hereby declare my consent agreement for fetching my information via Zoop API')),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
