# Generated by Django 4.0.5 on 2025-11-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoop', '0005_ocrliteverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrliteverification',
            name='card_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='ocr_lite/'),
        ),
        migrations.AlterField(
            model_name='ocrliteverification',
            name='card_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='ocr_lite/'),
        ),
    ]
