# Generated by Django 4.0.5 on 2025-11-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoop', '0006_alter_ocrliteverification_card_back_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrliteverification',
            name='card_type',
            field=models.CharField(choices=[('PAN', 'PAN Card'), ('AADHAAR', 'Aadhaar Card'), ('DRIVING_LICENSE', 'Driving License'), ('VOTER_ID', 'Voter ID'), ('PASSPORT', 'Passport'), ('OTHER', 'Other')], default='PAN', max_length=20),
        ),
    ]
