# Generated by Django 4.0.5 on 2025-11-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoop', '0007_alter_ocrliteverification_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankverification',
            name='is_penny_drop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankverification',
            name='penny_drop_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bankverification',
            name='penny_drop_txn_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
