# Generated by Django 4.0.5 on 2025-11-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoop', '0008_bankverification_is_penny_drop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterIDAdvanceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_epic_number', models.CharField(max_length=50)),
                ('name_to_match', models.CharField(max_length=255)),
                ('consent', models.CharField(default='Y', max_length=1)),
                ('consent_text', models.TextField(default='I hereby declare my consent agreement for fetching my information via Zoop API')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('group_id', models.CharField(blank=True, max_length=255, null=True)),
                ('success', models.BooleanField(default=False)),
                ('response_code', models.CharField(blank=True, max_length=50, null=True)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('user_name_english', models.CharField(blank=True, max_length=255, null=True)),
                ('user_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('user_age', models.IntegerField(blank=True, null=True)),
                ('relative_name_english', models.CharField(blank=True, max_length=255, null=True)),
                ('relative_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_number_applicable_part', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('epic_number', models.CharField(blank=True, max_length=50, null=True)),
                ('voter_last_updated_date', models.CharField(blank=True, max_length=100, null=True)),
                ('name_match_score', models.CharField(blank=True, max_length=20, null=True)),
                ('district_name', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('assembly_constituency_name', models.CharField(blank=True, max_length=255, null=True)),
                ('request_timestamp', models.CharField(blank=True, max_length=100, null=True)),
                ('response_timestamp', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
