# Generated by Django 4.0.5 on 2025-11-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoop', '0009_voteridadvanceverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteridadvanceverification',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='voteridadvanceverification',
            name='epic_number',
        ),
        migrations.RemoveField(
            model_name='voteridadvanceverification',
            name='name_match_score',
        ),
        migrations.RemoveField(
            model_name='voteridadvanceverification',
            name='request_timestamp',
        ),
        migrations.RemoveField(
            model_name='voteridadvanceverification',
            name='response_timestamp',
        ),
        migrations.RemoveField(
            model_name='voteridadvanceverification',
            name='state',
        ),
        migrations.AddField(
            model_name='voteridadvanceverification',
            name='constituency_part_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voteridadvanceverification',
            name='relative_name_vernacular',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='voteridadvanceverification',
            name='user_name_vernacular',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='voteridadvanceverification',
            name='assembly_constituency_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='voteridadvanceverification',
            name='consent_text',
            field=models.TextField(default='I hereby consent'),
        ),
        migrations.AlterField(
            model_name='voteridadvanceverification',
            name='group_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voteridadvanceverification',
            name='name_to_match',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='voteridadvanceverification',
            name='relative_name_english',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='voteridadvanceverification',
            name='relative_relation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='voteridadvanceverification',
            name='request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voteridadvanceverification',
            name='response_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='voteridadvanceverification',
            name='response_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='voteridadvanceverification',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voteridadvanceverification',
            name='user_name_english',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
