# Generated by Django 4.0.5 on 2025-11-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoop', '0010_remove_voteridadvanceverification_district_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportAdvanceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_file_number', models.CharField(max_length=50)),
                ('name_to_match', models.CharField(max_length=100)),
                ('customer_dob', models.CharField(max_length=20)),
                ('consent', models.CharField(default='Y', max_length=1)),
                ('consent_text', models.TextField(default='I hereby give my consent')),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('group_id', models.CharField(blank=True, max_length=100, null=True)),
                ('success', models.BooleanField(default=False)),
                ('response_code', models.CharField(blank=True, max_length=10, null=True)),
                ('response_message', models.CharField(blank=True, max_length=255, null=True)),
                ('passport_status', models.BooleanField(blank=True, null=True)),
                ('name_on_passport', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_applied_date', models.CharField(blank=True, max_length=50, null=True)),
                ('name_match_score', models.CharField(blank=True, max_length=10, null=True)),
                ('customer_dob_result', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
