# Generated by Django 4.0.5 on 2026-06-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoop', '0011_passportadvanceverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceMatchVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_image', models.TextField()),
                ('user_image', models.TextField()),
                ('consent', models.CharField(default='Y', max_length=1)),
                ('consent_text', models.TextField(default='I hereby declare my consent agreement for fetching my information via ZOOP API')),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('group_id', models.CharField(blank=True, max_length=100, null=True)),
                ('success', models.BooleanField(default=False)),
                ('response_code', models.CharField(blank=True, max_length=10, null=True)),
                ('response_message', models.CharField(blank=True, max_length=255, null=True)),
                ('billable', models.CharField(blank=True, max_length=5, null=True)),
                ('reason_message', models.CharField(blank=True, max_length=255, null=True)),
                ('face_match_score', models.CharField(blank=True, max_length=10, null=True)),
                ('request_timestamp', models.CharField(blank=True, max_length=50, null=True)),
                ('response_timestamp', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
