# Generated by Django 4.0.5 on 2024-06-09 16:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0062_alter_application_total_asset_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreMeBankAnalysis',
            fields=[
                ('score_me_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reference_id', models.CharField(blank=True, max_length=64, null=True)),
                ('json_url', models.TextField(blank=True, null=True)),
                ('excel_url', models.TextField(blank=True, null=True)),
                ('json_file', models.FileField(blank=True, max_length=225, null=True, upload_to='media/application_doc/bank_statement_reports')),
                ('excel_file', models.FileField(blank=True, max_length=225, null=True, upload_to='media/application_doc/bank_statement_reports')),
                ('webhook_response', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_me_application', to='application.application')),
            ],
        ),
    ]
