# Generated by Django 4.0.5 on 2024-06-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoremebankanalysis',
            name='average_monthly_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoremebankanalysis',
            name='cash_flow',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoremebankanalysis',
            name='leverage_to_income',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
