# Generated by Django 4.0.5 on 2024-07-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreme', '0002_scoremebankanalysis_average_monthly_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoremebankanalysis',
            name='excel_file',
        ),
        migrations.RemoveField(
            model_name='scoremebankanalysis',
            name='json_file',
        ),
    ]
