# Generated by Django 4.0.5 on 2026-07-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crif_bureau', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crifbureautrace',
            name='pdf_report_link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='crifbureautrace',
            name='reference_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
