# Generated by Django 4.0.5 on 2026-07-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crif_bureau', '0002_crifbureautrace_pdf_report_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrifBureauReportTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=15, unique=True)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('pdf_report_link', models.CharField(blank=True, max_length=512, null=True)),
                ('phone_to_pan_request', models.JSONField(blank=True, default=dict)),
                ('phone_to_pan_response', models.JSONField(blank=True, default=dict)),
                ('report_request_payload', models.JSONField(blank=True, default=dict)),
                ('report_response_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
