# Generated by Django 4.0.5 on 2025-10-20 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('task_summary', models.CharField(max_length=255)),
                ('is_auto_reject', models.BooleanField(default=False)),
                ('auto_reject_time', models.CharField(blank=True, max_length=100, null=True)),
                ('total_reward_assigned', models.IntegerField(default=0)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('upload_customer_data', models.FileField(blank=True, null=True, upload_to='uploads/customers/')),
                ('upload_employee_file', models.FileField(blank=True, null=True, upload_to='uploads/employees/')),
                ('state', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('team', models.CharField(blank=True, max_length=100)),
                ('badge', models.CharField(blank=True, max_length=100)),
                ('cumulative_amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition', models.CharField(choices=[('MANDATORY', 'Mandatory'), ('NON_MANDATORY', 'Non Mandatory')], default='MANDATORY', max_length=20)),
                ('reward', models.IntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flows.flow')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_flow_entries', to='tasks.task')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('task', 'flow')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='flows',
            field=models.ManyToManyField(related_name='tasks', through='tasks.TaskFlow', to='flows.flow'),
        ),
        migrations.AddField(
            model_name='task',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=255)),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('contact_no', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subtasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks_modified', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task')),
            ],
        ),
    ]
