# Generated by Django 4.0.5 on 2025-10-31 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='address',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='organization_name',
        ),
        migrations.AddField(
            model_name='subtask',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='contact_person_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('FIRM', 'FIRM'), ('INDIVIDUAL', 'INDIVIDUAL')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='organisation_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtask',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='registered_mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='sub_task_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='type_of_user',
            field=models.CharField(blank=True, choices=[('BANK', 'BANK'), ('CUSTOMER', 'CUSTOMER'), ('MERCHANT', 'MERCHANT')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='unique_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='verification_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='taskflow',
            name='condition',
            field=models.CharField(choices=[('MANDATORY', 'MANDATORY'), ('NON_MANDATORY', 'NON_MANDATORY')], default='MANDATORY', max_length=20),
        ),
        migrations.AlterModelTable(
            name='subtask',
            table='sub_tasks',
        ),
    ]
