# Generated by Django 4.0.5 on 2025-11-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_subtask_options_remove_subtask_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='sub_task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
