# Generated by Django 4.0.5 on 2025-11-09 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flows', '0002_flow_expected_duration'),
        ('tasks', '0003_alter_subtask_sub_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW_TASK', 'NEW_TASK'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='SubTaskTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flow_status', models.CharField(blank=True, choices=[('LOCATION_VERIFICATION_STARTED', 'LOCATION_VERIFICATION_STARTED'), ('FLOW_COMPLETED', 'FLOW_COMPLETED'), ('REACHED_ADDRESS', 'REACHED_ADDRESS'), ('LOCATION_PHOTO_ADDED', 'LOCATION_PHOTO_ADDED'), ('SELFIE_PHOTO_ADDED', 'SELFIE_PHOTO_ADDED'), ('VERIFIED_BY_CENTRAL_OPS', 'VERIFIED_BY_CENTRAL_OPS'), ('REJECTED_BY_CENTRAL_OPS', 'REJECTED_BY_CENTRAL_OPS')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks_tracker_created', to=settings.AUTH_USER_MODEL)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks_flow_tracker', to='flows.flow')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks_tracker_modified', to=settings.AUTH_USER_MODEL)),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='tasks.subtask')),
            ],
        ),
        migrations.CreateModel(
            name='SubTaskDocument',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_flow', models.CharField(blank=True, choices=[('LOCATION_VERIFICATION', 'LOCATION_VERIFICATION')], max_length=50, null=True)),
                ('document_type', models.CharField(blank=True, choices=[('LOCATION_PHOTO', 'LOCATION_PHOTO'), ('SELFIE_PHOTO', 'SELFIE_PHOTO')], max_length=50, null=True)),
                ('file_name', models.CharField(blank=True, max_length=225, null=True)),
                ('file', models.FileField(max_length=225, upload_to='media/subtask_doc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('subtask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtask_document', to='tasks.subtask')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FLOW_DOC_USER', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
