# Generated by Django 4.0.5 on 2025-11-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_subtask_status_subtasktracker_subtaskdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtasktracker',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
