# Generated by Django 4.0.5 on 2025-11-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_subtasktracker_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtasktracker',
            name='step_timestamps',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='subtasktracker',
            name='flow_status',
            field=models.CharField(blank=True, choices=[('LOCATION_VERIFICATION_STARTED', 'LOCATION_VERIFICATION_STARTED'), ('LOCATION_VERIFICATION_COMPLETED', 'LOCATION_VERIFICATION_COMPLETED'), ('LOCATION_RE_VERIFICATION', 'LOCATION_RE_VERIFICATION'), ('LOCATION_RE_VERIFICATION_COMPLETED', 'LOCATION_RE_VERIFICATION_COMPLETED'), ('UPLOAD_KYC_DOCUMENTS_STARTED', 'UPLOAD_KYC_DOCUMENTS_STARTED'), ('UPLOAD_KYC_DOCUMENTS_COMPLETED', 'UPLOAD_KYC_DOCUMENTS_COMPLETED'), ('LEAD_GENERATION_STARTED', 'LEAD_GENERATION_STARTED'), ('LEAD_GENERATION_COMPLETED', 'LEAD_GENERATION_COMPLETED'), ('LEAD_CLOSURE_STARTED', 'LEAD_CLOSURE_STARTED'), ('LEAD_CLOSURE_COMPLETED', 'LEAD_CLOSURE_COMPLETED'), ('QUESTIONNAIRE_STARTED', 'QUESTIONNAIRE_STARTED'), ('QUESTIONNAIRE_COMPLETED', 'QUESTIONNAIRE_COMPLETED'), ('REACHED_ADDRESS', 'REACHED_ADDRESS'), ('LOCATION_PHOTO_ADDED', 'LOCATION_PHOTO_ADDED'), ('SELFIE_PHOTO_ADDED', 'SELFIE_PHOTO_ADDED'), ('VERIFIED_BY_CENTRAL_OPS', 'VERIFIED_BY_CENTRAL_OPS'), ('REJECTED_BY_CENTRAL_OPS', 'REJECTED_BY_CENTRAL_OPS')], max_length=50, null=True),
        ),
    ]
