# Generated by Django 4.0.5 on 2025-11-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_subtasktracker_step_timestamps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtaskdocument',
            name='document_flow',
            field=models.CharField(blank=True, choices=[('LOCATION_VERIFICATION', 'LOCATION_VERIFICATION'), ('LOCATION_REVERIFICATION', 'LOCATION_REVERIFICATION')], max_length=50, null=True),
        ),
    ]
