# Generated by Django 4.0.5 on 2025-11-11 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0007_alter_subtaskdocument_document_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtasktracker',
            name='central_ops_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='central_ops_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='central_ops_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks_tracker_central_ops', to=settings.AUTH_USER_MODEL),
        ),
    ]
