# Generated by Django 4.0.5 on 2025-11-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_subtasktracker_central_ops_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtasktracker',
            name='is_last',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='reward',
            field=models.IntegerField(default=0),
        ),
    ]
