# Generated by Django 4.0.5 on 2025-11-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_subtasktracker_is_last_subtasktracker_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtasktracker',
            name='is_aadhar_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='is_pan_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='other_document',
            field=models.CharField(blank=True, choices=[('DRIVING_LICENSE', 'DRIVING_LICENSE'), ('VOTER_ID', 'VOTER_ID'), ('PASSPORT', 'PASSPORT')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='other_document_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='pan_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='pan_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtaskdocument',
            name='document_flow',
            field=models.CharField(blank=True, choices=[('LOCATION_VERIFICATION', 'LOCATION_VERIFICATION'), ('LOCATION_REVERIFICATION', 'LOCATION_REVERIFICATION'), ('KYC_DOCUMENT_UPLOAD', 'KYC_DOCUMENT_UPLOAD'), ('LEAD_GENERATION', 'LEAD_GENERATION')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subtaskdocument',
            name='document_type',
            field=models.CharField(blank=True, choices=[('LOCATION_PHOTO', 'LOCATION_PHOTO'), ('SELFIE_PHOTO', 'SELFIE_PHOTO'), ('PAN_CARD', 'PAN_CARD'), ('FRONT_AADHAR_CARD', 'FRONT_AADHAR_CARD'), ('BACK_AADHAR_CARD', 'BACK_AADHAR_CARD'), ('PASSPORT', 'PASSPORT'), ('DRIVING_LICENSE', 'DRIVING_LICENSE'), ('VOTER_ID', 'VOTER_ID')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subtasktracker',
            name='flow_status',
            field=models.CharField(blank=True, choices=[('LOCATION_VERIFICATION_STARTED', 'LOCATION_VERIFICATION_STARTED'), ('LOCATION_VERIFICATION_COMPLETED', 'LOCATION_VERIFICATION_COMPLETED'), ('LOCATION_RE_VERIFICATION', 'LOCATION_RE_VERIFICATION'), ('LOCATION_RE_VERIFICATION_COMPLETED', 'LOCATION_RE_VERIFICATION_COMPLETED'), ('UPLOAD_KYC_DOCUMENTS_STARTED', 'UPLOAD_KYC_DOCUMENTS_STARTED'), ('UPLOAD_KYC_DOCUMENTS_COMPLETED', 'UPLOAD_KYC_DOCUMENTS_COMPLETED'), ('LEAD_GENERATION_STARTED', 'LEAD_GENERATION_STARTED'), ('LEAD_GENERATION_COMPLETED', 'LEAD_GENERATION_COMPLETED'), ('LEAD_CLOSURE_STARTED', 'LEAD_CLOSURE_STARTED'), ('LEAD_CLOSURE_COMPLETED', 'LEAD_CLOSURE_COMPLETED'), ('QUESTIONNAIRE_STARTED', 'QUESTIONNAIRE_STARTED'), ('QUESTIONNAIRE_COMPLETED', 'QUESTIONNAIRE_COMPLETED'), ('REACHED_ADDRESS', 'REACHED_ADDRESS'), ('LOCATION_PHOTO_ADDED', 'LOCATION_PHOTO_ADDED'), ('SELFIE_PHOTO_ADDED', 'SELFIE_PHOTO_ADDED'), ('VERIFIED_BY_CENTRAL_OPS', 'VERIFIED_BY_CENTRAL_OPS'), ('SENT_BACK_BY_CENTRAL_OPS', 'SENT_BACK_BY_CENTRAL_OPS'), ('SENT_TO_CENTRAL_OPS', 'SENT_TO_CENTRAL_OPS'), ('AADHAR_CARD_VERIFIED', 'AADHAR_CARD_VERIFIED'), ('PAN_CARD_VERIFIED', 'PAN_CARD_VERIFIED'), ('CUSTOMER_DETAILS_ADDED', 'CUSTOMER_DETAILS_ADDED'), ('CUSTOMER_ADDRESS_ADDED', 'CUSTOMER_ADDRESS_ADDED')], max_length=50, null=True),
        ),
    ]
