# Generated by Django 4.0.5 on 2025-11-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_subtasktracker_is_aadhar_verify_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtasktracker',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='current_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='current_address_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='current_address_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='current_address_pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='current_address_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='father_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='is_whatsapp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='is_zoop_pan_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='permanent_address_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='permanent_address_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='permanent_address_pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='permanent_address_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='subtaskdocument',
            name='document_type',
            field=models.CharField(blank=True, choices=[('LOCATION_PHOTO', 'LOCATION_PHOTO'), ('SELFIE_PHOTO', 'SELFIE_PHOTO'), ('PAN_CARD', 'PAN_CARD'), ('FRONT_AADHAR_CARD', 'FRONT_AADHAR_CARD'), ('BACK_AADHAR_CARD', 'BACK_AADHAR_CARD'), ('FRONT_PASSPORT', 'FRONT_PASSPORT'), ('BACK_PASSPORT', 'BACK_PASSPORT'), ('FRONT_DRIVING_LICENSE', 'FRONT_DRIVING_LICENSE'), ('BACK_DRIVING_LICENSE', 'BACK_DRIVING_LICENSE'), ('FRONT_VOTER_ID', 'FRONT_VOTER_ID'), ('BACK_VOTER_ID', 'BACK_VOTER_ID'), ('PROFILE_PIC', 'PROFILE_PIC')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subtasktracker',
            name='flow_status',
            field=models.CharField(blank=True, choices=[('LOCATION_VERIFICATION_STARTED', 'LOCATION_VERIFICATION_STARTED'), ('LOCATION_VERIFICATION_COMPLETED', 'LOCATION_VERIFICATION_COMPLETED'), ('LOCATION_RE_VERIFICATION', 'LOCATION_RE_VERIFICATION'), ('LOCATION_RE_VERIFICATION_COMPLETED', 'LOCATION_RE_VERIFICATION_COMPLETED'), ('UPLOAD_KYC_DOCUMENTS_STARTED', 'UPLOAD_KYC_DOCUMENTS_STARTED'), ('UPLOAD_KYC_DOCUMENTS_COMPLETED', 'UPLOAD_KYC_DOCUMENTS_COMPLETED'), ('LEAD_GENERATION_STARTED', 'LEAD_GENERATION_STARTED'), ('LEAD_GENERATION_COMPLETED', 'LEAD_GENERATION_COMPLETED'), ('LEAD_CLOSURE_STARTED', 'LEAD_CLOSURE_STARTED'), ('LEAD_CLOSURE_COMPLETED', 'LEAD_CLOSURE_COMPLETED'), ('QUESTIONNAIRE_STARTED', 'QUESTIONNAIRE_STARTED'), ('QUESTIONNAIRE_COMPLETED', 'QUESTIONNAIRE_COMPLETED'), ('REACHED_ADDRESS', 'REACHED_ADDRESS'), ('LOCATION_PHOTO_ADDED', 'LOCATION_PHOTO_ADDED'), ('SELFIE_PHOTO_ADDED', 'SELFIE_PHOTO_ADDED'), ('VERIFIED_BY_CENTRAL_OPS', 'VERIFIED_BY_CENTRAL_OPS'), ('SENT_BACK_BY_CENTRAL_OPS', 'SENT_BACK_BY_CENTRAL_OPS'), ('SENT_TO_CENTRAL_OPS', 'SENT_TO_CENTRAL_OPS'), ('AADHAR_CARD_VERIFIED', 'AADHAR_CARD_VERIFIED'), ('PAN_CARD_VERIFIED', 'PAN_CARD_VERIFIED'), ('OTHER_DOCUMENTS_VERIFIED', 'OTHER_DOCUMENTS_VERIFIED'), ('CUSTOMER_DETAILS_ADDED', 'CUSTOMER_DETAILS_ADDED'), ('CUSTOMER_ADDRESS_ADDED', 'CUSTOMER_ADDRESS_ADDED')], max_length=50, null=True),
        ),
    ]
