# Generated by Django 4.0.5 on 2025-11-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_subtasktracker_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtasktracker',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='product_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='product_sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subtasktracker',
            name='flow_status',
            field=models.CharField(blank=True, choices=[('LOCATION_VERIFICATION_STARTED', 'LOCATION_VERIFICATION_STARTED'), ('LOCATION_VERIFICATION_COMPLETED', 'LOCATION_VERIFICATION_COMPLETED'), ('LOCATION_RE_VERIFICATION', 'LOCATION_RE_VERIFICATION'), ('LOCATION_RE_VERIFICATION_COMPLETED', 'LOCATION_RE_VERIFICATION_COMPLETED'), ('UPLOAD_KYC_DOCUMENTS_STARTED', 'UPLOAD_KYC_DOCUMENTS_STARTED'), ('UPLOAD_KYC_DOCUMENTS_COMPLETED', 'UPLOAD_KYC_DOCUMENTS_COMPLETED'), ('LEAD_GENERATION_STARTED', 'LEAD_GENERATION_STARTED'), ('LEAD_GENERATION_COMPLETED', 'LEAD_GENERATION_COMPLETED'), ('LEAD_CLOSURE_STARTED', 'LEAD_CLOSURE_STARTED'), ('LEAD_CLOSURE_COMPLETED', 'LEAD_CLOSURE_COMPLETED'), ('QUESTIONNAIRE_STARTED', 'QUESTIONNAIRE_STARTED'), ('QUESTIONNAIRE_COMPLETED', 'QUESTIONNAIRE_COMPLETED'), ('REACHED_ADDRESS', 'REACHED_ADDRESS'), ('LOCATION_PHOTO_ADDED', 'LOCATION_PHOTO_ADDED'), ('SELFIE_PHOTO_ADDED', 'SELFIE_PHOTO_ADDED'), ('VERIFIED_BY_CENTRAL_OPS', 'VERIFIED_BY_CENTRAL_OPS'), ('SENT_BACK_BY_CENTRAL_OPS', 'SENT_BACK_BY_CENTRAL_OPS'), ('SENT_TO_CENTRAL_OPS', 'SENT_TO_CENTRAL_OPS'), ('AADHAR_CARD_VERIFIED', 'AADHAR_CARD_VERIFIED'), ('PAN_CARD_VERIFIED', 'PAN_CARD_VERIFIED'), ('OTHER_DOCUMENTS_VERIFIED', 'OTHER_DOCUMENTS_VERIFIED'), ('CUSTOMER_DETAILS_ADDED', 'CUSTOMER_DETAILS_ADDED'), ('CUSTOMER_ADDRESS_ADDED', 'CUSTOMER_ADDRESS_ADDED'), ('ADD_LEAD_DETAILS', 'ADD_LEAD_DETAILS'), ('LEAD_OTP_VERIFIED', 'LEAD_OTP_VERIFIED')], max_length=50, null=True),
        ),
    ]
