# Generated by Django 4.0.5 on 2025-11-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_subtasktracker_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtasktracker',
            name='step_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
