# Generated by Django 4.0.5 on 2025-12-04 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0014_alter_subtasktracker_flow_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTaskApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_order', models.IntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('APPROVE', 'APPROVE'), ('SENT_FOR_CORRECTION', 'SENT_FOR_CORRECTION')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtask_approvals_created', to=settings.AUTH_USER_MODEL)),
                ('sub_task_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='tasks.subtasktracker')),
            ],
        ),
    ]
