# Generated by Django 4.0.5 on 2025-12-05 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flows', '0002_flow_expected_duration'),
        ('tasks', '0015_subtaskapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING_CORRECTION', 'Pending Correction'), ('RESUBMITTED', 'Resubmitted'), ('RESOLVED', 'Resolved')], default='PENDING_CORRECTION', max_length=20)),
                ('resubmitted_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'step_corrections',
                'ordering': ['-corrected_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='subtaskapproval',
            options={'ordering': ['step_order']},
        ),
        migrations.RenameField(
            model_name='subtaskapproval',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='subtaskapproval',
            name='approval_status',
            field=models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('CORRECTION_NEEDED', 'Correction Needed')], default='NOT_SUBMITTED', max_length=20),
        ),
        migrations.AddField(
            model_name='subtaskapproval',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtaskapproval',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subtaskapproval',
            name='flow_step',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='flows.flowstep'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtaskapproval',
            name='subtask_tracker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='step_approvals', to='tasks.subtasktracker'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subtaskapproval',
            name='step_order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='subtaskapproval',
            unique_together={('subtask_tracker', 'flow_step')},
        ),
        migrations.AddIndex(
            model_name='subtaskapproval',
            index=models.Index(fields=['subtask_tracker', 'approval_status'], name='flow_step_a_subtask_701205_idx'),
        ),
        migrations.AddIndex(
            model_name='subtaskapproval',
            index=models.Index(fields=['step_order'], name='flow_step_a_step_or_bb9ec4_idx'),
        ),
        migrations.AlterModelTable(
            name='subtaskapproval',
            table='flow_step_approvals',
        ),
        migrations.AddField(
            model_name='stepcorrection',
            name='corrected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stepcorrection',
            name='flow_step_approval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='tasks.subtaskapproval'),
        ),
        migrations.RemoveField(
            model_name='subtaskapproval',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='subtaskapproval',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='subtaskapproval',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='subtaskapproval',
            name='status',
        ),
        migrations.RemoveField(
            model_name='subtaskapproval',
            name='sub_task_track',
        ),
        migrations.AddIndex(
            model_name='stepcorrection',
            index=models.Index(fields=['flow_step_approval', 'status'], name='step_correc_flow_st_ef4ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='stepcorrection',
            index=models.Index(fields=['corrected_at'], name='step_correc_correct_e9d817_idx'),
        ),
    ]
