# Generated by Django 4.0.5 on 2025-12-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_stepcorrection_alter_subtaskapproval_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtaskapproval',
            name='all_steps_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtaskapproval',
            name='current_review_step',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
