# Generated by Django 4.0.5 on 2025-12-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_subtaskapproval_all_steps_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtaskapproval',
            name='all_steps_approved',
        ),
        migrations.RemoveField(
            model_name='subtaskapproval',
            name='current_review_step',
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='all_steps_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='current_review_step',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
