# Generated by Django 4.0.5 on 2025-12-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_remove_subtaskapproval_all_steps_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtasktracker',
            name='product_category',
            field=models.CharField(blank=True, choices=[('FRESH', 'FRESH'), ('TAKE_OVER_BT', 'TAKE_OVER_BT'), ('LOAN', 'LOAN'), ('INSURANCE', 'INSURANCE')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subtasktracker',
            name='product_sub_category',
            field=models.CharField(blank=True, choices=[('GOLD_LOAN', 'GOLD_LOAN'), ('PERSONAL_LOAN', 'PERSONAL_LOAN'), ('HOME_LOAN', 'HOME_LOAN'), ('LAP', 'LAP'), ('BUSINESS_LOAN', 'BUSINESS_LOAN'), ('WORKING_CAPITAL', 'WORKING_CAPITAL'), ('HEALTH_INSURANCE', 'HEALTH_INSURANCE')], max_length=100, null=True),
        ),
    ]
