# Generated by Django 4.0.5 on 2025-12-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_alter_subtasktracker_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtasktracker',
            name='lead_source',
            field=models.CharField(blank=True, choices=[('SELF', 'SELF'), ('CENTRAL', 'CENTRAL'), ('BANK_REFERRED', 'BANK_REFERRED')], max_length=50, null=True),
        ),
    ]
