# Generated by Django 4.0.5 on 2026-03-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_subtask_decline_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='sub_task_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
