# Generated by Django 4.0.5 on 2026-03-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_alter_subtask_sub_task_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['sub_task_id']},
        ),
        migrations.AddField(
            model_name='subtasktracker',
            name='lead_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
