# Generated by Django 4.0.5 on 2026-04-08 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_alter_subtask_options_subtasktracker_lead_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
