# Generated by Django 4.0.5 on 2026-06-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_alter_subtask_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtasktracker',
            name='is_face_match_verify',
            field=models.BooleanField(default=False),
        ),
    ]
