# Generated by Django 4.0.5 on 2023-05-26 00:18

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('lead_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_type', models.CharField(choices=[('TAKE_OVER', 'TAKE_OVER'), ('FRESH', 'FRESH')], default='FRESH', max_length=100)),
                ('address_line', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW_LEAD', 'NEW_LEAD'), ('LEAD_ACCOUNT_CREATED', 'LEAD_ACCOUNT_CREATED')], default='NEW_LEAD', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
        ),
    ]
