# Generated by Django 4.0.5 on 2023-08-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('TAKE_OVER_BT', 'TAKE_OVER_BT'), ('FRESH', 'FRESH')], default='FRESH', max_length=100),
        ),
    ]
