# Generated by Django 4.0.5 on 2024-02-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_alter_lead_lead_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
