# Generated by Django 4.0.5 on 2024-02-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_alter_lead_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('LOAN_OFFICER_APP', 'LOAN_OFFICER_APP'), ('CUSTOMER_APP', 'CUSTOMER_APP'), ('CRM_WEB_APP', 'CRM_WEB_APP'), ('RADIAN_FINSERV_WEBSITE', 'RADIAN_FINSERV_WEBSITE')], default='LOAN_OFFICER_APP', max_length=100),
        ),
    ]
