# Generated by Django 4.0.5 on 2024-04-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_lead_email_lead_is_phone_verified_lead_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lender_type',
            field=models.CharField(blank=True, choices=[('FEDRAL_BANK', 'FEDRAL_BANK'), ('STATE_BANK_OF_INDIA', 'STATE_BANK_OF_INDIA'), ('AXIS_BANK', 'AXIS_BANK')], max_length=100, null=True),
        ),
    ]
