# Generated by Django 4.0.5 on 2024-04-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0007_lead_lender_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
