# Generated by Django 4.0.5 on 2024-04-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_lead_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='pan_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
