# Generated by Django 4.0.5 on 2024-04-23 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lender', '0001_initial'),
        ('lead', '0009_lead_pan_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='lender_type',
        ),
        migrations.AddField(
            model_name='lead',
            name='lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_lenders', to='lender.lender'),
        ),
    ]
