# Generated by Django 4.0.5 on 2024-05-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0010_remove_lead_lender_type_lead_lender'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lending_type',
            field=models.CharField(choices=[('MSME_UNSECURED', 'MSME_UNSECURED'), ('MSME_SECURED', 'MSME_SECURED'), ('GOLD_LOAN', 'GOLD_LOAN')], default='GOLD_LOAN', max_length=20),
            preserve_default=False,
        ),
    ]
