# Generated by Django 4.0.5 on 2024-08-14 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lead', '0011_lead_lending_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='refered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_refered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('LOAN_OFFICER_APP', 'LOAN_OFFICER_APP'), ('CUSTOMER_APP', 'CUSTOMER_APP'), ('CRM_WEB_APP', 'CRM_WEB_APP'), ('RADIAN_FINSERV_WEBSITE', 'RADIAN_FINSERV_WEBSITE'), ('CUSTOMER_APP_REFERENCE', 'CUSTOMER_APP_REFERENCE')], default='LOAN_OFFICER_APP', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
