# Generated by Django 4.0.5 on 2024-09-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0012_lead_refered_by_alter_lead_city_alter_lead_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lending_type',
            field=models.CharField(choices=[('MSME_UNSECURED', 'MSME_UNSECURED'), ('MSME_SECURED', 'MSME_SECURED'), ('GOLD_LOAN', 'GOLD_LOAN'), ('WELLNESS', 'WELLNESS')], max_length=20),
        ),
    ]
