# Generated by Django 4.0.5 on 2024-11-27 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lead', '0012_lead_refered_by_alter_lead_city_alter_lead_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW_LEAD', 'NEW_LEAD'), ('LEAD_ACCOUNT_CREATED', 'LEAD_ACCOUNT_CREATED'), ('LEAD_CREATION_COMPLETED', 'LEAD_CREATION_COMPLETED')], default='NEW_LEAD', max_length=40),
        ),
        migrations.CreateModel(
            name='LeadDocument',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(blank=True, choices=[('AADHAR_CARD', 'AADHAR_CARD'), ('PAN_CARD', 'PAN_CARD'), ('PLEDGE_CARD', 'PLEDGE_CARD'), ('AGRI_PRODUCT_PROOF', 'AGRI_PRODUCT_PROOF')], default='no_type', max_length=255, null=True)),
                ('file_name', models.CharField(blank=True, max_length=225, null=True)),
                ('file', models.FileField(max_length=225, upload_to='media/lead_doc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_document', to='lead.lead')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
