# Generated by Django 4.0.5 on 2024-11-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0013_alter_lead_lending_type'),
        ('lead', '0013_alter_lead_status_leaddocument'),
    ]

    operations = [
    ]
