# Generated by Django 4.0.5 on 2024-12-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0014_merge_20241128_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lending_type',
            field=models.CharField(choices=[('MSME_UNSECURED', 'MSME_UNSECURED'), ('MEME_UNSECURED_AGRI', 'MEME_UNSECURED_AGRI'), ('MSME_SECURED', 'MSME_SECURED'), ('GOLD_LOAN', 'GOLD_LOAN'), ('WELLNESS', 'WELLNESS')], max_length=20),
        ),
    ]
