# Generated by Django 4.0.5 on 2024-12-29 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_alter_insuranceproduct_insurance_policy_type'),
        ('lead', '0015_alter_lead_lending_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_account', to='account.account'),
        ),
    ]
