# Generated by Django 4.0.5 on 2024-12-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0016_alter_lead_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lending_type',
            field=models.CharField(choices=[('MSME_UNSECURED', 'MSME_UNSECURED'), ('MSME_UNSECURED_AGRI', 'MSME_UNSECURED_AGRI'), ('MSME_SECURED', 'MSME_SECURED'), ('GOLD_LOAN', 'GOLD_LOAN'), ('WELLNESS', 'WELLNESS')], max_length=20),
        ),
    ]
