# Generated by Django 4.0.5 on 2025-11-16 21:03

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0017_alter_lead_lending_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewLead',
            fields=[
                ('new_lead_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('source', models.CharField(choices=[('MANIPAL', 'MANIPAL'), ('FINCOME', 'FINCOME')], max_length=100)),
                ('loan_type', models.CharField(choices=[('GOLD_LOAN', 'GOLD_LOAN'), ('PERSONAL_LOAN', 'PERSONAL_LOAN'), ('HOME_LOAN', 'HOME_LOAN'), ('LAP', 'LAP'), ('BUSINESS_LOAN', 'BUSINESS_LOAN'), ('WORKING_CAPITAL', 'WORKING_CAPITAL'), ('HEALTH_INSURANCE', 'HEALTH_INSURANCE')], max_length=100)),
                ('lead_type', models.CharField(blank=True, choices=[('FRESH', 'FRESH'), ('TAKE_OVER_BT', 'TAKE_OVER_BT')], max_length=100, null=True)),
                ('status', models.CharField(choices=[('NEW_LEAD', 'NEW_LEAD'), ('LEAD_CREATION_COMPLETED', 'LEAD_CREATION_COMPLETED')], default='NEW_LEAD', max_length=40)),
                ('lead_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
