# Generated by Django 4.0.5 on 2025-11-18 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lead', '0018_newlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_lead_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newlead',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_lead_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newlead',
            name='status',
            field=models.CharField(choices=[('NEW_LEAD', 'NEW_LEAD'), ('DISBURSED', 'DISBURSED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('LEAD_CREATION_COMPLETED', 'LEAD_CREATION_COMPLETED')], default='NEW_LEAD', max_length=40),
        ),
    ]
