# Generated by Django 4.0.5 on 2025-12-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0019_newlead_created_by_newlead_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlead',
            name='lead_type',
            field=models.CharField(blank=True, choices=[('FRESH', 'FRESH'), ('TAKE_OVER_BT', 'TAKE_OVER_BT'), ('LOAN', 'LOAN'), ('INSURANCE', 'INSURANCE')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newlead',
            name='source',
            field=models.CharField(choices=[('MANIPAL', 'MANIPAL'), ('FINCOME', 'FINCOME'), ('SELF', 'SELF'), ('CENTRAL', 'CENTRAL'), ('BANK_REFERRED', 'BANK_REFERRED')], max_length=100),
        ),
    ]
