# Generated by Django 4.0.5 on 2025-12-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0020_alter_newlead_lead_type_alter_newlead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlead',
            name='source_type',
            field=models.CharField(blank=True, choices=[('SELF', 'SELF'), ('CENTRAL', 'CENTRAL'), ('BANK_REFERRED', 'BANK_REFERRED')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newlead',
            name='source',
            field=models.CharField(choices=[('MANIPAL', 'MANIPAL'), ('FINCOME', 'FINCOME')], max_length=100),
        ),
    ]
