# Generated by Django 4.0.5 on 2025-12-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0021_newlead_source_type_alter_newlead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlead',
            name='address_line',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newlead',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newlead',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='newlead',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
