# Generated by Django 4.0.5 on 2026-06-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0022_newlead_address_line_newlead_city_newlead_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('LOAN_OFFICER_APP', 'LOAN_OFFICER_APP'), ('CUSTOMER_APP', 'CUSTOMER_APP'), ('CRM_WEB_APP', 'CRM_WEB_APP'), ('RADIAN_FINSERV_WEBSITE', 'RADIAN_FINSERV_WEBSITE'), ('CUSTOMER_APP_REFERENCE', 'CUSTOMER_APP_REFERENCE'), ('TELE', 'TELE')], default='LOAN_OFFICER_APP', max_length=100),
        ),
    ]
