# Use the official PostgreSQL image as the base image
# FROM postgres:latest

ARG APP_ENV
FROM postgres
# FROM postgres:15-bullseye

RUN echo "Database Environment is: "
RUN echo $APP_ENV


# Install the MinIO client and cron
RUN apt-get update && \
    apt-get install -y wget cron && \
    wget https://dl.min.io/client/mc/release/linux-amd64/mc -O /usr/local/bin/mc && \
    chmod +x /usr/local/bin/mc && \
    apt-get clean

# Create a directory for backups
RUN mkdir -p /backups

# Copy the backup script into the container
COPY docker/postgres/backup_to_minio.sh /usr/local/bin/backup_to_minio.sh
RUN chmod +x /usr/local/bin/backup_to_minio.sh

ENV APP_ENV=$APP_ENV

# # Add a cron job to run the backup script daily at midnight
# RUN echo "* * * * * /usr/local/bin/backup_to_minio.sh" > /etc/cron.d/backup_to_minio
# Add a cron job to run the backup script daily at midnight and log output
RUN echo "30 20 * * * /usr/local/bin/backup_to_minio.sh >> /var/log/cron.log 2>&1" > /etc/cron.d/backup_to_minio

# Give execution rights on the cron job file
RUN chmod 0644 /etc/cron.d/backup_to_minio

# Apply cron job
RUN crontab /etc/cron.d/backup_to_minio

# Create an entrypoint script to start cron and postgres
COPY docker/postgres/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
# CMD ["/usr/local/bin/entrypoint.sh"]
