# Generated by Django 4.0.5 on 2023-11-07 09:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0011_alter_nomineedetails_relation'),
        ('application', '0043_alter_assetdocuments_file_alter_loandocument_file'),
        # ('application', '0044_alter_assetdocuments_asset_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederalBankApplication',
            fields=[
                ('federal_application_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ekyc_consent_given', models.BooleanField(default=True)),
                ('ekyc_consent_given_at', models.DateTimeField(blank=True, null=True)),
                ('aadhar_rrn', models.CharField(editable=False, max_length=12)),
                ('account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='federal_account', to='account.account')),
                ('application', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='federal_application', to='application.application')),
            ],
        ),
    ]
