# Generated by Django 4.0.5 on 2023-11-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='federalbankapplication',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='customer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='ddupe_flag',
            field=models.CharField(blank=True, editable=False, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='ddupe_reference_id',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='dob_flag',
            field=models.CharField(blank=True, editable=False, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='kyc_flag',
            field=models.CharField(blank=True, editable=False, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='kyc_profile_flag',
            field=models.CharField(blank=True, editable=False, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='minor_flag',
            field=models.CharField(blank=True, editable=False, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='mobile_flag',
            field=models.CharField(blank=True, editable=False, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='nri_flag',
            field=models.CharField(blank=True, editable=False, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='partial_kyc_flag',
            field=models.CharField(blank=True, editable=False, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='federalbankapplication',
            name='aadhar_rrn',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True),
        ),
    ]
