# Generated by Django 4.0.5 on 2023-11-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0002_federalbankapplication_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='federalbankapplication',
            name='reserve_field1',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='reserve_field10',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='reserve_field2',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='reserve_field3',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='reserve_field4',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='reserve_field5',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='reserve_field6',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='reserve_field7',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='reserve_field8',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='reserve_field9',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True),
        ),
    ]
