# Generated by Django 4.0.5 on 2023-11-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0003_federalbankapplication_reserve_field1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='federalbankapplication',
            name='aadhar_seeded_Status',
            field=models.CharField(blank=True, editable=False, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='first_name',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='last_name',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='last_update_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='name_on_card',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='pan',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='pan_status',
            field=models.CharField(blank=True, editable=False, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='pan_title',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='unchck_status',
            field=models.CharField(blank=True, editable=False, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='unchk_first_name',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='unchk_ind_address_note',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='unchk_last_name',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='unchk_msg',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
