# Generated by Django 4.0.5 on 2023-11-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0004_federalbankapplication_aadhar_seeded_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='federalbankapplication',
            name='pan_response_code',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True),
        ),
    ]
