# Generated by Django 4.0.5 on 2023-11-09 19:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0005_federalbankapplication_pan_response_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolidMapping',
            fields=[
                ('solid_mapping_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('solid', models.CharField(max_length=10)),
                ('branch_location', models.CharField(max_length=100)),
            ],
        ),
    ]
