# Generated by Django 4.0.5 on 2023-11-10 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0006_solidmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityCode',
            fields=[
                ('city_code_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('city_name', models.CharField(max_length=100)),
                ('city_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StateCode',
            fields=[
                ('state_code_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state_name', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='sign_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='solId',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
