# Generated by Django 4.0.5 on 2023-11-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0007_citycode_statecode_federalbankapplication_sign_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='federalbankapplication',
            name='aua_specific_uid_token',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='careof',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='district',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='dob',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='ekyc_status',
            field=models.CharField(blank=True, editable=False, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='email',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='gender',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='house_no',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='lamdmark',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='locality',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='masked_aadhaar_number_from_UIDAI',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='phone',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='photo',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='pincode',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='post_office',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='state',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='street',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='vtc_name',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True),
        ),
    ]
