# Generated by Django 4.0.5 on 2023-11-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0008_federalbankapplication_aua_specific_uid_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federalbankapplication',
            name='aadhar_rrn',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
