# Generated by Django 4.0.5 on 2023-11-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0009_alter_federalbankapplication_aadhar_rrn'),
    ]

    operations = [
        migrations.AddField(
            model_name='federalbankapplication',
            name='ddupe_request_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='ekyc_request_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='name_dob_desc',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='name_dob_request_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='name_dob_status',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='pan_request_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='unchck_request_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
