# Generated by Django 4.0.5 on 2023-11-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0010_federalbankapplication_ddupe_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='federalbankapplication',
            name='gl_account_reference_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
