# Generated by Django 4.0.5 on 2023-11-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0011_federalbankapplication_gl_account_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federalbankapplication',
            name='ddupe_flag',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='federalbankapplication',
            name='dob_flag',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='federalbankapplication',
            name='kyc_flag',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='federalbankapplication',
            name='kyc_profile_flag',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='federalbankapplication',
            name='minor_flag',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='federalbankapplication',
            name='mobile_flag',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='federalbankapplication',
            name='nri_flag',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='federalbankapplication',
            name='partial_kyc_flag',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True),
        ),
    ]
