# Generated by Django 4.0.5 on 2023-11-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0012_alter_federalbankapplication_ddupe_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federalbankapplication',
            name='sign_id',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
