# Generated by Django 4.0.5 on 2023-11-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0013_alter_federalbankapplication_sign_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federalbankapplication',
            name='sign_id',
            field=models.FileField(blank=True, null=True, upload_to='media/sign_doc'),
        ),
    ]
