# Generated by Django 4.0.5 on 2023-11-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0014_alter_federalbankapplication_sign_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='federalbankapplication',
            name='agent_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-11-17'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='modefied_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
