# Generated by Django 4.0.5 on 2024-02-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0015_federalbankapplication_agent_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='federalbankapplication',
            name='dedupe_meta_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='ekyc_meta_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='is_eligible',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='is_existing_customer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='name_dob_meta_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='pan_validation_meta_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='federalbankapplication',
            name='unofac_meta_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='federalbankapplication',
            name='ekyc_consent_given',
            field=models.BooleanField(default=False),
        ),
    ]
