image: python:3.8

pipelines:
  # ----------------------------------
  # DEPLOYMENT PIPELINE (DEV ONLY)
  # ----------------------------------
  branches:
    cicd_backend:
      - step:
          name: Deploy Backend to Dev E2E
          deployment: development
          script:
            # install sshpass inside pipeline container
            - apt-get update && apt-get install -y sshpass
            # password-based SSH deployment
            - |
              sshpass -p "$EC2_PASSWORD" ssh \
                -o StrictHostKeyChecking=no \
                radian@dev-api.radianfinserv.com << 'EOF'
                  set -e
                  cd mf_backend
                  git pull
                  docker stop docker-manipal_app-1 docker-manipal_app-2 || true
                  docker rm docker-manipal_app-1 docker-manipal_app-2 || true
                  docker rmi manipal_app:development || true
                  docker compose -f docker/docker-compose-dev.yml up -d --build
                EOF
