version: "3.8"

volumes:
    app_data:
        name: radian_data
    media_data:
        name: radian_media_data
    search_data:
        name: radian_search_data
    # host_backup_data: # move this to the top level
    #     name: radian_host_backup_data  # adjust the volume name

services:
    radian_app:
        build:
            context: ../
            dockerfile: docker/dockerfile
        image: radian_app:development
        volumes:
            - media_data:/app/media
        container_name: radian_app
        command: /app/docker/start.sh
        depends_on:
            - radian_db
            - radian_redis
            - radian_search
        env_file:
            - ../.env
        ports:
            - 8000:8000
        environment:
            DJANGO_POSTGRES_HOST: radian_db
            BROKER_URL: redis://radian_redis:6379
            CELERY_RESULT_BACKEND: redis://radian_redis:6379
            ELASTICSEARCH_HOST: radian_search
            ELASTICSEARCH_PORT: 9200
            ELASTICSEARCH_USERNAME: radian
            ELASTICSEARCH_PASSWORD: radian1234
            APP_ENV: PROD
            
    radian_redis:
        container_name: radian_redis
        image: redis

    radian_db:
        image: postgres
        container_name: radian_db
        volumes:
            - app_data:/var/lib/postgresql/data
            # - host_backup_data:/host_backup  # adjust the volume reference
        environment:
            POSTGRES_PASSWORD: radian1234
            POSTGRES_USER: radian
            POSTGRES_DB: radian
        
        # command: >
        #     bash -c "
        #     echo '2 * * * * root /backup_script.sh' > /etc/cron.d/backup-cron &&
        #     crontab /etc/cron.d/backup-cron &&
        #     cron -f"
#        command: >
#            bash -c "
#            sleep 500 &&
#            mkdir -p /backup &&
#            PGPASSWORD=radian1234 pg_dump -h radian_db -U radian radian > /backup/radian_db.sql &&
#            cp /backup/radian_db.sql /host_backup/"
    radian_search:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.3
        container_name: radian_search
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node
            # - network.host=0.0.0.0
            - ES_JAVA_OPTS=-Xmx512m -Xms512m
            - ELASTIC_USERNAME=radian
            - ELASTIC_PASSWORD=radian1234
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        volumes:
            - search_data:/usr/share/elasticsearch/data
        ports:
            - 9292:9200
    # backup:
    #     image: postgres
    #     container_name: radian_backup
    #     volumes:
    #         - ./backup:/backup
    #         - host_backup_data:/host_backup  # adjust the volume reference
    #     depends_on:
    #         - radian_db
    #     command: /app/docker/backup.sh  # this script will be executed by the cron job

networks:
    default:
        name: radian_network
