version: "3.8"

volumes:
    search_data:
        name: radian_search_data

services:
    radian_search:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.3
        container_name: radian_search
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xmx512m -Xms512m
            - ELASTIC_USERNAME=radian
            - ELASTIC_PASSWORD=radian1234
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        volumes:
            - search_data:/usr/share/elasticsearch/data
        ports:
            - 9292:9200
        networks:
            - manipal_network  # Changed from radian_network

networks:
    manipal_network:  # Changed from default
        external: true
        name: manipal_network

