# Generated by Django 4.0.5 on 2023-05-26 00:18

import account.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer_id', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=20)),
                ('year_of_birth', models.DateTimeField()),
                ('occupation', models.CharField(choices=[('SALARIED', 'SALARIED'), ('BUSINESS', 'BUSINESS'), ('SELF_EMPLOYEED_PROFESSION', 'SELF_EMPLOYEED_PROFESSION'), ('RETIRED', 'RETIRED'), ('HOUSEWIFE', 'HOUSEWIFE'), ('OTHERS', 'OTHERS'), ('SALARIED_JOB_TYPE', 'SALARIED_JOB_TYPE'), ('SALARIED_INDUSTRY_TYPE', 'SALARIED_INDUSTRY_TYPE'), ('PVT_LTD_CO', 'PVT_LTD_CO'), ('PUBLIC_LTD', 'PUBLIC_LTD'), ('GOVT_SERVICES', 'GOVT_SERVICES'), ('MEDICAL_TEACHING', 'MEDICAL_TEACHING'), ('BANKING', 'BANKING'), ('MNC', 'MNC'), ('FINANCIAL_SERVICES', 'FINANCIAL_SERVICES'), ('TEACHING', 'TEACHING'), ('AGRI_BASED', 'AGRI_BASED'), ('TRADER', 'TRADER'), ('BUILDER', 'BUILDER'), ('SERVICE_PROVIDER', 'SERVICE_PROVIDER'), ('MANUFACTURING', 'MANUFACTURING'), ('DOCTOR', 'DOCTOR'), ('CA', 'CA'), ('CONSULTANT', 'CONSULTANT'), ('ARCHITECT', 'ARCHITECT')], default='OTHERS', max_length=100)),
                ('sub_occupation', models.CharField(choices=[('PRIVATE_JOB', 'PRIVATE_JOB'), ('PUBLIC_JOB', 'PUBLIC_JOB'), ('GOVERNMENT_JOB', 'GOVERNMENT_JOB'), ('MEDICAL_JOB', 'MEDICAL_JOB'), ('BANKING_JOB', 'BANKING_JOB'), ('MNC', 'MNC'), ('FINANCIAL_SERVICES', 'FINANCIAL_SERVICES'), ('TEACHING_JOB', 'TEACHING_JOB'), ('DEFENSE', 'DEFENSE'), ('PENSIONER', 'PENSIONER'), ('NBFC', 'NBFC'), ('PSU', 'PSU'), ('OTHER', 'OTHER'), ('INDIVIDUAL', 'INDIVIDUAL'), ('HUF', 'HUF'), ('PRIVATE_LTD_CO', 'PRIVATE_LTD_CO'), ('PARTNERSHIP_FIRM', 'PARTNERSHIP_FIRM'), ('PROPRIETARY_CONCERN', 'PROPRIETARY_CONCERN'), ('AGRI_BASED', 'AGRI_BASED'), ('TRADER', 'TRADER'), ('BUILDER', 'BUILDER'), ('HOUSEWIFE', 'HOUSEWIFE'), ('SERVICE_PROVIDER', 'SERVICE_PROVIDER'), ('MANUFACTURING', 'MANUFACTURING'), ('HOME_BASED_BUSINESS', 'HOME_BASED_BUSINESS'), ('WHOLESALE', 'WHOLESALE'), ('DOCTOR', 'DOCTOR'), ('CA', 'CA'), ('CONSULTANT', 'CONSULTANT'), ('ARCHITECT', 'ARCHITECT')], default='OTHER', max_length=100)),
                ('net_annual_income', models.IntegerField()),
                ('aadhar_no', models.BigIntegerField(unique=True)),
                ('pan_no', models.CharField(max_length=20, unique=True, validators=[account.models.validate_pan_card])),
                ('mother_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('spouse_name', models.CharField(blank=True, max_length=255, null=True)),
                ('education', models.CharField(blank=True, choices=[('10TH', '10TH'), ('12TH', '12TH'), ('UNDER_GRADUATE', 'UNDER_GRADUATE'), ('GRADUATE', 'GRADUATE'), ('POST_GRADUATE', 'POST_GRADUATE'), ('OTHERS', 'OTHERS')], default='OTHERS', max_length=100, null=True)),
                ('religion', models.CharField(choices=[('HINDU', 'HINDU'), ('MUSLIM', 'MUSLIM'), ('CHRISTIAN', 'CHRISTIAN'), ('BUDHIST', 'BUDHIST'), ('OTHER', 'OTHER')], default='OTHER', max_length=100)),
                ('disablity', models.BooleanField(blank=True, default=False, null=True)),
                ('nationality', models.CharField(blank=True, default='INDIA', max_length=255, null=True)),
                ('caste', models.CharField(blank=True, choices=[('GENERAL', 'GENERAL'), ('OBC', 'OBC'), ('ST', 'ST'), ('SC', 'SC'), ('MINORITY', 'MINORITY'), ('OTHERS', 'OTHERS')], default='OTHERS', max_length=100, null=True)),
                ('maritial_status', models.CharField(blank=True, choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED'), ('OTHERS', 'OTHERS')], max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('NEW_ACCOUNT_CREATED', 'NEW_ACCOUNT_CREATED'), ('ADDRESS_ADDED', 'ADDRESS_ADDED'), ('KYC_ADDED', 'KYC_ADDED'), ('BANK_DETAILS_ADDED', 'BANK_DETAILS_ADDED'), ('ACCOUNT_CONFIRMED', 'ACCOUNT_CONFIRMED')], default='NEW_ACCOUNT_CREATED', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modefied_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NomineeDetails',
            fields=[
                ('nominee_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('relation', models.CharField(choices=[('MOTHER', 'MOTHER'), ('FATHER', 'FATHER'), ('HUSBAND', 'HUSBAND'), ('SON', 'SON'), ('DAUGHTER', 'DAUGHTER'), ('SIBLINGS', 'SIBLINGS')], default='SIBLINGS', max_length=100)),
                ('age', models.IntegerField(default=0, validators=[account.models.validate_age])),
                ('insurance_company', models.CharField(blank=True, max_length=100, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomieedetails_account', to='account.account')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('bank_account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verified', models.BooleanField(default=False)),
                ('account_number', models.CharField(max_length=100)),
                ('ifsc', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankaccount_account', to='account.account')),
            ],
        ),
    ]
