# Generated by Django 4.0.5 on 2023-06-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomineedetails',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
