# Generated by Django 4.0.5 on 2023-06-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_nomineedetails_spouse_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomineedetails',
            name='nominee_added',
            field=models.BooleanField(default=False),
        ),
    ]
