# Generated by Django 4.0.5 on 2023-06-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_nomineedetails_nominee_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomineedetails',
            name='nominee_added',
        ),
    ]
