# Generated by Django 4.0.5 on 2023-07-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_nomineedetails_nominee_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='aadhar_meta_field',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='aadhar_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='pan_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
