# Generated by Django 4.0.5 on 2023-07-25 08:00

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_aadhar_meta_field_account_aadhar_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pan_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[account.models.validate_pan_card]),
        ),
    ]
