# Generated by Django 4.0.5 on 2023-08-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_account_pan_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW_ACCOUNT_CREATED', 'NEW_ACCOUNT_CREATED'), ('ADDRESS_ADDED', 'ADDRESS_ADDED'), ('KYC_ADDED', 'KYC_ADDED'), ('BANK_DETAILS_ADDED', 'BANK_DETAILS_ADDED'), ('ACCOUNT_CONFIRMED', 'ACCOUNT_CONFIRMED'), ('NOMINEE_ADDED', 'NOMINEE_ADDED')], default='NEW_ACCOUNT_CREATED', max_length=100, null=True),
        ),
    ]
