# Generated by Django 4.0.5 on 2023-08-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='occupation',
            field=models.CharField(choices=[('SALARIED', 'SALARIED'), ('BUSINESS', 'BUSINESS'), ('SELF_EMPLOYEED_PROFESSION', 'SELF_EMPLOYEED_PROFESSION'), ('RETIRED', 'RETIRED'), ('HOUSEWIFE', 'HOUSEWIFE'), ('OTHERS', 'OTHERS'), ('SALARIED_JOB_TYPE', 'SALARIED_JOB_TYPE'), ('SALARIED_INDUSTRY_TYPE', 'SALARIED_INDUSTRY_TYPE'), ('PVT_LTD_CO', 'PVT_LTD_CO'), ('PUBLIC_LTD', 'PUBLIC_LTD'), ('GOVT_SERVICES', 'GOVT_SERVICES'), ('MEDICAL_TEACHING', 'MEDICAL_TEACHING'), ('BANKING', 'BANKING'), ('MNC', 'MNC'), ('FINANCIAL_SERVICES', 'FINANCIAL_SERVICES'), ('TEACHING', 'TEACHING'), ('AGRI_BASED', 'AGRI_BASED'), ('TRADER', 'TRADER'), ('BUILDER', 'BUILDER'), ('SERVICE_PROVIDER', 'SERVICE_PROVIDER'), ('MANUFACTURING', 'MANUFACTURING'), ('DOCTOR', 'DOCTOR'), ('CA', 'CA'), ('CONSULTANT', 'CONSULTANT'), ('ARCHITECT', 'ARCHITECT'), ('AGRICULTURE', 'AGRICULTURE')], default='OTHERS', max_length=100),
        ),
    ]
