# Generated by Django 4.0.5 on 2023-09-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomineedetails',
            name='relation',
            field=models.CharField(choices=[('MOTHER', 'MOTHER'), ('FATHER', 'FATHER'), ('HUSBAND', 'HUSBAND'), ('SON', 'SON'), ('DAUGHTER', 'DAUGHTER'), ('SIBLINGS', 'SIBLINGS'), ('WIFE', 'WIFE')], default='SIBLINGS', max_length=100),
        ),
    ]
