# Generated by Django 4.0.5 on 2023-11-22 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_insuranceproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='insurance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='account',
            name='insurance_amount_covered_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurance_deducted_from', to='application.application'),
        ),
        migrations.AddField(
            model_name='account',
            name='insurance_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurance_product_chosen', to='account.insuranceproduct'),
        ),
        migrations.AddField(
            model_name='account',
            name='pan_meta_field',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomineedetails',
            name='aadhar_meta_field',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomineedetails',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='nomineedetails',
            name='is_aadhar_verified',
            field=models.BooleanField(default=False),
        ),
    ]
