# Generated by Django 4.0.5 on 2023-11-22 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_account_insurance_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomineedetails',
            old_name='is_aadhar_verified',
            new_name='aadhar_verified',
        ),
        migrations.RemoveField(
            model_name='nomineedetails',
            name='insurance_company',
        ),
    ]
