# Generated by Django 4.0.5 on 2023-11-22 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_rename_is_aadhar_verified_nomineedetails_aadhar_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceproduct',
            name='company_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
