# Generated by Django 4.0.5 on 2023-11-27 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_alter_branch_state'),
        ('account', '0015_alter_insuranceproduct_company_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_branch', to='branch.branch'),
        ),
    ]
