# Generated by Django 4.0.5 on 2023-11-30 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_account_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomineedetails',
            name='insurance_policy_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nominee_insurance', to='account.insuranceproduct'),
        ),
    ]
