# Generated by Django 4.0.5 on 2023-12-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_nomineedetails_insurance_policy_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='religion',
            field=models.CharField(choices=[('HINDU', 'HINDU'), ('MUSLIM', 'MUSLIM'), ('CHRISTIAN', 'CHRISTIAN'), ('BUDDHIST', 'BUDDHIST'), ('OTHER', 'OTHER')], default='OTHER', max_length=100),
        ),
    ]
