# Generated by Django 4.0.5 on 2023-12-18 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lender', '0001_initial'),
        ('account', '0018_alter_account_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_lender', to='lender.lender'),
        ),
    ]
