# Generated by Django 4.0.5 on 2023-12-18 09:14

from django.db import migrations, models
import django.db.models.deletion

from account.models import InsuranceProduct
from lender.models import Lender


def add_radian_as_lender(apps, schema_editor):
    lender=apps.get_model('lender', 'Lender')
    lender=lender.objects.filter(lender_code='RADIAN_FINSERV').first()
    if lender:
        insurance=apps.get_model('account','InsuranceProduct')
        insurance.objects.filter(company_name__icontains='Radian').update(company=lender)

class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_insuranceproduct_company'),
    ]
    operations = [
        migrations.RunPython(add_radian_as_lender)
    ]
