# Generated by Django 4.0.5 on 2023-12-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_insurance_data_migrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceproduct',
            name='company_code',
        ),
    ]
