# Generated by Django 4.0.5 on 2024-04-11 19:10

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branch', '0008_stampdutycharges_minimum_amount_gte_maximum_amount'),
        ('document', '0016_alter_document_account'),
        ('application', '0060_alter_application_eligible_amount'),
        ('account', '0021_remove_insuranceproduct_company_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAccount',
            fields=[
                ('account_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('customer_id', models.CharField(db_index=True, max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=20)),
                ('year_of_birth', models.DateTimeField()),
                ('occupation', models.CharField(choices=[('SALARIED', 'SALARIED'), ('BUSINESS', 'BUSINESS'), ('SELF_EMPLOYEED_PROFESSION', 'SELF_EMPLOYEED_PROFESSION'), ('RETIRED', 'RETIRED'), ('HOUSEWIFE', 'HOUSEWIFE'), ('OTHERS', 'OTHERS'), ('SALARIED_JOB_TYPE', 'SALARIED_JOB_TYPE'), ('SALARIED_INDUSTRY_TYPE', 'SALARIED_INDUSTRY_TYPE'), ('PVT_LTD_CO', 'PVT_LTD_CO'), ('PUBLIC_LTD', 'PUBLIC_LTD'), ('GOVT_SERVICES', 'GOVT_SERVICES'), ('MEDICAL_TEACHING', 'MEDICAL_TEACHING'), ('BANKING', 'BANKING'), ('MNC', 'MNC'), ('FINANCIAL_SERVICES', 'FINANCIAL_SERVICES'), ('TEACHING', 'TEACHING'), ('AGRI_BASED', 'AGRI_BASED'), ('TRADER', 'TRADER'), ('BUILDER', 'BUILDER'), ('SERVICE_PROVIDER', 'SERVICE_PROVIDER'), ('MANUFACTURING', 'MANUFACTURING'), ('DOCTOR', 'DOCTOR'), ('CA', 'CA'), ('CONSULTANT', 'CONSULTANT'), ('ARCHITECT', 'ARCHITECT'), ('AGRICULTURE', 'AGRICULTURE')], default='OTHERS', max_length=100)),
                ('sub_occupation', models.CharField(choices=[('PRIVATE_JOB', 'PRIVATE_JOB'), ('PUBLIC_JOB', 'PUBLIC_JOB'), ('GOVERNMENT_JOB', 'GOVERNMENT_JOB'), ('MEDICAL_JOB', 'MEDICAL_JOB'), ('BANKING_JOB', 'BANKING_JOB'), ('MNC', 'MNC'), ('FINANCIAL_SERVICES', 'FINANCIAL_SERVICES'), ('TEACHING_JOB', 'TEACHING_JOB'), ('DEFENSE', 'DEFENSE'), ('PENSIONER', 'PENSIONER'), ('NBFC', 'NBFC'), ('PSU', 'PSU'), ('OTHER', 'OTHER'), ('INDIVIDUAL', 'INDIVIDUAL'), ('HUF', 'HUF'), ('PRIVATE_LTD_CO', 'PRIVATE_LTD_CO'), ('PARTNERSHIP_FIRM', 'PARTNERSHIP_FIRM'), ('PROPRIETARY_CONCERN', 'PROPRIETARY_CONCERN'), ('AGRI_BASED', 'AGRI_BASED'), ('TRADER', 'TRADER'), ('BUILDER', 'BUILDER'), ('HOUSEWIFE', 'HOUSEWIFE'), ('SERVICE_PROVIDER', 'SERVICE_PROVIDER'), ('MANUFACTURING', 'MANUFACTURING'), ('HOME_BASED_BUSINESS', 'HOME_BASED_BUSINESS'), ('WHOLESALE', 'WHOLESALE'), ('DOCTOR', 'DOCTOR'), ('CA', 'CA'), ('CONSULTANT', 'CONSULTANT'), ('ARCHITECT', 'ARCHITECT')], default='OTHER', max_length=100)),
                ('net_annual_income', models.IntegerField()),
                ('aadhar_no', models.CharField(blank=True, max_length=100, null=True)),
                ('aadhar_meta_field', models.JSONField(blank=True, null=True)),
                ('pan_no', models.CharField(blank=True, db_index=True, max_length=20, null=True, validators=[account.models.validate_pan_card])),
                ('pan_verified', models.BooleanField(default=False)),
                ('aadhar_verified', models.BooleanField(default=False)),
                ('mother_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('spouse_name', models.CharField(blank=True, max_length=255, null=True)),
                ('education', models.CharField(blank=True, choices=[('10TH', '10TH'), ('12TH', '12TH'), ('UNDER_GRADUATE', 'UNDER_GRADUATE'), ('GRADUATE', 'GRADUATE'), ('POST_GRADUATE', 'POST_GRADUATE'), ('OTHERS', 'OTHERS')], default='OTHERS', max_length=100, null=True)),
                ('religion', models.CharField(choices=[('HINDU', 'HINDU'), ('MUSLIM', 'MUSLIM'), ('CHRISTIAN', 'CHRISTIAN'), ('BUDDHIST', 'BUDDHIST'), ('OTHER', 'OTHER')], default='OTHER', max_length=100)),
                ('disablity', models.BooleanField(blank=True, default=False, null=True)),
                ('nationality', models.CharField(blank=True, default='INDIA', max_length=255, null=True)),
                ('caste', models.CharField(blank=True, choices=[('GENERAL', 'GENERAL'), ('OBC', 'OBC'), ('ST', 'ST'), ('SC', 'SC'), ('MINORITY', 'MINORITY'), ('OTHERS', 'OTHERS')], default='OTHERS', max_length=100, null=True)),
                ('maritial_status', models.CharField(blank=True, choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED'), ('OTHERS', 'OTHERS')], max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('NEW_ACCOUNT_CREATED', 'NEW_ACCOUNT_CREATED'), ('ADDRESS_ADDED', 'ADDRESS_ADDED'), ('KYC_ADDED', 'KYC_ADDED'), ('BANK_DETAILS_ADDED', 'BANK_DETAILS_ADDED'), ('ACCOUNT_CONFIRMED', 'ACCOUNT_CONFIRMED'), ('NOMINEE_ADDED', 'NOMINEE_ADDED')], default='NEW_ACCOUNT_CREATED', max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('modefied_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('pan_meta_field', models.JSONField(blank=True, null=True)),
                ('insurance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='branch.branch')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_history', to='account.account')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('insurance_amount_covered_from', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='application.application')),
                ('insurance_product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.insuranceproduct')),
                ('profile_photo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='document.document')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical account',
                'verbose_name_plural': 'historical accounts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
