# Generated by Django 4.0.5 on 2024-04-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_historicalaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalaccount',
            name='history_relation',
        ),
    ]
