# Generated by Django 4.0.5 on 2024-05-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_remove_historicalaccount_history_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_purpose',
            field=models.CharField(choices=[('LOAN_DISBURSEMENT', 'LOAN_DISBURSEMENT'), ('E_NACH', 'E_NACH')], default='LOAN_DISBURSEMENT', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('SAVINGS', 'SAVINGS'), ('CURRENT', 'CURRENT'), ('OVERDRAFT', 'OVERDRAFT')], default='SAVINGS', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='branch_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
