# Generated by Django 4.0.5 on 2024-05-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_bankaccount_account_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW_ACCOUNT_CREATED', 'NEW_ACCOUNT_CREATED'), ('ADDRESS_ADDED', 'ADDRESS_ADDED'), ('KYC_ADDED', 'KYC_ADDED'), ('BANK_DETAILS_ADDED', 'BANK_DETAILS_ADDED'), ('ACCOUNT_CONFIRMED', 'ACCOUNT_CONFIRMED'), ('NOMINEE_ADDED', 'NOMINEE_ADDED'), ('CREDIT_STATUS_ADDED', 'CREDIT_STATUS_ADDED')], default='NEW_ACCOUNT_CREATED', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW_ACCOUNT_CREATED', 'NEW_ACCOUNT_CREATED'), ('ADDRESS_ADDED', 'ADDRESS_ADDED'), ('KYC_ADDED', 'KYC_ADDED'), ('BANK_DETAILS_ADDED', 'BANK_DETAILS_ADDED'), ('ACCOUNT_CONFIRMED', 'ACCOUNT_CONFIRMED'), ('NOMINEE_ADDED', 'NOMINEE_ADDED'), ('CREDIT_STATUS_ADDED', 'CREDIT_STATUS_ADDED')], default='NEW_ACCOUNT_CREATED', max_length=100, null=True),
        ),
    ]
