# Generated by Django 4.0.5 on 2024-08-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_alter_account_status_alter_historicalaccount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='tenure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='insurance_benefits',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
