# Generated by Django 4.0.5 on 2024-08-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_alter_account_status_alter_historicalaccount_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sub_occupation',
            field=models.CharField(choices=[('PRIVATE_JOB', 'PRIVATE_JOB'), ('PUBLIC_JOB', 'PUBLIC_JOB'), ('GOVERNMENT_JOB', 'GOVERNMENT_JOB'), ('MEDICAL_JOB', 'MEDICAL_JOB'), ('BANKING_JOB', 'BANKING_JOB'), ('MNC', 'MNC'), ('FINANCIAL_SERVICES', 'FINANCIAL_SERVICES'), ('TEACHING_JOB', 'TEACHING_JOB'), ('DEFENSE', 'DEFENSE'), ('PENSIONER', 'PENSIONER'), ('NBFC', 'NBFC'), ('PSU', 'PSU'), ('OTHER', 'OTHER'), ('INDIVIDUAL', 'INDIVIDUAL'), ('HUF', 'HUF'), ('PRIVATE_LTD_CO', 'PRIVATE_LTD_CO'), ('PARTNERSHIP_FIRM', 'PARTNERSHIP_FIRM'), ('PROPRIETARY_CONCERN', 'PROPRIETARY_CONCERN'), ('AGRI_BASED', 'AGRI_BASED'), ('TRADER', 'TRADER'), ('BUILDER', 'BUILDER'), ('HOUSEWIFE', 'HOUSEWIFE'), ('SERVICE_PROVIDER', 'SERVICE_PROVIDER'), ('MANUFACTURER', 'MANUFACTURER'), ('HOME_BASED_BUSINESS', 'HOME_BASED_BUSINESS'), ('WHOLESALE', 'WHOLESALE'), ('DOCTOR', 'DOCTOR'), ('CA', 'CA'), ('CONSULTANT', 'CONSULTANT'), ('ARCHITECT', 'ARCHITECT'), ('RETAILER', 'RETAILER'), ('EATERY', 'EATERY'), ('ALLIED_AGRI', 'ALLIED_AGRI'), ('HANDCART', 'HANDCART'), ('CATTAGE_INDUSTRIES', 'CATTAGE_INDUSTRIES')], default='OTHER', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='sub_occupation',
            field=models.CharField(choices=[('PRIVATE_JOB', 'PRIVATE_JOB'), ('PUBLIC_JOB', 'PUBLIC_JOB'), ('GOVERNMENT_JOB', 'GOVERNMENT_JOB'), ('MEDICAL_JOB', 'MEDICAL_JOB'), ('BANKING_JOB', 'BANKING_JOB'), ('MNC', 'MNC'), ('FINANCIAL_SERVICES', 'FINANCIAL_SERVICES'), ('TEACHING_JOB', 'TEACHING_JOB'), ('DEFENSE', 'DEFENSE'), ('PENSIONER', 'PENSIONER'), ('NBFC', 'NBFC'), ('PSU', 'PSU'), ('OTHER', 'OTHER'), ('INDIVIDUAL', 'INDIVIDUAL'), ('HUF', 'HUF'), ('PRIVATE_LTD_CO', 'PRIVATE_LTD_CO'), ('PARTNERSHIP_FIRM', 'PARTNERSHIP_FIRM'), ('PROPRIETARY_CONCERN', 'PROPRIETARY_CONCERN'), ('AGRI_BASED', 'AGRI_BASED'), ('TRADER', 'TRADER'), ('BUILDER', 'BUILDER'), ('HOUSEWIFE', 'HOUSEWIFE'), ('SERVICE_PROVIDER', 'SERVICE_PROVIDER'), ('MANUFACTURER', 'MANUFACTURER'), ('HOME_BASED_BUSINESS', 'HOME_BASED_BUSINESS'), ('WHOLESALE', 'WHOLESALE'), ('DOCTOR', 'DOCTOR'), ('CA', 'CA'), ('CONSULTANT', 'CONSULTANT'), ('ARCHITECT', 'ARCHITECT'), ('RETAILER', 'RETAILER'), ('EATERY', 'EATERY'), ('ALLIED_AGRI', 'ALLIED_AGRI'), ('HANDCART', 'HANDCART'), ('CATTAGE_INDUSTRIES', 'CATTAGE_INDUSTRIES')], default='OTHER', max_length=100),
        ),
    ]
