# Generated by Django 4.0.5 on 2024-08-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_insuranceproduct_rate_insuranceproduct_tenure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='insurance_policy_type',
            field=models.CharField(blank=True, choices=[('MSME_UNSECURED', 'MSME_UNSECURED'), ('MSME_SECURED', 'MSME_SECURED'), ('GOLD_LOAN', 'GOLD_LOAN')], default='GOLD_LOAN', max_length=100, null=True),
        ),
    ]
