# Generated by Django 4.0.5 on 2024-08-13 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_alter_account_sub_occupation_and_more'),
        ('account', '0032_insuranceproduct_insurance_policy_type'),
    ]

    operations = [
    ]
