# Generated by Django 4.0.5 on 2024-08-22 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_product_category_and_more'),
        ('account', '0033_merge_20240813_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_product_product', to='product.product'),
        ),
    ]
