# Generated by Django 4.0.5 on 2024-09-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_insuranceproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomineedetails',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
