# Generated by Django 4.0.5 on 2024-09-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_nomineedetails_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceproduct',
            name='insurance_policy_type',
            field=models.CharField(blank=True, choices=[('MSME_UNSECURED', 'MSME_UNSECURED'), ('MSME_SECURED', 'MSME_SECURED'), ('GOLD_LOAN', 'GOLD_LOAN'), ('WELLNESS', 'WELLNESS')], default='GOLD_LOAN', max_length=100, null=True),
        ),
    ]
