# Generated by Django 4.0.5 on 2024-10-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_alter_insuranceproduct_insurance_policy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomineedetails',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
