# Generated by Django 4.0.5 on 2024-12-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_alter_insuranceproduct_insurance_policy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceproduct',
            name='insurance_policy_type',
            field=models.CharField(blank=True, choices=[('MSME_UNSECURED', 'MSME_UNSECURED'), ('MSME_UNSECURED_AGRI', 'MSME_UNSECURED_AGRI'), ('MSME_SECURED', 'MSME_SECURED'), ('GOLD_LOAN', 'GOLD_LOAN'), ('WELLNESS', 'WELLNESS')], default='GOLD_LOAN', max_length=100, null=True),
        ),
    ]
