# Generated by Django 4.0.5 on 2025-01-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_alter_insuranceproduct_insurance_policy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomineedetails',
            name='relation',
            field=models.CharField(choices=[('MOTHER', 'MOTHER'), ('FATHER', 'FATHER'), ('HUSBAND', 'HUSBAND'), ('SON', 'SON'), ('DAUGHTER', 'DAUGHTER'), ('SIBLINGS', 'SIBLINGS'), ('WIFE', 'WIFE'), ('BUYERS', 'BUYERS'), ('SELLERS', 'SELLERS'), ('COMPETITORS', 'COMPETITORS'), ('DISTRIBUTORS', 'DISTRIBUTORS'), ('BUSINESS_PARTNERS', 'BUSINESS_PARTNERS'), ('EXISITING_MSME_CLIENTS', 'EXISITING_MSME_CLIENTS'), ('OTHERS', 'OTHERS')], default='SIBLINGS', max_length=100),
        ),
    ]
