# Generated by Django 4.0.5 on 2025-03-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_alter_nomineedetails_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='applicant_type',
            field=models.CharField(choices=[('APPLICANT', 'APPLICANT'), ('CO_APPLICANT', 'CO_APPLICANT')], default='APPLICANT', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='applicant_type',
            field=models.CharField(choices=[('APPLICANT', 'APPLICANT'), ('CO_APPLICANT', 'CO_APPLICANT')], default='APPLICANT', max_length=100),
        ),
    ]
