# Generated by Django 4.0.5 on 2025-04-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_account_applicant_historicalaccount_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW_ACCOUNT_CREATED', 'NEW_ACCOUNT_CREATED'), ('ADDRESS_ADDED', 'ADDRESS_ADDED'), ('KYC_ADDED', 'KYC_ADDED'), ('BANK_DETAILS_ADDED', 'BANK_DETAILS_ADDED'), ('CO_APPLICANT_NEW_ACCOUNT_CREATED', 'CO_APPLICANT_NEW_ACCOUNT_CREATED'), ('CO_APPLICANT_ADDRESS_ADDED', 'CO_APPLICANT_ADDRESS_ADDED'), ('CO_APPLICANT_KYC_ADDED', 'CO_APPLICANT_KYC_ADDED'), ('CO_APPLICANT_BANK_DETAILS_ADDED', 'CO_APPLICANT_BANK_DETAILS_ADDED'), ('ACCOUNT_CONFIRMED', 'ACCOUNT_CONFIRMED'), ('NOMINEE_ADDED', 'NOMINEE_ADDED'), ('CREDIT_STATUS_ADDED', 'CREDIT_STATUS_ADDED'), ('REFERENCE_PD_ADDED', 'REFERENCE_PD_ADDED'), ('RESIDENCE_PROOF_ADDED', 'RESIDENCE_PROOF_ADDED')], default='NEW_ACCOUNT_CREATED', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW_ACCOUNT_CREATED', 'NEW_ACCOUNT_CREATED'), ('ADDRESS_ADDED', 'ADDRESS_ADDED'), ('KYC_ADDED', 'KYC_ADDED'), ('BANK_DETAILS_ADDED', 'BANK_DETAILS_ADDED'), ('CO_APPLICANT_NEW_ACCOUNT_CREATED', 'CO_APPLICANT_NEW_ACCOUNT_CREATED'), ('CO_APPLICANT_ADDRESS_ADDED', 'CO_APPLICANT_ADDRESS_ADDED'), ('CO_APPLICANT_KYC_ADDED', 'CO_APPLICANT_KYC_ADDED'), ('CO_APPLICANT_BANK_DETAILS_ADDED', 'CO_APPLICANT_BANK_DETAILS_ADDED'), ('ACCOUNT_CONFIRMED', 'ACCOUNT_CONFIRMED'), ('NOMINEE_ADDED', 'NOMINEE_ADDED'), ('CREDIT_STATUS_ADDED', 'CREDIT_STATUS_ADDED'), ('REFERENCE_PD_ADDED', 'REFERENCE_PD_ADDED'), ('RESIDENCE_PROOF_ADDED', 'RESIDENCE_PROOF_ADDED')], default='NEW_ACCOUNT_CREATED', max_length=100, null=True),
        ),
    ]
