# Generated by Django 4.0.5 on 2025-11-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_alter_account_status_alter_historicalaccount_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='education',
            field=models.CharField(blank=True, choices=[('10TH', '10TH'), ('12TH', '12TH'), ('UNDER_GRADUATE', 'UNDER_GRADUATE'), ('GRADUATE', 'GRADUATE'), ('POST_GRADUATE', 'POST_GRADUATE'), ('SECONDARY', 'SECONDARY'), ('SENIOR_SECONDARY', 'SENIOR_SECONDARY'), ('OTHERS', 'OTHERS')], default='OTHERS', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='occupation',
            field=models.CharField(choices=[('SALARIED', 'SALARIED'), ('BUSINESS', 'BUSINESS'), ('SELF_EMPLOYEED_PROFESSION', 'SELF_EMPLOYEED_PROFESSION'), ('RETIRED', 'RETIRED'), ('HOUSEWIFE', 'HOUSEWIFE'), ('OTHERS', 'OTHERS'), ('SALARIED_JOB_TYPE', 'SALARIED_JOB_TYPE'), ('SALARIED_INDUSTRY_TYPE', 'SALARIED_INDUSTRY_TYPE'), ('PVT_LTD_CO', 'PVT_LTD_CO'), ('PUBLIC_LTD', 'PUBLIC_LTD'), ('GOVT_SERVICES', 'GOVT_SERVICES'), ('MEDICAL_TEACHING', 'MEDICAL_TEACHING'), ('BANKING', 'BANKING'), ('MNC', 'MNC'), ('FINANCIAL_SERVICES', 'FINANCIAL_SERVICES'), ('TEACHING', 'TEACHING'), ('AGRI_BASED', 'AGRI_BASED'), ('TRADER', 'TRADER'), ('BUILDER', 'BUILDER'), ('SERVICE_PROVIDER', 'SERVICE_PROVIDER'), ('MANUFACTURING', 'MANUFACTURING'), ('DOCTOR', 'DOCTOR'), ('CA', 'CA'), ('CONSULTANT', 'CONSULTANT'), ('ARCHITECT', 'ARCHITECT'), ('AGRICULTURE', 'AGRICULTURE'), ('BUSINESSMAN', 'BUSINESSMAN'), ('INSURANCE_AGENT', 'INSURANCE_AGENT')], default='OTHERS', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='education',
            field=models.CharField(blank=True, choices=[('10TH', '10TH'), ('12TH', '12TH'), ('UNDER_GRADUATE', 'UNDER_GRADUATE'), ('GRADUATE', 'GRADUATE'), ('POST_GRADUATE', 'POST_GRADUATE'), ('SECONDARY', 'SECONDARY'), ('SENIOR_SECONDARY', 'SENIOR_SECONDARY'), ('OTHERS', 'OTHERS')], default='OTHERS', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='occupation',
            field=models.CharField(choices=[('SALARIED', 'SALARIED'), ('BUSINESS', 'BUSINESS'), ('SELF_EMPLOYEED_PROFESSION', 'SELF_EMPLOYEED_PROFESSION'), ('RETIRED', 'RETIRED'), ('HOUSEWIFE', 'HOUSEWIFE'), ('OTHERS', 'OTHERS'), ('SALARIED_JOB_TYPE', 'SALARIED_JOB_TYPE'), ('SALARIED_INDUSTRY_TYPE', 'SALARIED_INDUSTRY_TYPE'), ('PVT_LTD_CO', 'PVT_LTD_CO'), ('PUBLIC_LTD', 'PUBLIC_LTD'), ('GOVT_SERVICES', 'GOVT_SERVICES'), ('MEDICAL_TEACHING', 'MEDICAL_TEACHING'), ('BANKING', 'BANKING'), ('MNC', 'MNC'), ('FINANCIAL_SERVICES', 'FINANCIAL_SERVICES'), ('TEACHING', 'TEACHING'), ('AGRI_BASED', 'AGRI_BASED'), ('TRADER', 'TRADER'), ('BUILDER', 'BUILDER'), ('SERVICE_PROVIDER', 'SERVICE_PROVIDER'), ('MANUFACTURING', 'MANUFACTURING'), ('DOCTOR', 'DOCTOR'), ('CA', 'CA'), ('CONSULTANT', 'CONSULTANT'), ('ARCHITECT', 'ARCHITECT'), ('AGRICULTURE', 'AGRICULTURE'), ('BUSINESSMAN', 'BUSINESSMAN'), ('INSURANCE_AGENT', 'INSURANCE_AGENT')], default='OTHERS', max_length=100),
        ),
    ]
