# Generated by Django 4.0.5 on 2025-11-06 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0044_alter_account_education_alter_account_occupation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('alternate_mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('house', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.CharField(blank=True, choices=[('SECONDARY', 'SECONDARY'), ('SENIOR_SECONDARY', 'SENIOR_SECONDARY'), ('GRADUATE', 'GRADUATE'), ('POST_GRADUATE', 'POST_GRADUATE')], default='GRADUATE', max_length=100, null=True)),
                ('occupation', models.CharField(choices=[('BUSINESSMAN', 'BUSINESSMAN'), ('CA', 'CA'), ('INSURANCE_AGENT', 'INSURANCE_AGENT'), ('OTHERS', 'OTHERS')], default='OTHERS', max_length=100)),
                ('aadhar_no', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('ACCOUNT_DETAILS_ADDED', 'ACCOUNT_DETAILS_ADDED'), ('ESIGN_PENDING', 'ESIGN_PENDING'), ('ACCOUNT_CREATED', 'ACCOUNT_CREATED')], default='ACCOUNT_DETAILS_ADDED', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_accounts_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_accounts_modified', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
