# Generated by Django 4.0.5 on 2025-11-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_agentaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentaccount',
            name='agent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
