# Generated by Django 4.0.5 on 2025-11-16 16:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_agentaccount_agent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentBankAccount',
            fields=[
                ('Agent_bank_account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verified', models.BooleanField(default=False)),
                ('account_number', models.CharField(max_length=100)),
                ('ifsc', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('branch_name', models.CharField(default='', max_length=100)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankaccount_agentaccount', to='account.agentaccount')),
            ],
        ),
    ]
