# Generated by Django 4.0.5 on 2025-11-16 21:03

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lead', '0018_newlead'),
        ('account', '0047_agentbankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAccount',
            fields=[
                ('new_account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer_id', models.CharField(max_length=12, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('pan_card_number', models.CharField(max_length=20, validators=[account.models.validate_pan_card])),
                ('is_pan_verified', models.BooleanField(default=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_account_lead', to='lead.newlead')),
            ],
        ),
        migrations.RemoveField(
            model_name='agentbankaccount',
            name='branch_name',
        ),
        migrations.CreateModel(
            name='NewAccountDocument',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(blank=True, choices=[('AADHAR_CARD', 'AADHAR_CARD'), ('PAN_CARD', 'PAN_CARD'), ('PLEDGE_CARD', 'PLEDGE_CARD'), ('AGRI_PRODUCT_PROOF', 'AGRI_PRODUCT_PROOF')], max_length=50, null=True)),
                ('file_name', models.CharField(blank=True, max_length=225, null=True)),
                ('file', models.FileField(max_length=225, upload_to='media/subtask_doc')),
                ('status', models.CharField(blank=True, choices=[('PAN_VERIFIED', 'PAN_VERIFIED'), ('ACCOUNT_CREATED', 'ACCOUNT_CREATED')], max_length=50, null=True)),
                ('source', models.CharField(blank=True, choices=[('MANIPAL', 'MANIPAL'), ('FINCOME', 'FINCOME')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('new_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_account_document', to='account.newaccount')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NEW_ACCOUNT_DOC_USER', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
