# Generated by Django 4.0.5 on 2025-12-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_newaccount_remove_agentbankaccount_branch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newaccountdocument',
            name='source',
            field=models.CharField(blank=True, choices=[('MANIPAL', 'MANIPAL'), ('FINCOME', 'FINCOME'), ('SELF', 'SELF'), ('CENTRAL', 'CENTRAL'), ('BANK_REFERRED', 'BANK_REFERRED')], max_length=100, null=True),
        ),
    ]
