# Generated by Django 4.0.5 on 2025-12-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_alter_newaccountdocument_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newaccountdocument',
            name='source',
            field=models.CharField(blank=True, choices=[('MANIPAL', 'MANIPAL'), ('FINCOME', 'FINCOME')], max_length=100, null=True),
        ),
    ]
