# Generated by Django 4.0.5 on 2026-04-29 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0046_alter_applicationdocument_document_type_and_more'),
        ('account', '0050_alter_newaccountdocument_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newaccount',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_account_lead', to='onboarding_v2.leadv2'),
        ),
    ]
