# Generated by Django 4.0.5 on 2026-06-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_alter_newaccount_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='caste',
            field=models.CharField(blank=True, choices=[('GENERAL', 'GENERAL'), ('OBC', 'OBC'), ('OTHER', 'OTHER'), ('SCHEDULE_CASTE', 'SCHEDULE_CASTE'), ('SCHEDULE_TRIBE', 'SCHEDULE_TRIBE'), ('ST', 'ST'), ('SC', 'SC'), ('MINORITY', 'MINORITY'), ('OTHERS', 'OTHERS')], default='OTHERS', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='education',
            field=models.CharField(blank=True, choices=[('10TH', '10TH'), ('12TH', '12TH'), ('UNDER_GRADUATE', 'UNDER_GRADUATE'), ('METRIC', 'METRIC'), ('INTERMEDIATE', 'INTERMEDIATE'), ('GRADUATE', 'GRADUATE'), ('ILLITERATE', 'ILLITERATE'), ('PRIMARY', 'PRIMARY'), ('POST_GRADUATE', 'POST_GRADUATE'), ('SECONDARY', 'SECONDARY'), ('SENIOR_SECONDARY', 'SENIOR_SECONDARY'), ('OTHERS', 'OTHERS')], default='OTHERS', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='maritial_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'SINGLE'), ('DIVORCED', 'DIVORCED'), ('MARRIED', 'MARRIED'), ('OTHERS', 'OTHERS'), ('UNMARRIED', 'UNMARRIED'), ('WIDOWED', 'WIDOWED')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='occupation',
            field=models.CharField(choices=[('SALARIED', 'SALARIED'), ('BUSINESS', 'BUSINESS'), ('SELF_EMPLOYEED_PROFESSION', 'SELF_EMPLOYEED_PROFESSION'), ('RETIRED', 'RETIRED'), ('HOUSEWIFE', 'HOUSEWIFE'), ('ANIMAL_HUSBANDRY', 'ANIMAL_HUSBANDRY'), ('HANDICRAFT', 'HANDICRAFT'), ('HOME_MAKER', 'HOME_MAKER'), ('LABOUR', 'LABOUR'), ('OTHERS', 'OTHERS'), ('RURAL_ARTISANS', 'RURAL_ARTISANS'), ('SELF_EMPLOYED', 'SELF_EMPLOYED'), ('STUDENT', 'STUDENT'), ('SERVICE', 'SERVICE'), ('TRADE', 'TRADE'), ('UNEMPLOYED', 'UNEMPLOYED'), ('SALARIED_JOB_TYPE', 'SALARIED_JOB_TYPE'), ('SALARIED_INDUSTRY_TYPE', 'SALARIED_INDUSTRY_TYPE'), ('PVT_LTD_CO', 'PVT_LTD_CO'), ('PUBLIC_LTD', 'PUBLIC_LTD'), ('GOVT_SERVICES', 'GOVT_SERVICES'), ('MEDICAL_TEACHING', 'MEDICAL_TEACHING'), ('BANKING', 'BANKING'), ('MNC', 'MNC'), ('FINANCIAL_SERVICES', 'FINANCIAL_SERVICES'), ('TEACHING', 'TEACHING'), ('AGRI_BASED', 'AGRI_BASED'), ('TRADER', 'TRADER'), ('BUILDER', 'BUILDER'), ('SERVICE_PROVIDER', 'SERVICE_PROVIDER'), ('MANUFACTURING', 'MANUFACTURING'), ('DOCTOR', 'DOCTOR'), ('CA', 'CA'), ('CONSULTANT', 'CONSULTANT'), ('ARCHITECT', 'ARCHITECT'), ('AGRICULTURE', 'AGRICULTURE'), ('BUSINESSMAN', 'BUSINESSMAN'), ('INSURANCE_AGENT', 'INSURANCE_AGENT')], default='OTHERS', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='religion',
            field=models.CharField(choices=[('BUDDHIST', 'BUDDHIST'), ('CHRISTIAN', 'CHRISTIAN'), ('HINDU', 'HINDU'), ('JAIN', 'JAIN'), ('MUSLIM', 'MUSLIM'), ('OTHERS', 'OTHERS'), ('OTHER', 'OTHER'), ('SIKH', 'SIKH')], default='OTHER', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='caste',
            field=models.CharField(blank=True, choices=[('GENERAL', 'GENERAL'), ('OBC', 'OBC'), ('OTHER', 'OTHER'), ('SCHEDULE_CASTE', 'SCHEDULE_CASTE'), ('SCHEDULE_TRIBE', 'SCHEDULE_TRIBE'), ('ST', 'ST'), ('SC', 'SC'), ('MINORITY', 'MINORITY'), ('OTHERS', 'OTHERS')], default='OTHERS', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='education',
            field=models.CharField(blank=True, choices=[('10TH', '10TH'), ('12TH', '12TH'), ('UNDER_GRADUATE', 'UNDER_GRADUATE'), ('METRIC', 'METRIC'), ('INTERMEDIATE', 'INTERMEDIATE'), ('GRADUATE', 'GRADUATE'), ('ILLITERATE', 'ILLITERATE'), ('PRIMARY', 'PRIMARY'), ('POST_GRADUATE', 'POST_GRADUATE'), ('SECONDARY', 'SECONDARY'), ('SENIOR_SECONDARY', 'SENIOR_SECONDARY'), ('OTHERS', 'OTHERS')], default='OTHERS', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='maritial_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'SINGLE'), ('DIVORCED', 'DIVORCED'), ('MARRIED', 'MARRIED'), ('OTHERS', 'OTHERS'), ('UNMARRIED', 'UNMARRIED'), ('WIDOWED', 'WIDOWED')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='occupation',
            field=models.CharField(choices=[('SALARIED', 'SALARIED'), ('BUSINESS', 'BUSINESS'), ('SELF_EMPLOYEED_PROFESSION', 'SELF_EMPLOYEED_PROFESSION'), ('RETIRED', 'RETIRED'), ('HOUSEWIFE', 'HOUSEWIFE'), ('ANIMAL_HUSBANDRY', 'ANIMAL_HUSBANDRY'), ('HANDICRAFT', 'HANDICRAFT'), ('HOME_MAKER', 'HOME_MAKER'), ('LABOUR', 'LABOUR'), ('OTHERS', 'OTHERS'), ('RURAL_ARTISANS', 'RURAL_ARTISANS'), ('SELF_EMPLOYED', 'SELF_EMPLOYED'), ('STUDENT', 'STUDENT'), ('SERVICE', 'SERVICE'), ('TRADE', 'TRADE'), ('UNEMPLOYED', 'UNEMPLOYED'), ('SALARIED_JOB_TYPE', 'SALARIED_JOB_TYPE'), ('SALARIED_INDUSTRY_TYPE', 'SALARIED_INDUSTRY_TYPE'), ('PVT_LTD_CO', 'PVT_LTD_CO'), ('PUBLIC_LTD', 'PUBLIC_LTD'), ('GOVT_SERVICES', 'GOVT_SERVICES'), ('MEDICAL_TEACHING', 'MEDICAL_TEACHING'), ('BANKING', 'BANKING'), ('MNC', 'MNC'), ('FINANCIAL_SERVICES', 'FINANCIAL_SERVICES'), ('TEACHING', 'TEACHING'), ('AGRI_BASED', 'AGRI_BASED'), ('TRADER', 'TRADER'), ('BUILDER', 'BUILDER'), ('SERVICE_PROVIDER', 'SERVICE_PROVIDER'), ('MANUFACTURING', 'MANUFACTURING'), ('DOCTOR', 'DOCTOR'), ('CA', 'CA'), ('CONSULTANT', 'CONSULTANT'), ('ARCHITECT', 'ARCHITECT'), ('AGRICULTURE', 'AGRICULTURE'), ('BUSINESSMAN', 'BUSINESSMAN'), ('INSURANCE_AGENT', 'INSURANCE_AGENT')], default='OTHERS', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='religion',
            field=models.CharField(choices=[('BUDDHIST', 'BUDDHIST'), ('CHRISTIAN', 'CHRISTIAN'), ('HINDU', 'HINDU'), ('JAIN', 'JAIN'), ('MUSLIM', 'MUSLIM'), ('OTHERS', 'OTHERS'), ('OTHER', 'OTHER'), ('SIKH', 'SIKH')], default='OTHER', max_length=100),
        ),
    ]
