from django.db import migrations, models
import django.db.models.deletion
import uuid


def default_json():
    return {}


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lender', '0001_initial'),
        migrations.swappable_dependency('users.User'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=64, unique=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('product_category', models.CharField(choices=[('LOAN', 'Loan'), ('INSURANCE', 'Insurance')], default='LOAN', max_length=32)),
                ('product_subcategory', models.CharField(blank=True, choices=[('GOLD_LOAN', 'Gold Loan'), ('PERSONAL_LOAN', 'Personal Loan'), ('CO_LENDING', 'Co Lending'), ('HOME_LOAN', 'Home Loan'), ('INSURANCE_GENERIC', 'Insurance')], max_length=64, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('source', models.CharField(choices=[('SELF', 'Self'), ('AGENT', 'Agent'), ('OTHER', 'Other')], default='SELF', max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT_FOR_PRE_SCREENING', 'SentForPreScreening'), ('IN_PROGRESS', 'InProgress'), ('CORRECTION', 'Correction'), ('REJECTED', 'Rejected'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'NotEligible'), ('PASSED', 'Passed'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=default_json)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_v2_leads', to='users.user')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_v2_leads_created', to='users.user')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_v2_leads_modified', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_id', models.CharField(max_length=64, unique=True)),
                ('loan_type', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT_FOR_PRE_SCREENING', 'SentForPreScreening'), ('IN_PROGRESS', 'InProgress'), ('CORRECTION', 'Correction'), ('REJECTED', 'Rejected'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'NotEligible'), ('PASSED', 'Passed')], default='DRAFT', max_length=64)),
                ('stage', models.CharField(choices=[('PAN', 'Pan'), ('BASIC', 'Basic'), ('ADDRESS', 'Address'), ('DOCUMENTS', 'Documents'), ('PERSONAL', 'Personal'), ('ADDRESS_SECONDARY', 'AddressSecondary'), ('GOLD', 'Gold'), ('LOAN', 'Loan'), ('BANK', 'Bank'), ('ADDITIONAL', 'Additional'), ('SUBMITTED', 'Submitted'), ('COMPLETE', 'Complete')], default='PAN', max_length=64)),
                ('pre_screen_completion', models.PositiveSmallIntegerField(default=0)),
                ('post_screen_completion', models.PositiveSmallIntegerField(default=0)),
                ('stage_payload', models.JSONField(blank=True, default=default_json)),
                ('saas_request_id', models.CharField(blank=True, max_length=128, null=True)),
                ('saas_status', models.CharField(blank=True, max_length=64, null=True)),
                ('saas_create_loan_status', models.CharField(blank=True, max_length=64, null=True)),
                ('saas_create_loan_raw', models.JSONField(blank=True, default=default_json)),
                ('saas_last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('saas_attempts', models.PositiveIntegerField(default=0)),
                ('bureau_score', models.IntegerField(blank=True, null=True)),
                ('bureau_decision', models.CharField(choices=[('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('PENDING', 'Pending')], default='PENDING', max_length=32)),
                ('bureau_raw', models.JSONField(blank=True, default=default_json)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='onboarding_v2.leadv2')),
                ('lending_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_v2_applications', to='lender.lender')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStageSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('PAN', 'Pan'), ('BASIC', 'Basic'), ('ADDRESS', 'Address'), ('DOCUMENTS', 'Documents'), ('PERSONAL', 'Personal'), ('ADDRESS_SECONDARY', 'AddressSecondary'), ('GOLD', 'Gold'), ('LOAN', 'Loan'), ('BANK', 'Bank'), ('ADDITIONAL', 'Additional'), ('SUBMITTED', 'Submitted'), ('COMPLETE', 'Complete')], max_length=64)),
                ('payload', models.JSONField(blank=True, default=default_json)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_snapshots', to='onboarding_v2.applicationv2')),
            ],
            options={
                'unique_together': {('application', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('PAN', 'PAN'), ('AADHAAR_FRONT', 'Aadhaar Front'), ('AADHAAR_BACK', 'Aadhaar Back'), ('LIVE_PHOTO', 'Live Photo'), ('VOTER_ID', 'Voter ID'), ('DRIVING_LICENSE', 'Driving License'), ('PASSPORT', 'Passport'), ('OTHER', 'Other')], default='OTHER', max_length=64)),
                ('subtype', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('VERIFIED', 'Verified'), ('PENDING_UPLOAD', 'PendingUpload'), ('UPLOADED', 'Uploaded')], default='UPLOADED', max_length=32)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='media/application_doc')),
                ('file_url', models.CharField(blank=True, max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, default=default_json)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='onboarding_v2.applicationv2')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_v2_documents', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('packet_id', models.CharField(max_length=128)),
                ('barcode_id', models.CharField(blank=True, max_length=128, null=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('gross_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('net_adjusted_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('net_adjusted_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('appraiser_id', models.CharField(blank=True, max_length=128, null=True)),
                ('appraiser_name', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=default_json)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='onboarding_v2.applicationv2')),
            ],
        ),
        migrations.CreateModel(
            name='JewelleryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_of_jewellery', models.CharField(blank=True, max_length=128, null=True)),
                ('number_of_articles', models.PositiveIntegerField(default=1)),
                ('purity', models.CharField(blank=True, max_length=64, null=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('stone_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('impurity_deducted', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('net_adjusted_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('percent_of_gold', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('actual_gold_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True)),
                ('gross_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('net_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('net_adjusted_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('front_image', models.FileField(blank=True, max_length=255, null=True, upload_to='media/application_doc')),
                ('back_image', models.FileField(blank=True, max_length=255, null=True, upload_to='media/application_doc')),
                ('weighing_machine_image', models.FileField(blank=True, max_length=255, null=True, upload_to='media/application_doc')),
                ('appraiser_certificate_image', models.FileField(blank=True, max_length=255, null=True, upload_to='media/application_doc')),
                ('metadata', models.JSONField(blank=True, default=default_json)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='onboarding_v2.packet')),
            ],
        ),
        migrations.CreateModel(
            name='BankDetailsV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=64, null=True)),
                ('customer_name_as_per_bank', models.CharField(blank=True, max_length=255, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cheque_image', models.FileField(blank=True, max_length=255, null=True, upload_to='media/application_doc')),
                ('metadata', models.JSONField(blank=True, default=default_json)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='onboarding_v2.applicationv2')),
            ],
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=255)),
                ('branch_name', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('branch_code', models.CharField(blank=True, max_length=64, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('metadata', models.JSONField(blank=True, default=default_json)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('lender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_v2_branches', to='lender.lender')),
            ],
            options={
                'unique_together': {('lender', 'ifsc_code')},
            },
        ),
        migrations.CreateModel(
            name='AdditionalDetailsV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_employee', models.BooleanField(default=False)),
                ('nominee_relation', models.CharField(blank=True, max_length=128, null=True)),
                ('nominee_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('nominee_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('metadata', models.JSONField(blank=True, default=default_json)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_details', to='onboarding_v2.applicationv2')),
            ],
        ),
        migrations.CreateModel(
            name='AddressV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('CURRENT', 'Current')], default='PERMANENT', max_length=32)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line3', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=default_json)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='onboarding_v2.applicationv2')),
            ],
            options={
                'unique_together': {('application', 'address_type')},
            },
        ),
    ]
