# Generated by Django 4.0.5 on 2025-12-15 13:22

from django.db import migrations, models
import onboarding_v2.models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0004_merge_20251215_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaldetailsv2',
            name='metadata',
            field=models.JSONField(blank=True, default=onboarding_v2.models.default_json),
        ),
        migrations.AlterField(
            model_name='addressv2',
            name='address_type',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('CURRENT', 'Current'), ('MAILING', 'Mailing')], default='PERMANENT', max_length=32),
        ),
        migrations.AlterField(
            model_name='addressv2',
            name='metadata',
            field=models.JSONField(blank=True, default=onboarding_v2.models.default_json),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='metadata',
            field=models.JSONField(blank=True, default=onboarding_v2.models.default_json),
        ),
        migrations.AlterField(
            model_name='applicationstagesnapshot',
            name='payload',
            field=models.JSONField(blank=True, default=onboarding_v2.models.default_json),
        ),
        migrations.AlterField(
            model_name='applicationv2',
            name='bureau_raw',
            field=models.JSONField(blank=True, default=onboarding_v2.models.default_json),
        ),
        migrations.AlterField(
            model_name='applicationv2',
            name='saas_create_loan_raw',
            field=models.JSONField(blank=True, default=onboarding_v2.models.default_json),
        ),
        migrations.AlterField(
            model_name='applicationv2',
            name='stage_payload',
            field=models.JSONField(blank=True, default=onboarding_v2.models.default_json),
        ),
        migrations.AlterField(
            model_name='applicationv2',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT_FOR_PRE_SCREENING', 'SentForPreScreening'), ('IN_PROGRESS', 'InProgress'), ('CORRECTION', 'Correction'), ('REJECTED', 'Rejected'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'NotEligible'), ('PASSED', 'Passed'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=64),
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='metadata',
            field=models.JSONField(blank=True, default=onboarding_v2.models.default_json),
        ),
        migrations.AlterField(
            model_name='bankdetailsv2',
            name='metadata',
            field=models.JSONField(blank=True, default=onboarding_v2.models.default_json),
        ),
        migrations.AlterField(
            model_name='jewelleryitem',
            name='metadata',
            field=models.JSONField(blank=True, default=onboarding_v2.models.default_json),
        ),
        migrations.AlterField(
            model_name='leadv2',
            name='metadata',
            field=models.JSONField(blank=True, default=onboarding_v2.models.default_json),
        ),
        migrations.AlterField(
            model_name='leadv2',
            name='product_subcategory',
            field=models.CharField(blank=True, choices=[('BALANCE_TRANSFER', 'Balance Transfer'), ('FRESH_LOAN', 'Fresh Loan'), ('CO_LENDING', 'Co Lending')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='packet',
            name='metadata',
            field=models.JSONField(blank=True, default=onboarding_v2.models.default_json),
        ),
    ]
