# Generated by Django 4.0.5 on 2025-12-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0006_webhookevent'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='webhookevent',
            name='onboarding__applic_3f8334_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookevent',
            name='onboarding__request_c9b60e_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookevent',
            name='onboarding__status__n_3c6f7f_idx',
        ),
        migrations.AlterField(
            model_name='leadv2',
            name='contact_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['application_id'], name='onboarding__applica_9e9fac_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['request_id'], name='onboarding__request_c3dd4b_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['status', 'next_retry_at'], name='onboarding__status_c16b34_idx'),
        ),
    ]
