# Generated by Django 4.0.5 on 2025-12-19 11:44

from django.db import migrations, models
import django.db.models.deletion
import onboarding_v2.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0007_remove_webhookevent_onboarding__applic_3f8334_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaasRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_identifier', models.CharField(max_length=128)),
                ('request_type', models.CharField(choices=[('CREATE_LEAD', 'Create Lead'), ('CREATE_LOAN', 'Create Loan'), ('BUREAU_CHECK', 'Bureau Check')], max_length=32)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_payload', models.JSONField(blank=True, default=onboarding_v2.models.default_json)),
                ('last_response_status', models.IntegerField(blank=True, null=True)),
                ('last_response_body', models.JSONField(blank=True, default=onboarding_v2.models.default_json)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('first_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saas_logs', to='onboarding_v2.applicationv2')),
            ],
        ),
        migrations.AddIndex(
            model_name='saasrequestlog',
            index=models.Index(fields=['application_identifier', 'request_type'], name='onboarding__applica_260eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='saasrequestlog',
            index=models.Index(fields=['last_attempt_at'], name='onboarding__last_at_5f6de4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='saasrequestlog',
            unique_together={('application_identifier', 'request_type')},
        ),
    ]
