# Generated by Django 4.0.5 on 2025-12-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding_v2", "0009_add_saas_request_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationv2",
            name="saas_lead_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
