# Generated by Django 4.0.5 on 2025-12-19 13:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding_v2", "0010_add_saas_lead_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdSequence",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, unique=True)),
                ("last_value", models.PositiveIntegerField(default=0)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="leadv2",
            name="lead_code",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
