# Generated by Django 4.2.27 on 2025-12-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0011_id_sequences_and_lead_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idsequence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leadv2',
            name='product_subcategory',
            field=models.CharField(blank=True, choices=[('BALANCE_TRANSFER', 'Balance Transfer'), ('FRESH_LOAN', 'Fresh Loan'), ('CO_LENDING', 'Co Lending'), ('GOLD_LOAN', 'Gold Loan')], max_length=64, null=True),
        ),
    ]
