# Generated by Django 4.0.5 on 2025-12-31 14:05

from django.db import migrations, models
import onboarding_v2.models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0013_merge_conflicting_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationv2',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT_FOR_PRE_SCREENING', 'SentForPreScreening'), ('IN_PROGRESS', 'InProgress'), ('READY_FOR_LOAN', 'ReadyForLoan'), ('APPROVED', 'Approved'), ('AGREEMENT_SIGNED', 'AgreementSigned'), ('DISBURSEMENT_READY', 'DisbursementReady'), ('DISBURSED', 'Disbursed'), ('MATURED', 'Matured'), ('DROPPED', 'Dropped'), ('DISBURSEMENT_CANCELLED', 'DisbursementCancelled'), ('DROP_REQUESTED', 'DropRequested'), ('ALLOCATION_PENDING', 'AllocationPending'), ('COMMERCIAL_PROCESSING', 'CommercialProcessing'), ('DEVIATION_REQUESTED', 'DeviationRequested'), ('CORRECTION', 'Correction'), ('REJECTED', 'Rejected'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'NotEligible'), ('PASSED', 'Passed'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=64),
        ),
        migrations.AlterField(
            model_name='jewelleryitem',
            name='appraiser_certificate_image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=onboarding_v2.models.jewellery_upload_path),
        ),
        migrations.AlterField(
            model_name='jewelleryitem',
            name='back_image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=onboarding_v2.models.jewellery_upload_path),
        ),
        migrations.AlterField(
            model_name='jewelleryitem',
            name='front_image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=onboarding_v2.models.jewellery_upload_path),
        ),
        migrations.AlterField(
            model_name='jewelleryitem',
            name='weighing_machine_image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=onboarding_v2.models.jewellery_upload_path),
        ),
        migrations.AlterField(
            model_name='leadv2',
            name='source',
            field=models.CharField(choices=[('SELF', 'Self'), ('AGENT', 'Agent'), ('OTHER', 'Other'), ('CENTRAL', 'Central')], default='SELF', max_length=32),
        ),
        migrations.AlterField(
            model_name='leadv2',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT_FOR_PRE_SCREENING', 'SentForPreScreening'), ('IN_PROGRESS', 'InProgress'), ('READY_FOR_LOAN', 'ReadyForLoan'), ('APPROVED', 'Approved'), ('AGREEMENT_SIGNED', 'AgreementSigned'), ('DISBURSEMENT_READY', 'DisbursementReady'), ('DISBURSED', 'Disbursed'), ('MATURED', 'Matured'), ('DROPPED', 'Dropped'), ('DISBURSEMENT_CANCELLED', 'DisbursementCancelled'), ('DROP_REQUESTED', 'DropRequested'), ('ALLOCATION_PENDING', 'AllocationPending'), ('COMMERCIAL_PROCESSING', 'CommercialProcessing'), ('DEVIATION_REQUESTED', 'DeviationRequested'), ('CORRECTION', 'Correction'), ('REJECTED', 'Rejected'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'NotEligible'), ('PASSED', 'Passed'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=64),
        ),
    ]
