# Generated by Django 4.0.5 on 2026-01-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0014_alter_applicationv2_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jewelleryitem',
            name='appraiser_certificate_image',
        ),
        migrations.RemoveField(
            model_name='jewelleryitem',
            name='back_image',
        ),
        migrations.RemoveField(
            model_name='jewelleryitem',
            name='front_image',
        ),
        migrations.RemoveField(
            model_name='jewelleryitem',
            name='weighing_machine_image',
        ),
        migrations.AddField(
            model_name='jewelleryitem',
            name='appraiser_certificate_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jewelleryitem',
            name='back_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jewelleryitem',
            name='front_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jewelleryitem',
            name='weighing_machine_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
