# Generated by Django 4.0.5 on 2026-01-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0015_remove_jewelleryitem_appraiser_certificate_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetailsv2',
            name='cheque_image',
        ),
        migrations.AddField(
            model_name='bankdetailsv2',
            name='cheque_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
