# Generated by Django 4.0.5 on 2026-01-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0017_alter_applicationv2_lending_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationv2',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT_FOR_PRE_SCREENING', 'SentForPreScreening'), ('IN_PROGRESS', 'InProgress'), ('READY_FOR_LOAN', 'ReadyForLoan'), ('APPROVED', 'Approved'), ('AGREEMENT_SIGNED', 'AgreementSigned'), ('DISBURSEMENT_READY', 'DisbursementReady'), ('DISBURSED', 'Disbursed'), ('MATURED', 'Matured'), ('DROPPED', 'Dropped'), ('DISBURSEMENT_CANCELLED', 'DisbursementCancelled'), ('DROP_REQUESTED', 'DropRequested'), ('ALLOCATION_PENDING', 'AllocationPending'), ('COMMERCIAL_PROCESSING', 'CommercialProcessing'), ('DEVIATION_REQUESTED', 'DeviationRequested'), ('CORRECTION', 'Correction'), ('REJECTED', 'Rejected'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'NotEligible'), ('PASSED', 'Passed'), ('SUBMITTED', 'Submitted'), ('FAILED_TO_SUBMIT', 'FailedToSubmit')], default='DRAFT', max_length=64),
        ),
        migrations.AlterField(
            model_name='leadv2',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT_FOR_PRE_SCREENING', 'SentForPreScreening'), ('IN_PROGRESS', 'InProgress'), ('READY_FOR_LOAN', 'ReadyForLoan'), ('APPROVED', 'Approved'), ('AGREEMENT_SIGNED', 'AgreementSigned'), ('DISBURSEMENT_READY', 'DisbursementReady'), ('DISBURSED', 'Disbursed'), ('MATURED', 'Matured'), ('DROPPED', 'Dropped'), ('DISBURSEMENT_CANCELLED', 'DisbursementCancelled'), ('DROP_REQUESTED', 'DropRequested'), ('ALLOCATION_PENDING', 'AllocationPending'), ('COMMERCIAL_PROCESSING', 'CommercialProcessing'), ('DEVIATION_REQUESTED', 'DeviationRequested'), ('CORRECTION', 'Correction'), ('REJECTED', 'Rejected'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'NotEligible'), ('PASSED', 'Passed'), ('SUBMITTED', 'Submitted'), ('FAILED_TO_SUBMIT', 'FailedToSubmit')], default='DRAFT', max_length=64),
        ),
    ]
