# Generated by Django 4.0.5 on 2026-02-05 04:57

from django.db import migrations, models
import onboarding_v2.models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0023_alter_applicationdocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationv2',
            name='number_of_animal_cattle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='document_type',
            field=models.CharField(choices=[('PAN', 'PAN'), ('AADHAAR', 'Aadhaar'), ('LIVE_PHOTO', 'Live Photo'), ('VOTER_ID', 'Voter ID'), ('DRIVING_LICENSE', 'Driving License'), ('PASSPORT', 'Passport'), ('OTHER', 'Other'), ('CATTLE', 'Cattle')], default='OTHER', max_length=64),
        ),
        migrations.AlterField(
            model_name='applicationv2',
            name='loan_type',
            field=models.CharField(blank=True, choices=[('FRESH', 'Fresh'), ('BT', 'BT'), ('CO_LENDING', 'Co-Lending')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='applicationv2',
            name='saas_prescreen_raw',
            field=models.JSONField(blank=True, default=onboarding_v2.models.default_json),
        ),
    ]
