# Generated by Django 4.0.5 on 2026-02-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0024_applicationv2_number_of_animal_cattle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadv2',
            name='customer_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
