# Generated by Django 4.0.5 on 2026-02-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0025_alter_leadv2_customer_id'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE onboarding_v2_leadv2 "
                        "DROP CONSTRAINT IF EXISTS onboarding_v2_leadv2_customer_id_key"
                    ),
                    reverse_sql=(
                        "ALTER TABLE onboarding_v2_leadv2 "
                        "ADD CONSTRAINT onboarding_v2_leadv2_customer_id_key UNIQUE (customer_id)"
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        "DROP INDEX IF EXISTS onboarding_v2_leadv2_customer_id_4ee011b9_uniq; "
                        "DROP INDEX IF EXISTS onboarding_v2_leadv2_customer_id_4ee011b9; "
                        "CREATE INDEX IF NOT EXISTS onboarding_v2_leadv2_customer_id_4ee011b9 "
                        "ON onboarding_v2_leadv2 (customer_id)"
                    ),
                    reverse_sql=(
                        "DROP INDEX IF EXISTS onboarding_v2_leadv2_customer_id_4ee011b9"
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='leadv2',
                    name='customer_id',
                    field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
            ],
        ),
    ]
