# Generated by Django 4.0.5 on 2026-02-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0026_alter_leadv2_customer_id'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "DROP INDEX IF EXISTS onboarding_v2_leadv2_contact_number_5b9b44ab; "
                        "CREATE INDEX IF NOT EXISTS onboarding_v2_leadv2_contact_number_5b9b44ab "
                        "ON onboarding_v2_leadv2 (contact_number)"
                    ),
                    reverse_sql=(
                        "DROP INDEX IF EXISTS onboarding_v2_leadv2_contact_number_5b9b44ab"
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='leadv2',
                    name='contact_number',
                    field=models.CharField(db_index=True, max_length=20),
                ),
            ],
        ),
    ]
