# Generated by Django 4.0.5 on 2026-03-12 14:58

from django.db import migrations, models
import django.db.models.deletion
import onboarding_v2.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0027_alter_leadv2_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationv2',
            name='lending_partner',
            field=models.CharField(blank=True, choices=[('AXIS_BANK', 'Axis Bank'), ('HDFC_BANK', 'HDFC Bank'), ('ICICI_BANK', 'ICICI Bank'), ('RBL_BANK', 'RBL Bank'), ('DBS_BANK', 'DBS Bank'), ('KOTAK_BANK', 'Kotak Bank'), ('KARNATAKA_BANK', 'Karnataka Bank'), ('OTHER', 'Other')], default='AXIS_BANK', max_length=64, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS onboarding_v2_loanpunchv2 (
                        id uuid PRIMARY KEY,
                        approval_status varchar(32) NOT NULL,
                        bank_name varchar(255) NOT NULL,
                        crm_id varchar(128) NULL,
                        is_agriculture boolean NOT NULL,
                        loan_account_number varchar(64) NOT NULL,
                        loan_opening_date date NOT NULL,
                        sanctioned_amount numeric(16, 2) NOT NULL,
                        approved_tenure integer NOT NULL CHECK (approved_tenure >= 0),
                        disbursed_amount numeric(16, 2) NOT NULL,
                        rate_of_interest numeric(8, 3) NOT NULL,
                        gross_weight numeric(14, 3) NULL,
                        net_weight numeric(14, 3) NULL,
                        is_customer_kit_gifted boolean NOT NULL,
                        rejection_reason varchar(255) NULL,
                        remarks text NULL,
                        metadata jsonb NOT NULL,
                        created_at timestamptz NOT NULL,
                        modified_at timestamptz NOT NULL,
                        application_id uuid NOT NULL
                    );
                    CREATE INDEX IF NOT EXISTS onboarding_v2_loanpunchv2_application_id_9c4b04fb
                    ON onboarding_v2_loanpunchv2 (application_id);
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM pg_constraint
                            WHERE conname = 'onboarding_v2_loan_application_id_9c4b04fb_fk_onboardi'
                        ) THEN
                            ALTER TABLE onboarding_v2_loanpunchv2
                            ADD CONSTRAINT onboarding_v2_loan_application_id_9c4b04fb_fk_onboardi
                            FOREIGN KEY (application_id)
                            REFERENCES onboarding_v2_applicationv2 (id)
                            DEFERRABLE INITIALLY DEFERRED;
                        END IF;
                    END
                    $$;
                    """,
                    reverse_sql="DROP TABLE IF EXISTS onboarding_v2_loanpunchv2 CASCADE;",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='LoanPunchV2',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('approval_status', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('CHANGE_BANK', 'Change Bank')], default='APPROVE', max_length=32)),
                        ('bank_name', models.CharField(max_length=255)),
                        ('crm_id', models.CharField(blank=True, max_length=128, null=True)),
                        ('is_agriculture', models.BooleanField(default=False)),
                        ('loan_account_number', models.CharField(max_length=64)),
                        ('loan_opening_date', models.DateField()),
                        ('sanctioned_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                        ('approved_tenure', models.PositiveIntegerField()),
                        ('disbursed_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                        ('rate_of_interest', models.DecimalField(decimal_places=3, max_digits=8)),
                        ('gross_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                        ('net_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                        ('is_customer_kit_gifted', models.BooleanField(default=False)),
                        ('rejection_reason', models.CharField(blank=True, max_length=255, null=True)),
                        ('remarks', models.TextField(blank=True, null=True)),
                        ('metadata', models.JSONField(blank=True, default=onboarding_v2.models.default_json)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('modified_at', models.DateTimeField(auto_now=True)),
                        ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punched_loans', to='onboarding_v2.applicationv2')),
                    ],
                ),
            ],
        ),
    ]
