# Generated by Django 4.0.5 on 2026-03-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0028_alter_applicationv2_lending_partner_loanpunchv2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocument',
            name='document_type',
            field=models.CharField(choices=[('PAN', 'PAN'), ('AADHAAR', 'Aadhaar'), ('LIVE_PHOTO', 'Live Photo'), ('VOTER_ID', 'Voter ID'), ('DRIVING_LICENSE', 'Driving License'), ('PASSPORT', 'Passport'), ('MANREGA_CARD', 'Manrega Card'), ('OTHER', 'Other'), ('CATTLE', 'Cattle')], default='OTHER', max_length=64),
        ),
    ]
