# Generated by Django 4.0.5 on 2026-03-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0031_alter_applicationv2_status_alter_leadv2_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpunchv2',
            name='is_bank_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanpunchv2',
            name='new_bank_branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loanpunchv2',
            name='new_bank_district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loanpunchv2',
            name='new_bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loanpunchv2',
            name='new_bank_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanpunchv2',
            name='approved_tenure',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanpunchv2',
            name='disbursed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='loanpunchv2',
            name='loan_account_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='loanpunchv2',
            name='loan_opening_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanpunchv2',
            name='rate_of_interest',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='loanpunchv2',
            name='sanctioned_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
