# Generated by Django 4.0.5 on 2026-03-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0032_loanpunchv2_is_bank_changed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpunchv2',
            name='approval_status',
            field=models.CharField(choices=[('APPROVED', 'Approve'), ('REJECTED', 'Reject'), ('CHANGE_BANK', 'Change Bank')], default='APPROVED', max_length=32),
        ),
    ]
