# Generated by Django 4.0.5 on 2026-03-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0033_alter_loanpunchv2_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpunchv2',
            name='approval_status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHANGE_BANK', 'Change Bank')], default='APPROVED', max_length=32),
        ),
    ]
