# Generated by Django 4.0.5 on 2026-03-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0034_alter_loanpunchv2_approval_status'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='bankbranch',
                    unique_together={('ifsc_code',)},
                ),
            ],
            database_operations=[]
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='district',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='pincode',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='sol_id',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='state',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='bankbranch',
                    name='lender',
                ),
            ],
            database_operations=[]
        ),
    ]
