# Generated by Django 4.0.5 on 2026-04-01 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0035_alter_bankbranch_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocument',
            name='document_type',
            field=models.CharField(choices=[('PAN', 'PAN'), ('AADHAAR', 'Aadhaar'), ('LIVE_PHOTO', 'Live Photo'), ('VOTER_ID', 'Voter ID'), ('DRIVING_LICENSE', 'Driving License'), ('PASSPORT', 'Passport'), ('MANREGA_CARD', 'Manrega Card'), ('OTHER', 'Other'), ('CATTLE', 'Cattle'), ('FRESH_LOAN', 'Fresh Loan')], default='OTHER', max_length=64),
        ),
        migrations.AlterField(
            model_name='applicationv2',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT_FOR_PRE_SCREENING', 'SentForPreScreening'), ('IN_PROGRESS', 'InProgress'), ('READY_FOR_LOAN', 'ReadyForLoan'), ('APPROVED', 'Approved'), ('AGREEMENT_SIGNED', 'AgreementSigned'), ('DISBURSEMENT_READY', 'DisbursementReady'), ('DISBURSED', 'Disbursed'), ('MATURED', 'Matured'), ('DROPPED', 'Dropped'), ('DISBURSEMENT_CANCELLED', 'DisbursementCancelled'), ('DROP_REQUESTED', 'DropRequested'), ('ALLOCATION_PENDING', 'AllocationPending'), ('COMMERCIAL_PROCESSING', 'CommercialProcessing'), ('DEVIATION_REQUESTED', 'DeviationRequested'), ('CORRECTION', 'Correction'), ('REJECTED', 'Rejected'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'NotEligible'), ('PASSED', 'Passed'), ('SUBMITTED', 'Submitted'), ('FAILED_TO_SUBMIT', 'FailedToSubmit'), ('FAILED_TO_SUBMIT_PRESCREEN', 'FailedToSubmitPrescreen'), ('FAILED_TO_SUBMIT_CREATE_LOAN', 'FailedToSubmitCreateLoan'), ('NEW_LEAD', 'NewLead'), ('UNVERIFIED', 'Unverified'), ('PUNCHING_PENDING', 'Punching Pending')], default='DRAFT', max_length=64),
        ),
        migrations.AlterField(
            model_name='leadv2',
            name='status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('ACTIVE', 'Active'), ('AUTO_CLOSED', 'Auto-closed'), ('APPLICATION_CREATED', 'Application created')], default='ACTIVE', max_length=64),
        ),
        migrations.CreateModel(
            name='LeadAutoClosureSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lead_type', models.CharField(choices=[('FRESH', 'Fresh'), ('BT', 'BT'), ('CO_LENDING', 'Co-Lending')], max_length=32)),
                ('product_subcategory', models.CharField(choices=[('GOLD_LOAN', 'Gold Loan'), ('HOME_LOAN', 'Home Loan'), ('PERSONAL_LOAN', 'Personal Loan'), ('BUSINESS_LOAN', 'Business Loan'), ('LOAN_AGAINST_PROPERTY', 'Loan Against Property'), ('MOTOR_LOAN', 'Motor Loan'), ('HEALTH_INSURANCE', 'Health Insurance'), ('MOTOR_INSURANCE', 'Motor Insurance')], max_length=64)),
                ('auto_closure_days', models.PositiveIntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('lead_type', 'product_subcategory')},
            },
        ),
    ]
