# Generated by Django 4.0.5 on 2026-04-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0036_alter_applicationdocument_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpunchv2',
            name='agent_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='loanpunchv2',
            name='agent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
