# Generated by Django 4.0.5 on 2026-04-13 06:40

from django.db import migrations, models
import onboarding_v2.models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0038_lendingpartnermaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationv2',
            name='lending_partner',
            field=models.CharField(blank=True, choices=[('AXIS_BANK', 'Axis Bank'), ('CSB_BANK', 'CSB Bank'), ('DBS', 'DBS'), ('DCB_BANK', 'DCB Bank'), ('HDFC_BANK', 'HDFC Bank'), ('ICICI_BANK', 'ICICI Bank'), ('KOTAK_MAHINDRA_BANK', 'Kotak Mahindra Bank'), ('RBL_BANK', 'RBL Bank'), ('Axis Bank', 'Axis Bank'), ('CSB Bank', 'CSB Bank'), ('DCB Bank', 'DCB Bank'), ('HDFC Bank', 'HDFC Bank'), ('ICICI Bank', 'ICICI Bank'), ('Kotak Mahindra Bank', 'Kotak Mahindra Bank'), ('RBL Bank', 'RBL Bank'), ('DBS_BANK', 'DBS Bank'), ('KOTAK_BANK', 'Kotak Bank'), ('KARNATAKA_BANK', 'Karnataka Bank'), ('OTHER', 'Other')], default='AXIS_BANK', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='applicationv2',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT_FOR_PRE_SCREENING', 'SentForPreScreening'), ('IN_PROGRESS', 'InProgress'), ('READY_FOR_LOAN', 'ReadyForLoan'), ('APPROVED', 'Approved'), ('AGREEMENT_SIGNED', 'AgreementSigned'), ('DISBURSEMENT_READY', 'DisbursementReady'), ('DISBURSED', 'Disbursed'), ('MATURED', 'Matured'), ('DROPPED', 'Dropped'), ('DISBURSEMENT_CANCELLED', 'DisbursementCancelled'), ('DROP_REQUESTED', 'DropRequested'), ('ALLOCATION_PENDING', 'AllocationPending'), ('COMMERCIAL_PROCESSING', 'CommercialProcessing'), ('DEVIATION_REQUESTED', 'DeviationRequested'), ('CORRECTION', 'Correction'), ('REJECTED', 'Rejected'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'NotEligible'), ('PASSED', 'Passed'), ('SUBMITTED', 'Submitted'), ('FAILED_TO_SUBMIT', 'FailedToSubmit'), ('FAILED_TO_SUBMIT_PRESCREEN', 'FailedToSubmitPrescreen'), ('FAILED_TO_SUBMIT_CREATE_LOAN', 'FailedToSubmitCreateLoan'), ('NEW_LEAD', 'NewLead'), ('UNVERIFIED', 'Unverified'), ('PUNCHING_PENDING', 'Punching Pending'), ('LOAN_STATUS_UPDATED', 'Loan Status Updated')], default='DRAFT', max_length=64),
        ),
        migrations.AlterField(
            model_name='leadv2',
            name='source',
            field=models.CharField(choices=[('SELF', 'Self'), ('BANK_REFERRED', 'Bank Reffered'), ('CENTRAL', 'Central'), ('TELE', 'Tele')], default='SELF', max_length=32),
        ),
        migrations.AlterField(
            model_name='lendingpartnermaster',
            name='metadata',
            field=models.JSONField(blank=True, default=onboarding_v2.models.default_json),
        ),
        migrations.AlterField(
            model_name='loanpunchv2',
            name='approval_status',
            field=models.CharField(choices=[('APPROVED', 'Loan Status Updated'), ('REJECTED', 'Rejected'), ('CHANGE_BANK', 'Change Bank')], default='APPROVED', max_length=32),
        ),
    ]
