# Generated by Django 4.0.5 on 2026-04-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0041_drop_legacy_unique_contact_number_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationv2',
            name='loan_type',
            field=models.CharField(blank=True, choices=[('FRESH', 'Fresh'), ('BALANCE_TRANSFER', 'Balance Transfer'), ('CO_LENDING', 'Co-Lending')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='leadautoclosuresetting',
            name='lead_type',
            field=models.CharField(choices=[('FRESH', 'Fresh'), ('BALANCE_TRANSFER', 'Balance Transfer'), ('CO_LENDING', 'Co-Lending')], max_length=32),
        ),
        migrations.AlterField(
            model_name='leadautoclosuresetting',
            name='product_subcategory',
            field=models.CharField(choices=[('GOLD_LOAN', 'Gold Loan'), ('HOME_LOAN', 'Home Loan'), ('PERSONAL_LOAN', 'Personal Loan'), ('BUSINESS_LOAN', 'Business Loan'), ('LOAN_AGAINST_PROPERTY', 'Loan Against Property'), ('MOTOR_LOAN', 'Motor Loan'), ('WORKING_CAPITAL', 'Working Capital'), ('OVERDRAFT_DOD', 'Overdraft(DOD)'), ('HEALTH_INSURANCE', 'Health Insurance'), ('MOTOR_INSURANCE', 'Motor Insurance')], max_length=64),
        ),
        migrations.AlterField(
            model_name='leadv2',
            name='lead_type',
            field=models.CharField(blank=True, choices=[('FRESH', 'Fresh'), ('BALANCE_TRANSFER', 'Balance Transfer'), ('CO_LENDING', 'Co-Lending')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='leadv2',
            name='product_subcategory',
            field=models.CharField(blank=True, choices=[('GOLD_LOAN', 'Gold Loan'), ('HOME_LOAN', 'Home Loan'), ('PERSONAL_LOAN', 'Personal Loan'), ('BUSINESS_LOAN', 'Business Loan'), ('LOAN_AGAINST_PROPERTY', 'Loan Against Property'), ('MOTOR_LOAN', 'Motor Loan'), ('WORKING_CAPITAL', 'Working Capital'), ('OVERDRAFT_DOD', 'Overdraft(DOD)'), ('HEALTH_INSURANCE', 'Health Insurance'), ('MOTOR_INSURANCE', 'Motor Insurance')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='leadv2',
            name='source',
            field=models.CharField(choices=[('SELF', 'Self'), ('BANK_REFERRED', 'Bank Reffered'), ('CENTRAL', 'Central'), ('TELE', 'Tele'), ('AGENT', 'Agent')], default='SELF', max_length=32),
        ),
        migrations.AlterField(
            model_name='lendingpartnermaster',
            name='available_for',
            field=models.CharField(choices=[('GOLD_LOAN', 'Gold Loan'), ('HOME_LOAN', 'Home Loan'), ('PERSONAL_LOAN', 'Personal Loan'), ('BUSINESS_LOAN', 'Business Loan'), ('LOAN_AGAINST_PROPERTY', 'Loan Against Property'), ('MOTOR_LOAN', 'Motor Loan'), ('WORKING_CAPITAL', 'Working Capital'), ('OVERDRAFT_DOD', 'Overdraft(DOD)'), ('HEALTH_INSURANCE', 'Health Insurance'), ('MOTOR_INSURANCE', 'Motor Insurance')], max_length=64),
        ),
    ]
