# Generated by Django 4.0.5 on 2026-04-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0041_rename_bt_to_balance_transfer'),
        ('onboarding_v2', '0043_add_leadv2_email_address'),
    ]

    operations = [
    ]
