# Generated by Django 4.0.5 on 2026-04-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0045_alter_applicationdocument_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocument',
            name='document_type',
            field=models.CharField(choices=[('PAN', 'PAN'), ('AADHAAR', 'Aadhaar'), ('LIVE_PHOTO', 'Live Photo'), ('VOTER_ID', 'Voter ID'), ('DRIVING_LICENSE', 'Driving License'), ('PASSPORT', 'Passport'), ('MANREGA_CARD', 'Manrega Card'), ('OTHER', 'Other'), ('CATTLE', 'Cattle'), ('FRESH_LOAN', 'Fresh Loan')], default='OTHER', max_length=64),
        ),
        migrations.AlterField(
            model_name='applicationstagesnapshot',
            name='stage',
            field=models.CharField(choices=[('PAN', 'Pan'), ('BASIC', 'Basic'), ('ADDRESS', 'Address'), ('DOCUMENTS', 'Documents'), ('PERSONAL', 'Personal'), ('ADDRESS_SECONDARY', 'AddressSecondary'), ('GOLD', 'Gold'), ('LOAN', 'Loan'), ('BANK', 'Bank'), ('ADDITIONAL', 'Additional'), ('SUBMITTED', 'Submitted'), ('COMPLETE', 'Complete')], max_length=64),
        ),
        migrations.AlterField(
            model_name='applicationv2',
            name='stage',
            field=models.CharField(choices=[('PAN', 'Pan'), ('BASIC', 'Basic'), ('ADDRESS', 'Address'), ('DOCUMENTS', 'Documents'), ('PERSONAL', 'Personal'), ('ADDRESS_SECONDARY', 'AddressSecondary'), ('GOLD', 'Gold'), ('LOAN', 'Loan'), ('BANK', 'Bank'), ('ADDITIONAL', 'Additional'), ('SUBMITTED', 'Submitted'), ('COMPLETE', 'Complete')], default='PAN', max_length=64),
        ),
        migrations.AlterField(
            model_name='applicationv2',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT_FOR_PRE_SCREENING', 'SentForPreScreening'), ('IN_PROGRESS', 'InProgress'), ('READY_FOR_LOAN', 'ReadyForLoan'), ('APPROVED', 'Approved'), ('AGREEMENT_SIGNED', 'AgreementSigned'), ('DISBURSEMENT_READY', 'DisbursementReady'), ('DISBURSED', 'Disbursed'), ('MATURED', 'Matured'), ('DROPPED', 'Dropped'), ('DISBURSEMENT_CANCELLED', 'DisbursementCancelled'), ('DROP_REQUESTED', 'DropRequested'), ('ALLOCATION_PENDING', 'AllocationPending'), ('COMMERCIAL_PROCESSING', 'CommercialProcessing'), ('DEVIATION_REQUESTED', 'DeviationRequested'), ('CORRECTION', 'Correction'), ('REJECTED', 'Rejected'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'NotEligible'), ('PASSED', 'Passed'), ('SUBMITTED', 'Submitted'), ('FAILED_TO_SUBMIT', 'FailedToSubmit'), ('FAILED_TO_SUBMIT_PRESCREEN', 'FailedToSubmitPrescreen'), ('FAILED_TO_SUBMIT_CREATE_LOAN', 'FailedToSubmitCreateLoan'), ('NEW_LEAD', 'NewLead'), ('UNVERIFIED', 'Unverified'), ('PUNCHING_PENDING', 'Punching Pending'), ('LOAN_STATUS_UPDATED', 'Loan Status Updated')], default='DRAFT', max_length=64),
        ),
        migrations.AlterField(
            model_name='leadautoclosuresetting',
            name='product_subcategory',
            field=models.CharField(choices=[('GOLD_LOAN', 'Gold Loan'), ('HOME_LOAN', 'Home Loan'), ('PERSONAL_LOAN', 'Personal Loan'), ('BUSINESS_LOAN', 'Business Loan'), ('LOAN_AGAINST_PROPERTY', 'Loan Against Property'), ('MOTOR_LOAN', 'Motor Loan'), ('WORKING_CAPITAL', 'Working Capital'), ('OVERDRAFT_DOD', 'Overdraft(DOD)'), ('HEALTH_INSURANCE', 'Health Insurance'), ('MOTOR_INSURANCE', 'Motor Insurance'), ('CREDIT_CARDS', 'Credit Cards')], max_length=64),
        ),
        migrations.AlterField(
            model_name='leadv2',
            name='product_subcategory',
            field=models.CharField(blank=True, choices=[('GOLD_LOAN', 'Gold Loan'), ('HOME_LOAN', 'Home Loan'), ('PERSONAL_LOAN', 'Personal Loan'), ('BUSINESS_LOAN', 'Business Loan'), ('LOAN_AGAINST_PROPERTY', 'Loan Against Property'), ('MOTOR_LOAN', 'Motor Loan'), ('WORKING_CAPITAL', 'Working Capital'), ('OVERDRAFT_DOD', 'Overdraft(DOD)'), ('HEALTH_INSURANCE', 'Health Insurance'), ('MOTOR_INSURANCE', 'Motor Insurance'), ('CREDIT_CARDS', 'Credit Cards')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='lendingpartnermaster',
            name='available_for',
            field=models.CharField(choices=[('GOLD_LOAN', 'Gold Loan'), ('HOME_LOAN', 'Home Loan'), ('PERSONAL_LOAN', 'Personal Loan'), ('BUSINESS_LOAN', 'Business Loan'), ('LOAN_AGAINST_PROPERTY', 'Loan Against Property'), ('MOTOR_LOAN', 'Motor Loan'), ('WORKING_CAPITAL', 'Working Capital'), ('OVERDRAFT_DOD', 'Overdraft(DOD)'), ('HEALTH_INSURANCE', 'Health Insurance'), ('MOTOR_INSURANCE', 'Motor Insurance'), ('CREDIT_CARDS', 'Credit Cards')], max_length=64),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='CorrectionOnboarding',
                ),
            ],
            database_operations=[],
        ),
    ]
