# Generated by Django 4.0.5 on 2026-04-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0044_merge_20260421_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadv2',
            name='source',
            field=models.CharField(choices=[('SELF', 'Self'), ('BANK_REFERRED', 'Bank Reffered'), ('CENTRAL', 'Central'), ('TELE', 'Tele'), ('AGENT', 'Agent'), ('WEBSITE', 'Website'), ('DIGITAL_MARKETING', 'Digital Marketing'), ('BTL', 'BTL'), ('CSR', 'CSR'), ('WALK_IN', 'Walk-in'), ('REPEAT', 'Repeat'), ('DATABASE', 'Database')], default='SELF', max_length=32),
        ),
    ]
