# Generated by Django 4.0.5 on 2026-05-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding_v2", "0046_alter_applicationdocument_document_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadv2",
            name="lead_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FRESH", "Fresh"),
                    ("BALANCE_TRANSFER", "Balance Transfer"),
                    ("CO_LENDING", "Co-Lending"),
                    ("BANK_LEAD", "Bank Lead"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="applicationv2",
            name="loan_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FRESH", "Fresh"),
                    ("BALANCE_TRANSFER", "Balance Transfer"),
                    ("CO_LENDING", "Co-Lending"),
                    ("BANK_LEAD", "Bank Lead"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]

