# Generated by Django 4.0.5 on 2026-05-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0046_alter_applicationdocument_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadv2',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadv2',
            name='bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadv2',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadv2',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadv2',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='leadv2',
            name='is_pan_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadv2',
            name='lending_partner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadv2',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicationv2',
            name='loan_type',
            field=models.CharField(blank=True, choices=[('FRESH', 'Fresh'), ('BALANCE_TRANSFER', 'Balance Transfer'), ('CO_LENDING', 'Co-Lending'), ('BANK_LEAD', 'Bank Lead')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='leadautoclosuresetting',
            name='lead_type',
            field=models.CharField(choices=[('FRESH', 'Fresh'), ('BALANCE_TRANSFER', 'Balance Transfer'), ('CO_LENDING', 'Co-Lending'), ('BANK_LEAD', 'Bank Lead')], max_length=32),
        ),
        migrations.AlterField(
            model_name='leadv2',
            name='lead_type',
            field=models.CharField(blank=True, choices=[('FRESH', 'Fresh'), ('BALANCE_TRANSFER', 'Balance Transfer'), ('CO_LENDING', 'Co-Lending'), ('BANK_LEAD', 'Bank Lead')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='leadv2',
            name='source',
            field=models.CharField(choices=[('SELF', 'Self'), ('BANK_REFERRED', 'Bank Reffered'), ('CENTRAL', 'Central'), ('TELE', 'Tele'), ('AGENT', 'Agent'), ('WEBSITE', 'Website'), ('DIGITAL_MARKETING', 'Digital Marketing'), ('BTL', 'BTL'), ('CSR', 'CSR'), ('WALK_IN', 'Walk-in'), ('REPEAT', 'Repeat'), ('DATABASE', 'Database')], default='SELF', max_length=32),
        ),
    ]
