# Generated by Django 4.0.5 on 2026-05-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0049_merge_20260430_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationv2',
            name='rh_rejection_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationv2',
            name='rh_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='document_type',
            field=models.CharField(choices=[('PAN', 'PAN'), ('AADHAAR', 'Aadhaar'), ('LIVE_PHOTO', 'Live Photo'), ('VOTER_ID', 'Voter ID'), ('DRIVING_LICENSE', 'Driving License'), ('PASSPORT', 'Passport'), ('MANREGA_CARD', 'Manrega Card'), ('OTHER', 'Other'), ('CATTLE', 'Cattle'), ('FRESH_LOAN', 'Fresh Loan'), ('PLEDGE_CARD', 'Pledge Card'), ('CUSTOMER_VISIT', 'Customer Visit'), ('SELFIE', 'Selfie')], default='OTHER', max_length=64),
        ),
        migrations.AlterField(
            model_name='applicationstagesnapshot',
            name='stage',
            field=models.CharField(choices=[('PAN', 'Pan'), ('BASIC', 'Basic'), ('ADDRESS', 'Address'), ('DOCUMENTS', 'Documents'), ('PERSONAL', 'Personal'), ('ADDRESS_SECONDARY', 'AddressSecondary'), ('GOLD', 'Gold'), ('PLEDGE_CARD', 'Pledge Card'), ('LOAN', 'Loan'), ('BANK', 'Bank'), ('ADDITIONAL', 'Additional'), ('CUSTOMER_VISIT', 'Customer Visit'), ('SELFIE', 'Selfie'), ('WAIVER', 'Waiver'), ('ELIGIBILITY', 'Eligibility'), ('SUBMITTED', 'Submitted'), ('COMPLETE', 'Complete')], max_length=64),
        ),
        migrations.AlterField(
            model_name='applicationv2',
            name='stage',
            field=models.CharField(choices=[('PAN', 'Pan'), ('BASIC', 'Basic'), ('ADDRESS', 'Address'), ('DOCUMENTS', 'Documents'), ('PERSONAL', 'Personal'), ('ADDRESS_SECONDARY', 'AddressSecondary'), ('GOLD', 'Gold'), ('PLEDGE_CARD', 'Pledge Card'), ('LOAN', 'Loan'), ('BANK', 'Bank'), ('ADDITIONAL', 'Additional'), ('CUSTOMER_VISIT', 'Customer Visit'), ('SELFIE', 'Selfie'), ('WAIVER', 'Waiver'), ('ELIGIBILITY', 'Eligibility'), ('SUBMITTED', 'Submitted'), ('COMPLETE', 'Complete')], default='PAN', max_length=64),
        ),
        migrations.AlterField(
            model_name='applicationv2',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT_FOR_PRE_SCREENING', 'SentForPreScreening'), ('IN_PROGRESS', 'InProgress'), ('READY_FOR_LOAN', 'ReadyForLoan'), ('APPROVED', 'Approved'), ('AGREEMENT_SIGNED', 'AgreementSigned'), ('DISBURSEMENT_READY', 'DisbursementReady'), ('DISBURSED', 'Disbursed'), ('MATURED', 'Matured'), ('DROPPED', 'Dropped'), ('DISBURSEMENT_CANCELLED', 'DisbursementCancelled'), ('DROP_REQUESTED', 'DropRequested'), ('ALLOCATION_PENDING', 'AllocationPending'), ('COMMERCIAL_PROCESSING', 'CommercialProcessing'), ('DEVIATION_REQUESTED', 'DeviationRequested'), ('CORRECTION', 'Correction'), ('CORRECTION_RAISED_BY_UNDERWRITING', 'Correction raised by underwriting'), ('REJECTED', 'Rejected'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'NotEligible'), ('PASSED', 'Passed'), ('SUBMITTED', 'Submitted'), ('FAILED_TO_SUBMIT', 'FailedToSubmit'), ('FAILED_TO_SUBMIT_PRESCREEN', 'FailedToSubmitPrescreen'), ('FAILED_TO_SUBMIT_CREATE_LOAN', 'FailedToSubmitCreateLoan'), ('NEW_LEAD', 'NewLead'), ('UNVERIFIED', 'Unverified'), ('PUNCHING_PENDING', 'Punching Pending'), ('LOAN_STATUS_UPDATED', 'Loan Status Updated'), ('SUBMITTED_TO_UNDERWRITING', 'Application Submitted to Underwriting'), ('ESIGN_COMPLETED', 'E-sign Completed'), ('RH_APPROVAL_PENDING', 'RH Approval Pending'), ('RH_APPROVED', 'Approved by RH'), ('REJECTED_BY_RH', 'Rejected by RH'), ('CORRECTION_RAISED_BY_RH', 'Correction raised by RH')], default='DRAFT', max_length=64),
        ),
        migrations.AlterField(
            model_name='correctiononboarding',
            name='stage',
            field=models.CharField(choices=[('PAN', 'Pan'), ('BASIC', 'Basic'), ('ADDRESS', 'Address'), ('DOCUMENTS', 'Documents'), ('PERSONAL', 'Personal'), ('ADDRESS_SECONDARY', 'AddressSecondary'), ('GOLD', 'Gold'), ('PLEDGE_CARD', 'Pledge Card'), ('LOAN', 'Loan'), ('BANK', 'Bank'), ('ADDITIONAL', 'Additional'), ('CUSTOMER_VISIT', 'Customer Visit'), ('SELFIE', 'Selfie'), ('WAIVER', 'Waiver'), ('ELIGIBILITY', 'Eligibility'), ('SUBMITTED', 'Submitted'), ('COMPLETE', 'Complete')], max_length=64),
        ),
    ]
