# Generated by Django 4.0.5 on 2026-05-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0050_applicationv2_rh_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationv2',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT_FOR_PRE_SCREENING', 'SentForPreScreening'), ('IN_PROGRESS', 'InProgress'), ('READY_FOR_LOAN', 'ReadyForLoan'), ('APPROVED', 'Approved'), ('AGREEMENT_SIGNED', 'AgreementSigned'), ('DISBURSEMENT_READY', 'DisbursementReady'), ('DISBURSED', 'Disbursed'), ('MATURED', 'Matured'), ('DROPPED', 'Dropped'), ('DISBURSEMENT_CANCELLED', 'DisbursementCancelled'), ('DROP_REQUESTED', 'DropRequested'), ('ALLOCATION_PENDING', 'AllocationPending'), ('COMMERCIAL_PROCESSING', 'CommercialProcessing'), ('DEVIATION_REQUESTED', 'DeviationRequested'), ('CORRECTION', 'Correction'), ('CORRECTION_RAISED_BY_UNDERWRITING', 'Correction raised by underwriting'), ('REJECTED', 'Rejected'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'NotEligible'), ('PASSED', 'Passed'), ('SUBMITTED', 'Submitted'), ('FAILED_TO_SUBMIT', 'FailedToSubmit'), ('FAILED_TO_SUBMIT_PRESCREEN', 'FailedToSubmitPrescreen'), ('FAILED_TO_SUBMIT_CREATE_LOAN', 'FailedToSubmitCreateLoan'), ('NEW_LEAD', 'NewLead'), ('UNVERIFIED', 'Unverified'), ('PUNCHING_PENDING', 'Punching Pending'), ('LOAN_STATUS_UPDATED', 'Loan Status Updated'), ('SUBMITTED_TO_UNDERWRITING', 'Application Submitted to Underwriting'), ('FAILED_TO_SUBMIT_TO_UNDERWRITING', 'Failed to submit to underwriting'), ('REJECTED_BY_UNDERWRITING', 'Rejected by Underwriting'), ('ESIGN_INITIATED', 'E-sign Initiated'), ('ESIGN_COMPLETED', 'E-sign Completed'), ('RH_APPROVAL_PENDING', 'RH Approval Pending'), ('RH_APPROVED', 'Approved by RH'), ('REJECTED_BY_RH', 'Rejected by RH'), ('CORRECTION_RAISED_BY_RH', 'Correction raised by RH')], default='DRAFT', max_length=64),
        ),
    ]
