# Generated by Django 4.0.5 on 2026-05-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "onboarding_v2",
            "0047_leadv2_address_leadv2_bank_leadv2_bank_branch_and_more",
        ),
        ("onboarding_v2", "0051_alter_applicationv2_status"),
    ]

    operations = []
