# Generated by Django 4.0.5 on 2026-05-13 11:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding_v2", "0047_alter_leadv2_lead_type_add_bank_lead"),
        ("onboarding_v2", "0053_thirdpartylender"),
    ]

    operations = []
