# Generated by Django 4.0.5 on 2026-05-13 05:50

from django.db import migrations, models


class AddFieldIfNotExists(migrations.AddField):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        table_name = model._meta.db_table
        column_name = model._meta.get_field(self.name).column

        with schema_editor.connection.cursor() as cursor:
            existing_columns = {
                column.name
                for column in schema_editor.connection.introspection.get_table_description(
                    cursor, table_name
                )
            }

        if column_name in existing_columns:
            return

        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding_v2", "0054_merge_20260513_1117"),
    ]

    operations = [
        AddFieldIfNotExists(
            model_name="lendingpartnermaster",
            name="bank_rate",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="applicationstagesnapshot",
            name="stage",
            field=models.CharField(
                choices=[
                    ("PAN", "Pan"),
                    ("BASIC", "Basic"),
                    ("ADDRESS", "Address"),
                    ("DOCUMENTS", "Documents"),
                    ("PERSONAL", "Personal"),
                    ("ADDRESS_SECONDARY", "AddressSecondary"),
                    ("GOLD", "Gold"),
                    ("PLEDGE_CARD", "Pledge Card"),
                    ("LOAN", "Loan"),
                    ("BANK", "Bank"),
                    ("ADDITIONAL", "Additional"),
                    ("CUSTOMER_VISIT", "Customer Visit"),
                    ("SELFIE", "Selfie"),
                    ("WAIVER", "Waiver"),
                    ("ELIGIBILITY", "Eligibility"),
                    ("AMOUNT_TRANSFERRED", "Amount Transferred"),
                    ("GOLD_RECEIVED", "Gold Received"),
                    ("GOLD_SUBMITTED", "Gold Submitted"),
                    ("CHOOSE_CUSTOMER", "Choose Customer"),
                    ("FUND_REFUND", "Fund Refund"),
                    ("SUBMITTED", "Submitted"),
                    ("COMPLETE", "Complete"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="applicationv2",
            name="stage",
            field=models.CharField(
                choices=[
                    ("PAN", "Pan"),
                    ("BASIC", "Basic"),
                    ("ADDRESS", "Address"),
                    ("DOCUMENTS", "Documents"),
                    ("PERSONAL", "Personal"),
                    ("ADDRESS_SECONDARY", "AddressSecondary"),
                    ("GOLD", "Gold"),
                    ("PLEDGE_CARD", "Pledge Card"),
                    ("LOAN", "Loan"),
                    ("BANK", "Bank"),
                    ("ADDITIONAL", "Additional"),
                    ("CUSTOMER_VISIT", "Customer Visit"),
                    ("SELFIE", "Selfie"),
                    ("WAIVER", "Waiver"),
                    ("ELIGIBILITY", "Eligibility"),
                    ("AMOUNT_TRANSFERRED", "Amount Transferred"),
                    ("GOLD_RECEIVED", "Gold Received"),
                    ("GOLD_SUBMITTED", "Gold Submitted"),
                    ("CHOOSE_CUSTOMER", "Choose Customer"),
                    ("FUND_REFUND", "Fund Refund"),
                    ("SUBMITTED", "Submitted"),
                    ("COMPLETE", "Complete"),
                ],
                default="PAN",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="applicationv2",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SENT_FOR_PRE_SCREENING", "SentForPreScreening"),
                    ("IN_PROGRESS", "InProgress"),
                    ("READY_FOR_LOAN", "ReadyForLoan"),
                    ("APPROVED", "Approved"),
                    ("AGREEMENT_SIGNED", "AgreementSigned"),
                    ("DISBURSEMENT_READY", "DisbursementReady"),
                    ("DISBURSED", "Disbursed"),
                    ("MATURED", "Matured"),
                    ("DROPPED", "Dropped"),
                    ("DISBURSEMENT_CANCELLED", "DisbursementCancelled"),
                    ("DROP_REQUESTED", "DropRequested"),
                    ("ALLOCATION_PENDING", "AllocationPending"),
                    ("COMMERCIAL_PROCESSING", "CommercialProcessing"),
                    ("DEVIATION_REQUESTED", "DeviationRequested"),
                    ("CORRECTION", "Correction"),
                    (
                        "CORRECTION_RAISED_BY_UNDERWRITING",
                        "Correction raised by underwriting",
                    ),
                    ("REJECTED", "Rejected"),
                    ("ELIGIBLE", "Eligible"),
                    ("NOT_ELIGIBLE", "NotEligible"),
                    ("PASSED", "Passed"),
                    ("SUBMITTED", "Submitted"),
                    ("FAILED_TO_SUBMIT", "FailedToSubmit"),
                    ("FAILED_TO_SUBMIT_PRESCREEN", "FailedToSubmitPrescreen"),
                    ("FAILED_TO_SUBMIT_CREATE_LOAN", "FailedToSubmitCreateLoan"),
                    ("NEW_LEAD", "NewLead"),
                    ("UNVERIFIED", "Unverified"),
                    ("PUNCHING_PENDING", "Punching Pending"),
                    ("LOAN_STATUS_UPDATED", "Loan Status Updated"),
                    (
                        "SUBMITTED_TO_UNDERWRITING",
                        "Application Submitted to Underwriting",
                    ),
                    (
                        "FAILED_TO_SUBMIT_TO_UNDERWRITING",
                        "Failed to submit to underwriting",
                    ),
                    ("REJECTED_BY_UNDERWRITING", "Rejected by Underwriting"),
                    ("ESIGN_INITIATED", "E-sign Initiated"),
                    ("ESIGN_COMPLETED", "E-sign Completed"),
                    ("RH_APPROVAL_PENDING", "RH Approval Pending"),
                    ("RH_APPROVED", "Approved by RH"),
                    ("REJECTED_BY_RH", "Rejected by RH"),
                    ("CORRECTION_RAISED_BY_RH", "Correction raised by RH"),
                    (
                        "AMOUNT_PAID_TO_EXISTING_LENDER",
                        "Amount paid to Existing Lender",
                    ),
                    (
                        "AMOUNT_NOT_PAID_TO_EXISTING_LENDER",
                        "Amount not paid to Existing Lender",
                    ),
                    (
                        "AMOUNT_PAID_TO_EXISTING_LENDER_ON_HOLD",
                        "Amount paid to Existing Lender-On Hold",
                    ),
                    (
                        "GOLD_RECEIVED_FROM_EXISTING_LENDER",
                        "Gold received from Existing lender",
                    ),
                    (
                        "GOLD_NOT_RECEIVED_FROM_EXISTING_LENDER",
                        "Gold not received from Existing lender",
                    ),
                    (
                        "GOLD_RECEIVED_FROM_EXISTING_LENDER_ON_HOLD",
                        "Gold received from Existing lender - On Hold",
                    ),
                    (
                        "GOLD_SUBMITTED_TO_PARTNER_BANK",
                        "Gold Submitted to Partner Bank",
                    ),
                    (
                        "GOLD_NOT_SUBMITTED_TO_PARTNER_BANK",
                        "Gold not Submitted to Partner bank",
                    ),
                    (
                        "GOLD_SUBMITTED_TO_PARTNER_BANK_ON_HOLD",
                        "Gold Submitted to Partner bank - On Hold",
                    ),
                    ("NEW_LOAN_TAKEN_BY_SELF", "New loan taken by Self"),
                    ("LOAN_TRANSFERRED", "Loan Transferred"),
                ],
                default="DRAFT",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="correctiononboarding",
            name="stage",
            field=models.CharField(
                choices=[
                    ("PAN", "Pan"),
                    ("BASIC", "Basic"),
                    ("ADDRESS", "Address"),
                    ("DOCUMENTS", "Documents"),
                    ("PERSONAL", "Personal"),
                    ("ADDRESS_SECONDARY", "AddressSecondary"),
                    ("GOLD", "Gold"),
                    ("PLEDGE_CARD", "Pledge Card"),
                    ("LOAN", "Loan"),
                    ("BANK", "Bank"),
                    ("ADDITIONAL", "Additional"),
                    ("CUSTOMER_VISIT", "Customer Visit"),
                    ("SELFIE", "Selfie"),
                    ("WAIVER", "Waiver"),
                    ("ELIGIBILITY", "Eligibility"),
                    ("AMOUNT_TRANSFERRED", "Amount Transferred"),
                    ("GOLD_RECEIVED", "Gold Received"),
                    ("GOLD_SUBMITTED", "Gold Submitted"),
                    ("CHOOSE_CUSTOMER", "Choose Customer"),
                    ("FUND_REFUND", "Fund Refund"),
                    ("SUBMITTED", "Submitted"),
                    ("COMPLETE", "Complete"),
                ],
                max_length=64,
            ),
        ),
    ]
