# Generated by Django 4.0.5 on 2026-05-14 12:09

from django.db import migrations, models


class AddFieldIfNotExists(migrations.AddField):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        table_name = model._meta.db_table
        column_name = model._meta.get_field(self.name).column

        with schema_editor.connection.cursor() as cursor:
            existing_columns = {
                column.name
                for column in schema_editor.connection.introspection.get_table_description(
                    cursor, table_name
                )
            }

        if column_name in existing_columns:
            return

        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0055_sync_lending_partner_bank_rate_and_choices'),
    ]

    operations = [
        AddFieldIfNotExists(
            model_name='applicationv2',
            name='parent_application_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        AddFieldIfNotExists(
            model_name='leadv2',
            name='parent_lead_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
