# Generated by Django 4.0.5 on 2026-05-15 18:30

from django.db import migrations, models

def update_rh_approved_status(apps, schema_editor):
    ApplicationV2 = apps.get_model('onboarding_v2', 'ApplicationV2')
    ApplicationV2.objects.filter(status='RH_APPROVED').update(status='APPROVED_BY_RH')

def reverse_rh_approved_status(apps, schema_editor):
    ApplicationV2 = apps.get_model('onboarding_v2', 'ApplicationV2')
    ApplicationV2.objects.filter(status='APPROVED_BY_RH').update(status='RH_APPROVED')

class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0056_applicationv2_parent_application_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationv2',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT_FOR_PRE_SCREENING', 'SentForPreScreening'), ('IN_PROGRESS', 'InProgress'), ('READY_FOR_LOAN', 'ReadyForLoan'), ('APPROVED', 'Approved'), ('AGREEMENT_SIGNED', 'AgreementSigned'), ('DISBURSEMENT_READY', 'DisbursementReady'), ('DISBURSED', 'Disbursed'), ('MATURED', 'Matured'), ('DROPPED', 'Dropped'), ('DISBURSEMENT_CANCELLED', 'DisbursementCancelled'), ('DROP_REQUESTED', 'DropRequested'), ('ALLOCATION_PENDING', 'AllocationPending'), ('COMMERCIAL_PROCESSING', 'CommercialProcessing'), ('DEVIATION_REQUESTED', 'DeviationRequested'), ('CORRECTION', 'Correction'), ('CORRECTION_RAISED_BY_UNDERWRITING', 'Correction raised by underwriting'), ('REJECTED', 'Rejected'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'NotEligible'), ('PASSED', 'Passed'), ('SUBMITTED', 'Submitted'), ('FAILED_TO_SUBMIT', 'FailedToSubmit'), ('FAILED_TO_SUBMIT_PRESCREEN', 'FailedToSubmitPrescreen'), ('FAILED_TO_SUBMIT_CREATE_LOAN', 'FailedToSubmitCreateLoan'), ('NEW_LEAD', 'NewLead'), ('UNVERIFIED', 'Unverified'), ('PUNCHING_PENDING', 'Punching Pending'), ('LOAN_STATUS_UPDATED', 'Loan Status Updated'), ('SUBMITTED_TO_UNDERWRITING', 'Application Submitted to Underwriting'), ('FAILED_TO_SUBMIT_TO_UNDERWRITING', 'Failed to submit to underwriting'), ('REJECTED_BY_UNDERWRITING', 'Rejected by Underwriting'), ('ESIGN_INITIATED', 'E-sign Initiated'), ('ESIGN_COMPLETED', 'E-sign Completed'), ('RH_APPROVAL_PENDING', 'RH Approval Pending'), ('APPROVED_BY_RH', 'Approved by RH'), ('REJECTED_BY_RH', 'Rejected by RH'), ('CORRECTION_RAISED_BY_RH', 'Correction raised by RH'), ('AMOUNT_PAID_TO_EXISTING_LENDER', 'Amount paid to Existing Lender'), ('AMOUNT_NOT_PAID_TO_EXISTING_LENDER', 'Amount not paid to Existing Lender'), ('AMOUNT_PAID_TO_EXISTING_LENDER_ON_HOLD', 'Amount paid to Existing Lender-On Hold'), ('GOLD_RECEIVED_FROM_EXISTING_LENDER', 'Gold received from Existing lender'), ('GOLD_NOT_RECEIVED_FROM_EXISTING_LENDER', 'Gold not received from Existing lender'), ('GOLD_RECEIVED_FROM_EXISTING_LENDER_ON_HOLD', 'Gold received from Existing lender - On Hold'), ('GOLD_SUBMITTED_TO_PARTNER_BANK', 'Gold Submitted to Partner Bank'), ('GOLD_NOT_SUBMITTED_TO_PARTNER_BANK', 'Gold not Submitted to Partner bank'), ('GOLD_SUBMITTED_TO_PARTNER_BANK_ON_HOLD', 'Gold Submitted to Partner bank - On Hold'), ('NEW_LOAN_TAKEN_BY_SELF', 'New loan taken by Self'), ('LOAN_TRANSFERRED', 'Loan Transferred')], default='DRAFT', max_length=64),
        ),
        migrations.RunPython(update_rh_approved_status, reverse_rh_approved_status),
    ]
