# Generated by Django 4.0.5 on 2026-05-20 11:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding_v2', '0058_leadv2_bankleadid_alter_applicationv2_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationv2',
            name='assigned_rh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_assigned_rh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationv2',
            name='punched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_punched', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationv2',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT_FOR_PRE_SCREENING', 'SentForPreScreening'), ('IN_PROGRESS', 'InProgress'), ('READY_FOR_LOAN', 'ReadyForLoan'), ('APPROVED', 'Approved'), ('AGREEMENT_SIGNED', 'AgreementSigned'), ('DISBURSEMENT_READY', 'DisbursementReady'), ('DISBURSED', 'Disbursed'), ('MATURED', 'Matured'), ('DROPPED', 'Dropped'), ('DISBURSEMENT_CANCELLED', 'DisbursementCancelled'), ('DROP_REQUESTED', 'DropRequested'), ('ALLOCATION_PENDING', 'AllocationPending'), ('COMMERCIAL_PROCESSING', 'CommercialProcessing'), ('DEVIATION_REQUESTED', 'DeviationRequested'), ('CORRECTION', 'Correction'), ('CORRECTION_RAISED_BY_UNDERWRITING', 'Correction raised by underwriting'), ('REJECTED', 'Rejected'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'NotEligible'), ('PASSED', 'Passed'), ('SUBMITTED', 'Submitted'), ('FAILED_TO_SUBMIT', 'FailedToSubmit'), ('FAILED_TO_SUBMIT_PRESCREEN', 'FailedToSubmitPrescreen'), ('FAILED_TO_SUBMIT_CREATE_LOAN', 'FailedToSubmitCreateLoan'), ('NEW_LEAD', 'NewLead'), ('UNVERIFIED', 'Unverified'), ('PUNCHING_PENDING', 'Punching Pending'), ('LOAN_STATUS_UPDATED', 'Loan Status Updated'), ('SUBMITTED_TO_UNDERWRITING', 'Application Submitted to Underwriting'), ('FAILED_TO_SUBMIT_TO_UNDERWRITING', 'Failed to submit to underwriting'), ('REJECTED_BY_UNDERWRITING', 'Rejected by Underwriting'), ('APPROVED_BY_ACCOUNTS', 'Approved by Accounts'), ('BT_FUND_DISBURSED', 'BT Fund Disbursed'), ('ESIGN_INITIATED', 'E-sign Initiated'), ('ESIGN_COMPLETED', 'E-sign Completed'), ('RH_APPROVAL_PENDING', 'RH Approval Pending'), ('APPROVED_BY_RH', 'Approved by RH'), ('REJECTED_BY_RH', 'Rejected by RH'), ('CORRECTION_RAISED_BY_RH', 'Correction raised by RH'), ('AMOUNT_PAID_TO_EXISTING_LENDER', 'Amount paid to Existing Lender'), ('AMOUNT_NOT_PAID_TO_EXISTING_LENDER', 'Amount not paid to Existing Lender'), ('AMOUNT_PAID_TO_EXISTING_LENDER_ON_HOLD', 'Amount paid to Existing Lender-On Hold'), ('GOLD_RECEIVED_FROM_EXISTING_LENDER', 'Gold received from Existing lender'), ('GOLD_NOT_RECEIVED_FROM_EXISTING_LENDER', 'Gold not received from Existing lender'), ('GOLD_RECEIVED_FROM_EXISTING_LENDER_ON_HOLD', 'Gold received from Existing lender - On Hold'), ('GOLD_SUBMITTED_TO_PARTNER_BANK', 'Gold Submitted to Partner Bank'), ('GOLD_NOT_SUBMITTED_TO_PARTNER_BANK', 'Gold not Submitted to Partner bank'), ('GOLD_SUBMITTED_TO_PARTNER_BANK_ON_HOLD', 'Gold Submitted to Partner bank - On Hold'), ('NEW_LOAN_TAKEN_BY_SELF', 'New loan taken by Self'), ('LOAN_TRANSFERRED', 'Loan Transferred')], default='DRAFT', max_length=64),
        ),
        migrations.CreateModel(
            name='CustomerBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid IFSC code (e.g., SBIN0001234)', regex='^[A-Z]{4}0[A-Z0-9]{6}$')])),
                ('branch', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Customer Bank Account',
                'verbose_name_plural': 'Customer Bank Accounts',
                'unique_together': {('bank_name', 'ifsc_code')},
            },
        ),
    ]
