# Generated by Django 4.0.5 on 2026-06-12 11:13

from django.db import migrations, models
import onboarding_v2.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0061_normalize_eligible_workflow_status'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='DailyGoldRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('carat', models.CharField(help_text='Gold purity, e.g. 24K, 22K, 18K', max_length=10)),
                ('rate_per_gram', models.DecimalField(decimal_places=2, help_text='Rate per gram in INR', max_digits=12)),
                ('bank_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Bank evaluated rate per gram in INR', max_digits=12, null=True)),
                ('metadata', models.JSONField(blank=True, default=onboarding_v2.models.default_json)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'carat'],
                'unique_together': {('date', 'carat')},
            },
        ),
    ]
