# Generated by Django 4.0.5 on 2026-06-15 07:15

from django.db import migrations, models


def add_van_number_if_not_exists(apps, schema_editor):
    connection = schema_editor.connection
    table_name = 'onboarding_v2_applicationv2'
    column_name = 'van_number'

    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = %s AND column_name = %s
            """,
            [table_name, column_name]
        )
        result = cursor.fetchone()

        if not result:
            # Column doesn't exist, add it via raw SQL to avoid django model registry lookup error
            cursor.execute(
                "ALTER TABLE onboarding_v2_applicationv2 ADD COLUMN van_number character varying(128) NULL;"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0062_daily_gold_rate'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_van_number_if_not_exists, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='applicationv2',
                    name='van_number',
                    field=models.CharField(blank=True, max_length=128, null=True),
                ),
            ]
        ),
        migrations.AlterField(
            model_name='saasrequestlog',
            name='request_type',
            field=models.CharField(choices=[('CREATE_LEAD', 'Create Lead'), ('CREATE_LOAN', 'Create Loan'), ('BUREAU_CHECK', 'Bureau Check'), ('FUND_REFUND', 'Fund Refund')], max_length=32),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='purpose',
            field=models.CharField(choices=[('PRESCREEN', 'Pre-screen'), ('LOAN_CREATION', 'Loan Creation'), ('FUND_REFUND', 'Fund Refund'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=32),
        ),
    ]
