# Generated by Django 4.0.5 on 2026-06-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0063_applicationv2_van_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailygoldrate',
            options={'ordering': ['-date', 'carat', 'bank']},
        ),
        migrations.AlterUniqueTogether(
            name='dailygoldrate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailygoldrate',
            name='bank',
            field=models.CharField(choices=[('AXIS_BANK', 'Axis Bank')], default='AXIS_BANK', help_text='Bank associated with the gold rate', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='dailygoldrate',
            unique_together={('date', 'carat', 'bank')},
        ),
    ]
