# Generated by Django 4.0.5 on 2026-06-15 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import onboarding_v2.models
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding_v2', '0064_alter_dailygoldrate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDailyGoldRate',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('date', models.DateField(db_index=True)),
                ('carat', models.CharField(help_text='Gold purity, e.g. 24K, 22K, 18K', max_length=10)),
                ('rate_per_gram', models.DecimalField(decimal_places=2, help_text='Rate per gram in INR', max_digits=12)),
                ('bank_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Bank evaluated rate per gram in INR', max_digits=12, null=True)),
                ('bank', models.CharField(choices=[('AXIS_BANK', 'Axis Bank')], default='AXIS_BANK', help_text='Bank associated with the gold rate', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=onboarding_v2.models.default_json)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical daily gold rate',
                'verbose_name_plural': 'historical daily gold rates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
