# Generated by Django 4.0.5 on 2026-06-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0065_historicaldailygoldrate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailygoldrate',
            options={'ordering': ['product_type', 'carat', 'bank']},
        ),
        migrations.AlterUniqueTogether(
            name='dailygoldrate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='historicaldailygoldrate',
            name='bank_rate',
        ),
        migrations.RemoveField(
            model_name='historicaldailygoldrate',
            name='date',
        ),
        migrations.RemoveField(
            model_name='historicaldailygoldrate',
            name='rate_per_gram',
        ),
        migrations.AddField(
            model_name='dailygoldrate',
            name='gold_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Gold rate per gram in INR', max_digits=12),
        ),
        migrations.AddField(
            model_name='dailygoldrate',
            name='product_type',
            field=models.CharField(choices=[('GENERAL_PURPOSE', 'General Purpose'), ('MSME', 'MSME'), ('AGRI_ALLIED', 'Agri Allied')], db_index=True, default='GENERAL_PURPOSE', help_text='Product type associated with the gold rate', max_length=128),
        ),
        migrations.AddField(
            model_name='historicaldailygoldrate',
            name='gold_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Gold rate per gram in INR', max_digits=12),
        ),
        migrations.AddField(
            model_name='historicaldailygoldrate',
            name='product_type',
            field=models.CharField(choices=[('GENERAL_PURPOSE', 'General Purpose'), ('MSME', 'MSME'), ('AGRI_ALLIED', 'Agri Allied')], db_index=True, default='GENERAL_PURPOSE', help_text='Product type associated with the gold rate', max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='dailygoldrate',
            unique_together={('product_type', 'carat', 'bank')},
        ),
        migrations.RemoveField(
            model_name='dailygoldrate',
            name='bank_rate',
        ),
        migrations.RemoveField(
            model_name='dailygoldrate',
            name='date',
        ),
        migrations.RemoveField(
            model_name='dailygoldrate',
            name='rate_per_gram',
        ),
    ]
