# Generated by Django 4.0.5 on 2026-06-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0065_historicaldailygoldrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationv2',
            name='score_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
