# Generated by Django 4.0.5 on 2026-06-18 06:48

from django.db import migrations, models
import onboarding_v2.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0066_alter_dailygoldrate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoiConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lead_type', models.CharField(choices=[('FRESH', 'Fresh'), ('BALANCE_TRANSFER', 'Balance Transfer'), ('CO_LENDING', 'Co-Lending')], default='CO_LENDING', help_text='Type of Lead', max_length=64)),
                ('bank', models.CharField(choices=[('AXIS_BANK', 'Axis Bank')], default='AXIS_BANK', help_text='Bank selection', max_length=64)),
                ('product_type', models.CharField(choices=[('GENERAL_PURPOSE', 'General Purpose'), ('MSME', 'MSME'), ('AGRI_ALLIED', 'Agri Allied')], default='GENERAL_PURPOSE', help_text='Type of Product', max_length=64)),
                ('tenure', models.CharField(choices=[('3_MONTHS', '3 months'), ('6_MONTHS', '6 months'), ('9_MONTHS', '9 months'), ('12_MONTHS', '12 months')], default='6_MONTHS', help_text='Tenure', max_length=64)),
                ('repayment_schedule', models.CharField(choices=[('BULLET', 'Bullet'), ('MONTHLY', 'Monthly'), ('NA', 'NA')], default='BULLET', help_text='Repayment schedule', max_length=64)),
                ('bank_roi', models.DecimalField(blank=True, decimal_places=2, help_text='Bank ROI percentage', max_digits=5, null=True)),
                ('manipal_roi', models.DecimalField(blank=True, decimal_places=2, help_text='Manipal ROI percentage', max_digits=5, null=True)),
                ('blended_roi', models.DecimalField(blank=True, decimal_places=2, help_text='Blended ROI percentage', max_digits=5, null=True)),
                ('metadata', models.JSONField(blank=True, default=onboarding_v2.models.default_json)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['lead_type', 'bank', 'product_type', 'tenure', 'repayment_schedule'],
                'unique_together': {('lead_type', 'bank', 'product_type', 'tenure', 'repayment_schedule')},
            },
        ),
    ]
