# Generated by Django 4.0.5 on 2026-06-19 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('onboarding_v2', '0066_applicationv2_score_color_applicationv2_van_number'),
        ('onboarding_v2', '0067_roiconfiguration'),
    ]

    operations = []
