# Generated by Django 4.0.5 on 2026-06-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0068_merge_20260619_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roiconfiguration',
            options={'ordering': ['lead_type', 'bank', 'product_type', 'tenure', 'repayment_schedule', 'loan_range']},
        ),
        migrations.AlterUniqueTogether(
            name='roiconfiguration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='zone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roiconfiguration',
            name='loan_range',
            field=models.CharField(choices=[('LESS_THAN_2_5_LAKHS', 'Less than 2.5 lakhs (<2.5 lakhs)'), ('MORE_THAN_2_5_LAKHS', 'More than 2.5 lakhs (>2.5 lakhs)')], default='LESS_THAN_2_5_LAKHS', help_text='Loan range', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='roiconfiguration',
            unique_together={('lead_type', 'bank', 'product_type', 'tenure', 'repayment_schedule', 'loan_range')},
        ),
    ]
