# Generated by Django 4.0.5 on 2026-07-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0069_alter_roiconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstagesnapshot',
            name='stage',
            field=models.CharField(choices=[('PAN', 'Pan'), ('BASIC', 'Basic'), ('ADDRESS', 'Address'), ('DOCUMENTS', 'Documents'), ('PERSONAL', 'Personal'), ('ADDRESS_SECONDARY', 'AddressSecondary'), ('GOLD', 'Gold'), ('PLEDGE_CARD', 'Pledge Card'), ('LOAN', 'Loan'), ('BANK', 'Bank'), ('ADDITIONAL', 'Additional'), ('CUSTOMER_VISIT', 'Customer Visit'), ('SELFIE', 'Selfie'), ('WAIVER', 'Waiver'), ('ELIGIBILITY', 'Eligibility'), ('AMOUNT_TRANSFERRED', 'Amount Transferred'), ('GOLD_RECEIVED', 'Gold Received'), ('GOLD_SUBMITTED', 'Gold Submitted'), ('CHOOSE_CUSTOMER', 'Choose Customer'), ('FUND_REFUND', 'Fund Refund'), ('SUBMITTED', 'Submitted'), ('COMPLETE', 'Complete'), ('LOAN_RANGE_SELECTION', 'Loan Range Selection'), ('PRODUCT_SELECTION', 'Product Selection'), ('LENDING_PARTNER_BANK', 'Lending Partner Bank')], max_length=64),
        ),
        migrations.AlterField(
            model_name='applicationv2',
            name='stage',
            field=models.CharField(choices=[('PAN', 'Pan'), ('BASIC', 'Basic'), ('ADDRESS', 'Address'), ('DOCUMENTS', 'Documents'), ('PERSONAL', 'Personal'), ('ADDRESS_SECONDARY', 'AddressSecondary'), ('GOLD', 'Gold'), ('PLEDGE_CARD', 'Pledge Card'), ('LOAN', 'Loan'), ('BANK', 'Bank'), ('ADDITIONAL', 'Additional'), ('CUSTOMER_VISIT', 'Customer Visit'), ('SELFIE', 'Selfie'), ('WAIVER', 'Waiver'), ('ELIGIBILITY', 'Eligibility'), ('AMOUNT_TRANSFERRED', 'Amount Transferred'), ('GOLD_RECEIVED', 'Gold Received'), ('GOLD_SUBMITTED', 'Gold Submitted'), ('CHOOSE_CUSTOMER', 'Choose Customer'), ('FUND_REFUND', 'Fund Refund'), ('SUBMITTED', 'Submitted'), ('COMPLETE', 'Complete'), ('LOAN_RANGE_SELECTION', 'Loan Range Selection'), ('PRODUCT_SELECTION', 'Product Selection'), ('LENDING_PARTNER_BANK', 'Lending Partner Bank')], default='PAN', max_length=64),
        ),
        migrations.AlterField(
            model_name='correctiononboarding',
            name='stage',
            field=models.CharField(choices=[('PAN', 'Pan'), ('BASIC', 'Basic'), ('ADDRESS', 'Address'), ('DOCUMENTS', 'Documents'), ('PERSONAL', 'Personal'), ('ADDRESS_SECONDARY', 'AddressSecondary'), ('GOLD', 'Gold'), ('PLEDGE_CARD', 'Pledge Card'), ('LOAN', 'Loan'), ('BANK', 'Bank'), ('ADDITIONAL', 'Additional'), ('CUSTOMER_VISIT', 'Customer Visit'), ('SELFIE', 'Selfie'), ('WAIVER', 'Waiver'), ('ELIGIBILITY', 'Eligibility'), ('AMOUNT_TRANSFERRED', 'Amount Transferred'), ('GOLD_RECEIVED', 'Gold Received'), ('GOLD_SUBMITTED', 'Gold Submitted'), ('CHOOSE_CUSTOMER', 'Choose Customer'), ('FUND_REFUND', 'Fund Refund'), ('SUBMITTED', 'Submitted'), ('COMPLETE', 'Complete'), ('LOAN_RANGE_SELECTION', 'Loan Range Selection'), ('PRODUCT_SELECTION', 'Product Selection'), ('LENDING_PARTNER_BANK', 'Lending Partner Bank')], max_length=64),
        ),
    ]
