# Generated by Codex on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding_v2", "0070_alter_applicationstagesnapshot_stage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationv2",
            name="client_loan_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
