# Generated by Codex on 2026-07-13

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding_v2", "0072_customers_fl_id_nullable_customer_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankLeadTrace",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("bank_name", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ("contact_number", models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ("lead_type", models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ("crm_type", models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ("bank_api_url", models.URLField(blank=True, max_length=2048, null=True)),
                ("request_headers", models.JSONField(blank=True, default=dict)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("response_status_code", models.IntegerField(blank=True, null=True)),
                ("bank_lead_id", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("VALIDATION_FAILED", "Validation Failed"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="INITIATED",
                        max_length=32,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_lead_traces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_lead_traces",
                        to="onboarding_v2.leadv2",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="bankleadtrace",
            index=models.Index(fields=["bank_name", "created_at"], name="onboarding_bank_name_6b8438_idx"),
        ),
        migrations.AddIndex(
            model_name="bankleadtrace",
            index=models.Index(fields=["contact_number", "created_at"], name="onboarding_contact_1956a4_idx"),
        ),
        migrations.AddIndex(
            model_name="bankleadtrace",
            index=models.Index(fields=["status", "created_at"], name="onboarding_status_3c742d_idx"),
        ),
    ]
