# Generated by Django 4.0.5 on 2026-07-07 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0070_customers'),
        ('onboarding_v2', '0072_add_not_eligible_lead_status'),
    ]

    operations = [
    ]
