# Generated by Django 4.0.5 on 2026-07-13 13:29

from django.db import migrations, models
import onboarding_v2.models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0073_bankleadtrace'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bankleadtrace',
            name='onboarding_bank_name_6b8438_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankleadtrace',
            name='onboarding_contact_1956a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankleadtrace',
            name='onboarding_status_3c742d_idx',
        ),
        migrations.AddField(
            model_name='banner',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', help_text='Current status of the banner', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankleadtrace',
            name='metadata',
            field=models.JSONField(blank=True, default=onboarding_v2.models.default_json),
        ),
        migrations.AlterField(
            model_name='bankleadtrace',
            name='request_headers',
            field=models.JSONField(blank=True, default=onboarding_v2.models.default_json),
        ),
        migrations.AlterField(
            model_name='bankleadtrace',
            name='request_payload',
            field=models.JSONField(blank=True, default=onboarding_v2.models.default_json),
        ),
        migrations.AlterField(
            model_name='bankleadtrace',
            name='response_payload',
            field=models.JSONField(blank=True, default=onboarding_v2.models.default_json),
        ),
        migrations.AddIndex(
            model_name='bankleadtrace',
            index=models.Index(fields=['bank_name', 'created_at'], name='onboarding__bank_na_052ea1_idx'),
        ),
        migrations.AddIndex(
            model_name='bankleadtrace',
            index=models.Index(fields=['contact_number', 'created_at'], name='onboarding__contact_ff37f4_idx'),
        ),
        migrations.AddIndex(
            model_name='bankleadtrace',
            index=models.Index(fields=['status', 'created_at'], name='onboarding__status_ca64a3_idx'),
        ),
    ]
