# Generated by Codex on 2026-07-08

from django.db import migrations, models


def move_fl_ids_out_of_customer_id(apps, schema_editor):
    Customers = apps.get_model("onboarding_v2", "Customers")
    for customer in Customers.objects.filter(fl_id__isnull=True).exclude(customer_id__isnull=True):
        customer_id = str(customer.customer_id).strip()
        if customer_id.isdigit() or customer_id.upper().startswith("FL"):
            customer.fl_id = customer_id
            customer.customer_id = None
            customer.save(update_fields=["fl_id", "customer_id"])


def move_fl_ids_back_to_customer_id(apps, schema_editor):
    Customers = apps.get_model("onboarding_v2", "Customers")
    for customer in Customers.objects.filter(customer_id__isnull=True).exclude(fl_id__isnull=True):
        customer.customer_id = customer.fl_id
        customer.fl_id = None
        customer.save(update_fields=["customer_id", "fl_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding_v2", "0073_merge_20260707_1222"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="customer_id",
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="customers",
            name="fl_id",
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.RunPython(move_fl_ids_out_of_customer_id, move_fl_ids_back_to_customer_id),
    ]
