# Generated by Django 4.0.5 on 2026-07-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0074_remove_bankleadtrace_onboarding_bank_name_6b8438_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadv2',
            name='crm_type',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
