# Generated by Django 4.0.5 on 2026-07-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0075_leadv2_crm_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationv2',
            name='lending_partner',
            field=models.CharField(blank=True, choices=[('AXIS_BANK', 'Axis Bank'), ('CSB_BANK', 'CSB Bank'), ('DBS', 'DBS'), ('DCB_BANK', 'DCB Bank'), ('HDFC_BANK', 'HDFC Bank'), ('ICICI_BANK', 'ICICI Bank'), ('KOTAK_MAHINDRA_BANK', 'Kotak Mahindra Bank'), ('RBL_BANK', 'RBL Bank'), ('BAJAJ_FINSERV', 'Bajaj Finserv'), ('Axis Bank', 'Axis Bank'), ('CSB Bank', 'CSB Bank'), ('DCB Bank', 'DCB Bank'), ('HDFC Bank', 'HDFC Bank'), ('ICICI Bank', 'ICICI Bank'), ('Kotak Mahindra Bank', 'Kotak Mahindra Bank'), ('RBL Bank', 'RBL Bank'), ('Bajaj Finserv', 'Bajaj Finserv'), ('DBS_BANK', 'DBS Bank'), ('KOTAK_BANK', 'Kotak Bank'), ('KARNATAKA_BANK', 'Karnataka Bank'), ('OTHER', 'Other')], default='AXIS_BANK', max_length=64, null=True),
        ),
    ]
