# Generated by Django on 2026-07-21 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0076_merge_20260715_1245'),
        ('onboarding_v2', '0077_application_stage_status_tracing'),
    ]

    operations = [
    ]
