# Generated by Django 4.0.5 on 2026-07-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0078_merge_20260721_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstagesnapshot',
            name='stage',
            field=models.CharField(choices=[('SELF_DECLARATION', 'Self Declaration'), ('PAN', 'Pan'), ('BASIC', 'Basic'), ('ADDRESS', 'Address'), ('DOCUMENTS', 'Documents'), ('PERSONAL', 'Personal'), ('ADDRESS_SECONDARY', 'AddressSecondary'), ('GOLD', 'Gold'), ('PLEDGE_CARD', 'Pledge Card'), ('LOAN', 'Loan'), ('BANK', 'Bank'), ('ADDITIONAL', 'Additional'), ('CHARGES', 'Charges and Details'), ('CUSTOMER_VISIT', 'Customer Visit'), ('SELFIE', 'Selfie'), ('WAIVER', 'Waiver'), ('ELIGIBILITY', 'Eligibility'), ('AMOUNT_TRANSFERRED', 'Amount Transferred'), ('GOLD_RECEIVED', 'Gold Received'), ('GOLD_SUBMITTED', 'Gold Submitted'), ('CHOOSE_CUSTOMER', 'Choose Customer'), ('FUND_REFUND', 'Fund Refund'), ('SUBMITTED', 'Submitted'), ('COMPLETE', 'Complete'), ('LOAN_RANGE_SELECTION', 'Loan Range Selection'), ('PRODUCT_SELECTION', 'Product Selection'), ('LENDING_PARTNER_BANK', 'Lending Partner Bank')], max_length=64),
        ),
        migrations.AlterField(
            model_name='applicationstatushistory',
            name='to_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT_FOR_PRE_SCREENING', 'SentForPreScreening'), ('IN_PROGRESS', 'InProgress'), ('READY_FOR_LOAN', 'ReadyForLoan'), ('APPROVED', 'Approved'), ('AGREEMENT_SIGNED', 'AgreementSigned'), ('DISBURSEMENT_READY', 'DisbursementReady'), ('DISBURSED', 'Disbursed'), ('MATURED', 'Matured'), ('DROPPED', 'Dropped'), ('DISBURSEMENT_CANCELLED', 'DisbursementCancelled'), ('DROP_REQUESTED', 'DropRequested'), ('ALLOCATION_PENDING', 'AllocationPending'), ('COMMERCIAL_PROCESSING', 'CommercialProcessing'), ('DEVIATION_REQUESTED', 'DeviationRequested'), ('CORRECTION', 'Correction'), ('CORRECTION_RAISED_BY_UNDERWRITING', 'Correction raised by underwriting'), ('REJECTED', 'Rejected'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'NotEligible'), ('PASSED', 'Passed'), ('SUBMITTED', 'Submitted'), ('FAILED_TO_SUBMIT', 'FailedToSubmit'), ('FAILED_TO_SUBMIT_PRESCREEN', 'FailedToSubmitPrescreen'), ('FAILED_TO_SUBMIT_CREATE_LOAN', 'FailedToSubmitCreateLoan'), ('NEW_LEAD', 'NewLead'), ('UNVERIFIED', 'Unverified'), ('PUNCHING_PENDING', 'Punching Pending'), ('LOAN_STATUS_UPDATED', 'Loan Status Updated'), ('SUBMITTED_TO_UNDERWRITING', 'Application Submitted to Underwriting'), ('FAILED_TO_SUBMIT_TO_UNDERWRITING', 'Failed to submit to underwriting'), ('REJECTED_BY_UNDERWRITING', 'Rejected by Underwriting'), ('APPROVED_BY_ACCOUNTS', 'Approved by Accounts'), ('REJECTED_BY_ACCOUNTS', 'Rejected by accounts'), ('BT_FUND_DISBURSED', 'BT Fund Disbursed'), ('ESIGN_INITIATED', 'E-sign Initiated'), ('ESIGN_COMPLETED', 'E-sign Completed'), ('RH_APPROVAL_PENDING', 'RH Approval Pending'), ('APPROVED_BY_RH', 'Approved by RH'), ('REJECTED_BY_RH', 'Rejected by RH'), ('CORRECTION_RAISED_BY_RH', 'Correction raised by RH'), ('AMOUNT_PAID_TO_EXISTING_LENDER', 'Amount paid to Existing Lender'), ('AMOUNT_NOT_PAID_TO_EXISTING_LENDER', 'Amount not paid to Existing Lender'), ('AMOUNT_PAID_TO_EXISTING_LENDER_ON_HOLD', 'Amount paid to Existing Lender-On Hold'), ('GOLD_RECEIVED_FROM_EXISTING_LENDER', 'Gold received from Existing lender'), ('GOLD_NOT_RECEIVED_FROM_EXISTING_LENDER', 'Gold not received from Existing lender'), ('GOLD_RECEIVED_FROM_EXISTING_LENDER_ON_HOLD', 'Gold received from Existing lender - On Hold'), ('GOLD_SUBMITTED_TO_PARTNER_BANK', 'Gold Submitted to Partner Bank'), ('GOLD_NOT_SUBMITTED_TO_PARTNER_BANK', 'Gold not Submitted to Partner bank'), ('GOLD_SUBMITTED_TO_PARTNER_BANK_ON_HOLD', 'Gold Submitted to Partner bank - On Hold'), ('NEW_LOAN_TAKEN_BY_SELF', 'New loan taken by Self'), ('LOAN_TRANSFERRED', 'Loan Transferred'), ('AMOUNT_NOT_PAID_TO_EXISTING_LENDER_BT_RETURN_COMPLETED', 'Amount Not Paid to Existing Lender and BT Return Completed'), ('GOLD_NOT_RECEIVED_FROM_EXISTING_LENDER_BT_RETURN_COMPLETED', 'Gold Not Received From Existing Lender and BT Return Completed'), ('GOLD_NOT_SUBMITTED_TO_PARTNER_BANK_BT_RETURN_COMPLETED', 'Gold Not Submitted to Partner Bank and BT Return Completed'), ('LOAN_TRANSFERRED_BT_RETURN_COMPLETED', 'Loan Transferred and BT Return Completed'), ('LOAN_STATUS_UPDATED_BT_RETURN_COMPLETED', 'Loan status updated and BT Return Completed')], max_length=64),
        ),
        migrations.AlterField(
            model_name='applicationv2',
            name='loan_type',
            field=models.CharField(blank=True, choices=[('FRESH', 'Fresh'), ('BALANCE_TRANSFER', 'Balance Transfer'), ('CO_LENDING', 'Co-Lending'), ('SELF_LENDING', 'Self Lending'), ('BANK_LEAD', 'Bank Lead')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='applicationv2',
            name='stage',
            field=models.CharField(choices=[('SELF_DECLARATION', 'Self Declaration'), ('PAN', 'Pan'), ('BASIC', 'Basic'), ('ADDRESS', 'Address'), ('DOCUMENTS', 'Documents'), ('PERSONAL', 'Personal'), ('ADDRESS_SECONDARY', 'AddressSecondary'), ('GOLD', 'Gold'), ('PLEDGE_CARD', 'Pledge Card'), ('LOAN', 'Loan'), ('BANK', 'Bank'), ('ADDITIONAL', 'Additional'), ('CHARGES', 'Charges and Details'), ('CUSTOMER_VISIT', 'Customer Visit'), ('SELFIE', 'Selfie'), ('WAIVER', 'Waiver'), ('ELIGIBILITY', 'Eligibility'), ('AMOUNT_TRANSFERRED', 'Amount Transferred'), ('GOLD_RECEIVED', 'Gold Received'), ('GOLD_SUBMITTED', 'Gold Submitted'), ('CHOOSE_CUSTOMER', 'Choose Customer'), ('FUND_REFUND', 'Fund Refund'), ('SUBMITTED', 'Submitted'), ('COMPLETE', 'Complete'), ('LOAN_RANGE_SELECTION', 'Loan Range Selection'), ('PRODUCT_SELECTION', 'Product Selection'), ('LENDING_PARTNER_BANK', 'Lending Partner Bank')], default='PAN', max_length=64),
        ),
        migrations.AlterField(
            model_name='correctiononboarding',
            name='stage',
            field=models.CharField(choices=[('SELF_DECLARATION', 'Self Declaration'), ('PAN', 'Pan'), ('BASIC', 'Basic'), ('ADDRESS', 'Address'), ('DOCUMENTS', 'Documents'), ('PERSONAL', 'Personal'), ('ADDRESS_SECONDARY', 'AddressSecondary'), ('GOLD', 'Gold'), ('PLEDGE_CARD', 'Pledge Card'), ('LOAN', 'Loan'), ('BANK', 'Bank'), ('ADDITIONAL', 'Additional'), ('CHARGES', 'Charges and Details'), ('CUSTOMER_VISIT', 'Customer Visit'), ('SELFIE', 'Selfie'), ('WAIVER', 'Waiver'), ('ELIGIBILITY', 'Eligibility'), ('AMOUNT_TRANSFERRED', 'Amount Transferred'), ('GOLD_RECEIVED', 'Gold Received'), ('GOLD_SUBMITTED', 'Gold Submitted'), ('CHOOSE_CUSTOMER', 'Choose Customer'), ('FUND_REFUND', 'Fund Refund'), ('SUBMITTED', 'Submitted'), ('COMPLETE', 'Complete'), ('LOAN_RANGE_SELECTION', 'Loan Range Selection'), ('PRODUCT_SELECTION', 'Product Selection'), ('LENDING_PARTNER_BANK', 'Lending Partner Bank')], max_length=64),
        ),
        migrations.AlterField(
            model_name='leadautoclosuresetting',
            name='lead_type',
            field=models.CharField(choices=[('FRESH', 'Fresh'), ('BALANCE_TRANSFER', 'Balance Transfer'), ('CO_LENDING', 'Co-Lending'), ('SELF_LENDING', 'Self Lending'), ('BANK_LEAD', 'Bank Lead')], max_length=32),
        ),
        migrations.AlterField(
            model_name='leadv2',
            name='lead_type',
            field=models.CharField(blank=True, choices=[('FRESH', 'Fresh'), ('BALANCE_TRANSFER', 'Balance Transfer'), ('CO_LENDING', 'Co-Lending'), ('SELF_LENDING', 'Self Lending'), ('BANK_LEAD', 'Bank Lead')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='roiconfiguration',
            name='lead_type',
            field=models.CharField(choices=[('FRESH', 'Fresh'), ('BALANCE_TRANSFER', 'Balance Transfer'), ('CO_LENDING', 'Co-Lending'), ('SELF_LENDING', 'Self Lending')], default='CO_LENDING', help_text='Type of Lead', max_length=64),
        ),
    ]
