# Generated by Django 4.0.5 on 2026-08-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_v2', '0083_merge_20260805_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roiconfiguration',
            name='bank',
            field=models.CharField(choices=[('AXIS_BANK', 'Axis Bank'), ('SIMPLEPAY', 'Simplepay')], default='AXIS_BANK', help_text='Bank selection', max_length=64),
        ),
        migrations.AlterField(
            model_name='roiconfiguration',
            name='repayment_schedule',
            field=models.CharField(choices=[('BULLET', 'Bullet'), ('QUARTERLY', 'Quarterly'), ('MONTHLY', 'Monthly'), ('NA', 'NA')], default='BULLET', help_text='Repayment schedule', max_length=64),
        ),
    ]
