# Generated by Django 4.0.5 on 2024-02-07 10:11

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loan', '0049_takeoverresidenceaddress_no_adults_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('repayment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reference_id', models.CharField(max_length=32)),
                ('payment_mode', models.CharField(choices=[('CASH', 'CASH'), ('VPA_REQUEST', 'VPA_REQUEST'), ('DynamicQR', 'DynamicQR')], max_length=16)),
                ('payment_status', models.CharField(choices=[('TRANSACTION_SUCCESSFUL_1', 'TRANSACTION_SUCCESSFUL_1'), ('TRANSACTION_UNDER_PROCESS_2', 'TRANSACTION_UNDER_PROCESS_2'), ('TRANSACTION_UNDER_PROCESS_3', 'TRANSACTION_UNDER_PROCESS_3'), ('TRANSACTION_UNDER_PROCESS_4', 'TRANSACTION_UNDER_PROCESS_4'), ('TRANSACTION_FAILED_0', 'TRANSACTION_FAILED_0')], default='TRANSACTION_UNDER_PROCESS_2', max_length=32)),
                ('utr_no', models.CharField(blank=True, max_length=16, null=True)),
                ('txn_id', models.CharField(blank=True, max_length=32, null=True)),
                ('sender_vpa', models.CharField(blank=True, max_length=32, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=128, null=True)),
                ('receiver_vpa', models.CharField(max_length=32)),
                ('receiver_name', models.CharField(blank=True, max_length=128, null=True)),
                ('receiver_account_number', models.CharField(blank=True, max_length=16, null=True)),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('modified_At', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_created_by', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_initiated_by', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_loan', to='loan.loan')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
