# Generated by Django 4.0.5 on 2024-02-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='remarks',
            field=models.CharField(default='DEFAULT', max_length=64),
            preserve_default=False,
        ),
    ]
