# Generated by Django 4.0.5 on 2024-02-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_repayment_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayment',
            name='reference_id',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
