# Generated by Django 4.0.5 on 2024-02-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_repayment_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='upi_ref_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
