# Generated by Django 4.0.5 on 2024-09-25 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0075_alter_loandocument_document_type'),
        ('payment', '0004_repayment_upi_ref_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BharatSwasthyaRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('pg_ref_num', models.CharField(blank=True, max_length=50, null=True)),
                ('pg_txn_message', models.TextField(blank=True, null=True)),
                ('rrn', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('txn_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bs_repayments', to='application.application')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bs_repayment_created_by', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bs_repayment_initiated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
