# Generated by Django 4.0.5 on 2026-06-18 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0005_bharatswasthyarepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOfficerPayout',
            fields=[
                ('payout_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('payout_type', models.CharField(choices=[('COMMISSION', 'COMMISSION'), ('INCENTIVE', 'INCENTIVE')], max_length=16)),
                ('loan_id', models.CharField(blank=True, max_length=64, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=64, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('lead_id', models.CharField(blank=True, max_length=64, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('agent_type', models.CharField(blank=True, max_length=32, null=True)),
                ('request_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('disbursed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('disbursed_on', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('utr', models.CharField(blank=True, max_length=64, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('clawback_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('settled_on', models.DateTimeField(blank=True, null=True)),
                ('settlement_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('agent_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_payouts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_payouts_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_payouts_modified', to=settings.AUTH_USER_MODEL)),
                ('so_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='so_payouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
