# Generated by Django 4.0.5 on 2023-05-26 00:18

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('role', models.CharField(choices=[('LOAN_OFFICER', 'LOAN_OFFICER'), ('SUPER_ADMIN', 'SUPER_ADMIN'), ('BRANCH_MANAGER', 'BRANCH_MANAGER'), ('CUSTOMER', 'CUSTOMER'), ('CENTRALISED_PROCESSING_CELL', 'CENTRALISED_PROCESSING_CELL'), ('ASSISTANT_BRANCH_MANAGER', 'ASSISTANT_BRANCH_MANAGER'), ('CLUSTER_MANAGER', 'CLUSTER_MANAGER'), ('REGIONAL_HEAD', 'REGIONAL_HEAD')], max_length=32)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('aadhar_no', models.CharField(blank=True, max_length=12, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=10, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserOtp',
            fields=[
                ('otp_type', models.CharField(choices=[('LOGIN_OTP', 'LOGIN_OTP'), ('GOLD_DEPOSIT_OTP', 'GOLD_DEPOSIT_OTP')], default=None, max_length=32)),
                ('user_otp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_key', models.TextField(blank=True, default=None, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDeviceDetails',
            fields=[
                ('user_details_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0')),
                ('device_id', models.TextField()),
                ('device_details', models.JSONField(default=dict)),
                ('push_token', models.TextField()),
                ('platform_type', models.CharField(choices=[('ios', 'ios'), ('android', 'android'), ('web', 'web')], default=None, max_length=32)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('platform_version', models.CharField(blank=True, max_length=128, null=True)),
                ('hardware_model', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('software_version', models.CharField(default='1.0', max_length=32)),
                ('locale_language', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('imei', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('platform_device_id', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeStamp',
            fields=[
                ('timestamp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('CHECKED_IN', 'CHECKED_IN'), ('CHECKED_OUT', 'CHECKED_OUT')], max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'check_in',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('residential_ownership', models.CharField(blank=True, choices=[('INDIVIDUAL_OWNERSHIP', 'INDIVIDUAL_OWNERSHIP'), ('JOINT_OWNERSHIP', 'JOINT_OWNERSHIP'), ('RENTED', 'RENTED')], default='INDIVIDUAL_OWNERSHIP', max_length=255, null=True)),
                ('address_type', models.CharField(choices=[('PERMANENT_ADDRESS', 'PERMANENT_ADDRESS'), ('CORRESPONDENCE_ADDRESS', 'CORRESPONDENCE_ADDRESS')], default='CORRESPONDENCE_ADDRESS', max_length=50)),
                ('building_name', models.CharField(blank=True, max_length=255, null=True)),
                ('street_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addresse', to='account.account')),
            ],
        ),
        migrations.AddConstraint(
            model_name='userdevicedetails',
            constraint=models.UniqueConstraint(fields=('user', 'device_id', 'platform_type'), name='user_paltform_type_unique'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('address_type', 'account'), name='ADDRESS_TYPE_ACCOUNT'),
        ),
    ]
