# Generated by Django 4.0.5 on 2023-06-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp_type',
            field=models.CharField(choices=[('LOGIN_OTP', 'LOGIN_OTP')], default=None, max_length=32),
        ),
    ]
