# Generated by Django 4.0.5 on 2023-09-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userotp_user_phone_unregistered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userotp',
            name='user_phone_unregistered',
        ),
    ]
