# Generated by Django 4.0.5 on 2023-09-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_userotp_user_phone_unregistered'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='user_phone_unregistered',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
