# Generated by Django 4.0.5 on 2023-11-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userotp_user_phone_unregistered'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_profile_pic'),
        ),
    ]
