# Generated by Django 4.0.5 on 2023-12-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_employee_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LOAN_OFFICER', 'LOAN_OFFICER'), ('SUPER_ADMIN', 'SUPER_ADMIN'), ('BRANCH_MANAGER', 'BRANCH_MANAGER'), ('CUSTOMER', 'CUSTOMER'), ('CENTRALISED_PROCESSING_CELL', 'CENTRALISED_PROCESSING_CELL'), ('ASSISTANT_BRANCH_MANAGER', 'ASSISTANT_BRANCH_MANAGER'), ('CLUSTER_MANAGER', 'CLUSTER_MANAGER'), ('REGIONAL_HEAD', 'REGIONAL_HEAD'), ('CHIEF_BUSINESS_OPERATOR', 'CHIEF_BUSINESS_OPERATOR'), ('BUSINESS_HEAD', 'BUSINESS_HEAD')], max_length=32),
        ),
    ]
