# Generated by Django 4.0.5 on 2024-02-12 09:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('verification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identification', models.CharField(blank=True, max_length=256, null=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expiry', models.DateTimeField(default=datetime.datetime(2024, 2, 12, 9, 38, 33, 911572, tzinfo=utc))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userotp',
            name='otp_type',
            field=models.CharField(choices=[('LOGIN_OTP', 'LOGIN_OTP'), ('LEAD_PHONE_VERIFICATION_OTP', 'LEAD_PHONE_VERIFICATION_OTP'), ('GOLD_COLLECT_VERIFICATION', 'GOLD_COLLECT_VERIFICATION'), ('GOLD_DEPOSIT_VERIFICATION', 'GOLD_DEPOSIT_VERIFICATION')], default=None, max_length=32),
        ),
    ]
