# Generated by Django 4.0.5 on 2024-02-16 09:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_verificationtoken_alter_userotp_otp_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 9, 46, 1, 234781, tzinfo=utc)),
        ),
    ]
