# Generated by Django 4.0.5 on 2024-02-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_verificationtoken_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtoken',
            name='expiry',
            field=models.DateTimeField(),
        ),
    ]
