# Generated by Django 4.0.5 on 2024-05-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_verificationtoken_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LOAN_OFFICER', 'LOAN_OFFICER'), ('SUPER_ADMIN', 'SUPER_ADMIN'), ('BRANCH_MANAGER', 'BRANCH_MANAGER'), ('CUSTOMER', 'CUSTOMER'), ('CENTRALISED_PROCESSING_CELL', 'CENTRALISED_PROCESSING_CELL'), ('ASSISTANT_BRANCH_MANAGER', 'ASSISTANT_BRANCH_MANAGER'), ('CLUSTER_MANAGER', 'CLUSTER_MANAGER'), ('REGIONAL_HEAD', 'REGIONAL_HEAD'), ('CHIEF_BUSINESS_OFFICER', 'CHIEF_BUSINESS_OFFICER'), ('BUSINESS_HEAD', 'BUSINESS_HEAD'), ('BRANCH_OPERATION_MANAGER', 'BRANCH_OPERATION_MANAGER'), ('THIRD_PARTY_VENDOR', 'THIRD_PARTY_VENDOR'), ('THIRD_PARTY_CUSTOMER', 'THIRD_PARTY_CUSTOMER'), ('AUDIT_ADMIN', 'AUDIT_ADMIN'), ('RELATIONSHIP_MANAGER', 'RELATIONSHIP_MANAGER'), ('CREDIT_MANAGER', 'CREDIT_MANAGER')], max_length=32),
        ),
    ]
