# Generated by Django 4.0.5 on 2025-04-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entity_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
