# Generated by Django 4.0.5 on 2025-11-06 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_badge_user_city_user_district_user_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assign_so',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_so', to=settings.AUTH_USER_MODEL),
        ),
    ]
