# Generated by Django 4.0.5 on 2025-11-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_assign_so'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamp',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timestamp',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='media/selfie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LOAN_OFFICER', 'LOAN_OFFICER'), ('SUPER_ADMIN', 'SUPER_ADMIN'), ('BRANCH_MANAGER', 'BRANCH_MANAGER'), ('CUSTOMER', 'CUSTOMER'), ('CENTRALISED_PROCESSING_CELL', 'CENTRALISED_PROCESSING_CELL'), ('ASSISTANT_BRANCH_MANAGER', 'ASSISTANT_BRANCH_MANAGER'), ('CLUSTER_MANAGER', 'CLUSTER_MANAGER'), ('REGIONAL_HEAD', 'REGIONAL_HEAD'), ('CHIEF_BUSINESS_OFFICER', 'CHIEF_BUSINESS_OFFICER'), ('BUSINESS_HEAD', 'BUSINESS_HEAD'), ('BRANCH_OPERATION_MANAGER', 'BRANCH_OPERATION_MANAGER'), ('THIRD_PARTY_VENDOR', 'THIRD_PARTY_VENDOR'), ('THIRD_PARTY_CUSTOMER', 'THIRD_PARTY_CUSTOMER'), ('AUDIT_ADMIN', 'AUDIT_ADMIN'), ('RELATIONSHIP_MANAGER', 'RELATIONSHIP_MANAGER'), ('CREDIT_MANAGER', 'CREDIT_MANAGER'), ('CREDIT_OFFICER', 'CREDIT_OFFICER'), ('AGENT', 'AGENT'), ('SALES_OFFICER', 'SALES_OFFICER')], max_length=32),
        ),
    ]
