# Generated by Django 4.0.5 on 2025-11-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_userreward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, choices=[('FOS', 'FOS'), ('RH', 'RH'), ('CH', 'CH'), ('ZH', 'ZH'), ('NSH', 'NSH'), ('SUPER_ADMIN', 'SUPER_ADMIN'), ('ADMIN', 'ADMIN'), ('MANAGEMENT_USER', 'MANAGEMENT_USER'), ('TASK_MANAGEMENT_ADMIN', 'TASK_MANAGEMENT_ADMIN'), ('TASK_MANAGEMENT_USER', 'TASK_MANAGEMENT_USER'), ('DV', 'DV'), ('OPH', 'OPH'), ('ACCOUNT_MAKER', 'ACCOUNT_MAKER'), ('ACCOUNT_CHECKER', 'ACCOUNT_CHECKER'), ('RECON_USER', 'RECON_USER'), ('MIS_USER', 'MIS_USER')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(blank=True, choices=[('DST', 'DST'), ('BANCA', 'BANCA'), ('CENTRAL', 'CENTRAL')], default=None, max_length=100, null=True),
        ),
    ]
