# Generated by Django 4.0.5 on 2026-03-19 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_user_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Pincode must be 6 digits')]),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='otp_type',
            field=models.CharField(choices=[('LOGIN_OTP', 'LOGIN_OTP'), ('LEAD_PHONE_VERIFICATION_OTP', 'LEAD_PHONE_VERIFICATION_OTP'), ('GOLD_COLLECT_VERIFICATION', 'GOLD_COLLECT_VERIFICATION'), ('GOLD_DEPOSIT_VERIFICATION', 'GOLD_DEPOSIT_VERIFICATION'), ('FORGOT_PASSWORD_OTP', 'FORGOT_PASSWORD_OTP')], default=None, max_length=32),
        ),
    ]
