# Generated by Django 4.0.5 on 2026-04-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_user_remember_password_user_remember_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp_type',
            field=models.CharField(choices=[('LOGIN_OTP', 'LOGIN_OTP'), ('LEAD_PHONE_VERIFICATION_OTP', 'LEAD_PHONE_VERIFICATION_OTP'), ('PAN_VERIFICATION_OTP', 'PAN_VERIFICATION_OTP'), ('GOLD_COLLECT_VERIFICATION', 'GOLD_COLLECT_VERIFICATION'), ('GOLD_DEPOSIT_VERIFICATION', 'GOLD_DEPOSIT_VERIFICATION'), ('FORGOT_PASSWORD_OTP', 'FORGOT_PASSWORD_OTP')], default=None, max_length=32),
        ),
    ]
