# Generated by Django 4.0.5 on 2026-05-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_alter_userotp_otp_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timestamp",
            name="latitude",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="timestamp",
            name="longitude",
            field=models.TextField(),
        ),
    ]
