# Generated by Django 4.0.5 on 2026-05-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_user_pincode_alter_userotp_otp_type'),
        ('users', '0033_alter_timestamp_latitude_longitude'),
    ]

    operations = []
