# Generated by Django 4.0.5 on 2026-05-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_alter_timestamp_selfie"),
        ("users", "0034_merge_user_migration_branches"),
    ]

    operations = []
