# Generated by Django 4.0.5 on 2026-06-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_merge_user_migration_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='residential_ownership',
            field=models.CharField(blank=True, choices=[('NATIVE_OWNED', 'NATIVE_OWNED'), ('RENTED', 'RENTED'), ('SELF_OWNED', 'SELF_OWNED'), ('INDIVIDUAL_OWNERSHIP', 'INDIVIDUAL_OWNERSHIP'), ('JOINT_OWNERSHIP', 'JOINT_OWNERSHIP')], default='INDIVIDUAL_OWNERSHIP', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='otp_type',
            field=models.CharField(choices=[('LOGIN_OTP', 'LOGIN_OTP'), ('LEAD_PHONE_VERIFICATION_OTP', 'LEAD_PHONE_VERIFICATION_OTP'), ('PAN_VERIFICATION_OTP', 'PAN_VERIFICATION_OTP'), ('GOLD_COLLECT_VERIFICATION', 'GOLD_COLLECT_VERIFICATION'), ('GOLD_DEPOSIT_VERIFICATION', 'GOLD_DEPOSIT_VERIFICATION'), ('FORGOT_PASSWORD_OTP', 'FORGOT_PASSWORD_OTP')], default=None, max_length=32),
        ),
    ]
