# Generated by Django 4.0.5 on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_address_residential_ownership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exclude_from_bt_date_logic',
            field=models.BooleanField(default=False),
        ),
    ]
