# Generated by Django 4.0.5 on 2026-06-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_address_residential_ownership_and_more'),
        ('users', '0035_merge_timestamp_selfie_branch'),
    ]

    operations = [
    ]
