# Generated by Django 4.0.5 on 2026-07-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_merge_20260624_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamp',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='media/selfie'),
        ),
    ]
