# Generated by Django 4.0.5 on 2026-07-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0036_user_exclude_from_bt_date_logic"),
        ("users", "0037_alter_timestamp_selfie"),
    ]

    operations = []
