# Generated by Django 4.0.5 on 2023-05-26 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchusermapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lm_branch_map', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branchproductmapping',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_product_map', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='branchproductmapping',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_branch_map', to='product.product'),
        ),
        migrations.AddField(
            model_name='branch',
            name='assistant_bm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='cluster_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cluster', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='regional_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='branchusermapping',
            constraint=models.UniqueConstraint(fields=('user', 'branch'), name='user_branch_unique'),
        ),
        migrations.AddConstraint(
            model_name='branchproductmapping',
            constraint=models.UniqueConstraint(fields=('branch', 'product'), name='branch_product_unique'),
        ),
    ]
