# Generated by Django 4.0.5 on 2023-07-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='state',
            field=models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Tamil Nadu', 'Tamil Nadu'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Karnataka', 'Karnataka'), ('Telangana', 'Telangana')], max_length=100, null=True),
        ),
    ]
