# Generated by Django 4.0.5 on 2023-09-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_alter_branch_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(default='cpc_gl@radianfinserv.com', max_length=254),
        ),
    ]
