# Generated by Django 4.0.5 on 2023-12-28 13:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_alter_branch_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='stamp_duty_amount',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='stamp_duty_minimum_amount_eligibility',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='stamp_duty_percent',
        ),
        migrations.CreateModel(
            name='StampDutyCharges',
            fields=[
                ('stamp_duty_charge_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stamp_duty_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stamp_duty_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stamp_duty', to='branch.branch')),
            ],
        ),
    ]
