# Generated by Django 4.0.5 on 2023-12-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0006_remove_branch_stamp_duty_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stampdutycharges',
            name='minimum_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
