# Generated by Django 4.0.5 on 2024-01-01 07:07

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0007_alter_stampdutycharges_minimum_amount'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stampdutycharges',
            constraint=models.CheckConstraint(check=models.Q(('minimum_amount__lte', django.db.models.expressions.F('maximum_amount'))), name='minimum_amount_gte_maximum_amount'),
        ),
    ]
