# Generated by Django 4.0.5 on 2024-06-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0008_stampdutycharges_minimum_amount_gte_maximum_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(default='cpc_gl@curie.credit', max_length=254),
        ),
    ]
