# Generated by Django 4.0.5 on 2024-08-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0009_alter_branch_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
