# Generated by Django 4.0.5 on 2023-05-26 00:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW_APPLICATION', 'NEW_APPLICATION'), ('PRODUCT_CHOOSE', 'PRODUCT_CHOOSE'), ('ASSET_ADDED', 'ASSET_ADDED'), ('ASSET_DOCUMENT_ADDED', 'ASSET_DOCUMENT_ADDED'), ('LOAN_AMOUNT_ADDED', 'LOAN_AMOUNT_ADDED'), ('APPLICATION_INITIATED', 'APPLICATION_INITIATED'), ('APPLICATION_SENT_TO_CPC', 'APPLICATION_SENT_TO_CPC'), ('APPLICATION_REJECTED_BRANCH_MANAGER', 'APPLICATION_REJECTED_BRANCH_MANAGER'), ('APPLICATION_REJECTED_BY_CPC', 'APPLICATION_REJECTED_BY_CPC'), ('LOAN_DOCUMENT_GENERATED', 'LOAN_DOCUMENT_GENERATED'), ('GENERATE_LOAN_DOCUMENT', 'GENERATE_LOAN_DOCUMENT'), ('SIGNED_LOAN_DOCUMENT_SUBMITED', 'SIGNED_LOAN_DOCUMENT_SUBMITED'), ('APPLICATION_COMPLETED', 'APPLICATION_COMPLETED'), ('GOLD_DEPOSITED', 'GOLD_DEPOSITED'), ('LOAN_DOCUMENT_SENT', 'LOAN_DOCUMENT_SENT'), ('LOAN_DOCUMENT_VERIFIED', 'LOAN_DOCUMENT_VERIFIED'), ('LOAN_SENT_FOR_DISBURSEMENT', 'LOAN_SENT_FOR_DISBURSEMENT'), ('LOAN_DISBURSED', 'LOAN_DISBURSED')], default='NEW_APPLICATION', max_length=100)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('application_number', models.CharField(max_length=15, unique=True)),
                ('purpose_of_loan', models.CharField(choices=[('EDUCATIONAL', 'EDUCATIONAL'), ('MARRIAGE', 'MARRIAGE'), ('INCOME_GENERATION', 'INCOME_GENERATION'), ('MEDICAL_EMERGENCY', 'MEDICAL_EMERGENCY'), ('BROAD_CATEGORY', 'BROAD_CATEGORY'), ('PURCHASE_OF_ASSETS', 'PURCHASE_OF_ASSETS'), ('PURCHASE_OF_GOODS', 'PURCHASE_OF_GOODS'), ('LAND_DEVELOPMENT', 'LAND_DEVELOPMENT'), ('PURCHASE_OF_SEEDS', 'PURCHASE_OF_SEEDS'), ('PLANTATION_EXPENSES', 'PLANTATION_EXPENSES'), ('PURCHASE_OF_AGRICULTURAL_EQUIPMENTS', 'PURCHASE_OF_AGRICULTURAL_EQUIPMENTS'), ('PAYMENT_OF_LABOUR_EXPENSES', 'PAYMENT_OF_LABOUR_EXPENSES'), ('MEDICAL_EXPENSES', 'MEDICAL_EXPENSES'), ('TRAVEL_EXPENSES', 'TRAVEL_EXPENSES'), ('OTHER', 'OTHER')], default='OTHER', max_length=300)),
                ('eligible_amount', models.IntegerField(blank=True, null=True)),
                ('loan_amount', models.IntegerField(blank=True, null=True)),
                ('total_goods_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('approvedByBMAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('approvedByCPCAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('bm_comment', models.TextField(blank=True, null=True)),
                ('cpc_comment', models.TextField(blank=True, null=True)),
                ('processing_fee', models.IntegerField(blank=True, null=True)),
                ('current_gst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('gst', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('stamp_duty', models.IntegerField(blank=True, null=True)),
                ('penalty', models.IntegerField(blank=True, null=True)),
                ('ltv', models.IntegerField(blank=True, null=True)),
                ('gold_rate_per_gram', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('lending_gold_rate_per_gram', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tenure', models.IntegerField(blank=True, null=True)),
                ('intrest_rate', models.IntegerField(blank=True, null=True)),
                ('disbursed_amount', models.IntegerField(blank=True, null=True)),
                ('disbursed_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('processing_fee_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('penalty_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('repayment_frequency', models.CharField(choices=[('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY'), ('QUATERLY', 'QUATERLY')], default='MONTHLY', max_length=50)),
                ('amortization_type', models.CharField(choices=[('Amortization Schedule', 'Amortization Schedule'), ('Interest Only', 'Interest Only'), ('Bullet', 'Bullet')], default='Amortization Schedule', max_length=50)),
                ('disbursal_amount', models.IntegerField(blank=True, null=True)),
                ('net_disbursed_amount', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modefied_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationGoodsMapping',
            fields=[
                ('application_goods_mapping_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modefied_at', models.DateTimeField(auto_now=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agmMap_application', to='application.application')),
            ],
        ),
    ]
