# Generated by Django 4.0.5 on 2023-05-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='intrest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
