# Generated by Django 4.0.5 on 2023-06-02 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0005_alter_application_status_applicationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='live_tracking_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LoanDocument',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(blank=True, choices=[('SIGNED_LOAN_DOCUMENT', 'SIGNED_LOAN_DOCUMENT')], default='no_type', max_length=255, null=True)),
                ('file_name', models.CharField(blank=True, max_length=225, null=True)),
                ('file', models.FileField(max_length=225, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_document_application', to='application.application')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetDocuments',
            fields=[
                ('asset_document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_document_type', models.CharField(blank=True, choices=[('PICTURE_OF_GOLD_JEWELLERY', 'PICTURE_OF_GOLD_JEWELLERY'), ('PICTURE_OF_STONE_WITH_MARK', 'PICTURE_OF_STONE_WITH_MARK'), ('PICTURE_OF_SCALE_WITH_GOLD', 'PICTURE_OF_SCALE_WITH_GOLD'), ('PICTURE_OF_DAMAGES', 'PICTURE_OF_DAMAGES')], default='no_type', max_length=255, null=True)),
                ('file_name', models.CharField(blank=True, max_length=225, null=True)),
                ('file', models.FileField(max_length=225, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_document_asset', to='asset.asset')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ASSET_DOC_USER', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
