# Generated by Django 4.0.5 on 2023-06-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_application_live_tracking_id_loandocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contra_loan_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
