# Generated by Django 4.0.5 on 2023-06-09 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_product_type'),
        ('application', '0007_application_contra_loan_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='application_product', to='product.product'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('NEW_APPLICATION', 'NEW_APPLICATION'), ('ASSET_ADDED', 'ASSET_ADDED'), ('LOAN_AMOUNT_ADDED', 'LOAN_AMOUNT_ADDED'), ('APPLICATION_INITIATED', 'APPLICATION_INITIATED'), ('APPLICATION_REJECTED_BY_CPC', 'APPLICATION_REJECTED_BY_CPC'), ('GENERATE_LOAN_DOCUMENT', 'GENERATE_LOAN_DOCUMENT'), ('SIGNED_LOAN_DOCUMENT_SUBMITED', 'SIGNED_LOAN_DOCUMENT_SUBMITED'), ('GOLD_COLLECTED', 'GOLD_COLLECTED'), ('GOLD_DEPOSITED', 'GOLD_DEPOSITED'), ('LOAN_DISBURSED', 'LOAN_DISBURSED'), ('TAKE_OVER_LOAN', 'TAKE_OVER_LOAN')], default='NEW_APPLICATION', max_length=100),
        ),
    ]
