# Generated by Django 4.0.5 on 2023-06-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_application_product_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='take_over_lender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='take_over_loan_amount_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='take_over_loan_maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='take_over_loan_reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='take_over_loan_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='take_over_total_payment_done',
            field=models.IntegerField(default=0),
        ),
    ]
