# Generated by Django 4.0.5 on 2023-06-09 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lender', '0001_initial'),
        ('application', '0009_application_take_over_lender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_lender', to='lender.lender'),
        ),
    ]
