# Generated by Django 4.0.5 on 2023-06-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='take_over_lender',
        ),
        migrations.RemoveField(
            model_name='application',
            name='take_over_loan_amount_remaining',
        ),
        migrations.RemoveField(
            model_name='application',
            name='take_over_loan_maturity_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='take_over_loan_reference_number',
        ),
        migrations.RemoveField(
            model_name='application',
            name='take_over_loan_start_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='take_over_total_payment_done',
        ),
    ]
