# Generated by Django 4.0.5 on 2023-06-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_remove_application_take_over_lender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('NEW', 'NEW'), ('TAKEOVER', 'TAKEOVER')], default='NEW', max_length=100),
        ),
    ]
