# Generated by Django 4.0.5 on 2023-06-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_application_application_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contra_loan_gst_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='contra_loan_net_payable_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='contra_loan_processing_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='contra_loan_processing_fee_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='contra_loan_stamp_duty_amount',
            field=models.IntegerField(default=0),
        ),
    ]
