# Generated by Django 4.0.5 on 2023-06-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_application_contra_loan_gst_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandocument',
            name='document_type',
            field=models.CharField(blank=True, choices=[('SIGNED_LOAN_DOCUMENT', 'SIGNED_LOAN_DOCUMENT'), ('EXISTING_LOAN_PROOF', 'EXISTING_LOAN_PROOF'), ('BT_UNDERTAKING', 'BT_UNDERTAKING')], default='no_type', max_length=255, null=True),
        ),
    ]
