# Generated by Django 4.0.5 on 2023-06-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_alter_loandocument_document_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='loandocument',
            constraint=models.UniqueConstraint(fields=('document_type', 'application'), name='document_type_application'),
        ),
    ]
