# Generated by Django 4.0.5 on 2023-06-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_loandocument_document_type_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandocument',
            name='document_type',
            field=models.CharField(blank=True, choices=[('SIGNED_LOAN_DOCUMENT', 'SIGNED_LOAN_DOCUMENT'), ('EXISTING_LOAN_PROOF', 'EXISTING_LOAN_PROOF'), ('BT_UNDERTAKING', 'BT_UNDERTAKING'), ('SECURITY_CHEQUE', 'SECURITY_CHEQUE')], default='no_type', max_length=255, null=True),
        ),
    ]
