# Generated by Django 4.0.5 on 2023-08-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_alter_assetdocuments_asset_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdocuments',
            name='asset_document_type',
            field=models.CharField(blank=True, choices=[('PICTURE_OF_GOLD_JEWELLERY', 'PICTURE_OF_GOLD_JEWELLERY'), ('PICTURE_OF_STONE_WITH_MARK', 'PICTURE_OF_STONE_WITH_MARK'), ('PICTURE_OF_SCALE_WITH_GOLD', 'PICTURE_OF_SCALE_WITH_GOLD'), ('PICTURE_OF_DAMAGES', 'PICTURE_OF_DAMAGES'), ('PICTURE_OF_THE_HALLMARK', 'PICTURE_OF_THE_HALLMARK'), ('PICTURE_OF_STONE_FOR_GOLD_APPRAISAL', 'PICTURE_OF_STONE_FOR_GOLD_APPRAISAL')], default='no_type', max_length=255, null=True),
        ),
    ]
