# Generated by Django 4.0.5 on 2023-08-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_alter_assetdocuments_asset_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='esign_application_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='esign_application_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
