# Generated by Django 4.0.5 on 2023-08-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_application_esign_application_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='esign_application_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
