# Generated by Django 4.0.5 on 2023-08-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_application_esign_application_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_rejection_status',
            field=models.CharField(blank=True, choices=[('INVALID BANK DETAILS', 'INVALID BANK DETAILS'), ('INVALID ASSET DOCUMENTS', 'INVALID ASSET DOCUMENTS'), ('INCORRECT KYC', 'INCORRECT KYC')], max_length=100, null=True),
        ),
    ]
