# Generated by Django 4.0.5 on 2023-08-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_application_application_rejection_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='esign_application_file',
        ),
    ]
