# Generated by Django 4.0.5 on 2023-08-10 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_alter_application_application_rejection_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='application_rejection_status',
        ),
    ]
