# Generated by Django 4.0.5 on 2023-08-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_application_rejection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='rejection_status',
            field=models.CharField(blank=True, choices=[('INVALID BANK DETAILS', 'INVALID BANK DETAILS'), ('INVALID ASSET DOCUMENTS', 'INVALID ASSET DOCUMENTS'), ('INCORRECT KYC', 'INCORRECT KYC'), ('APPLICATION_REJECTED', 'APPLICATION_REJECTED')], max_length=100, null=True),
        ),
    ]
