# Generated by Django 4.0.5 on 2023-08-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0029_alter_application_rejection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('NEW_APPLICATION', 'NEW_APPLICATION'), ('ASSET_ADDED', 'ASSET_ADDED'), ('LOAN_AMOUNT_ADDED', 'LOAN_AMOUNT_ADDED'), ('APPLICATION_INITIATED', 'APPLICATION_INITIATED'), ('APPLICATION_REJECTED_BY_CPC', 'APPLICATION_REJECTED_BY_CPC'), ('GENERATE_LOAN_DOCUMENT', 'GENERATE_LOAN_DOCUMENT'), ('SIGNED_LOAN_DOCUMENT_SUBMITED', 'SIGNED_LOAN_DOCUMENT_SUBMITED'), ('GOLD_COLLECTED', 'GOLD_COLLECTED'), ('GOLD_DEPOSITED', 'GOLD_DEPOSITED'), ('LOAN_DISBURSED', 'LOAN_DISBURSED'), ('TAKE_OVER_LOAN_PENDING', 'TAKE_OVER_LOAN_PENDING'), ('TAKE_OVER_LOAN_APPROVED', 'TAKE_OVER_LOAN_APPROVED'), ('TAKEOVER_FIRST_DISBURSEMENT_DONE', 'TAKEOVER_FIRST_DISBURSEMENT_DONE'), ('WHITE_GOODS_ADDED', 'WHITE_GOODS_ADDED'), ('E_SIGN_PENDING', 'E_SIGN_PENDING')], default='NEW_APPLICATION', max_length=100),
        ),
    ]
