# Generated by Django 4.0.5 on 2023-08-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0031_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='rejection_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
