# Generated by Django 4.0.5 on 2023-08-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0034_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='kick_back_comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='rejection_status',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
