# Generated by Django 4.0.5 on 2023-08-29 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0035_alter_application_kick_back_comment_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='loandocument',
            name='document_type_application',
        ),
    ]
