# Generated by Django 4.0.5 on 2023-09-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0037_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='processing_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
