# Generated by Django 4.0.5 on 2023-09-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0038_alter_application_processing_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='esign_application_link',
            new_name='esign_signature_link',
        ),
        migrations.AddField(
            model_name='application',
            name='esign_signed_doc_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
