# Generated by Django 4.0.5 on 2023-09-17 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0039_rename_esign_application_link_application_esign_signature_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationotp',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application'),
        ),
        migrations.AlterField(
            model_name='applicationotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
