# Generated by Django 4.0.5 on 2023-09-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0040_alter_applicationotp_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandocument',
            name='document_type',
            field=models.CharField(blank=True, choices=[('SIGNED_LOAN_DOCUMENT', 'SIGNED_LOAN_DOCUMENT'), ('EXISTING_LOAN_PROOF', 'EXISTING_LOAN_PROOF'), ('BT_UNDERTAKING', 'BT_UNDERTAKING'), ('FINCARE_PLEDGE_CARD', 'FINCARE_PLEDGE_CARD'), ('SECURITY_CHEQUE', 'SECURITY_CHEQUE')], default='no_type', max_length=255, null=True),
        ),
    ]
