# Generated by Django 4.0.5 on 2023-10-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0042_alter_application_purpose_of_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdocuments',
            name='file',
            field=models.FileField(max_length=225, upload_to='media/asset_doc'),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='file',
            field=models.FileField(max_length=225, upload_to='media/loan_doc'),
        ),
    ]
