# Generated by Django 4.0.5 on 2023-11-02 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_alter_branch_state'),
        ('application', '0044_alter_assetdocuments_asset_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_branch', to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='assetdocuments',
            name='asset_document_type',
            field=models.CharField(blank=True, choices=[('PICTURE_OF_GOLD_JEWELLERY', 'PICTURE_OF_GOLD_JEWELLERY'), ('PICTURE_OF_STONE_WITH_MARK', 'PICTURE_OF_STONE_WITH_MARK'), ('PICTURE_OF_SCALE_WITH_GOLD', 'PICTURE_OF_SCALE_WITH_GOLD'), ('PICTURE_OF_THE_HALLMARK', 'PICTURE_OF_THE_HALLMARK'), ('PICTURE_OF_STONE_FOR_GOLD_APPRAISAL', 'PICTURE_OF_STONE_FOR_GOLD_APPRAISAL')], default='no_type', max_length=255, null=True),
        ),
    ]
