# Generated by Django 4.0.5 on 2023-11-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0044_alter_assetdocuments_asset_document_type'),
        ('application', '0044_application_branch_and_more'),
    ]

    operations = [
    ]
