# Generated by Django 4.0.5 on 2023-11-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0045_merge_20231120_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='insurance_amount_deducted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
