# Generated by Django 4.0.5 on 2023-12-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0047_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='insurance_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
