# Generated by Django 4.0.5 on 2023-12-13 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_account_religion'),
        ('application', '0048_application_insurance_deducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='insurance_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='insurance_selected', to='account.insuranceproduct'),
        ),
    ]
