# Generated by Django 4.0.5 on 2023-12-18 09:14

from django.db import migrations, models
import django.db.models.deletion

from account.models import InsuranceProduct
from lender.models import Lender


def add_lender(apps, schema_editor):
    LoanTakeOver = apps.get_model('loan', 'LoanTakeOver')
    existing_bt = LoanTakeOver.objects.all()
    for i in existing_bt:
        if i.lender is None:
            i.lender = i.application.lender
            i.save()

class Migration(migrations.Migration):

    dependencies = [
        ('application', '0049_application_insurance_product'),
        # Depend on the migration that introduces LoanTakeOver to avoid LookupError.
        ('loan', '0006_loandisbursaltransaction_is_cleared_and_more'),
    ]
    operations = [
        migrations.RunPython(add_lender)
    ]
