# Generated by Django 4.0.5 on 2023-12-18 09:14

from django.db import migrations, models
import django.db.models.deletion

from account.models import InsuranceProduct
from lender.models import Lender


# def add_lender(apps, schema_editor):
#     lender = apps.get_model('lender', 'Lender')
#     existing_bt_app = apps.get_model('loan', 'LoanTakeOver')
#     lender = lender.objects.filter(lender_code='RADIAN_FINSERV').first()
#
#     existing_bt=existing_bt_app.objects.all()
#     for i in existing_bt:
#         if i.lender is None:
#             i.lender=lender
#             i.save()
#         application=i.application
#         if application.lender is None:
#             application.lender=i.lender
#             application.save()

class Migration(migrations.Migration):

    dependencies = [
        ('application', '0051_set_default_bt_apps'),
    ]
    operations = [
        #migrations.RunPython(add_lender)
    ]
