# Generated by Django 4.0.5 on 2024-01-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0053_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='source',
            field=models.CharField(default='RADIAN', max_length=100),
        ),
    ]
