# Generated by Django 4.0.5 on 2024-01-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0054_application_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='purpose_of_loan',
            field=models.CharField(blank=True, choices=[('EDUCATIONAL', 'EDUCATIONAL'), ('MARRIAGE', 'MARRIAGE'), ('INCOME_GENERATION', 'INCOME_GENERATION'), ('MEDICAL_EMERGENCY', 'MEDICAL_EMERGENCY'), ('BROAD_CATEGORY', 'BROAD_CATEGORY'), ('PURCHASE_OF_ASSETS', 'PURCHASE_OF_ASSETS'), ('PURCHASE_OF_GOODS', 'PURCHASE_OF_GOODS'), ('LAND_DEVELOPMENT', 'LAND_DEVELOPMENT'), ('PURCHASE_OF_SEEDS', 'PURCHASE_OF_SEEDS'), ('PLANTATION_EXPENSES', 'PLANTATION_EXPENSES'), ('PURCHASE_OF_AGRICULTURAL_EQUIPMENTS', 'PURCHASE_OF_AGRICULTURAL_EQUIPMENTS'), ('PAYMENT_OF_LABOUR_EXPENSES', 'PAYMENT_OF_LABOUR_EXPENSES'), ('MEDICAL_EXPENSES', 'MEDICAL_EXPENSES'), ('TRAVEL_EXPENSES', 'TRAVEL_EXPENSES'), ('OTHERS', 'OTHERS')], max_length=300, null=True),
        ),
    ]
