# Generated by Django 4.0.5 on 2024-02-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0058_application_total_asset_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='eligible_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
