# Generated by Django 4.0.5 on 2024-02-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0059_alter_application_eligible_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='eligible_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
