# Generated by Django 4.0.5 on 2024-03-07 08:19

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_whitegoods_available_in'),
        ('account', '0021_remove_insuranceproduct_company_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branch', '0008_stampdutycharges_minimum_amount_gte_maximum_amount'),
        ('lender', '0001_initial'),
        ('application', '0060_alter_application_eligible_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalApplication',
            fields=[
                ('application_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('NEW_APPLICATION', 'NEW_APPLICATION'), ('ASSET_ADDED', 'ASSET_ADDED'), ('LOAN_AMOUNT_ADDED', 'LOAN_AMOUNT_ADDED'), ('APPLICATION_INITIATED', 'APPLICATION_INITIATED'), ('APPLICATION_REJECTED_BY_CPC', 'APPLICATION_REJECTED_BY_CPC'), ('GENERATE_LOAN_DOCUMENT', 'GENERATE_LOAN_DOCUMENT'), ('SIGNED_LOAN_DOCUMENT_SUBMITED', 'SIGNED_LOAN_DOCUMENT_SUBMITED'), ('GOLD_COLLECTED', 'GOLD_COLLECTED'), ('GOLD_DEPOSITED', 'GOLD_DEPOSITED'), ('PAYMENT_DETAILS_RECORDED', 'PAYMENT_DETAILS_RECORDED'), ('TAKE_OVER_LOAN_INITIATED', 'TAKE_OVER_LOAN_INITIATED'), ('TAKE_OVER_LOAN_PENDING', 'TAKE_OVER_LOAN_PENDING'), ('TAKE_OVER_LOAN_APPROVED', 'TAKE_OVER_LOAN_APPROVED'), ('BT_PAYMENT_DETAILS_RECORDED', 'BT_PAYMENT_DETAILS_RECORDED'), ('WHITE_GOODS_ADDED', 'WHITE_GOODS_ADDED'), ('E_SIGN_PENDING', 'E_SIGN_PENDING'), ('APPLICATION_SENT_BACK_BY_CPC', 'APPLICATION_SENT_BACK_BY_CPC'), ('APPLICATION_REVERTED_AFTER_CORRECTION', 'APPLICATION_REVERTED_AFTER_CORRECTION'), ('BT_NOMINEE_ADDED', 'BT_NOMINEE_ADDED'), ('BT_RESIDENCE_ADDED', 'BT_RESIDENCE_ADDED'), ('RESIDENCE_ADDED', 'RESIDENCE_ADDED'), ('FEDERAL_CONSENT_SUBMITTED', 'FEDERAL_CONSENT_SUBMITTED'), ('FEDERAL_EKYC_SUBMITTED', 'FEDERAL_EKYC_SUBMITTED'), ('FEDERAL_ELIGIBILITY_CHECKED', 'FEDERAL_ELIGIBILITY_CHECKED'), ('FEDERAL_CUSTOMER_CREATED', 'FEDERAL_CUSTOMER_CREATED'), ('FEDERAL_GL_ACCOUNT_CREATED', 'FEDERAL_GL_ACCOUNT_CREATED')], default='NEW_APPLICATION', max_length=100)),
                ('live_tracking_id', models.UUIDField(blank=True, null=True)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('application_number', models.CharField(db_index=True, max_length=15)),
                ('purpose_of_loan', models.CharField(blank=True, choices=[('EDUCATIONAL', 'EDUCATIONAL'), ('MARRIAGE', 'MARRIAGE'), ('INCOME_GENERATION', 'INCOME_GENERATION'), ('MEDICAL_EMERGENCY', 'MEDICAL_EMERGENCY'), ('BROAD_CATEGORY', 'BROAD_CATEGORY'), ('PURCHASE_OF_ASSETS', 'PURCHASE_OF_ASSETS'), ('PURCHASE_OF_GOODS', 'PURCHASE_OF_GOODS'), ('LAND_DEVELOPMENT', 'LAND_DEVELOPMENT'), ('PURCHASE_OF_SEEDS', 'PURCHASE_OF_SEEDS'), ('PLANTATION_EXPENSES', 'PLANTATION_EXPENSES'), ('PURCHASE_OF_AGRICULTURAL_EQUIPMENTS', 'PURCHASE_OF_AGRICULTURAL_EQUIPMENTS'), ('PAYMENT_OF_LABOUR_EXPENSES', 'PAYMENT_OF_LABOUR_EXPENSES'), ('MEDICAL_EXPENSES', 'MEDICAL_EXPENSES'), ('TRAVEL_EXPENSES', 'TRAVEL_EXPENSES'), ('OTHERS', 'OTHERS')], max_length=300, null=True)),
                ('eligible_amount', models.IntegerField(blank=True, null=True)),
                ('loan_amount', models.IntegerField(blank=True, null=True)),
                ('contra_loan_amount', models.IntegerField(blank=True, null=True)),
                ('contra_loan_processing_fee', models.FloatField(default=0)),
                ('contra_loan_processing_fee_amount', models.IntegerField(default=0)),
                ('contra_loan_gst_amount', models.IntegerField(default=0)),
                ('contra_loan_stamp_duty_amount', models.IntegerField(default=0)),
                ('contra_loan_net_payable_balance', models.IntegerField(default=0)),
                ('total_goods_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_wastage', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_gross_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_asset_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('application_type', models.CharField(choices=[('NEW', 'NEW'), ('TAKEOVER', 'TAKEOVER')], default='NEW', max_length=100)),
                ('source', models.CharField(default='RADIAN', max_length=100)),
                ('approvedByBMAt', models.DateTimeField(blank=True, editable=False, null=True)),
                ('approvedByCPCAt', models.DateTimeField(blank=True, editable=False, null=True)),
                ('bm_comment', models.TextField(blank=True, null=True)),
                ('cpc_comment', models.TextField(blank=True, null=True)),
                ('processing_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_gst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('gst', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('stamp_duty', models.IntegerField(blank=True, null=True)),
                ('penalty', models.IntegerField(blank=True, null=True)),
                ('ltv', models.IntegerField(blank=True, null=True)),
                ('gold_rate_per_gram', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('lending_gold_rate_per_gram', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tenure', models.IntegerField(blank=True, null=True)),
                ('intrest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disbursed_amount', models.IntegerField(blank=True, null=True)),
                ('disbursed_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('processing_fee_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('penalty_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('repayment_frequency', models.CharField(choices=[('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY'), ('QUATERLY', 'QUATERLY')], default='MONTHLY', max_length=50)),
                ('amortization_type', models.CharField(choices=[('Amortization Schedule', 'Amortization Schedule'), ('Interest Only', 'Interest Only'), ('Bullet', 'Bullet')], default='Amortization Schedule', max_length=50)),
                ('disbursal_amount', models.IntegerField(blank=True, null=True)),
                ('esign_signed_doc_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('esign_signature_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('esign_application_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('rejection_status', models.CharField(blank=True, max_length=1000, null=True)),
                ('kick_back_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('insurance_deducted', models.BooleanField(default=False)),
                ('net_disbursed_amount', models.IntegerField(blank=True, null=True)),
                ('insurance_amount_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('modefied_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Originatedby', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account')),
                ('appraisedBy', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('approvedByBM', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('approvedByCPC', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='branch.branch')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('insurance_product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.insuranceproduct')),
                ('lender', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lender.lender')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product')),
            ],
            options={
                'verbose_name': 'historical application',
                'verbose_name_plural': 'historical applications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
