# Generated by Django 4.0.5 on 2024-04-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0061_historicalapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='total_asset_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='total_goods_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='total_gross_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='total_wastage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
