# Generated by Django 4.0.5 on 2024-06-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0062_alter_application_total_asset_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_loan_type',
            field=models.CharField(choices=[('MSME_UNSECURED', 'MSME_UNSECURED'), ('MSME_SECURED', 'MSME_SECURED'), ('GOLD_LOAN', 'GOLD_LOAN')], default='GOLD_LOAN', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='application_loan_type',
            field=models.CharField(choices=[('MSME_UNSECURED', 'MSME_UNSECURED'), ('MSME_SECURED', 'MSME_SECURED'), ('GOLD_LOAN', 'GOLD_LOAN')], default='GOLD_LOAN', max_length=50),
        ),
    ]
