# Generated by Django 4.0.5 on 2024-06-13 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0064_application_amount_requirement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='amount_requirement',
            new_name='requested_loan_amount',
        ),
        migrations.RenameField(
            model_name='historicalapplication',
            old_name='amount_requirement',
            new_name='requested_loan_amount',
        ),
    ]
