# Generated by Django 4.0.5 on 2024-06-21 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0067_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='approvalActionBH',
            field=models.CharField(blank=True, choices=[('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('ON_HOLD', 'ON_HOLD')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='approvalActionCM',
            field=models.CharField(blank=True, choices=[('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('DEVIATED', 'DEVIATED'), ('ON_HOLD', 'ON_HOLD')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='approvedByBH',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_approvedByBH', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='approvedByCM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_approvedByCM', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='bh_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='cm_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='deviated_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='approvalActionBH',
            field=models.CharField(blank=True, choices=[('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('ON_HOLD', 'ON_HOLD')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='approvalActionCM',
            field=models.CharField(blank=True, choices=[('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('DEVIATED', 'DEVIATED'), ('ON_HOLD', 'ON_HOLD')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='approvedByBH',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='approvedByCM',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='bh_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='cm_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='deviated_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('NEW_APPLICATION', 'NEW_APPLICATION'), ('ASSET_ADDED', 'ASSET_ADDED'), ('LOAN_AMOUNT_ADDED', 'LOAN_AMOUNT_ADDED'), ('APPLICATION_INITIATED', 'APPLICATION_INITIATED'), ('APPLICATION_REJECTED_BY_CPC', 'APPLICATION_REJECTED_BY_CPC'), ('GENERATE_LOAN_DOCUMENT', 'GENERATE_LOAN_DOCUMENT'), ('SIGNED_LOAN_DOCUMENT_SUBMITED', 'SIGNED_LOAN_DOCUMENT_SUBMITED'), ('GOLD_COLLECTED', 'GOLD_COLLECTED'), ('GOLD_DEPOSITED', 'GOLD_DEPOSITED'), ('PAYMENT_DETAILS_RECORDED', 'PAYMENT_DETAILS_RECORDED'), ('TAKE_OVER_LOAN_INITIATED', 'TAKE_OVER_LOAN_INITIATED'), ('TAKE_OVER_LOAN_PENDING', 'TAKE_OVER_LOAN_PENDING'), ('TAKE_OVER_LOAN_APPROVED', 'TAKE_OVER_LOAN_APPROVED'), ('BT_PAYMENT_DETAILS_RECORDED', 'BT_PAYMENT_DETAILS_RECORDED'), ('WHITE_GOODS_ADDED', 'WHITE_GOODS_ADDED'), ('E_SIGN_PENDING', 'E_SIGN_PENDING'), ('APPLICATION_SENT_BACK_BY_CPC', 'APPLICATION_SENT_BACK_BY_CPC'), ('APPLICATION_REVERTED_AFTER_CORRECTION', 'APPLICATION_REVERTED_AFTER_CORRECTION'), ('BT_NOMINEE_ADDED', 'BT_NOMINEE_ADDED'), ('BT_RESIDENCE_ADDED', 'BT_RESIDENCE_ADDED'), ('RESIDENCE_ADDED', 'RESIDENCE_ADDED'), ('TELE_VERIFICATION_DONE', 'TELE_VERIFICATION_DONE'), ('APPLICATION_SENT_BACK_BY_CM', 'APPLICATION_SENT_BACK_BY_CM'), ('APPLICATION_REJECTED_BY_CM', 'APPLICATION_REJECTED_BY_CM'), ('APPLICATION_SENT_TO_BH', 'APPLICATION_SENT_TO_BH'), ('APPLICATION_SENT_BACK_BY_BH', 'APPLICATION_SENT_BACK_BY_BH'), ('FEDERAL_CONSENT_SUBMITTED', 'FEDERAL_CONSENT_SUBMITTED'), ('FEDERAL_EKYC_SUBMITTED', 'FEDERAL_EKYC_SUBMITTED'), ('FEDERAL_ELIGIBILITY_CHECKED', 'FEDERAL_ELIGIBILITY_CHECKED'), ('FEDERAL_CUSTOMER_CREATED', 'FEDERAL_CUSTOMER_CREATED'), ('FEDERAL_GL_ACCOUNT_CREATED', 'FEDERAL_GL_ACCOUNT_CREATED')], default='NEW_APPLICATION', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='status',
            field=models.CharField(choices=[('NEW_APPLICATION', 'NEW_APPLICATION'), ('ASSET_ADDED', 'ASSET_ADDED'), ('LOAN_AMOUNT_ADDED', 'LOAN_AMOUNT_ADDED'), ('APPLICATION_INITIATED', 'APPLICATION_INITIATED'), ('APPLICATION_REJECTED_BY_CPC', 'APPLICATION_REJECTED_BY_CPC'), ('GENERATE_LOAN_DOCUMENT', 'GENERATE_LOAN_DOCUMENT'), ('SIGNED_LOAN_DOCUMENT_SUBMITED', 'SIGNED_LOAN_DOCUMENT_SUBMITED'), ('GOLD_COLLECTED', 'GOLD_COLLECTED'), ('GOLD_DEPOSITED', 'GOLD_DEPOSITED'), ('PAYMENT_DETAILS_RECORDED', 'PAYMENT_DETAILS_RECORDED'), ('TAKE_OVER_LOAN_INITIATED', 'TAKE_OVER_LOAN_INITIATED'), ('TAKE_OVER_LOAN_PENDING', 'TAKE_OVER_LOAN_PENDING'), ('TAKE_OVER_LOAN_APPROVED', 'TAKE_OVER_LOAN_APPROVED'), ('BT_PAYMENT_DETAILS_RECORDED', 'BT_PAYMENT_DETAILS_RECORDED'), ('WHITE_GOODS_ADDED', 'WHITE_GOODS_ADDED'), ('E_SIGN_PENDING', 'E_SIGN_PENDING'), ('APPLICATION_SENT_BACK_BY_CPC', 'APPLICATION_SENT_BACK_BY_CPC'), ('APPLICATION_REVERTED_AFTER_CORRECTION', 'APPLICATION_REVERTED_AFTER_CORRECTION'), ('BT_NOMINEE_ADDED', 'BT_NOMINEE_ADDED'), ('BT_RESIDENCE_ADDED', 'BT_RESIDENCE_ADDED'), ('RESIDENCE_ADDED', 'RESIDENCE_ADDED'), ('TELE_VERIFICATION_DONE', 'TELE_VERIFICATION_DONE'), ('APPLICATION_SENT_BACK_BY_CM', 'APPLICATION_SENT_BACK_BY_CM'), ('APPLICATION_REJECTED_BY_CM', 'APPLICATION_REJECTED_BY_CM'), ('APPLICATION_SENT_TO_BH', 'APPLICATION_SENT_TO_BH'), ('APPLICATION_SENT_BACK_BY_BH', 'APPLICATION_SENT_BACK_BY_BH'), ('FEDERAL_CONSENT_SUBMITTED', 'FEDERAL_CONSENT_SUBMITTED'), ('FEDERAL_EKYC_SUBMITTED', 'FEDERAL_EKYC_SUBMITTED'), ('FEDERAL_ELIGIBILITY_CHECKED', 'FEDERAL_ELIGIBILITY_CHECKED'), ('FEDERAL_CUSTOMER_CREATED', 'FEDERAL_CUSTOMER_CREATED'), ('FEDERAL_GL_ACCOUNT_CREATED', 'FEDERAL_GL_ACCOUNT_CREATED')], default='NEW_APPLICATION', max_length=100),
        ),
    ]
