# Generated by Django 4.0.5 on 2024-07-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0070_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandocument',
            name='esign_id',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='esign_signature_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='loandocument',
            name='esign_signed_doc_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='document_type',
            field=models.CharField(blank=True, choices=[('SIGNED_LOAN_DOCUMENT', 'SIGNED_LOAN_DOCUMENT'), ('EXISTING_LOAN_PROOF', 'EXISTING_LOAN_PROOF'), ('BT_UNDERTAKING', 'BT_UNDERTAKING'), ('FINCARE_PLEDGE_CARD', 'FINCARE_PLEDGE_CARD'), ('SECURITY_CHEQUE', 'SECURITY_CHEQUE'), ('SIGNED_UNSECURED_LOAN_DOCUMENT', 'SIGNED_UNSECURED_LOAN_DOCUMENT'), ('SIGNED_SANCTION_LETTER', 'SIGNED_SANCTION_LETTER'), ('SIGNED_DPN_DOCUMENT', 'SIGNED_DPN_DOCUMENT')], default='no_type', max_length=255, null=True),
        ),
    ]
