# Generated by Django 4.0.5 on 2024-07-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0071_alter_loandocument_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandocument',
            name='document_type',
            field=models.CharField(blank=True, choices=[('SIGNED_LOAN_DOCUMENT', 'SIGNED_LOAN_DOCUMENT'),
                                                        ('EXISTING_LOAN_PROOF', 'EXISTING_LOAN_PROOF'),
                                                        ('BT_UNDERTAKING', 'BT_UNDERTAKING'),
                                                        ('FINCARE_PLEDGE_CARD', 'FINCARE_PLEDGE_CARD'),
                                                        ('SECURITY_CHEQUE', 'SECURITY_CHEQUE'),
                                                        ('BSA_JSON_FILE', 'BSA_JSON_FILE'),
                                                        ('BSA_EXCEL_FILE', 'BSA_EXCEL_FILE'),
                                                        ("CIBIL_REPORT", "CIBIL_REPORT"),], default='no_type',
                                   max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='cibil_report_json',
            field=models.FileField(blank=True, null=True, upload_to='media/loan_doc'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='cibil_report_json',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
