# Generated by Django 4.0.5 on 2024-07-29 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0071_loandocument_esign_id_and_more'),
        ('application', '0072_application_cibil_report_json_and_more'),
    ]

    operations = [
    ]
