# Generated by Django 4.0.5 on 2024-07-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0073_merge_20240729_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandocument',
            name='document_type',
            field=models.CharField(blank=True, choices=[('SIGNED_LOAN_DOCUMENT', 'SIGNED_LOAN_DOCUMENT'), ('EXISTING_LOAN_PROOF', 'EXISTING_LOAN_PROOF'), ('BT_UNDERTAKING', 'BT_UNDERTAKING'), ('FINCARE_PLEDGE_CARD', 'FINCARE_PLEDGE_CARD'), ('SECURITY_CHEQUE', 'SECURITY_CHEQUE'), ('SIGNED_UNSECURED_LOAN_DOCUMENT', 'SIGNED_UNSECURED_LOAN_DOCUMENT'), ('SIGNED_SANCTION_LETTER', 'SIGNED_SANCTION_LETTER'), ('SIGNED_DPN_DOCUMENT', 'SIGNED_DPN_DOCUMENT'), ('CIBIL_REPORT', 'CIBIL_REPORT'), ('BSA_JSON_FILE', 'BSA_JSON_FILE'), ('BSA_EXCEL_FILE', 'BSA_EXCEL_FILE')], default='no_type', max_length=255, null=True),
        ),
    ]
