# Generated by Django 4.0.5 on 2024-10-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0076_alter_application_application_loan_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='amortization_type',
            field=models.CharField(choices=[('Amortization Schedule', 'Amortization Schedule'), ('Interest Only', 'Interest Only'), ('Bullet', 'Bullet'), ('None', 'None')], default='Amortization Schedule', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='repayment_frequency',
            field=models.CharField(choices=[('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY'), ('QUATERLY', 'QUATERLY'), ('NONE', 'NONE')], default='MONTHLY', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='amortization_type',
            field=models.CharField(choices=[('Amortization Schedule', 'Amortization Schedule'), ('Interest Only', 'Interest Only'), ('Bullet', 'Bullet'), ('None', 'None')], default='Amortization Schedule', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='repayment_frequency',
            field=models.CharField(choices=[('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY'), ('QUATERLY', 'QUATERLY'), ('NONE', 'NONE')], default='MONTHLY', max_length=50),
        ),
    ]
