# Generated by Django 4.0.5 on 2024-11-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0077_alter_application_amortization_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='co_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='co_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
