# Generated by Django 4.0.5 on 2024-12-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0079_alter_application_application_loan_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_loan_type',
            field=models.CharField(choices=[('MSME_UNSECURED', 'MSME_UNSECURED'), ('MSME_UNSECURED_AGRI', 'MSME_UNSECURED_AGRI'), ('MSME_SECURED', 'MSME_SECURED'), ('GOLD_LOAN', 'GOLD_LOAN'), ('WELLNESS', 'WELLNESS')], default='GOLD_LOAN', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='purpose_of_loan',
            field=models.CharField(blank=True, choices=[('EDUCATIONAL', 'EDUCATIONAL'), ('MARRIAGE', 'MARRIAGE'), ('INCOME_GENERATION', 'INCOME_GENERATION'), ('MEDICAL_EMERGENCY', 'MEDICAL_EMERGENCY'), ('BROAD_CATEGORY', 'BROAD_CATEGORY'), ('PURCHASE_OF_ASSETS', 'PURCHASE_OF_ASSETS'), ('PURCHASE_OF_GOODS', 'PURCHASE_OF_GOODS'), ('EXPANSION', 'EXPANSION'), ('STOCKS', 'STOCKS'), ('CONSUMPTION', 'CONSUMPTION'), ('LAND_DEVELOPMENT', 'LAND_DEVELOPMENT'), ('PURCHASE_OF_SEEDS', 'PURCHASE_OF_SEEDS'), ('PLANTATION_EXPENSES', 'PLANTATION_EXPENSES'), ('PURCHASE_OF_AGRICULTURAL_EQUIPMENTS', 'PURCHASE_OF_AGRICULTURAL_EQUIPMENTS'), ('PAYMENT_OF_LABOUR_EXPENSES', 'PAYMENT_OF_LABOUR_EXPENSES'), ('MEDICAL_EXPENSES', 'MEDICAL_EXPENSES'), ('TRAVEL_EXPENSES', 'TRAVEL_EXPENSES'), ('OTHERS', 'OTHERS'), ('AGRI_ONLY', 'AGRI_ONLY')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='application_loan_type',
            field=models.CharField(choices=[('MSME_UNSECURED', 'MSME_UNSECURED'), ('MSME_UNSECURED_AGRI', 'MSME_UNSECURED_AGRI'), ('MSME_SECURED', 'MSME_SECURED'), ('GOLD_LOAN', 'GOLD_LOAN'), ('WELLNESS', 'WELLNESS')], default='GOLD_LOAN', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='purpose_of_loan',
            field=models.CharField(blank=True, choices=[('EDUCATIONAL', 'EDUCATIONAL'), ('MARRIAGE', 'MARRIAGE'), ('INCOME_GENERATION', 'INCOME_GENERATION'), ('MEDICAL_EMERGENCY', 'MEDICAL_EMERGENCY'), ('BROAD_CATEGORY', 'BROAD_CATEGORY'), ('PURCHASE_OF_ASSETS', 'PURCHASE_OF_ASSETS'), ('PURCHASE_OF_GOODS', 'PURCHASE_OF_GOODS'), ('EXPANSION', 'EXPANSION'), ('STOCKS', 'STOCKS'), ('CONSUMPTION', 'CONSUMPTION'), ('LAND_DEVELOPMENT', 'LAND_DEVELOPMENT'), ('PURCHASE_OF_SEEDS', 'PURCHASE_OF_SEEDS'), ('PLANTATION_EXPENSES', 'PLANTATION_EXPENSES'), ('PURCHASE_OF_AGRICULTURAL_EQUIPMENTS', 'PURCHASE_OF_AGRICULTURAL_EQUIPMENTS'), ('PAYMENT_OF_LABOUR_EXPENSES', 'PAYMENT_OF_LABOUR_EXPENSES'), ('MEDICAL_EXPENSES', 'MEDICAL_EXPENSES'), ('TRAVEL_EXPENSES', 'TRAVEL_EXPENSES'), ('OTHERS', 'OTHERS'), ('AGRI_ONLY', 'AGRI_ONLY')], max_length=300, null=True),
        ),
    ]
