# Generated by Django 4.0.5 on 2025-11-16 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_newaccount_remove_agentbankaccount_branch_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0080_alter_application_application_loan_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewApplication',
            fields=[
                ('new_application_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('APPLICATION_SENT_TO_LENDER', 'APPLICATION_SENT_TO_LENDER')], max_length=100)),
                ('application_number', models.CharField(max_length=15, unique=True)),
                ('vendor', models.CharField(choices=[('HDFC', 'HDFC'), ('ABCL', 'ABCL')], max_length=100)),
                ('fulfilment_type', models.CharField(choices=[('SELF', 'SELF'), ('MANIPAL', 'MANIPAL')], max_length=100)),
                ('application_reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('ddp_reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modefied_at', models.DateTimeField(auto_now=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_applications_account', to='account.newaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_application_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_application_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
