# Generated by Codex on 2026-05-05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding_v2", "0046_alter_applicationdocument_document_type_and_more"),
        ("application", "0081_newapplication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newapplication",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="new_applications_account",
                to="account.newaccount",
            ),
        ),
        migrations.AddField(
            model_name="newapplication",
            name="onboarding_application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="new_applications",
                to="onboarding_v2.applicationv2",
            ),
        ),
    ]
