# Generated by Django 4.0.5 on 2026-06-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0082_newapplication_onboarding_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newapplication',
            name='vendor',
            field=models.CharField(choices=[('HDFC', 'HDFC'), ('ABCL', 'ABCL'), ('INCRED', 'INCRED'), ('Sammaan Capital', 'Sammaan Capital'), ('Paisa Wapas', 'Paisa Wapas'), ('Urban Money', 'Urban Money'), ('Piramal Capital', 'Piramal Capital'), ('Piramal', 'Piramal'), ('Kotak', 'Kotak'), ('Finnable', 'Finnable'), ('Shubham', 'Shubham')], max_length=100),
        ),
    ]
