# Generated by Django 4.0.5 on 2023-05-26 00:18

from django.db import migrations, models
import django.db.models.deletion
import document.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDocuments',
            fields=[
                ('asset_document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_document_type', models.CharField(blank=True, choices=[('PICTURE_OF_GOLD_JEWELLERY', 'PICTURE_OF_GOLD_JEWELLERY'), ('PICTURE_OF_STONE_WITH_MARK', 'PICTURE_OF_STONE_WITH_MARK'), ('PICTURE_OF_SCALE_WITH_GOLD', 'PICTURE_OF_SCALE_WITH_GOLD'), ('PICTURE_OF_DAMAGES', 'PICTURE_OF_DAMAGES')], default='no_type', max_length=255, null=True)),
                ('file_name', models.CharField(blank=True, max_length=225, null=True)),
                ('file', models.FileField(max_length=225, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(blank=True, choices=[('CUSTOMER_PROFILE_PIC', 'CUSTOMER_PROFILE_PIC'), ('ADHAR_FRONT', 'ADHAR_FRONT'), ('ADHAR_BACK', 'ADHAR_BACK'), ('PAN_CARD', 'PAN_CARD'), ('UTILITY_BILL', 'UTILITY_BILL'), ('GAS_BILL', 'GAS_BILL'), ('RENTAL_BILL', 'RENTAL_BILL'), ('PASSPORT', 'PASSPORT'), ('DRIVING_LICENSE', 'DRIVING_LICENSE'), ('BANK_PASSBOOK', 'BANK_PASSBOOK'), ('CHEQUE_BOOK', 'CHEQUE_BOOK'), ('LAND_DOCUMENT', 'LAND_DOCUMENT'), ('OTHER', 'OTHER')], default='no_type', max_length=255, null=True)),
                ('file_name', models.CharField(blank=True, max_length=225, null=True)),
                ('file', models.FileField(max_length=225, upload_to='', validators=[document.models.file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanDocument',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(blank=True, choices=[('SIGNED_LOAN_DOCUMENT', 'SIGNED_LOAN_DOCUMENT')], default='no_type', max_length=255, null=True)),
                ('file_name', models.CharField(blank=True, max_length=225, null=True)),
                ('file', models.FileField(max_length=225, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_document_application', to='application.application')),
            ],
        ),
    ]
