# Generated by Django 4.0.5 on 2023-05-26 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
        ('asset', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0003_initial'),
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_account', to='account.account'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DOC_USER', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetdocuments',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.application'),
        ),
        migrations.AddField(
            model_name='assetdocuments',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_document_asset', to='asset.asset'),
        ),
        migrations.AddField(
            model_name='assetdocuments',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ASSET_DOC_USER', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('document_type', 'account'), name='document_type_account'),
        ),
    ]
