# Generated by Django 4.0.5 on 2023-06-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loandocument',
            name='application',
        ),
        migrations.RemoveField(
            model_name='loandocument',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='AssetDocuments',
        ),
        migrations.DeleteModel(
            name='LoanDocument',
        ),
    ]
