# Generated by Django 4.0.5 on 2023-09-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=225, upload_to=''),
        ),
    ]
