# Generated by Django 4.0.5 on 2023-09-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_alter_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
