# Generated by Django 4.0.5 on 2023-10-05 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_nomineedetails_relation'),
        ('document', '0012_document_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_account', to='account.account'),
        ),
    ]
