# Generated by Django 4.0.5 on 2023-10-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0013_alter_document_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=225, upload_to='media/'),
        ),
    ]
