# Generated by Django 4.0.5 on 2023-10-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0014_alter_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='url',
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=225, upload_to='media/doc'),
        ),
    ]
