# Generated by Django 4.0.5 on 2023-12-08 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0015_remove_document_url_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_account', to='account.account'),
        ),
    ]
