# Generated by Django 4.0.5 on 2024-05-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0016_alter_document_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(blank=True, choices=[('CUSTOMER_PROFILE_PIC', 'CUSTOMER_PROFILE_PIC'), ('ADHAR_FRONT', 'ADHAR_FRONT'), ('ADHAR_BACK', 'ADHAR_BACK'), ('PAN_CARD', 'PAN_CARD'), ('UTILITY_BILL', 'UTILITY_BILL'), ('GAS_BILL', 'GAS_BILL'), ('RENTAL_BILL', 'RENTAL_BILL'), ('PASSPORT', 'PASSPORT'), ('DRIVING_LICENSE', 'DRIVING_LICENSE'), ('BANK_PASSBOOK', 'BANK_PASSBOOK'), ('CHEQUE_BOOK', 'CHEQUE_BOOK'), ('LAND_DOCUMENT', 'LAND_DOCUMENT'), ('OTHER', 'OTHER'), ('GOLD COLLECTED', 'GOLD COLLECTED'), ('GOLD DEPOSITED', 'GOLD DEPOSITED'), ('FORM_16', 'FORM_16'), ('E_PASSBOOK', 'E_PASSBOOK'), ('BANK_STATEMENT_1', 'BANK_STATEMENT_1'), ('BANK_STATEMENT_2', 'BANK_STATEMENT_2')], default='no_type', max_length=255, null=True),
        ),
    ]
