# Generated by Django 4.0.5 on 2024-06-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0017_alter_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_password',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
