# Generated by Django 4.0.5 on 2024-06-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0018_document_is_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='password',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
