# Generated by Django 4.0.5 on 2023-05-26 00:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_number', models.CharField(max_length=4, unique=True)),
                ('product_type', models.CharField(choices=[('GOLD_LOAN', 'GOLD_LOAN')], default='GOLD_LOAN', max_length=50)),
                ('product_name', models.CharField(max_length=255)),
                ('product_category', models.CharField(choices=[('AGRI', 'AGRI'), ('NON_AGRI', 'NON_AGRI')], default='NON_AGRI', max_length=50)),
                ('pre_payment_col', models.PositiveIntegerField(default=0)),
                ('processing_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('penalty', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('has_white_goods', models.BooleanField(blank=True, default=False, null=True)),
                ('period', models.CharField(choices=[('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY'), ('QUATERLY', 'QUATERLY')], default='MONTHLY', max_length=50)),
                ('has_required_documents', models.BooleanField(blank=True, default=False, null=True)),
                ('maximum_ticket_size', models.IntegerField(blank=True, null=True)),
                ('minimum_ticket_size', models.IntegerField(blank=True, null=True)),
                ('ltv_percentage', models.IntegerField(default=75, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('tenure', models.IntegerField()),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amortization_type', models.CharField(choices=[('Amortization Schedule', 'Amortization Schedule'), ('Interest Only', 'Interest Only'), ('Bullet', 'Bullet')], default='Amortization Schedule', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecificDocuments',
            fields=[
                ('product_document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('document_name', models.CharField(max_length=255)),
                ('document_description', models.CharField(max_length=255)),
                ('document_type', models.CharField(max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('modified_At', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductWhiteGoodsMapping',
            fields=[
                ('product_white_goods_mapping_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('modified_At', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhiteGoods',
            fields=[
                ('goods_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('goods_name', models.CharField(max_length=255)),
                ('goods_description', models.CharField(max_length=255)),
                ('goods_price', models.IntegerField(default=0)),
                ('minimum_order_quantity', models.IntegerField(default=0)),
                ('quantity_available', models.IntegerField(default=0)),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('modified_At', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
