# Generated by Django 4.0.5 on 2023-05-26 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lender', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitegoods',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_goods_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productwhitegoodsmapping',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_white_goods_mapping_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productwhitegoodsmapping',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_white_goods_mapping', to='product.whitegoods'),
        ),
        migrations.AddField(
            model_name='productwhitegoodsmapping',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_white_goods_mapping', to='product.product'),
        ),
        migrations.AddField(
            model_name='productspecificdocuments',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_specific_documents_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productspecificdocuments',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_specific_documents', to='product.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lender', to='lender.lender'),
        ),
    ]
