# Generated by Django 4.0.5 on 2023-06-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_contra_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('GOLD_LOAN', 'GOLD_LOAN'), ('PERSONAL_LOAN', 'PERSONAL_LOAN')], default='GOLD_LOAN', max_length=50),
        ),
    ]
