# Generated by Django 4.0.5 on 2023-06-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitegoods',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
