# Generated by Django 4.0.5 on 2023-06-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_whitegoods_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whitegoods',
            name='status',
        ),
        migrations.AddField(
            model_name='whitegoods',
            name='goods_added',
            field=models.BooleanField(default=False),
        ),
    ]
