# Generated by Django 4.0.5 on 2023-06-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_whitegoods_status_whitegoods_goods_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whitegoods',
            name='goods_added',
        ),
    ]
