# Generated by Django 4.0.5 on 2023-07-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_whitegoods_goods_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitegoods',
            name='available_in',
            field=models.JSONField(default=[]),
        ),
    ]
