# Generated by Django 4.0.5 on 2023-09-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ltv_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
