# Generated by Django 4.0.5 on 2023-09-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_ltv_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
