# Generated by Django 4.0.5 on 2024-02-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_product_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitegoods',
            name='available_in',
            field=models.JSONField(default=dict),
        ),
    ]
