# Generated by Django 4.0.5 on 2024-06-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_whitegoods_available_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(blank=True, choices=[('AGRI', 'AGRI'), ('NON_AGRI', 'NON_AGRI')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('GOLD_LOAN', 'GOLD_LOAN'), ('PERSONAL_LOAN', 'PERSONAL_LOAN'), ('MSME_UNSECURED', 'MSME_UNSECURED'), ('MSME_SECURED', 'MSME_SECURED')], default='GOLD_LOAN', max_length=50),
        ),
    ]
