# Generated by Django 4.0.5 on 2024-08-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='other_deduction',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(blank=True, choices=[('AGRI', 'AGRI'), ('NON_AGRI', 'NON_AGRI')], max_length=50, null=True),
        ),
    ]
