# Generated by Django 4.0.5 on 2024-09-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_other_deduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(blank=True, choices=[('AGRI', 'AGRI'), ('NON_AGRI', 'NON_AGRI'), ('WELLNESS', 'WELLNESS')], max_length=50, null=True),
        ),
    ]
