# Generated by Django 4.0.5 on 2024-09-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(blank=True, choices=[('AGRI', 'AGRI'), ('NON_AGRI', 'NON_AGRI')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('GOLD_LOAN', 'GOLD_LOAN'), ('PERSONAL_LOAN', 'PERSONAL_LOAN'), ('MSME_UNSECURED', 'MSME_UNSECURED'), ('MSME_SECURED', 'MSME_SECURED'), ('WELLNESS', 'WELLNESS')], default='GOLD_LOAN', max_length=50),
        ),
    ]
