# Generated by Django 4.0.5 on 2024-09-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_product_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='insurance_applicable_on',
            field=models.CharField(choices=[('ACCOUNT', 'ACCOUNT'), ('APPLICATION', 'APPLICATION')], default='ACCOUNT', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='is_insurance_applicable',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
