# Generated by Django 4.0.5 on 2024-11-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_product_amortization_type_alter_product_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_stamp_duty_applicable',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
