# Generated by Django 4.0.5 on 2024-12-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_product_is_stamp_duty_applicable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('GOLD_LOAN', 'GOLD_LOAN'), ('PERSONAL_LOAN', 'PERSONAL_LOAN'), ('MSME_UNSECURED', 'MSME_UNSECURED'), ('MEME_UNSECURED_AGRI', 'MEME_UNSECURED_AGRI'), ('MSME_SECURED', 'MSME_SECURED'), ('WELLNESS', 'WELLNESS')], default='GOLD_LOAN', max_length=50),
        ),
    ]
