# Generated by Django 4.0.5 on 2024-12-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0010_branch_latitude_branch_longitude'),
        ('product', '0022_alter_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_in_branches',
            field=models.ManyToManyField(blank=True, related_name='available_products_in_branch', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_available_to_all_branches',
            field=models.BooleanField(default=True),
        ),
    ]
