# Generated by Django 4.0.5 on 2024-12-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_product_available_in_branches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('GOLD_LOAN', 'GOLD_LOAN'), ('PERSONAL_LOAN', 'PERSONAL_LOAN'), ('MSME_UNSECURED', 'MSME_UNSECURED'), ('MSME_UNSECURED_AGRI', 'MSME_UNSECURED_AGRI'), ('MSME_SECURED', 'MSME_SECURED'), ('WELLNESS', 'WELLNESS')], default='GOLD_LOAN', max_length=50),
        ),
    ]
