"""
Django settings for radian_backend project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path
import sys
from utils.envSetup import environment, env
from radian_backend.sentry import init_sentry


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
import os


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g*&urcw$10pe5bmosqmyr0)q*6(34kyuc=o#p^o*8--fai&g)c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
# CSRF_TRUSTED_ORIGINS=['https://dev-api.radianfinserv.com', 'https://uat-api.radianfinserv.com']
CSRF_TRUSTED_ORIGINS = [
    'https://dev-api.radianfinserv.com',
    'https://uat-api.radianfinserv.com',
    'https://manipal.getafixtechnologies.com',
    "https://manipal.getafixtechnologies.com:81",
    'https://devmanipal.getafixtechnologies.com',
    'http://localhost:3000',
    'https://localhost:3000',
    'http://91.203.132.113',
    'http://91.203.132.113:8000',
    'https://manipal-fintech-dashboard.vercel.app',
]

# CORS settings
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'https://localhost:3000',
    'http://91.203.132.113',
    'http://91.203.132.113:8000',
    'https://manipal.getafixtechnologies.com',
    'https://manipal.getafixtechnologies.com:81',
    'https://devmanipal.getafixtechnologies.com',
    'https://164.52.198.201',
    'https://manipal-fintech-dashboard.vercel.app',
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'authorization',
    'content-type',
    'accept',
    'origin',
    'user-agent',
    'x-csrftoken',
    'accept-encoding',
    'accept-language',
    # Dashboard analytics API key header
    'x-dashboard-api-key',
]

# Allow React dashboard on localhost:5173 (Vite default)
CORS_ALLOWED_ORIGINS += [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:5174',
    'http://127.0.0.1:5174',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'phonenumber_field',
    'corsheaders',
    'django_celery_beat',
    'account',
    'application',
    'lead',
    'users',
    'lender',
    'oauth2_provider',
    'drf_spectacular',
    'document',
    'disbursements',
    'loan',
    'product',
    'asset',
    'branch',
    'django_rest_passwordreset',
    'django_filters',
    'core',
    #'minio_storage',
    'django_elasticsearch_dsl',
    'django_elasticsearch_dsl_drf',
    'federal',
    'payment',
    'simple_history',
    'credit_status',
    'reference_pd',
    'tele_verification',
    'scoreme',
    'cibil_score',
    'crif_bureau',
    'tasks',
    'flows',
    'zoop',
    'Leegality',
    'onboarding_v2',
    'insurance',
    'atlas_ocr',
    # Analytics dashboard (read-only, API-key secured)
    'dashboard',
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(levelname)s %(asctime)s %(name)s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'api.request': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'api.error': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'radian': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'users': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'logs': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'onboarding_v2.views': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'simple': {
#             'format': '{levelname}|{process:d}|{asctime}|{pathname}|{message}',
#             'style': '{',
#         },
#     },
#     'handlers': {
#         'info': {
#             'level': 'INFO',
#             'filename':  os.path.join(BASE_DIR, 'logs/radian.log'),
#             'class': 'logging.handlers.TimedRotatingFileHandler',
#             'when': 'midnight',
#             'interval': 1,
#             'formatter': 'simple'
#         }
#     },
#     'loggers': {
#         'radian': {
#             'propagate': True,
#             'handlers': ['info'],
#             'level': 'INFO'
#         }
#     },
# }

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',   # ← must be first for CORS preflight
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'middlewares.logs.ApiLoggingMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'radian_backend.urls'

LOGIN_URL='/admin/login/'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'application', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
CORS_ORIGIN_ALLOW_ALL = False
CORS_ALLOW_ALL_ORIGINS = False

WSGI_APPLICATION = 'radian_backend.wsgi.application'

AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'EXCEPTION_HANDLER': 'utility.error_handler.exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

# Atlas Docstream OCR
# Credentials must be supplied through deployment environment variables.
ATLAS_DOCSTREAM_BASE_URL = os.getenv(
    "ATLAS_DOCSTREAM_BASE_URL", "https://docstream.dev.kreditmind.com"
)
ATLAS_CLIENT_ID = os.getenv("ATLAS_CLIENT_ID", "MPF329f2794411f18a9206e2ca")
ATLAS_CLIENT_SECRET = os.getenv("ATLAS_CLIENT_SECRET", "f3c9a1d2e8b74f60c5a9d3efklm")
ATLAS_PRODUCT_TYPE = os.getenv("ATLAS_PRODUCT_TYPE", "MANIPAL_FINTECH_POC")
ATLAS_REQUEST_TIMEOUT = int(os.getenv("ATLAS_REQUEST_TIMEOUT", "20"))

init_sentry()

SPECTACULAR_SETTINGS = {
    'TITLE': 'Manipal Backend API',
    'DESCRIPTION': 'OpenAPI documentation for backend endpoints.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'ENUM_NAME_OVERRIDES': {
        'LeadTypeEnum': 'onboarding_v2.constants.LeadType',
        'AvailableForEnum': 'onboarding_v2.constants.ProductSubCategory',
        'ActionEnum': [
            ('APPROVE', 'APPROVE'),
            ('REJECT', 'REJECT'),
            ('CORRECTION', 'CORRECTION'),
        ],
    },
    'APPEND_COMPONENTS': {},
    'SECURITY': [],
    'POSTPROCESSING_HOOKS': [
        'radian_backend.swagger_hooks.remove_swagger_security',
        'drf_spectacular.hooks.postprocess_schema_enums'
    ],
}



# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
print("DATABASE_URL exists:", bool(os.environ.get("DATABASE_URL")))
DATABASES = {
    'default': env.db(
        'DATABASE_URL',
        default=f"postgres://{environment.DJANGO_POSTGRES_USER or ''}:{environment.DJANGO_POSTGRES_PASSWORD or ''}@{environment.DJANGO_POSTGRES_HOST or 'localhost'}:{environment.DJANGO_POSTGRES_PORT or 5432}/{environment.DJANGO_POSTGRES_DATABASE or ''}"
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


ACCESS_TOKEN_EXPIRY_IN_DAYS = 7


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST = environment.EMAIL_HOST
EMAIL_PORT = environment.EMAIL_PORT
EMAIL_HOST_USER = environment.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = environment.EMAIL_HOST_PASSWORD
DEFAULT_FROM_EMAIL = environment.DEFAULT_FROM_EMAIL
DEFAULT_TO_EMAIL = environment.DEFAULT_TO_EMAIL

DEFAULT_BH_EMAIL = environment.DEFAULT_BH_EMAIL




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    ("static_assets", os.path.join(BASE_DIR, "assets")),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

if environment.APP_ENV == 'PROD':
    STORAGE_BUCKET_NAME = environment.PROD_STORAGE_BUCKET_NAME
elif environment.APP_ENV == 'QA':
    STORAGE_BUCKET_NAME = environment.QA_STORAGE_BUCKET_NAME
elif environment.APP_ENV == 'DEV':
    STORAGE_BUCKET_NAME = environment.DEV_STORAGE_BUCKET_NAME
else:
    STORAGE_BUCKET_NAME = environment.DEV_STORAGE_BUCKET_NAME
    
# Use local static storage in DEV so /static is populated for nginx; keep MinIO for non-dev
if environment.APP_ENV and environment.APP_ENV.upper() == "DEV":
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
else:
    STATICFILES_STORAGE = "minio_storage.storage.MinioStaticStorage"

# MINIO_STORAGE_STATIC_URL = 'https://' + environment.STORAGE_ENDPOINT + '/' + STORAGE_BUCKET_NAME + '/'
# MINIO_STORAGE_USE_HTTPS = True

MEDIA_URL = '/media/' # Public URL at the browser
MEDIA_PATH = 'media/'
DEFAULT_MEDIA_ROOT = os.path.join(BASE_DIR, MEDIA_PATH) # Directory where uploaded media is saved.
MEDIA_ROOT = DEFAULT_MEDIA_ROOT # Directory where uploaded media is saved.
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # Directory where uploaded media is saved.
IMAGE_ASSETS = os.path.join(BASE_DIR, 'assets/image')
LOGO = os.path.join(IMAGE_ASSETS, 'logo.jpg')

SIGNATURE_DOCUMENT = os.path.join(MEDIA_PATH, 'sign_doc')
ACCOUNT_DOCUMENT = os.path.join(MEDIA_PATH, 'doc')
ASSET_DOCUMENT = os.path.join(MEDIA_PATH, 'asset_doc')  
LOAN_DOCUMENT = os.path.join(MEDIA_PATH, 'loan_doc')
APPLICATION_DOCUMENT = os.path.join(MEDIA_PATH, 'application_doc')
LEAD_DOCUMENT = os.path.join(MEDIA_PATH, 'lead_doc')
SELFIE = os.path.join(MEDIA_PATH, 'selfie')
SUBTASK_DOCUMENT = os.path.join(MEDIA_PATH, 'subtask_doc')

print("Env: "+environment.APP_ENV)
print("STORAGE_BUCKET_NAME: " + STORAGE_BUCKET_NAME)

DEFAULT_FILE_STORAGE = "minio_storage.storage.MinioMediaStorage"
MINIO_STORAGE_ACCESS_KEY = environment.STORAGE_ACCESS_KEY
MINIO_STORAGE_SECRET_KEY = environment.STORAGE_SECRET_KEY
MINIO_STORAGE_ENDPOINT = environment.STORAGE_ENDPOINT
MINIO_STORAGE_USE_HTTPS = True
# STORAGE_BUCKET_NAME = environment.DEV_STORAGE_BUCKET_NAME
# MINIO_STORAGE_MEDIA_BUCKET_NAME = os.path.join(STORAGE_BUCKET_NAME, STORAGE_BUCKET_MEDIA_PATH)
MINIO_STORAGE_MEDIA_BUCKET_NAME = STORAGE_BUCKET_NAME
MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET = True
MINIO_STORAGE_STATIC_BUCKET_NAME = STORAGE_BUCKET_NAME
MINIO_STORAGE_AUTO_CREATE_STATIC_BUCKET = True
# DEFAULT_FILE_STORAGE = "minio_storage.storage.MinioMediaStorage"
# STATICFILES_STORAGE = "minio_storage.storage.MinioStaticStorage"
# MINIO_STORAGE_ACCESS_KEY = environment.STORAGE_ACCESS_KEY
# MINIO_STORAGE_SECRET_KEY = environment.STORAGE_SECRET_KEY
# MINIO_STORAGE_ENDPOINT = environment.STORAGE_ENDPOINT
# MINIO_STORAGE_USE_HTTPS = False
# # STORAGE_BUCKET_NAME = environment.DEV_STORAGE_BUCKET_NAME
# # MINIO_STORAGE_MEDIA_BUCKET_NAME = os.path.join(STORAGE_BUCKET_NAME, STORAGE_BUCKET_MEDIA_PATH)
# MINIO_STORAGE_MEDIA_BUCKET_NAME = STORAGE_BUCKET_NAME
# MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET = True
# MINIO_STORAGE_STATIC_BUCKET_NAME = STORAGE_BUCKET_NAME
# MINIO_STORAGE_AUTO_CREATE_STATIC_BUCKET = True



# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

FCM_API_KEY = environment.FCM_API_KEY
GOOGLE_API_KEY = environment.GOOGLE_API_KEY or os.getenv("GOOGLE_API_KEY", "AIzaSyBYYunuUa1MRrgtHN0v-P4fgJXcj-klTVM")

BROKER_URL = environment.BROKER_URL
CELERY_RESULT_BACKEND = environment.CELERY_RESULT_BACKEND
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'

FILE_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024 # 20 Mb limit
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024 # 20 Mb limit

# SAAS Tech configuration
SAAS_URL = environment.SAAS_URL
SAAS_ACCESS_KEY = environment.SAAS_ACCESS_KEY
SAAS_SECRET_KEY = environment.SAAS_SECRET_KEY
SAAS_CLIENT_CODE = environment.SAAS_CLIENT_CODE
SAAS_MODEL_NAME = environment.SAAS_MODEL_NAME
SAAS_AGREEMENT_ID = environment.SAAS_AGREEMENT_ID or "2605"
SAAS_CREATE_LOAN_URL = environment.SAAS_CREATE_LOAN_URL
SAAS_UPLOAD_DOC_URL = environment.SAAS_UPLOAD_DOC_URL
SAAS_PRODUCT_ID = environment.SAAS_PRODUCT_ID
SAAS_WEBHOOK_SECRET = environment.SAAS_WEBHOOK_SECRET
# Per-endpoint overrides
SAAS_ACCESS_KEY_PRE_SCREEN = environment.SAAS_ACCESS_KEY_PRE_SCREEN
SAAS_SECRET_KEY_PRE_SCREEN = environment.SAAS_SECRET_KEY_PRE_SCREEN
SAAS_CLIENT_CODE_PRE_SCREEN = environment.SAAS_CLIENT_CODE_PRE_SCREEN
SAAS_ACCESS_KEY_CREATE_LOAN = environment.SAAS_ACCESS_KEY_CREATE_LOAN
SAAS_SECRET_KEY_CREATE_LOAN = environment.SAAS_SECRET_KEY_CREATE_LOAN
SAAS_CLIENT_CODE_CREATE_LOAN = environment.SAAS_CLIENT_CODE_CREATE_LOAN
SAAS_SAVE_ONBOARD_URL = environment.SAAS_SAVE_ONBOARD_URL or "https://uat-manipal-api.finncub.com/kyc/api/on-board/saveOnboardDetails"
SAAS_UPDATE_ONBOARD_URL = environment.SAAS_UPDATE_ONBOARD_URL or "https://uat-manipal-api.finncub.com/kyc/api/on-board/updateOnboardDetails"
SAAS_NOTIFICATION_URL = environment.SAAS_NOTIFICATION_URL or "https://uat-manipal-api.finncub.com/kyc/api/webhook/notifications"
SAAS_FUND_REFUND_URL = environment.SAAS_FUND_REFUND_URL or "https://uat-manipal-api.finncub.com/kyc/api/fund-return/submit"
SAAS_ACCESS_KEY_ONBOARD = environment.SAAS_ACCESS_KEY_ONBOARD or "0722a834114d88ddb99ed1dc832"
SAAS_SECRET_KEY_ONBOARD = environment.SAAS_SECRET_KEY_ONBOARD or "996e184895ae9920f0726e24e98b"
SAAS_CLIENT_CODE_ONBOARD = environment.SAAS_CLIENT_CODE_ONBOARD or "UAT-GETAFIX"
# Slack notification endpoint for SAAS lifecycle
SAAS_SLACK_WEBHOOK_URL = environment.SAAS_SLACK_WEBHOOK_URL

# Bureau (Signzy Experian)
SIGNZY_EXP_API_URL = environment.SIGNZY_EXP_API_URL
SIGNZY_EXP_AUTH_TOKEN = environment.SIGNZY_EXP_AUTH_TOKEN
SIGNZY_CONSENT_IP = environment.SIGNZY_CONSENT_IP
SIGNZY_CONSENT_MESSAGE_ID = environment.SIGNZY_CONSENT_MESSAGE_ID

#Cover fox insurance
COVER_FOX_USERNAME = environment.COVER_FOX_USERNAME
COVER_FOX_PASSWORD= environment.COVER_FOX_PASSWORD
COVER_FOX_REQUEST_TOKEN_URL=environment.COVER_FOX_REQUEST_TOKEN_URL
COVER_FOX_LOGIN_URL= environment.COVER_FOX_LOGIN_URL

# CRIF Bureau Configuration
CRIF_CALLBACK_URL = environment.CRIF_CALLBACK_URL
CRIF_REDIRECT_URL = environment.CRIF_REDIRECT_URL
CRIF_WEBHOOK_SECRET = environment.CRIF_WEBHOOK_SECRET
CRIF_BUREAU_ELIGIBLE_SCORE = environment.CRIF_BUREAU_ELIGIBLE_SCORE

# Medibuddy insurance
MEDI_BUDDY_SECRET_KEY= environment.MEDI_BUDDY_SECRET_KEY
MEDI_BUDDY_URL=environment.MEDI_BUDDY_URL
MEDI_BUDDY_CORPORATE_ID= environment.MEDI_BUDDY_CORPORATE_ID
MEDI_BUDDY_SHARED_SECRET= environment.MEDI_BUDDY_SHARED_SECRET

# API PAGINATION PAGE SIZE
API_PAGE_SIZE = 20


# Elastic Seach configurations:
ELASTICSEARCH_DSL={
    'default': {
        'hosts': f'http://{environment.ELASTICSEARCH_HOST}:{environment.ELASTICSEARCH_PORT}',
        'timeout': 600,  # Custom timeout
        'http_auth': (environment.ELASTICSEARCH_USERNAME, environment.ELASTICSEARCH_PASSWORD),
    }
}
ELASTICSEARCH_DSL_PARALLEL = True

# In local DEV, Elasticsearch often runs under a Docker-only hostname such as
# `radian_search`. Disabling autosync prevents regular model saves from failing
# when Elasticsearch is not reachable from the host machine.
if 'test' in sys.argv or (environment.APP_ENV and environment.APP_ENV.upper() == 'DEV'):
    ELASTICSEARCH_DSL_AUTOSYNC = False
    ELASTICSEARCH_DSL_AUTO_REFRESH = False
    ELASTICSEARCH_DSL_SIGNAL_PROCESSOR = 'django_elasticsearch_dsl.signals.BaseSignalProcessor'

# Score Me Configurations
SCORE_ME_BASE_URL = environment.SCORE_ME_BASE_URL
SCORE_ME_CLIENT_ID = environment.SCORE_ME_CLIENT_ID
SCORE_ME_CLIENT_SECRET = environment.SCORE_ME_CLIENT_SECRET

# AbleCredit (video PD)
ABLE_CREDIT_HOST = environment.ABLE_CREDIT_HOST or "https://col-api-qa.ablecredit.com"
ABLE_CREDIT_TENANT_ID = environment.ABLE_CREDIT_TENANT_ID or "MANIPAL-43482838"
ABLE_CREDIT_API_KEY = environment.ABLE_CREDIT_API_KEY or "2db9f501-158d-49b2-b5f2-e00f00ea0c9c"
ABLE_CREDIT_SDK_KEY = environment.ABLE_CREDIT_SDK_KEY or "c64648de-be1c-47a2-a17b-cf1f901aabdc"


WORKAPPS_API_KEY = environment.WORKAPPS_API_KEY
WORKAPPS_API_SECRET = environment.WORKAPPS_API_SECRET

# ZOOP Credentials
ZOOP_APP_ID = os.getenv("ZOOP_APP_ID", "6257bb6ab1ff4b001d3c01fd")
ZOOP_API_KEY = os.getenv("ZOOP_API_KEY", "19Q144Q-5HHMT02-P0R3VCD-XM6W8CR")

# ZOOP API URLs
ZOOP_PAN_URL = "https://test.zoop.one/api/v1/in/identity/pan/pro"
ZOOP_BANK_VERIFICATION_URL = "https://test.zoop.one/api/v1/in/financial/bav/lite"
ZOOP_BANK_VERIFICATION_LITE_URL = "https://test.zoop.one/api/v1/in/financial/bav/lite"
ZOOP_DL_URL = "https://test.zoop.one/api/v1/in/identity/dl/advance"
ZOOP_CHEQUE_OCR_URL = "https://test.zoop.one/api/v1/in/utility/ocr/cheque"
ZOOP_OCR_LITE_URL = "https://test.zoop.one/api/v1/in/utility/ocr/lite"
ZOOP_VOTER_ADVANCE_URL = "https://test.zoop.one/api/v1/in/identity/voter/advance"
ZOOP_PASSPORT_ADVANCE_URL = "https://test.zoop.one/api/v1/in/identity/passport/advance"
ZOOP_FACE_MATCH_URL = "https://test.zoop.one/api/v1/in/ml/face/match"

# Leegality API Configuration
LEEGALITY_API_BASE = environment.LEEGALITY_BASE_URL or "https://sandbox.leegality.com/api/v3.0"
LEEGALITY_BASE_URL = f"{LEEGALITY_API_BASE}/sign/request"
LEEGALITY_AUTH_TOKEN = environment.LEEGALITY_AUTH_TOKEN or "2ndmdSN332MiIzmtsTkZ8uuRqegrdUtE" 
LEEGALITY_SALT_KEY = environment.LEEGALITY_SALT_KEY or "6ASdZ3XU5rmY40moKr00PxCXyRy2K6EP" 

# Additional API Endpoints
  
LEEGALITY_DOCUMENT_DETAILS_URL = f"{LEEGALITY_API_BASE}/document/details"
LEEGALITY_DOCUMENT_DELETE_URL = f"{LEEGALITY_API_BASE}/document/delete"
LEEGALITY_SEARCH_URL = f"{LEEGALITY_API_BASE}/sign/request/list"
LEEGALITY_REACTIVATE_URL = f"{LEEGALITY_API_BASE}/sign/request/reactivate"
LEEGALITY_RESEND_NOTIFICATION_URL = f"{LEEGALITY_API_BASE}/sign/request/resend"
LEEGALITY_DELETE_INVITATION_URL = f"{LEEGALITY_API_BASE}/sign/request/invitation"
LEEGALITY_MARK_COMPLETE_URL = f"{LEEGALITY_API_BASE}/sign/request/complete"
LEEGALITY_COMPLETED_DOCUMENTS_URL = f"{LEEGALITY_API_BASE}/document/completed"
LEEGALITY_DOCSIGNER_INVITATION_URL = f"{LEEGALITY_API_BASE}/sign/docSigner/invitation"
LEEGALITY_STAMP_DETAILS_URL = f"{LEEGALITY_API_BASE}/series/list"
LEEGALITY_STAMP_GROUPS_URL = f"{LEEGALITY_API_BASE}/series/groups/list"

# SMSGatewayHub Config
SMS_API_KEY = os.getenv("SMS_API_KEY", "089790f1-8c30-4ec8-b669-10c9e3db3d0b")
SMS_SENDER_ID = "MNIPLF"
SMS_ENTITY_ID = "1201173893563835134"
SMS_TEMPLATE_ID = "1007172090059222355"
SMS_OTP_TEXT = "Use OTP {#var#} to verify your mobile number and login/signup securely to your account. Keep this confidential. - Manipal Fintech Private Limited"

SMS_LEAD_GENERATION_TEMPLATE_ID = "1007022300526847799"
SMS_LEAD_GENERATION_OTP_TEXT = "Dear Customer, {#var#} is your OTP to confirm your enquiry with Manipal Fintech."
SMS_LEAD_AUTO_CLOSED_TEMPLATE_ID = "1007172090059222355"
SMS_LEAD_AUTO_CLOSED_TEXT = "Lead {#var#} ({#var#}) has been auto-closed due to inactivity. Manipal Fintech Private Limited"
SMS_PAN_VERIFICATION_TEMPLATE_ID = "1007788001501641886"
SMS_PAN_VERIFICATION_OTP_TEXT = (
    "Dear customer, To complete onboarding, we need your consent to process personal data "
    "including KYC & Credit Bureau checks and to contact you. Code to share your consent is "
    "{#var#}. - Team Manipal Fintech"
)
SMS_BT_PAN_VERIFICATION_TEMPLATE_ID = "1007613213003792024"
SMS_BT_PAN_VERIFICATION_OTP_TEXT = (
    "Dear Customer, OTP {#var#} confirms your consent to process your personal data for "
    "onboarding including KYC verification, credit bureau checks, Account Aggregator "
    "Services and to contact you. You also consent to recording of your interaction with "
    "our sales officer for service and assessment purposes. - Team Manipal Fintech "
    "(LSP of Simplepay Finance Pvt Ltd)"
)

# Dynamically append AutoLoginAuthentication for non-production environments with DEBUG = True
if environment.APP_ENV != 'PROD' and DEBUG:
    REST_FRAMEWORK['DEFAULT_AUTHENTICATION_CLASSES'].append('radian_backend.auth.AutoLoginAuthentication')
