# Generated by Django 4.0.5 on 2024-05-24 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference_PD',
            fields=[
                ('pd_details_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('enterprise_name', models.CharField(blank=True, max_length=128, null=True)),
                ('nature_of_business', models.CharField(choices=[('RETAIL', 'RETAIL'), ('TRADERS', 'TRADERS'), ('ALLIED_AGRI', 'ALLIED_AGRI'), ('ADRI', 'ADRI')], max_length=20)),
                ('sub_nature_of_business', models.CharField(blank=True, max_length=32, null=True)),
                ('residential', models.CharField(choices=[('OWN', 'OWN'), ('RENTED', 'RENTED')], max_length=20)),
                ('number_of_years', models.CharField(choices=[('1_TO_1O', '1_TO_1O'), ('ABOVE_10', 'ABOVE_10')], max_length=20)),
                ('number_of_family_members', models.IntegerField(null=True)),
                ('number_of_earning_members', models.IntegerField(null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('relation_with_applicant', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modefied_at', models.DateTimeField(auto_now=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refenrence_pd_account', to='account.account')),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
