# Generated by Django 4.0.5 on 2024-05-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_pd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_pd',
            name='enterprise_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='reference_pd',
            name='nature_of_business',
            field=models.CharField(choices=[('RETAIL', 'RETAIL'), ('TRADERS', 'TRADERS'), ('ALLIED_AGRI', 'ALLIED_AGRI'), ('AGRI', 'AGRI')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reference_pd',
            name='number_of_earning_members',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reference_pd',
            name='number_of_family_members',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reference_pd',
            name='relation_with_applicant',
            field=models.CharField(choices=[('MOTHER', 'MOTHER'), ('FATHER', 'FATHER'), ('HUSBAND', 'HUSBAND'), ('SON', 'SON'), ('DAUGHTER', 'DAUGHTER'), ('SIBLINGS', 'SIBLINGS'), ('WIFE', 'WIFE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reference_pd',
            name='sub_nature_of_business',
            field=models.CharField(max_length=32),
        ),
    ]
