# Generated by Django 4.0.5 on 2024-12-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_pd', '0002_alter_reference_pd_enterprise_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_pd',
            name='nature_of_business',
            field=models.CharField(choices=[('RETAIL', 'RETAIL'), ('TRADERS', 'TRADERS'), ('ALLIED_AGRI', 'ALLIED_AGRI'), ('AGRI', 'AGRI'), ('CROP', 'CROP'), ('DAIRY', 'DAIRY'), ('CROP_AND_DAIRY', 'CROP_AND_DAIRY'), ('OTHERS', 'OTHERS')], max_length=20),
        ),
    ]
