# Generated by Django 4.0.5 on 2025-01-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_pd', '0003_alter_reference_pd_nature_of_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference_pd',
            name='others_relations',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reference_pd',
            name='relation_with_applicant',
            field=models.CharField(choices=[('MOTHER', 'MOTHER'), ('FATHER', 'FATHER'), ('HUSBAND', 'HUSBAND'), ('SON', 'SON'), ('DAUGHTER', 'DAUGHTER'), ('SIBLINGS', 'SIBLINGS'), ('WIFE', 'WIFE'), ('BUYERS', 'BUYERS'), ('SELLERS', 'SELLERS'), ('COMPETITORS', 'COMPETITORS'), ('DISTRIBUTORS', 'DISTRIBUTORS'), ('BUSINESS_PARTNERS', 'BUSINESS_PARTNERS'), ('EXISITING_MSME_CLIENTS', 'EXISITING_MSME_CLIENTS'), ('OTHERS', 'OTHERS')], max_length=50),
        ),
    ]
