# Generated by Django 4.0.5 on 2024-06-13 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0065_rename_amount_requirement_application_requested_loan_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tele_verification',
            fields=[
                ('tele_verification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('report_in_brief', models.TextField()),
                ('location_captured', models.TextField()),
                ('picture_captured', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10)),
                ('observation', models.CharField(choices=[('POSITIVE', 'POSITIVE'), ('NEGATIVE', 'NEGATIVE')], max_length=10)),
                ('observation_comment', models.TextField(blank=True, null=True)),
                ('residential_stability', models.CharField(choices=[('POSITIVE', 'POSITIVE'), ('NEGATIVE', 'NEGATIVE')], max_length=10)),
                ('residential_stability_comment', models.TextField(blank=True, null=True)),
                ('business_stability', models.CharField(choices=[('POSITIVE', 'POSITIVE'), ('NEGATIVE', 'NEGATIVE')], max_length=10)),
                ('business_stability_comment', models.TextField(blank=True, null=True)),
                ('no_of_similar_business', models.IntegerField()),
                ('suppliers_customer_feeedback', models.TextField()),
                ('external_income', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tele_application', to='application.application')),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
