# Generated by Django 4.0.5 on 2024-06-19 09:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0066_alter_application_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tele_verification', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tele_verification',
            new_name='TeleVerification',
        ),
    ]
