# Generated by Django 4.0.5 on 2024-06-24 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0066_alter_application_status_and_more'),
        ('tele_verification', '0002_rename_tele_verification_televerification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='televerification',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tele_application', to='application.application'),
        ),
    ]
