# Generated by Django 4.0.5 on 2025-04-08 04:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tele_verification', '0003_alter_televerification_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videokyc',
            fields=[
                ('video_kyc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('entity_id', models.IntegerField()),
                ('client_user_id', models.IntegerField(unique=True)),
                ('product_type', models.IntegerField(choices=[(4, 'Individual Guest Chat'), (5, 'Group Guest Chat')])),
                ('first_name', models.CharField(max_length=64)),
                ('customer_id', models.CharField(blank=True, max_length=20, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=100, null=True)),
                ('application_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=256, null=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('other_info', models.TextField(blank=True, null=True)),
                ('user_photo', models.TextField(blank=True, null=True)),
                ('status_url', models.URLField(blank=True, null=True)),
                ('use_case', models.IntegerField(choices=[(1, 'VideoKYC')])),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
