# Generated by Django 4.0.5 on 2025-04-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tele_verification', '0004_videokyc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videokyc',
            name='status_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
