# Generated by Django 4.0.5 on 2023-05-26 00:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('disbursement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('disbursement_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('disbursal_date', models.DateTimeField(auto_now_add=True)),
                ('disbursal_status', models.DateTimeField(auto_now_add=True)),
                ('payment_mode', models.CharField(max_length=25)),
                ('utr_no', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modefied_at', models.DateTimeField(auto_now=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.application')),
            ],
        ),
    ]
