# Generated by Django 4.0.5 on 2023-06-02 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_application_live_tracking_id_loandocument_and_more'),
        ('loan', '0005_alter_livetracking_loan_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disbursements', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_disbursed_applications', to='application.application'),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_disbursed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_disbursement_transactions', to='loan.loan'),
        ),
    ]
