# Generated by Django 4.0.5 on 2023-06-11 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0011_loan_next_due_date_loan_next_due_generation_date_and_more'),
        ('disbursements', '0003_alter_disbursement_application_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disbursement',
            name='disbursal_status',
        ),
        migrations.AddField(
            model_name='disbursement',
            name='disbursement_status',
            field=models.CharField(choices=[('APPLICATION_DISBURSED', 'APPLICATION_DISBURSED'), ('APPLICATION_TAKE_OVER_DISBURSED', 'APPLICATION_TAKE_OVER_DISBURSED'), ('APPLICATION_TAKE_OVER_DISBURSED_RADIAN', 'APPLICATION_TAKE_OVER_DISBURSED_RADIAN')], default='APPLICATION_DISBURSED', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_disbursement_transactions', to='loan.loan'),
        ),
    ]
