# Generated by Django 4.0.5 on 2023-06-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursements', '0004_remove_disbursement_disbursal_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='disbursement_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('SUCCESS', 'SUCCESS')], max_length=100),
        ),
    ]
