# Generated by Django 4.0.5 on 2023-06-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursements', '0005_alter_disbursement_disbursement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='disbursement_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('SUCCESS', 'SUCCESS'), ('TAKEOVER', 'TAKEOVER')], max_length=100),
        ),
    ]
