# Generated by Django 4.0.5 on 2023-07-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursements', '0006_alter_disbursement_disbursement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='disbursal_date',
            field=models.DateField(null=True),
        ),
    ]
