# Generated by Django 4.0.5 on 2023-09-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursements', '0007_alter_disbursement_disbursal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='utr_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
