# Generated by Django 4.0.5 on 2023-09-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursements', '0008_alter_disbursement_utr_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
