# Generated by Django 4.0.5 on 2023-09-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursements', '0009_alter_disbursement_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='disbursal_date',
            field=models.DateTimeField(null=True),
        ),
    ]
