# Generated by Django 4.0.5 on 2023-09-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursements', '0010_alter_disbursement_disbursal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='disbursal_date',
            field=models.DateField(null=True),
        ),
    ]
