# Generated by Django 4.0.5 on 2023-09-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursements', '0011_alter_disbursement_disbursal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='payment_status',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (0, 0)], default=0),
        ),
    ]
