# Generated by Django 4.0.5 on 2023-09-12 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disbursements', '0012_disbursement_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disbursement',
            old_name='modefied_at',
            new_name='modified_at',
        ),
    ]
