# Generated by Django 4.0.5 on 2025-11-18 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Leegality', '0001_initial'),
    ]

    # These fields are already present in 0001_initial. Keep 0002 as a no-op so
    # fresh database setups do not fail with duplicate-column errors.
    operations = []
