# Generated by Django 4.0.5 on 2025-11-18 19:17



from django.conf import settings

from django.db import migrations, models

import django.db.models.deletion





class Migration(migrations.Migration):



    dependencies = [

        ('Leegality', '0002_leegalitydocument_audit_trail_and_more'),

    ]



    operations = [

        migrations.AlterField(

            model_name='leegalitydocument',

            name='user',

            field=models.ForeignKey(

                blank=True, 

                null=True, 

                on_delete=django.db.models.deletion.CASCADE, 

                related_name='leegality_documents', 

                to=settings.AUTH_USER_MODEL

            ),

        ),

    ]
