# Generated by Django 4.2.27 on 2025-12-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leegality', '0003_alter_leegalitydocument_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leegalitydocument',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
