# Generated by Django 4.0.5 on 2024-08-12 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0075_alter_loandocument_document_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CibilScore',
            fields=[
                ('cibil_score_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cb_score', models.IntegerField(blank=True, null=True)),
                ('obligation', models.IntegerField(blank=True, null=True)),
                ('existing_loan_amount', models.IntegerField(blank=True, null=True)),
                ('emi_of_existing_loan', models.IntegerField(blank=True, null=True)),
                ('no_of_loans_running', models.IntegerField(blank=True, null=True)),
                ('no_of_loans_closed_in_last_1_year', models.IntegerField(blank=True, null=True)),
                ('any_loan_applied_in_last_30_days', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cibil_score_application', to='application.application')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cibil_score_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
