# Generated by Django 4.0.5 on 2025-10-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='expected_duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
