state_code_dict = {
    "Jammu & Kashmir": 1,
    "Himachal Pradesh": 2,
    "Punjab": 3,
    "Chandigarh": 4,
    "Uttaranchal/Uttarakhand": 5,
    "Haryana": 6,
    "Delhi": 7,
    "Rajasthan": 8,
    "Uttar Pradesh": 9,
    "Bihar": 10,
    "Sikkim": 11,
    "Arunachal Pradesh": 12,
    "Nagaland": 13,
    "Manipur": 14,
    "Mizoram": 15,
    "Tripura": 16,
    "Meghalaya": 17,
    "Assam": 18,
    "West Bengal": 19,
    "Jharkhand": 20,
    "Orissa": 21,
    "Chhattisgarh": 22,
    "Madhya Pradesh": 23,
    "Gujarat": 24,
    "Daman & Diu": 25,
    "Dadra & Nagar Haveli and Daman & Diu": 26,
    "Maharashtra": 27,
    "Andhra Pradesh": 28,
    "Karnataka": 29,
    "Goa": 30,
    "Lakshadweep": 31,
    "Kerala": 32,
    "Tamil Nadu": 33,
    "Pondicherry": 34,
    "Andaman & Nicobar Islands": 35,
    "Telangana": 36,
    "Ladakh": 38,
    "APO Address": 99
}

SCORE_MIN      = 500    # Bureau score must be >= this
DPD_DAYS_MAX   = 180     # Days Past Due limit per month
# DPD_AMOUNT_MAX = 10000  # Amount Past Due limit in rupees
LOOKBACK_YEARS = 2      # Years to look back for suit / write-off