# Generated by Django 5.2.15 on 2026-06-04 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_integration', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lead',
            new_name='bajaj_lead__mobile__003f85_idx',
            old_name='bajaj_lead_mobile_status_idx',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='leadaudit',
            name='logged_in_user',
        ),
    ]
