# Generated by Django 5.2.15 on 2026-06-17 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_integration', '0003_lead_fullname_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='bank_id',
        ),
    ]
