import enum


class APP_ENV(enum.Enum):
    PROD = "PROD"
    UAT = "UAT"
    DEV = "DEV"


class ROLES(enum.Enum):
    LOAN_OFFICER = "LOAN_OFFICER"
    SUPER_ADMIN = "SUPER_ADMIN"
    BRANCH_MANAGER = "BRANCH_MANAGER"
    CUSTOMER = "CUSTOMER"
    CPC = "CENTRALISED_PROCESSING_CELL"
    ASSISTANT_BRANCH_MANAGER = "ASSISTANT_BRANCH_MANAGER" # TODO: this role can be removed. not exist in Radian anymore
    CLUSTER_MANAGER = "CLUSTER_MANAGER"
    REGIONAL_HEAD = "REGIONAL_HEAD"
    CHIEF_BUSINESS_OPERATOR='CHIEF_BUSINESS_OFFICER'
    BUSINESS_HEAD='BUSINESS_HEAD'
    BRANCH_OPERATION_MANAGER="BRANCH_OPERATION_MANAGER" # TODO: need to remove this role. we are using BRANCH_MANAGER for BOM.
    THIRD_PARTY_VENDOR="THIRD_PARTY_VENDOR"
    THIRD_PARTY_CUSTOMER="THIRD_PARTY_CUSTOMER"
    AUDIT_ADMIN="AUDIT_ADMIN"

    RELATIONSHIP_MANAGER="RELATIONSHIP_MANAGER" 
    CREDIT_MANAGER="CREDIT_MANAGER"
    CREDIT_OFFICER="CREDIT_OFFICER"

    AGENT="AGENT"
    SALES_OFFICER="SALES_OFFICER"
    VERTICAL_ADMIN="VERTICAL_ADMIN"
    TELE_ADMIN="TELE_ADMIN"
    TELE_USER="TELE_USER"
    CENTRAL_OPS_ADMIN="CENTRAL_OPS_ADMIN"
    ANALYTICS_ADMIN="ANALYTICS_ADMIN"
    REPORTING_USER="REPORTING_USER"
    SALES_HEAD="SALES_HEAD"
    NATIONAL_SALES_HEAD="NATIONAL_SALES_HEAD"
    ZONAL_HEAD="ZONAL_HEAD"
    CLUSTER_HEAD="CLUSTER_HEAD"
    APPRAISER="APPRAISER"
    MANAGEMENT_USER="MANAGEMENT_USER"

API_IMMUTABLE_ROLES = (
    ROLES.SUPER_ADMIN.value,
)


API_MANAGEABLE_ROLES = tuple(
    role.value for role in ROLES if role.value not in API_IMMUTABLE_ROLES
)


ROLE_MANAGEMENT_SCOPE = {
    ROLES.SUPER_ADMIN.value: API_MANAGEABLE_ROLES + (ROLES.VERTICAL_ADMIN.value,),
    ROLES.VERTICAL_ADMIN.value: tuple(
        role for role in API_MANAGEABLE_ROLES if role != ROLES.VERTICAL_ADMIN.value
    ),
    ROLES.CPC.value: API_MANAGEABLE_ROLES + (ROLES.VERTICAL_ADMIN.value,),
    ROLES.BRANCH_MANAGER.value: (
        ROLES.LOAN_OFFICER.value,
    ),
    ROLES.TELE_ADMIN.value: (
        ROLES.TELE_USER.value,
    ),
}

class SALES_PAYOUT_TYPE(enum.Enum):
    COMMISSION = "COMMISSION"
    INCENTIVE = "INCENTIVE"


class LOAN_STATUS(enum.Enum):
    NEW = "NEW"
    SUBMITTED_TO_LENDER = "SUBMITTED_TO_LENDER"
    ASSET_COLLECTED = "ASSET_COLLECTED"
    GOOD_STANDING = "Active - Good Standing"
    BAD_STANDING = "Active - Bad Standing"
    APPROVED = "Approved"
    CLOSED_OBLIGATIONS_MET = "Closed - Obligations Met"


class TIMESTAMP(enum.Enum):
    CHECKED_IN = "CHECKED_IN"
    CHECKED_OUT = "CHECKED_OUT"


class LEAD_TYPE(enum.Enum):
    TAKE_OVER = "TAKE_OVER_BT"
    FRESH = "FRESH"


class LEAD_SOURCE(enum.Enum):
    LOAN_OFFICER_APP = "LOAN_OFFICER_APP"
    CUSTOMER_APP = "CUSTOMER_APP"
    CRM_WEB_APP = "CRM_WEB_APP"
    RADIAN_FINSERV_WEBSITE = "RADIAN_FINSERV_WEBSITE"
    CUSTOMER_APP_REFERENCE = "CUSTOMER_APP_REFERENCE"
    TELE = "TELE"


class NEW_LEAD_SOURCE(enum.Enum):
    MANIPAL = "MANIPAL"
    FINCOME = "FINCOME"

    

class SOURCE_TYPE(enum.Enum):
    SELF = "SELF"
    CENTRAL = "CENTRAL"
    BANK_REFERRED = "BANK_REFERRED"
    

class NEW_LOAN_TYPE(enum.Enum):
    GOLD_LOAN = "GOLD_LOAN"
    PERSONAL_LOAN = "PERSONAL_LOAN"
    HOME_LOAN = "HOME_LOAN"
    LAP = "LAP"
    BUSINESS_LOAN = "BUSINESS_LOAN"
    WORKING_CAPITAL = "WORKING_CAPITAL"
    HEALTH_INSURANCE = "HEALTH_INSURANCE"

class NEW_LEAD_TYPE(enum.Enum):
    FRESH = "FRESH"
    TAKE_OVER_BT = "TAKE_OVER_BT"
    LOAN = "LOAN"
    INSURANCE ="INSURANCE"

class NEW_LEAD_STATUS(enum.Enum):
    NEW_LEAD = "NEW_LEAD"
    DISBURSED = "DISBURSED"
    IN_PROGRESS = "IN_PROGRESS"
    LEAD_CREATION_COMPLETED = "LEAD_CREATION_COMPLETED"

class NEW_ACCOUNT_STATUS(enum.Enum):
    PAN_VERIFIED = "PAN_VERIFIED"
    ACCOUNT_CREATED = "ACCOUNT_CREATED"

class NEW_APPLICATION_STATUS(enum.Enum):
    APPLICATION_SENT_TO_LENDER = "APPLICATION_SENT_TO_LENDER"

class VENDOR(enum.Enum):
    HDFC = "HDFC"
    ABCL = "ABCL"
    INCRED = "INCRED"
    SAMMAAN_CAPITAL = "Sammaan Capital"
    PAISA_WAPAS = "Paisa Wapas"
    URBAN_MONEY = "Urban Money"
    PIRAMAL_CAPITAL = "Piramal Capital"
    PIRAMAL = "Piramal"
    KOTAK="Kotak"
    FINNABLE="Finnable"
    SHUBHAM="Shubham"

class FULFILMENT_TYPE(enum.Enum):
    SELF = "SELF"
    MANIPAL = "MANIPAL"
class LEAD_DOCUMENT_TYPE(enum.Enum):
    AADHAR_CARD = "AADHAR_CARD"
    PAN_CARD = "PAN_CARD"
    PLEDGE_CARD = "PLEDGE_CARD"
    AGRI_PRODUCT_PROOF="AGRI_PRODUCT_PROOF"


class LOAN_TYPE(enum.Enum):
    GOLD_LOAN = "GOLD_LOAN"
    PERSONAL_LOAN = "PERSONAL_LOAN"
    MSME_UNSECURED = "MSME_UNSECURED" #(PERSONAL_LOAN)
    MSME_UNSECURED_AGRI = "MSME_UNSECURED_AGRI"
    MSME_SECURED="MSME_SECURED" #(HOME_LOAN)
    WELLNESS="WELLNESS"


class PRODUCT_TYPE(enum.Enum):
    AGRI = "AGRI"
    NON_AGRI = "NON_AGRI"

class WHITE_GOODS(enum.Enum):
    TABLE_FAN = "TABLE_FAN"
    CHAIR = "CHAIR"
    GRINDER = "GRINDER"


class PERIOD(enum.Enum):
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"
    QUATERLY = "QUATERLY"
    NONE = "NONE"
    
class AMORTIZATIONTYPE(enum.Enum):
    AMORTIZATION_SCHEDULE = "Amortization Schedule"
    INTEREST_ONLY = "Interest Only"
    BULLET = "Bullet"
    NONE = "None"


class RESENDITIAL_OWNERSHIP(enum.Enum):
    NATIVE_OWNED = "NATIVE_OWNED"
    RENTED = "RENTED"
    SELF_OWNED = "SELF_OWNED"
    INDIVIDUAL_OWNERSHIP = "INDIVIDUAL_OWNERSHIP"
    JOINT_OWNERSHIP = "JOINT_OWNERSHIP"


class ADDRESS_TYPE(enum.Enum):
    PERMANENT_ADDRESS = "PERMANENT_ADDRESS"
    CORRESPONDENCE_ADDRESS = "CORRESPONDENCE_ADDRESS"


class ACCOUNT_STATUS(enum.Enum):
    NEW_ACCOUNT_CREATED = "NEW_ACCOUNT_CREATED"
    ADDRESS_ADDED = "ADDRESS_ADDED"
    KYC_ADDED = "KYC_ADDED"
    BANK_DETAILS_ADDED = "BANK_DETAILS_ADDED"

    CO_APPLICANT_NEW_ACCOUNT_CREATED = "CO_APPLICANT_NEW_ACCOUNT_CREATED"
    CO_APPLICANT_ADDRESS_ADDED = "CO_APPLICANT_ADDRESS_ADDED"
    CO_APPLICANT_KYC_ADDED = "CO_APPLICANT_KYC_ADDED"
    CO_APPLICANT_BANK_DETAILS_ADDED = "CO_APPLICANT_BANK_DETAILS_ADDED"
    
    ACCOUNT_CONFIRMED = "ACCOUNT_CONFIRMED"
    NOMINEE_ADDED = 'NOMINEE_ADDED'
    CREDIT_STATUS_ADDED = 'CREDIT_STATUS_ADDED'
    REFERENCE_PD_ADDED = 'REFERENCE_PD_ADDED'
    RESIDENCE_PROOF_ADDED = 'RESIDENCE_PROOF_ADDED'

class PurposeOfLoan(enum.Enum):
    # Non-Agri Loan purposes
    EDUCATIONAL = "EDUCATIONAL"
    MARRIAGE = "MARRIAGE"
    INCOME_GENERATION = "INCOME_GENERATION"
    MEDICAL_EMERGENCY = "MEDICAL_EMERGENCY"
    BROAD_CATEGORY = "BROAD_CATEGORY"
    PURCHASE_OF_ASSETS = "PURCHASE_OF_ASSETS"
    PURCHASE_OF_GOODS = "PURCHASE_OF_GOODS"

    # Personal Loan
    EXPANSION = "EXPANSION"
    STOCKS = "STOCKS"
    CONSUMPTION = "CONSUMPTION"

    # Agri Loan purposes
    LAND_DEVELOPMENT = "LAND_DEVELOPMENT"
    PURCHASE_OF_SEEDS = "PURCHASE_OF_SEEDS"
    PLANTATION_EXPENSES = "PLANTATION_EXPENSES"
    PURCHASE_OF_AGRICULTURAL_EQUIPMENTS = "PURCHASE_OF_AGRICULTURAL_EQUIPMENTS"
    PAYMENT_OF_LABOUR_EXPENSES = "PAYMENT_OF_LABOUR_EXPENSES"
    MEDICAL_EXPENSES = "MEDICAL_EXPENSES"
    TRAVEL_EXPENSES = "TRAVEL_EXPENSES"
    OTHER = "OTHERS"

    #MSME Agri
    AGRI_ONLY = "AGRI_ONLY"

class RELATION(enum.Enum):
    MOTHER = "MOTHER"
    FATHER = "FATHER"
    HUSBAND = "HUSBAND"
    SON = "SON"
    DAUGHTER = "DAUGHTER"
    SIBLINGS = "SIBLINGS"
    WIFE="WIFE"

    BUYERS = "BUYERS"
    SELLERS = "SELLERS"
    COMPETITORS = "COMPETITORS"
    DISTRIBUTORS = "DISTRIBUTORS"
    BUSINESS_PARTNERS="BUSINESS_PARTNERS"
    EXISITING_MSME_CLIENTS="EXISITING_MSME_CLIENTS"
    OTHERS="OTHERS"


class RELIGION(enum.Enum):
    BUDDHIST = "BUDDHIST"
    CHRISTIAN = "CHRISTIAN"
    HINDU = "HINDU"
    JAIN = "JAIN"
    MUSLIM = "MUSLIM"
    OTHERS = "OTHERS"
    OTHER = "OTHER"
    SIKH = "SIKH"


class APPLICATION_STATUS(enum.Enum):
    NEW_APPLICATION = "NEW_APPLICATION"
    # PRODUCT_CHOOSE = "PRODUCT_CHOOSE"
    ASSET_ADDED = "ASSET_ADDED"
    # ASSET_DOCUMENT_ADDED = "ASSET_DOCUMENT_ADDED"
    LOAN_AMOUNT_ADDED = "LOAN_AMOUNT_ADDED"
    APPLICATION_INITIATED = "APPLICATION_INITIATED"
    # APPLICATION_SENT_TO_CPC = "APPLICATION_SENT_TO_CPC"
    # APPLICATION_REJECTED_BRANCH_MANAGER = "APPLICATION_REJECTED_BRANCH_MANAGER"
    APPLICATION_REJECTED_BY_CPC = "APPLICATION_REJECTED_BY_CPC"
    # LOAN_DOCUMENT_GENERATED = "LOAN_DOCUMENT_GENERATED"
    GENERATE_LOAN_DOCUMENT = "GENERATE_LOAN_DOCUMENT"
    SIGNED_LOAN_DOCUMENT_SUBMITED = "SIGNED_LOAN_DOCUMENT_SUBMITED"
    GOLD_COLLECTED = "GOLD_COLLECTED"
    # APPLICATION_COMPLETED = "APPLICATION_COMPLETED"
    GOLD_DEPOSITED = "GOLD_DEPOSITED"
    # LOAN_DOCUMENT_SENT = "LOAN_DOCUMENT_SENT"
    # LOAN_DOCUMENT_VERIFIED = "LOAN_DOCUMENT_VERIFIED"
    # LOAN_SENT_FOR_DISBURSEMENT = "LOAN_SENT_FOR_DISBURSEMENT"
    LOAN_DISBURSED = "PAYMENT_DETAILS_RECORDED"
    TAKE_OVER_LOAN_INITIATED='TAKE_OVER_LOAN_INITIATED'
    TAKE_OVER='TAKE_OVER_LOAN_PENDING'
    TAKE_OVER_APPROVED='TAKE_OVER_LOAN_APPROVED'
    TAKEOVER_FIRST_DISBURSEMENT_DONE='BT_PAYMENT_DETAILS_RECORDED'
    WHITE_GOODS_ADDED='WHITE_GOODS_ADDED'
    E_SIGN_REQUEST_SENT='E_SIGN_PENDING'
    ROLL_BACK_BY_CPC='APPLICATION_SENT_BACK_BY_CPC'
    ROLL_BACK='APPLICATION_REVERTED_AFTER_CORRECTION'
    BT_NOMINEE_ADDED='BT_NOMINEE_ADDED'
    BT_RESIDENCE_ADDED='BT_RESIDENCE_ADDED'
    RESIDENCE_ADDED='RESIDENCE_ADDED'
    BANK_STATEMENT_REPORT_INITIATED ='BANK_STATEMENT_REPORT_INITIATED'
    BANK_STATEMENT_REPORT_GENERATED ='BANK_STATEMENT_REPORT_GENERATED'
    TELE_VERIFICATION_DONE='TELE_VERIFICATION_DONE'
    ROLL_BACK_BY_CM='APPLICATION_SENT_BACK_BY_CM'
    APPLICATION_REJECTED_BY_CM='APPLICATION_REJECTED_BY_CM'
    APPLICATION_SENT_TO_BH='APPLICATION_SENT_TO_BH'
    APPLICATION_SENT_BACK_BY_BH= 'APPLICATION_SENT_BACK_BY_BH'


    WELLNESS_NOMINEE_ADDED='WELLNESS_NOMINEE_ADDED'
    IMONEY_QR_GENERATED='IMONEY_QR_GENERATED'
    IMONEY_PAYMENT_SUCCESSFUL='IMONEY_PAYMENT_SUCCESSFUL'
    IMONEY_PAYMENT_FAILED='IMONEY_PAYMENT_FAILED'

    PROOF_DOCUMENTS_UPLOADED= 'PROOF_DOCUMENTS_UPLOADED'

    # Federeal flow statuses:
    FEDERAL_CONSENT_SUBMITTED = 'FEDERAL_CONSENT_SUBMITTED'
    FEDERAL_EKYC_SUBMITTED = 'FEDERAL_EKYC_SUBMITTED'
    FEDERAL_ELIGIBILITY_CHECKED = 'FEDERAL_ELIGIBILITY_CHECKED'
    FEDERAL_CUSTOMER_CREATED = 'FEDERAL_CUSTOMER_CREATED'
    FEDERAL_GL_ACCOUNT_CREATED = 'FEDERAL_GL_ACCOUNT_CREATED'
    CIBIL_REPORT_INITIATED = 'CIBIL_REPORT_INITIATED'
    CIBIL_REPORT_GENERATED = 'CIBIL_REPORT_GENERATED'

    APPLICATION_SENT_TO_CO = "APPLICATION_SENT_TO_CO"



APPROVED = "APPROVED"
REJECTED = "REJECTED"

ON_HOLD = "ON_HOLD"
DEVIATED = "DEVIATED"

class LENDER(enum.Enum):
    FEDRAL_BANK="FEDRAL_BANK"
    STATE_BANK_OF_INDIA="STATE_BANK_OF_INDIA"
    AXIS_BANK="AXIS_BANK"
    KOTAK_BANK="KOTAK_BANK"
    FINCARE_SMALL_FINANCE_BANK = "FINCARE_SMALL_FINANCE_BANK"
    RADIAN_FINSERV = "RADIAN_FINSERV"


class GENDER(enum.Enum):
    MALE = "MALE"
    FEMALE = "FEMALE"

    OTHERS = "OTHERS"
#RIL-21:ADDED ACCOUNT TYPE
class ACCOUNT_TYPE(enum.Enum):
    LOAN_DISBURSEMENT = "LOAN_DISBURSEMENT"
    E_NACH = "E_NACH"
class TYPE_OF_LOCATION(enum.Enum):
    BRANCHES = "1"
    OFFICIES = "2"


class CODE_OF_STATES(enum.Enum):
    MAHARASTRA = "27"


class NO_OF_LOCATION(enum.Enum):
    REGISTERED_OFFICE_GURGAON = "0001"

class APPLICANT_TYPE(enum.Enum):
    APPLICANT = "APPLICANT"
    CO_APPLICANT = "CO_APPLICANT"

class OCCUPATION(enum.Enum):
    SALARIED = "SALARIED"
    BUSINESS = "BUSINESS"
    SELF_EMPLOYEED_PROFESSION = "SELF_EMPLOYEED_PROFESSION"
    RETIRED = "RETIRED"
    HOUSEWIFE = "HOUSEWIFE"
    ANIMAL_HUSBANDRY = "ANIMAL_HUSBANDRY"
    HANDICRAFT = "HANDICRAFT"
    HOME_MAKER = "HOME_MAKER"
    LABOUR = "LABOUR"
    OTHERS = "OTHERS"
    RURAL_ARTISANS = "RURAL_ARTISANS"
    SELF_EMPLOYED = "SELF_EMPLOYED"
    STUDENT = "STUDENT"
    SERVICE = "SERVICE"
    TRADE = "TRADE"
    UNEMPLOYED = "UNEMPLOYED"
    SALARIED_JOB_TYPE = 'SALARIED_JOB_TYPE'
    SALARIED_INDUSTRY_TYPE = 'SALARIED_INDUSTRY_TYPE'
    PVT_LTD_CO = 'PVT_LTD_CO'
    PUBLIC_LTD = 'PUBLIC_LTD'
    GOVT_SERVICES = 'GOVT_SERVICES'
    MEDICAL_TEACHING = 'MEDICAL_TEACHING'
    BANKING = 'BANKING'
    MNC = 'MNC'
    FINANCIAL_SERVICES = 'FINANCIAL_SERVICES'
    TEACHING = 'TEACHING'
    AGRI_BASED = 'AGRI_BASED'
    TRADER = 'TRADER'
    BUILDER = 'BUILDER'
    SERVICE_PROVIDER = 'SERVICE_PROVIDER'
    MANUFACTURING = 'MANUFACTURING'
    DOCTOR = 'DOCTOR'
    CA = 'CA'
    CONSULTANT = 'CONSULTANT'
    ARCHITECT = 'ARCHITECT'
    AGRICULTURE='AGRICULTURE'
    BUSINESSMAN = 'BUSINESSMAN'    
    INSURANCE_AGENT='INSURANCE_AGENT'

class SUB_OCCUPATION(enum.Enum):
    PRIVATE_JOB = "PRIVATE_JOB"
    PUBLIC_JOB = "PUBLIC_JOB"
    GOVERNMENT_JOB = "GOVERNMENT_JOB"
    MEDICAL_JOB = "MEDICAL_JOB"
    BANKING_JOB = "BANKING_JOB"
    MNC = "MNC"
    FINANCIAL_SERVICES = "FINANCIAL_SERVICES"
    TEACHING_JOB = "TEACHING_JOB"
    DEFENSE = "DEFENSE"
    PENSIONER = "PENSIONER"
    NBFC = "NBFC"
    PSU = "PSU"
    OTHER = "OTHER"
    INDIVIDUAL = "INDIVIDUAL"
    HUF = "HUF"
    PRIVATE_LTD_CO = "PRIVATE_LTD_CO"
    PARTNERSHIP_FIRM = "PARTNERSHIP_FIRM"
    PROPRIETARY_CONCERN = "PROPRIETARY_CONCERN"
    AGRI_BASED = "AGRI_BASED"
    TRADER = "TRADER"
    BUILDER = "BUILDER"
    HOUSEWIFE = "HOUSEWIFE"
    SERVICE_PROVIDER = "SERVICE_PROVIDER"
    MANUFACTURER = "MANUFACTURER"
    HOME_BASED_BUSINESS = "HOME_BASED_BUSINESS"
    WHOLESALE = "WHOLESALE"
    DOCTOR = "DOCTOR"
    CA = "CA"
    CONSULTANT = "CONSULTANT"
    ARCHITECT = "ARCHITECT"
    RETAILER = "RETAILER"
    EATERY = "EATERY"
    ALLIED_AGRI = "ALLIED_AGRI"
    HANDCART = "HANDCART"
    CATTAGE_INDUSTRIES = "CATTAGE_INDUSTRIES"

class GOLD_OWNERSHIP(enum.Enum):
    ancestral = 'Ancestral'
    gifted = 'Gifted'
    self_purchased = 'Self Purchased'


class EDUCATION(enum.Enum):
    _10TH = "10TH"
    _12TH = "12TH"
    UNDER_GRADUATE = "UNDER_GRADUATE"
    METRIC = "METRIC"
    INTERMEDIATE = "INTERMEDIATE"
    GRADUATE = "GRADUATE"
    ILLITERATE = "ILLITERATE"
    PRIMARY = "PRIMARY"
    POST_GRADUATE = "POST_GRADUATE"
    SECONDARY = "SECONDARY"
    SENIOR_SECONDARY = "SENIOR_SECONDARY"
    OTHERS = "OTHERS"


class MARRIED_STATUS(enum.Enum):
    SINGLE = "SINGLE"
    DIVORCED = "DIVORCED"
    MARRIED = "MARRIED"
    OTHERS = "OTHERS"
    UNMARRIED = "UNMARRIED"
    WIDOWED = "WIDOWED"


class CASTE(enum.Enum):
    GENERAL = "GENERAL"
    OBC = "OBC"
    OTHER = "OTHER"
    SCHEDULE_CASTE = "SCHEDULE_CASTE"
    SCHEDULE_TRIBE = "SCHEDULE_TRIBE"
    ST = "ST"
    SC = "SC"
    MINORITY = "MINORITY"
    OTHERS = "OTHERS"


class LEAD_STATUS(enum.Enum):
    NEW_LEAD = "NEW_LEAD"
    LEAD_ACCOUNT_CREATED = "LEAD_ACCOUNT_CREATED"
    LEAD_CREATION_COMPLETED = "LEAD_CREATION_COMPLETED"


ADHAR_FRONT = "ADHAR_FRONT"
ADHAR_BACK = "ADHAR_BACK"
PAN_CARD = "PAN_CARD"
UTILITY_BILL = "UTILITY_BILL"
GAS_BILL = "GAS_BILL"
RENTAL_BILL = "RENTAL_BILL"
PASSPORT = "PASSPORT"
DRIVING_LICENSE = "DRIVING_LICENSE"
OTHER = "OTHER"
BANK_PASSBOOK = "BANK_PASSBOOK"
CHEQUE_BOOK = "CHEQUE_BOOK"
LAND_DOCUMENT = "LAND_DOCUMENT"
FORM_16 = "FORM_16"
BANK_STATEMENT_1 = "BANK_STATEMENT_1"
BANK_STATEMENT_2 = "BANK_STATEMENT_2"

DOCUMENT_TYPE = [
    ("CUSTOMER_PROFILE_PIC", "CUSTOMER_PROFILE_PIC"),
    (ADHAR_FRONT, "ADHAR_FRONT"),
    (ADHAR_BACK, "ADHAR_BACK"),
    (PAN_CARD, "PAN_CARD"),
    (UTILITY_BILL, "UTILITY_BILL"),
    (GAS_BILL, "GAS_BILL"),
    (RENTAL_BILL, "RENTAL_BILL"),
    (PASSPORT, "PASSPORT"),
    (DRIVING_LICENSE, "DRIVING_LICENSE"),
    (BANK_PASSBOOK, "BANK_PASSBOOK"),
    (CHEQUE_BOOK, "CHEQUE_BOOK"),
    (LAND_DOCUMENT, "LAND_DOCUMENT"),
    (OTHER, "OTHER"),
    ("GOLD COLLECTED","GOLD COLLECTED"),
    ("GOLD DEPOSITED","GOLD DEPOSITED"),
    (FORM_16, "FORM_16"),
    ('E_PASSBOOK','E_PASSBOOK'),
    ("BANK_STATEMENT_1","BANK_STATEMENT_1"),
    ("BANK_STATEMENT_2","BANK_STATEMENT_2"),
    
    
]
LOAN_DOCUMENT = [
    ("SIGNED_LOAN_DOCUMENT", "SIGNED_LOAN_DOCUMENT"),
    ("EXISTING_LOAN_PROOF", "EXISTING_LOAN_PROOF"),
    ("BT_UNDERTAKING", "BT_UNDERTAKING"),
    ("FINCARE_PLEDGE_CARD","FINCARE_PLEDGE_CARD"),
    ("SECURITY_CHEQUE", "SECURITY_CHEQUE"),
    ("SIGNED_UNSECURED_LOAN_DOCUMENT", "SIGNED_UNSECURED_LOAN_DOCUMENT"),
    ("SIGNED_SANCTION_LETTER" ,"SIGNED_SANCTION_LETTER"),
    ("SIGNED_DPN_DOCUMENT","SIGNED_DPN_DOCUMENT"),
    ("CIBIL_REPORT", "CIBIL_REPORT"),
    ("BSA_JSON_FILE", "BSA_JSON_FILE"),
    ("BSA_EXCEL_FILE", "BSA_EXCEL_FILE"),
    ("CIBIL_JSON_REPORT","CIBIL_JSON_REPORT"),

]


ASSET_DOCUMENT = [
    ("PICTURE_OF_GOLD_JEWELLERY", "PICTURE_OF_GOLD_JEWELLERY"),
    ("PICTURE_OF_STONE_WITH_MARK", "PICTURE_OF_STONE_WITH_MARK"),
    ("PICTURE_OF_SCALE_WITH_GOLD", "PICTURE_OF_SCALE_WITH_GOLD"),
    ("PICTURE_OF_THE_HALLMARK","PICTURE_OF_THE_HALLMARK"),
    ("PICTURE_OF_STONE_FOR_GOLD_APPRAISAL","PICTURE_OF_STONE_FOR_GOLD_APPRAISAL")
]

APPLICATION_DOCUMENT = [
    ("OWN_HOUSE_PROOF","OWN_HOUSE_PROOF"),
    ("BUSINESS_PROOF","BUSINESS_PROOF"),
    ("POST_DATED_CHEQUE","POST_DATED_CHEQUE"),
    ("VINTAGE_PROOF","VINTAGE_PROOF"),
    ("AGRI_PROOF","AGRI_PROOF")
]


LEAD_DOCUMENT = [
    ("AADHAR_CARD", "AADHAR_CARD"),
    ("PAN_CARD", "PAN_CARD"),
    ("PLEDGE_CARD", "PLEDGE_CARD"),
    ("AGRI_PRODUCT_PROOF","AGRI_PRODUCT_PROOF")
]

ACCOUNT_ID_NOT_NULL = "account_id should not be null"
APPLICATION_ID_NOT_NULL = "application_id should not be null"


class PLATFORM_TYPE(enum.Enum):
    IOS = "ios"
    ANDROID = "android"
    WEB = "web"


class OTP_TYPE(enum.Enum):
    LOGIN_OTP = "LOGIN_OTP"
    LEAD_PHONE_VERIFICATION_OTP = "LEAD_PHONE_VERIFICATION_OTP"
    ACCOUNT_PHONE_VERIFICATION_OTP = "LEAD_PHONE_VERIFICATION_OTP"
    PAN_VERIFICATION_OTP = "PAN_VERIFICATION_OTP"
    GOLD_COLLECT_VERIFICATION = 'GOLD_COLLECT_VERIFICATION'
    GOLD_DEPOSIT_VERIFICATION = 'GOLD_DEPOSIT_VERIFICATION'
    FORGOT_PASSWORD_OTP = "FORGOT_PASSWORD_OTP"



class APPLICATION_OTP_TYPE(enum.Enum):
    GOLD_DEPOSIT_OTP = "GOLD_DEPOSIT_OTP"
    GOLD_COLLECTION_OTP = "GOLD_COLLECTION_OTP"


class ApplicationType(enum.Enum):
    NEW='NEW'
    TAKEOVER='TAKEOVER'


RADIAN_OFFICE_IN_INDIA=['Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh', 'Dadra and Nagar Haveli', 'Daman and Diu', 'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Ladakh', 'Lakshadweep', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal']

class FRS_DOC_VERIFY(enum.Enum):
    PAN='PAN'
    AADHAR='AADHAR'
    PASSPORT='PASSPORT'
    MOBILE_NUMBER='MOBILE_NUMBER'
    ESIGN_DOC='ESIGN_DOC'
    ESIGN_STATUS='ESIGN_STATUS'



class JewelleryItems(enum.Enum):
    EARRINGS = "EARRINGS"
    NECKLACE = "NECKLACE"
    BRACELET = "BRACELET"
    FINGER_RING = "FINGER RING"
    CHAIN = "CHAIN"
    HAIR_ORNAMENTS = "HAIR ORNAMENTS"
    PENDANT = "PENDANT"
    BANGLES = "BANGLES"
    BELLY_CHAIN = "BELLY CHAIN"
    ANKLET = "ANKLET"
    GEMSTONE_JEWELER = "GEMSTONE_JEWELER"
    MENS_KADA = "MENS KADA"
    MATTI = "MATTI"
    STUDS_WITH_STONE = "STUDS(WITH STONE)"
    OTHERS = "OTHERS"


class REJECTION_APPLICATION(enum.Enum):
    INVALID_BANK_ACCOUNT='INVALID BANK DETAILS'
    INVALID_ASSET_DOCUMENTS = 'INVALID ASSET DOCUMENTS'
    INVALID_KYC = 'INCORRECT KYC'
    APPLICATION_REJECTED='APPLICATION_REJECTED'

class PAYMENT_STATUS(enum.Enum):
    PAYMENT_FILE_GENERATED=1
    PAYMENT_DONE=2
    PAYMENT_FILE_PENDING=0


class ACCOMODATION(enum.Enum):
    LOW_INCOME="LOW_INCOME"
    FLAT_APARTMENT="FLAT_APARTMENT"
    BUNGALOW="BUNGALOW"


class ADDRESS_LOCATING_DIFFICULTY(enum.Enum):
    EASY="EASY"
    MEDIUM="MEDIUM"
    DIFFICULT="DIFFICULT"



class AREA_SQFT(enum.Enum):
    BELOW_400='<400'
    BETWEEN_400_750='400-750'
    BETWEEN_750_1000= '750-1000'
    BETWEEN_1000_1500='1000-1500'
    ABOVE_1500='>1500'


class REPAYMENT_PAYMENT_STATUS(enum.Enum):
    TRANSACTION_SUCCESSFUL_1 = "TRANSACTION_SUCCESSFUL_1"
    TRANSACTION_UNDER_PROCESS_2 = "TRANSACTION_UNDER_PROCESS_2"
    TRANSACTION_UNDER_PROCESS_3 = "TRANSACTION_UNDER_PROCESS_3"
    TRANSACTION_UNDER_PROCESS_4 = "TRANSACTION_UNDER_PROCESS_4"
    TRANSACTION_FAILED_0 = "TRANSACTION_FAILED_0"

# (Cash | VPA_Request | DynamicQR)
class REPAYMENT_PAYMENT_MODE(enum.Enum):
    CASH = "CASH"
    VPA_REQUEST = "VPA_REQUEST"
    DYNAMICQR = "DynamicQR"


class KYC_VENDORS(enum.Enum):
    RNFI="RNFI"
    FRS="FRS"

class LENDING_TYPE(enum.Enum):
    MSME_UNSECURED = "MSME_UNSECURED" #(PERSONAL_LOAN)
    MSME_UNSECURED_AGRI = "MSME_UNSECURED_AGRI"
    MSME_SECURED="MSME_SECURED" #(HOME_LOAN)
    GOLD_LOAN="GOLD_LOAN"
    WELLNESS = "WELLNESS"


class HOUSE_OWNERSHIP(enum.Enum):
    OWN = "OWN"
    RENT = "RENTED"

class SHOP_OWNERSHIP(enum.Enum):
    OWN = "OWN"
    RENT = "RENTED"

class NO_OF_YEARS(enum.Enum):
    LESS_THAN_2 = "LESS_THAN_2"
    _2_TO_10 = "2_TO_10"
    MORE_THAN_10 = "MORE_THAN_10"

class NATURE_OF_BUSINESS(enum.Enum):
    RETAIL="RETAIL"
    TRADERS="TRADERS"
    ALLIED_AGRI="ALLIED_AGRI"
    AGRI= "AGRI"

    #Agri
    CROP = "CROP"
    DAIRY = "DAIRY"
    CROP_AND_DAIRY = "CROP_AND_DAIRY"
    OTHERS = "OTHERS"


class YES_OR_NO(enum.Enum):
    YES="YES"
    NO="NO"

class ACCOUNT_PURPOSE(enum.Enum):
    LOAN_DISBURSEMENT = "LOAN_DISBURSEMENT"
    E_NACH = "E_NACH"

class ACCOUNT_TYPE(enum.Enum):
    SAVINGS =  "SAVINGS"
    CURRENT = "CURRENT"
    OVERDRAFT = "OVERDRAFT"

class RESIDENTIAL_OWNERSHIP(enum.Enum):
    OWN ="OWN"
    RENTED = "RENTED"
class RESIDENTIAL_NO_OF_YEARS(enum.Enum):
   ONE_TO_1O ="1_TO_1O"
   ABOVE_10 ="ABOVE_10"

class PHOTO_TYPE(enum.Enum):
    IMAGE_OF_HOUSE_WITH_PERSON_STANDING_AT_THE_GATE = "IMAGE_OF_HOUSE_WITH_PERSON_STANDING_AT_THE_GATE"
    IMAGE_OF_SHOP_WITH_PERSON_STANDING_AT_THE_GATE = "IMAGE_OF_SHOP_WITH_PERSON_STANDING_AT_THE_GATE"
    IMAGE_OF_INSIDE_THE_SHOP = "IMAGE_OF_INSIDE_THE_SHOP"
    OTHERS = "OTHERS"
    CO_IMAGE_OF_HOUSE_WITH_PERSON_STANDING_AT_THE_GATE = "CO_IMAGE_OF_HOUSE_WITH_PERSON_STANDING_AT_THE_GATE"
    CO_IMAGE_OF_SHOP_WITH_PERSON_STANDING_AT_THE_GATE = "CO_IMAGE_OF_SHOP_WITH_PERSON_STANDING_AT_THE_GATE"
    CO_IMAGE_OF_INSIDE_THE_SHOP = "CO_IMAGE_OF_INSIDE_THE_SHOP"
    CO_OTHERS = "CO_OTHERS"

    AGRI_IMAGE_1 = "AGRI_IMAGE_1"
    AGRI_IMAGE_2 = "AGRI_IMAGE_2"
    AGRI_IMAGE_3 = "AGRI_IMAGE_3"
    AGRI_IMAGE_4 = "AGRI_IMAGE_4"
    CO_AGRI_IMAGE_1 = "CO_AGRI_IMAGE_1"
    CO_AGRI_IMAGE_2 = "CO_AGRI_IMAGE_2"
    CO_AGRI_IMAGE_3 = "CO_AGRI_IMAGE_3"
    CO_AGRI_IMAGE_4 = "CO_AGRI_IMAGE_4"

class POSITIVE_OR_NEGATIVE(enum.Enum):
    POSITIVE = "POSITIVE"
    NEGATIVE = "NEGATIVE"

class INSURANCE_APPLICABLE(enum.Enum):
    ACCOUNT = "ACCOUNT"
    APPLICATION = "APPLICATION"

class USER_TYPE(enum.Enum):
    BANK = "BANK"
    CUSTOMER = "CUSTOMER"
    MERCHANT = "MERCHANT"

class ENTITY_TYPE(enum.Enum):
    FIRM = "FIRM"
    INDIVIDUAL = "INDIVIDUAL"

class PRIORITY_CHOICES(enum.Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"

class TASK_STATUS(enum.Enum):
    YET_TO_START = "YET_TO_START"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CLOSED = "CLOSED"

class CONDITION(enum.Enum):
    MANDATORY = "MANDATORY"
    NON_MANDATORY = "NON_MANDATORY"


class TEAM(enum.Enum):
    DST = "DST"
    BANCA = "BANCA"

    CENTRAL = "CENTRAL"

class BADGE(enum.Enum):
    GOLD = "GOLD"
    SILVER = "SILVER"
    PLATINUM = "PLATINUM"

class DESIGNATION(enum.Enum):
    #DST / BANCA
    FOS = "FOS"
    RH = "RH"
    CH = "CH"
    ZH = "ZH"
    NSH = "NSH"

    #CENTRAL
    SUPER_ADMIN = "SUPER_ADMIN"
    ADMIN = "ADMIN"
    MANAGEMENT_USER = "MANAGEMENT_USER"
    TASK_MANAGEMENT_ADMIN = "TASK_MANAGEMENT_ADMIN"
    TASK_MANAGEMENT_USER = "TASK_MANAGEMENT_USER"
    DV = "DV"
    OPH = "OPH"
    ACCOUNT_MAKER = "ACCOUNT_MAKER"
    ACCOUNT_CHECKER = "ACCOUNT_CHECKER"
    RECON_USER = "RECON_USER"
    MIS_USER = "MIS_USER"


class AGENT_ACCOUNT_STATUS(enum.Enum):
    ACCOUNT_DETAILS_ADDED = "ACCOUNT_DETAILS_ADDED"
    ESIGN_PENDING = "ESIGN_PENDING"
    ACCOUNT_CREATED = "ACCOUNT_CREATED"

class AGENT_EDUCATION(enum.Enum):
    SECONDARY = "SECONDARY"
    SENIOR_SECONDARY = "SENIOR_SECONDARY"
    GRADUATE = "GRADUATE"
    POST_GRADUATE = "POST_GRADUATE"

class AGENT_OCCUPATION(enum.Enum):
    BUSSINESSMAN = "BUSINESSMAN"
    CA = "CA"
    INSURANCE_AGENT = "INSURANCE_AGENT"
    OTHERS = "OTHERS"


class SUBTASK_STATUS(enum.Enum):
    NEW_TASK = "NEW_TASK"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    DECLINED = "DECLINED"

class FLOW_STATUS(enum.Enum):
    LOCATION_VERIFICATION_STARTED = "LOCATION_VERIFICATION_STARTED"
    LOCATION_VERIFICATION_REACHED_ADDRESS = "LOCATION_VERIFICATION_REACHED_ADDRESS"
    LOCATION_VERIFICATION_COMPLETED = "LOCATION_VERIFICATION_COMPLETED"
    LOCATION_VERIFICATION_VERIFIED_BY_CENTRAL_OPS = "LOCATION_VERIFICATION_VERIFIED_BY_CENTRAL_OPS" 

    LOCATION_RE_VERIFICATION_STARTED = "LOCATION_RE_VERIFICATION_STARTED"
    LOCATION_RE_VERIFICATION_REACHED_ADDRESS = "LOCATION_RE_VERIFICATION_REACHED_ADDRESS"
    LOCATION_RE_VERIFICATION_COMPLETED = "LOCATION_RE_VERIFICATION_COMPLETED"
    LOCATION_RE_VERIFICATION_VERIFIED_BY_CENTRAL_OPS = "LOCATION_RE_VERIFICATION_VERIFIED_BY_CENTRAL_OPS" 

    UPLOAD_KYC_DOCUMENTS_STARTED = "UPLOAD_KYC_DOCUMENTS_STARTED"
    KYC_REACHED_ADDRESS = "KYC_REACHED_ADDRESS"
    UPLOAD_KYC_DOCUMENTS_COMPLETED = "UPLOAD_KYC_DOCUMENTS_COMPLETED"
    UPLOAD_KYC_DOCUMENT_VERIFIED_BY_CENTRAL_OPS = "UPLOAD_KYC_DOCUMENT_VERIFIED_BY_CENTRAL_OPS"
    DOCUMENTS_VERIFIED = "DOCUMENTS_VERIFIED"

    LEAD_GENERATION_STARTED = "LEAD_GENERATION_STARTED"
    LEAD_GENERATION_COMPLETED = "LEAD_GENERATION_COMPLETED"

    LEAD_CLOSURE_STARTED = "LEAD_CLOSURE_STARTED"
    LEAD_CLOSURE_DETAILS_ADDED = "LEAD_CLOSURE_DETAILS_ADDED"
    LEAD_CLOSURE_COMPLETED = "LEAD_CLOSURE_COMPLETED"

    # LEAD_CLOSURE_STARTED = "LEAD_CLOSURE_STARTED"
    # LEAD_CLOSURE_COMPLETED = "LEAD_CLOSURE_COMPLETED"

    QUESTIONNAIRE_STARTED = "QUESTIONNAIRE_STARTED"
    QUESTIONNAIRE_COMPLETED = "QUESTIONNAIRE_COMPLETED"

    # Keep generic ones for backward compatibility
    REACHED_ADDRESS = "REACHED_ADDRESS"  # DEPRECATED
    LOCATION_PHOTO_ADDED = "LOCATION_PHOTO_ADDED"
    SELFIE_PHOTO_ADDED = "SELFIE_PHOTO_ADDED"
    VERIFIED_BY_CENTRAL_OPS = "VERIFIED_BY_CENTRAL_OPS"
    SENT_BACK_BY_CENTRAL_OPS = "SENT_BACK_BY_CENTRAL_OPS"
    SENT_TO_CENTRAL_OPS = "SENT_TO_CENTRAL_OPS"
    REJECTED_BY_CENTRAL_OPS = "REJECTED_BY_CENTRAL_OPS"


    AADHAR_CARD_VERIFIED = "AADHAR_CARD_VERIFIED"
    PAN_CARD_VERIFIED = "PAN_CARD_VERIFIED"
    OTHER_DOCUMENTS_VERIFIED = "OTHER_DOCUMENTS_VERIFIED"
    CUSTOMER_DETAILS_ADDED = "CUSTOMER_DETAILS_ADDED"
    CUSTOMER_ADDRESS_ADDED = "CUSTOMER_ADDRESS_ADDED"

    ADD_LEAD_DETAILS = "ADD_LEAD_DETAILS"
    LEAD_OTP_VERIFIED = "LEAD_OTP_VERIFIED"

class DOCUMENT_FLOW(enum.Enum):
    LOCATION_VERIFICATION = "LOCATION_VERIFICATION"
    LOCATION_REVERIFICATION = "LOCATION_REVERIFICATION"
    KYC_DOCUMENT_UPLOAD = "KYC_DOCUMENT_UPLOAD"
    LEAD_GENERATION = "LEAD_GENERATION"
    LEAD_CLOSURE = "LEAD_CLOSURE"


class FLOW_DOCUMENT_TYPE(enum.Enum):
    LOCATION_PHOTO = "LOCATION_PHOTO"
    SELFIE_PHOTO = "SELFIE_PHOTO"
    PAN_CARD = "PAN_CARD"
    FRONT_AADHAR_CARD = "FRONT_AADHAR_CARD"
    BACK_AADHAR_CARD = "BACK_AADHAR_CARD"
    FRONT_PASSPORT = "FRONT_PASSPORT"
    BACK_PASSPORT = "BACK_PASSPORT"
    FRONT_DRIVING_LICENSE = "FRONT_DRIVING_LICENSE"
    BACK_DRIVING_LICENSE = "BACK_DRIVING_LICENSE"
    FRONT_VOTER_ID = "FRONT_VOTER_ID"
    BACK_VOTER_ID = "BACK_VOTER_ID"
    PROFILE_PIC = "PROFILE_PIC"
    PLEDGE_CARD_KFS = "PLEDGE_CARD_KFS"



class CENTRAL_OPS_STATUS(enum.Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class OTHER_DOCUMENTS(enum.Enum):
    DRIVING_LICENSE = "DRIVING_LICENSE"
    VOTER_ID = "VOTER_ID"
    PASSPORT = "PASSPORT"
    
class APPROVAL_STATUS(enum.Enum):
    APPROVE = "APPROVE"
    SENT_FOR_CORRECTION = "SENT_FOR_CORRECTION"
    
    
# utils/constants.py - ADD THIS SECTION

from enum import Enum

class CORRECTION_REASONS:
    """Flow-specific correction reasons"""
    
    # Location Verification Flow
    LOCATION_VERIFICATION = {
        1: [   # Location Image
            "Image is blur",
            "Premises is not properly visible",
            "Business Name is not properly visible"
        ],
        2: [   # Selfie with Customer
            "Customer's face is not properly visible",
            "SO is not properly in the image",
            "Both SO and Customer are not in a single frame"
        ]
    }
    
    # Location Re-Verification Flow
    LOCATION_RE_VERIFICATION = LOCATION_VERIFICATION
    
    # Upload KYC Document Flow
    UPLOAD_KYC_DOCUMENT = {
        1: [   # Aadhar Document Upload
            "ID Number doesn't match with image",
            "Document image is not visible properly"
        ],
        2: [   # PAN Document Upload
            "ID Number doesn't match with image",
            "Document image is not visible properly"
        ],
        3: [   # Driving Licence
            "ID Number doesn't match with image",
            "Document image is not visible properly"
        ],
        4: [   # Current Photo
            "Image is blur",
            "Image is not proper",
            "Image is in an odd angle"
        ],
        5: [   # Full Name (manual entry)
            "Full name mismatch with document"
        ]
    }
    
    # Lead Generation Flow
    LEAD_GENERATION = {
        1: [
            "Incomplete contact details",
            "Invalid phone number",
            "Wrong product category",
            "Amount not specified",
            "Missing required fields"
        ],
        2: [
            "OTP not verified",
            "Phone number not reachable",
            "Invalid OTP"
        ]
    }
    
    # Lead Closure Flow
    LEAD_CLOSURE = {
        1: [
            "Invalid lead ID",
            "Lead ID not found",
            "Lead already closed"
        ],
        2: [
            "Lead status not updated",
            "Lead verification pending"
        ]
    }
    
    @classmethod
    def get_reasons_for_flow(cls, flow_description, step_order):
        """Get correction reasons for a specific flow and step"""
        flow_mapping = {
            'Location Verification': cls.LOCATION_VERIFICATION,
            'Location Re-Verification': cls.LOCATION_RE_VERIFICATION,
            'Upload KYC Document': cls.UPLOAD_KYC_DOCUMENT,
            'Lead Generation': cls.LEAD_GENERATION,
            'Lead Closure (fulfilment)': cls.LEAD_CLOSURE,
        }
        
        flow_reasons = flow_mapping.get(flow_description, {})
        return flow_reasons.get(step_order, ["Other - Please specify in comment"])
